\set QUIET on
\set ON_ERROR_STOP on
\pset format unaligned
\pset tuples_only on
\pset footer off

-- P0-DB column parity fingerprint.
-- Run against path A (baseline-draft + active migrations, psql) and path B
-- (Drizzle-generated baseline, drizzle-kit migrate). The workflow diffs the two
-- outputs; the only accepted differences are the classified entries in
-- schema-column-parity.known-drift.txt.
-- One line per column: table, column, then type, nullability, default and any
-- identity/generation clause as a DDL fragment. Column order is excluded on
-- purpose (ALTER TABLE ADD COLUMN appends). Constraints and indexes are covered
-- by schema-constraint-index-parity.sql; the drizzle schema is excluded.

SELECT fingerprint
  FROM (
    SELECT 'COLUMN|'
           || rel.relname || '|'
           || att.attname || '|'
           || format_type(att.atttypid, att.atttypmod)
           || CASE WHEN att.attnotnull THEN ' NOT NULL' ELSE '' END
           || CASE att.attidentity
                WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                ELSE ''
              END
           || CASE
                WHEN att.attgenerated = 's'
                  THEN ' GENERATED ALWAYS AS ('
                       || regexp_replace(pg_get_expr(def.adbin, def.adrelid), '\s+', ' ', 'g')
                       || ') STORED'
                WHEN def.adbin IS NOT NULL
                  THEN ' DEFAULT '
                       || regexp_replace(pg_get_expr(def.adbin, def.adrelid), '\s+', ' ', 'g')
                ELSE ''
              END AS fingerprint
      FROM pg_attribute att
      JOIN pg_class rel ON rel.oid = att.attrelid
      JOIN pg_namespace ns ON ns.oid = rel.relnamespace
      LEFT JOIN pg_attrdef def ON def.adrelid = att.attrelid AND def.adnum = att.attnum
     WHERE ns.nspname = 'public'
       AND rel.relkind IN ('r', 'p')
       AND att.attnum > 0
       AND NOT att.attisdropped
  ) columns
 ORDER BY fingerprint COLLATE "C";
