/**
 * Carnet du chien (Sprint 02 — Couche A).
 *
 * Récit personnel illustré de la vie du chien : balades, observations,
 * jalons, visites. Pas un journal médical, pas un dashboard de données.
 *
 * ⚠ Invariants :
 *  - Aucune émotion humaine attribuée au chien (calme/actif, jamais anthropomorphisé).
 *  - Aucun claim médical (la visite véto note le TYPE, jamais l'évaluation).
 *  - Les jalons concernent le PROPRIÉTAIRE ("VOUS avez…"), jamais une perf du chien.
 */

import { MOCK_DOG } from './mock-data';

export type ActivityTag =
  | 'balade'
  | 'repas'
  | 'dressage'
  | 'jeu'
  | 'repos'
  | 'rencontre'
  | 'baignade'
  | 'voyage'
  | 'autre';

export const ACTIVITY_LABELS: Record<ActivityTag, string> = {
  balade: 'Balade',
  repas: 'Repas',
  dressage: 'Dressage',
  jeu: 'Jeu',
  repos: 'Repos',
  rencontre: 'Rencontre',
  baignade: 'Baignade',
  voyage: 'Voyage',
  autre: 'Autre',
};

export type EntryType = 'photo_text' | 'walk_recorded' | 'milestone' | 'observation' | 'vet_visit';

interface BaseEntry {
  id: string;
  /** ISO 8601. */
  occurredAt: string;
  title?: string;
  /** Vrai pour les jalons générés par le système (non éditables). */
  isAutoGenerated?: boolean;
}

export interface PhotoTextEntry extends BaseEntry {
  type: 'photo_text';
  content: string;
  /** Data URLs (prototype) ou URLs distantes. */
  photoUrls: string[];
  activityTag?: ActivityTag;
  locationName?: string;
}

export interface WalkEntry extends BaseEntry {
  type: 'walk_recorded';
  content?: string;
  durationSeconds: number;
  distanceMeters: number;
  elevationGainMeters?: number;
  weather?: { tempC: number; conditions: string };
  photoUrls: string[];
  locationName?: string;
}

export interface MilestoneEntry extends BaseEntry {
  type: 'milestone';
  content: string;
  milestoneKind: string;
}

export interface ObservationEntry extends BaseEntry {
  type: 'observation';
  /** Max 280 caractères (format court). */
  content: string;
}

export interface VetVisitEntry extends BaseEntry {
  type: 'vet_visit';
  visitType: 'annual' | 'vaccine' | 'control' | 'other';
  vetName?: string;
  content?: string;
  /** ISO date d'un rappel optionnel. */
  nextVisitReminder?: string;
}

export type JournalEntry =
  | PhotoTextEntry
  | WalkEntry
  | MilestoneEntry
  | ObservationEntry
  | VetVisitEntry;

export interface EntryTypeMeta {
  label: string;
  tone: 'accent' | 'accent2';
}

export const ENTRY_TYPE_META: Record<EntryType, EntryTypeMeta> = {
  photo_text: { label: 'Souvenir', tone: 'accent2' },
  walk_recorded: { label: 'Balade', tone: 'accent2' },
  milestone: { label: 'Jalon', tone: 'accent' },
  observation: { label: 'Observation', tone: 'accent2' },
  vet_visit: { label: 'Visite vétérinaire', tone: 'accent' },
};

export const VET_VISIT_LABELS: Record<VetVisitEntry['visitType'], string> = {
  annual: 'Visite annuelle',
  vaccine: 'Vaccin',
  control: 'Contrôle',
  other: 'Autre',
};

/* ------------------------------------------------------------------ */
/* Le chien (méta enrichie pour les jalons)                            */
/* ------------------------------------------------------------------ */

export const DOG = {
  name: MOCK_DOG.name, // "Gus"
  breed: MOCK_DOG.breed,
  birthDate: '2021-09-14',
  adoptionDate: '2021-11-20',
};

export const JOURNAL_OWNER_HEADER = 'x-journal-owner-token';
const JOURNAL_OWNER_TOKEN_KEY = 'breiz-journal-owner-token';

function makeOwnerToken(): string {
  const uuid = globalThis.crypto?.randomUUID?.();
  return uuid ? `journal-${uuid}` : `journal-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

export function getJournalOwnerToken(): string {
  if (typeof window === 'undefined') return '';
  try {
    const existing = localStorage.getItem(JOURNAL_OWNER_TOKEN_KEY);
    if (existing) return existing;
    const created = makeOwnerToken();
    localStorage.setItem(JOURNAL_OWNER_TOKEN_KEY, created);
    return created;
  } catch {
    return makeOwnerToken();
  }
}

/* ------------------------------------------------------------------ */
/* Données mock                                                        */
/* ------------------------------------------------------------------ */

/**
 * ⚠ DEMO MOCK DATA — entrées du carnet de Gus.
 * À remplacer par `GET /api/v6/dogs/:id/journal?month=YYYY-MM`.
 */
export const INITIAL_ENTRIES: JournalEntry[] = [
  {
    id: 'e-obs-0529',
    type: 'observation',
    occurredAt: '2026-05-29T08:12:00+02:00',
    content: 'Réveil calme ce matin, quelques étirements avant la sortie. Pas d’agitation au départ.',
  },
  {
    id: 'e-walk-0528',
    type: 'walk_recorded',
    occurredAt: '2026-05-28T18:40:00+02:00',
    title: 'Boucle du port',
    durationSeconds: 42 * 60,
    distanceMeters: 3200,
    elevationGainMeters: 35,
    weather: { tempC: 17, conditions: 'Ciel voilé' },
    photoUrls: [],
    locationName: 'Lorient — Port de pêche',
    content: 'Rythme régulier, retour rapide au calme une fois rentré.',
  },
  {
    id: 'e-vet-0526',
    type: 'vet_visit',
    occurredAt: '2026-05-26T11:00:00+02:00',
    title: 'Visite annuelle',
    visitType: 'annual',
    vetName: 'Clinique du Ter — Lorient',
    content: 'Contrôle de routine. Poids et rappels à jour. Prochaine visite programmée dans un an.',
    nextVisitReminder: '2027-05-26',
  },
  {
    id: 'e-photo-0524',
    type: 'photo_text',
    occurredAt: '2026-05-24T15:30:00+02:00',
    title: 'Première baignade de la saison',
    content: 'Activité élevée observée pendant une bonne heure sur la plage, puis longue phase de repos à l’ombre.',
    photoUrls: [],
    activityTag: 'baignade',
    locationName: 'Plage de Gâvres',
  },
  {
    id: 'e-milestone-0520',
    type: 'milestone',
    occurredAt: '2026-05-20T09:00:00+02:00',
    title: '100 balades enregistrées',
    content: 'Vous avez accompagné Gus sur 100 sorties depuis le 14 février. Beau rythme !',
    milestoneKind: 'walks_100',
    isAutoGenerated: true,
  },
  {
    id: 'e-obs-0518',
    type: 'observation',
    occurredAt: '2026-05-18T22:10:00+02:00',
    content: 'Endormissement un peu plus long que d’habitude, légère agitation en début de nuit.',
  },
  {
    id: 'e-walk-0515',
    type: 'walk_recorded',
    occurredAt: '2026-05-15T07:50:00+02:00',
    title: 'Sentier côtier',
    durationSeconds: 65 * 60,
    distanceMeters: 5100,
    elevationGainMeters: 80,
    weather: { tempC: 14, conditions: 'Crachin' },
    photoUrls: [],
    locationName: 'Larmor-Plage',
  },
  {
    id: 'e-photo-0510',
    type: 'photo_text',
    occurredAt: '2026-05-10T11:20:00+02:00',
    title: 'Nouveau jouet',
    content: 'S’est emparé du jouet bleu immédiatement, longue séance de jeu actif dans le jardin.',
    photoUrls: [],
    activityTag: 'jeu',
  },
  // Mois précédent (pour la navigation mensuelle)
  {
    id: 'e-walk-0428',
    type: 'walk_recorded',
    occurredAt: '2026-04-28T17:00:00+02:00',
    title: 'Forêt de Brocéliande',
    durationSeconds: 90 * 60,
    distanceMeters: 6800,
    elevationGainMeters: 120,
    weather: { tempC: 12, conditions: 'Éclaircies' },
    photoUrls: [],
    locationName: 'Paimpont',
  },
  {
    id: 'e-obs-0415',
    type: 'observation',
    occurredAt: '2026-04-15T19:30:00+02:00',
    content: 'Retour au calme très rapide après le passage d’un autre chien dans la rue.',
  },
];

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

/** Clé mois "YYYY-MM" à partir d'une date ISO. */
export function monthKey(iso: string): string {
  return iso.slice(0, 7);
}

/** Mois disponibles (clés "YYYY-MM"), triés du plus récent au plus ancien. */
export function availableMonths(entries: JournalEntry[]): string[] {
  return Array.from(new Set(entries.map((e) => monthKey(e.occurredAt)))).sort((a, b) => b.localeCompare(a));
}

export interface MonthSummary {
  totalEntries: number;
  walksCount: number;
  photosCount: number;
  milestonesCount: number;
}

export function monthSummary(entries: JournalEntry[]): MonthSummary {
  return {
    totalEntries: entries.length,
    walksCount: entries.filter((e) => e.type === 'walk_recorded').length,
    photosCount: entries.reduce(
      (n, e) => n + ((e.type === 'photo_text' || e.type === 'walk_recorded') ? e.photoUrls.length : 0),
      0,
    ),
    milestonesCount: entries.filter((e) => e.type === 'milestone').length,
  };
}

/** Regroupe les entrées par jour (clé "YYYY-MM-DD"), triées DESC. */
export function groupByDay(entries: JournalEntry[]): Array<[string, JournalEntry[]]> {
  const sorted = [...entries].sort((a, b) => b.occurredAt.localeCompare(a.occurredAt));
  const map = new Map<string, JournalEntry[]>();
  for (const e of sorted) {
    const day = e.occurredAt.slice(0, 10);
    const list = map.get(day);
    if (list) list.push(e);
    else map.set(day, [e]);
  }
  return Array.from(map.entries());
}

const DAYS = ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'];
const MONTHS = [
  'janvier', 'février', 'mars', 'avril', 'mai', 'juin',
  'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre',
];

/** "Jeudi 29 mai" à partir d'une clé jour "YYYY-MM-DD". */
export function formatDayHeader(dayKey: string): string {
  const d = new Date(`${dayKey}T12:00:00`);
  return `${DAYS[d.getDay()]} ${d.getDate()} ${MONTHS[d.getMonth()]}`;
}

/** "Mai 2026" à partir d'une clé mois "YYYY-MM". */
export function formatMonthLabel(key: string): string {
  const [y, m] = key.split('-');
  const label = MONTHS[Number(m) - 1] ?? '';
  return `${label.charAt(0).toUpperCase()}${label.slice(1)} ${y}`;
}

export function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' });
}

export function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.round((seconds % 3600) / 60);
  return h > 0 ? `${h} h ${m.toString().padStart(2, '0')}` : `${m} min`;
}

export function formatDistance(meters: number): string {
  return meters >= 1000 ? `${(meters / 1000).toFixed(1)} km` : `${meters} m`;
}

export function formatDateLong(iso: string): string {
  const d = new Date(iso);
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}`;
}

const ENTRY_TYPES = new Set<EntryType>(['photo_text', 'walk_recorded', 'milestone', 'observation', 'vet_visit']);
const MAX_JOURNAL_CONTENT_LENGTH = 2000;
const MAX_JOURNAL_TITLE_LENGTH = 160;
const MAX_JOURNAL_PHOTOS = 4;
const MAX_JOURNAL_PHOTO_URL_LENGTH = 4096;

/** Validation serveur minimale d'une entrée du carnet (entrée construite côté client). */
export function validateJournalEntry(e: Partial<JournalEntry>): string[] {
  const errors: string[] = [];
  if (!e.id) errors.push('id manquant.');
  if (!e.type || !ENTRY_TYPES.has(e.type)) errors.push("Type d'entrée invalide.");
  if (!e.occurredAt || Number.isNaN(new Date(e.occurredAt).getTime())) errors.push('Date invalide.');
  if (e.title && e.title.length > MAX_JOURNAL_TITLE_LENGTH) errors.push('Titre trop long.');
  if ('content' in e && typeof (e as { content?: unknown }).content === 'string') {
    const content = (e as { content?: string }).content ?? '';
    if (content.length > MAX_JOURNAL_CONTENT_LENGTH) errors.push('Contenu trop long.');
  }
  if ('photoUrls' in e && Array.isArray((e as { photoUrls?: unknown }).photoUrls)) {
    const photoUrls = (e as { photoUrls?: string[] }).photoUrls ?? [];
    if (photoUrls.length > MAX_JOURNAL_PHOTOS) errors.push('Trop de photos.');
    if (photoUrls.some((url) => typeof url !== 'string' || url.length > MAX_JOURNAL_PHOTO_URL_LENGTH)) {
      errors.push('Photo invalide.');
    }
  }
  if ((e.type === 'observation' || e.type === 'photo_text') && !('content' in e && (e as { content?: string }).content?.trim())) {
    errors.push('Contenu requis pour ce type.');
  }
  return errors;
}
