/**
 * Détection des jalons du carnet (Sprint 02).
 *
 * Un jalon récompense un cap atteint — le sujet est TOUJOURS le propriétaire
 * (invariant 4 : gamification du propriétaire, jamais du chien). Côté prod, la
 * détection tournerait après chaque insert + un cron quotidien (backend).
 *
 * Seuils réels conservés : en démo, seuls les jalons réellement atteints
 * apparaissent (les autres sont fournis dans les données mock).
 */

import type { JournalEntry, MilestoneEntry } from './journal';
import { DOG } from './journal';

export interface MilestoneCandidate {
  milestoneKind: string;
  title: string;
  content: string;
}

function isSameDayMonth(iso: string, ref: Date): boolean {
  const d = new Date(iso);
  return d.getMonth() === ref.getMonth() && d.getDate() === ref.getDate();
}

/**
 * Évalue les jalons éligibles à partir de l'état actuel du carnet.
 * Renvoie uniquement ceux qui ne sont pas déjà présents (par `milestoneKind`).
 */
export function detectMilestones(entries: JournalEntry[], now: Date = new Date()): MilestoneCandidate[] {
  const existingKinds = new Set(
    entries.filter((e): e is MilestoneEntry => e.type === 'milestone').map((e) => e.milestoneKind),
  );
  const candidates: MilestoneCandidate[] = [];

  // Première entrée du carnet
  if (entries.length === 1 && !existingKinds.has('first_entry')) {
    candidates.push({
      milestoneKind: 'first_entry',
      title: 'Première entrée du carnet',
      content: `Vous venez d’ouvrir le carnet de ${DOG.name}. À vous d’écrire la suite.`,
    });
  }

  // 100 balades enregistrées
  const walks = entries.filter((e) => e.type === 'walk_recorded').length;
  if (walks >= 100 && !existingKinds.has('walks_100')) {
    candidates.push({
      milestoneKind: 'walks_100',
      title: '100 balades enregistrées',
      content: `Vous avez accompagné ${DOG.name} sur 100 sorties. Beau rythme !`,
    });
  }

  // Anniversaire du chien
  if (DOG.birthDate && isSameDayMonth(DOG.birthDate, now) && !existingKinds.has(`birthday_${now.getFullYear()}`)) {
    const age = now.getFullYear() - new Date(DOG.birthDate).getFullYear();
    candidates.push({
      milestoneKind: `birthday_${now.getFullYear()}`,
      title: `${DOG.name} a ${age} ${age === 1 ? 'an' : 'ans'} aujourd’hui`,
      content: `Une année de plus passée ensemble. Pensez à ajouter un souvenir du jour.`,
    });
  }

  // Anniversaire d'adoption
  if (DOG.adoptionDate && isSameDayMonth(DOG.adoptionDate, now) && !existingKinds.has(`adoption_${now.getFullYear()}`)) {
    const years = now.getFullYear() - new Date(DOG.adoptionDate).getFullYear();
    candidates.push({
      milestoneKind: `adoption_${now.getFullYear()}`,
      title: `${years} ${years === 1 ? 'an' : 'ans'} avec ${DOG.name}`,
      content: `Vous avez adopté ${DOG.name} il y a ${years} ${years === 1 ? 'an' : 'ans'} jour pour jour.`,
    });
  }

  return candidates;
}

/** Construit une entrée de carnet à partir d'un jalon détecté. */
export function milestoneToEntry(candidate: MilestoneCandidate, occurredAt: string = new Date().toISOString()): MilestoneEntry {
  return {
    id: `milestone-${candidate.milestoneKind}-${Date.now()}`,
    type: 'milestone',
    occurredAt,
    title: candidate.title,
    content: candidate.content,
    milestoneKind: candidate.milestoneKind,
    isAutoGenerated: true,
  };
}
