/**
 * LEGACY / HOLD — automatic milestone detector from the earlier prototype.
 *
 * Experience-hardening decision 2026-09-06:
 * - the journal no longer calls this module;
 * - automatic count/activity milestones are not release authority;
 * - Memories/relationship history requires deliberate Owner authorship or
 *   confirmation under #228 and the Experience Doctrine;
 * - historical entries may remain readable, but this module must not be wired
 *   back into launch flows without a new controlled review.
 *
 * Tracked by #223 / #233.
 */

import type { JournalEntry, MilestoneEntry } from './journal';
import { DOG } from './journal';

export interface MilestoneCandidate {
  milestoneKind: string;
  title: string;
  content: string;
}

function isSameDayMonth(iso: string, ref: Date): boolean {
  const d = new Date(iso);
  return d.getMonth() === ref.getMonth() && d.getDate() === ref.getDate();
}

/**
 * @deprecated Legacy prototype behavior. Do not use in launch flows.
 *
 * Evaluates historical auto-milestone rules retained only so old prototype data
 * and tests can be understood during migration.
 */
export function detectMilestones(entries: JournalEntry[], now: Date = new Date()): MilestoneCandidate[] {
  const existingKinds = new Set(
    entries.filter((e): e is MilestoneEntry => e.type === 'milestone').map((e) => e.milestoneKind),
  );
  const candidates: MilestoneCandidate[] = [];

  // Legacy: first journal entry.
  if (entries.length === 1 && !existingKinds.has('first_entry')) {
    candidates.push({
      milestoneKind: 'first_entry',
      title: 'Première entrée du carnet',
      content: `Vous venez d’ouvrir le carnet de ${DOG.name}. À vous d’écrire la suite.`,
    });
  }

  // Legacy: activity-volume milestone. Not release-authorized under #233.
  const walks = entries.filter((e) => e.type === 'walk_recorded').length;
  if (walks >= 100 && !existingKinds.has('walks_100')) {
    candidates.push({
      milestoneKind: 'walks_100',
      title: '100 balades enregistrées',
      content: `Vous avez accompagné ${DOG.name} sur 100 sorties. Beau rythme !`,
    });
  }

  // Legacy automatic calendar milestone. Future Memories flow requires explicit
  // Owner confirmation before durable relationship-history creation.
  if (DOG.birthDate && isSameDayMonth(DOG.birthDate, now) && !existingKinds.has(`birthday_${now.getFullYear()}`)) {
    const age = now.getFullYear() - new Date(DOG.birthDate).getFullYear();
    candidates.push({
      milestoneKind: `birthday_${now.getFullYear()}`,
      title: `${DOG.name} a ${age} ${age === 1 ? 'an' : 'ans'} aujourd’hui`,
      content: `Une année de plus passée ensemble. Pensez à ajouter un souvenir du jour.`,
    });
  }

  // Legacy automatic calendar milestone. Same confirmation rule as above.
  if (DOG.adoptionDate && isSameDayMonth(DOG.adoptionDate, now) && !existingKinds.has(`adoption_${now.getFullYear()}`)) {
    const years = now.getFullYear() - new Date(DOG.adoptionDate).getFullYear();
    candidates.push({
      milestoneKind: `adoption_${now.getFullYear()}`,
      title: `${years} ${years === 1 ? 'an' : 'ans'} avec ${DOG.name}`,
      content: `Vous avez adopté ${DOG.name} il y a ${years} ${years === 1 ? 'an' : 'ans'} jour pour jour.`,
    });
  }

  return candidates;
}

/** @deprecated Legacy auto-generated milestone conversion. Do not use in launch flows. */
export function milestoneToEntry(candidate: MilestoneCandidate, occurredAt: string = new Date().toISOString()): MilestoneEntry {
  return {
    id: `milestone-${candidate.milestoneKind}-${Date.now()}`,
    type: 'milestone',
    occurredAt,
    title: candidate.title,
    content: candidate.content,
    milestoneKind: candidate.milestoneKind,
    isAutoGenerated: true,
  };
}
