/**
 * EMOPET Breed Knowledge Seed Data - Part 1 (Breeds 1-40)
 * Top 80 breeds in France, first half.
 *
 * Sources: FCI standards, breed-specific literature, veterinary references.
 * All onboardingTips and funFacts are in FRENCH.
 */

export interface BreedKnowledge {
  breedId: string;
  fciNumber: number | null;
  displayNameFr: string;
  displayNameEn: string;
  sizeClass: 'xs' | 'small' | 'medium' | 'large' | 'giant';
  weightMinKg: number | null;
  weightMaxKg: number | null;
  heightMinCm: number | null;
  heightMaxCm: number | null;
  isBrachycephalic: boolean;
  isLongBacked: boolean;
  isGiant: boolean;
  furLength: 'hairless' | 'short' | 'medium' | 'long' | 'wire' | 'curly' | null;
  furDensity: 'sparse' | 'moderate' | 'dense' | 'very_dense' | null;
  hasDoubleCoat: boolean;
  furContactClass: 'FC-1' | 'FC-2' | 'FC-3' | null;
  sheddingLevel: 'none' | 'low' | 'moderate' | 'heavy' | 'seasonal_heavy' | null;
  activityLevel: 'low' | 'moderate' | 'high' | 'very_high' | null;
  dailyExerciseMinMinutes: number | null;
  dailyExerciseMaxMinutes: number | null;
  dailyWalkKmMin: number | null;
  dailyWalkKmMax: number | null;
  exerciseTypePreference: string[];
  separationAnxietyTendency: 'low' | 'moderate' | 'high' | null;
  vocalizationTendency: 'quiet' | 'moderate' | 'vocal' | 'very_vocal' | null;
  sociabilityDogs: 'low' | 'moderate' | 'high' | null;
  sociabilityHumans: 'reserved' | 'moderate' | 'friendly' | 'very_friendly' | null;
  trainability: 'independent' | 'moderate' | 'eager' | 'very_eager' | null;
  energyIndoor: 'calm' | 'moderate' | 'active' | null;
  destructivenessTendency: 'low' | 'moderate' | 'high' | null;
  heatSensitivity: 'low' | 'moderate' | 'high' | 'very_high' | null;
  coldSensitivity: 'low' | 'moderate' | 'high' | null;
  heatAlertThresholdC: number | null;
  commonBreedConcerns: string[];
  lifespanMinYears: number | null;
  lifespanMaxYears: number | null;
  onboardingTips: string[];
  funFacts: string[];
  breedGroupFci: string | null;
  originCountry: string | null;
  dataCompleteness: number;
  source: string;
}

export const BREED_KNOWLEDGE_PART1: BreedKnowledge[] = [
  // ── 1. Berger Allemand ──────────────────────────────────────────────
  {
    breedId: 'berger-allemand',
    fciNumber: 166,
    displayNameFr: 'Berger Allemand',
    displayNameEn: 'German Shepherd',
    sizeClass: 'large',
    weightMinKg: 22,
    weightMaxKg: 40,
    heightMinCm: 55,
    heightMaxCm: 65,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 10,
    exerciseTypePreference: ['running', 'fetch', 'tracking', 'agility'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'moderate',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'skin', 'cardiac'],
    lifespanMinYears: 9,
    lifespanMaxYears: 13,
    onboardingTips: [
      'Proposez-lui au moins deux longues promenades par jour pour canaliser son energie.',
      'Variez les activites mentales : pistage, recherche de jouets, jeux d\'obeissance.',
      'Brossez son pelage deux a trois fois par semaine, et quotidiennement en periode de mue.',
      'Commencez la socialisation des le plus jeune age pour un chien equilibre.',
    ],
    funFacts: [
      'Le Berger Allemand est la race la plus utilisee par les forces de l\'ordre et l\'armee dans le monde.',
      'Rin Tin Tin, un Berger Allemand sauve d\'un champ de bataille en 1918, est devenu une star de cinema a Hollywood.',
      'Leur odorat est environ 10 000 fois plus sensible que celui de l\'homme.',
    ],
    breedGroupFci: 'shepherd',
    originCountry: 'DE',
    dataCompleteness: 0.95,
    source: 'fci-standard-166',
  },

  // ── 2. Berger Australien ────────────────────────────────────────────
  {
    breedId: 'berger-australien',
    fciNumber: 342,
    displayNameFr: 'Berger Australien',
    displayNameEn: 'Australian Shepherd',
    sizeClass: 'medium',
    weightMinKg: 18,
    weightMaxKg: 30,
    heightMinCm: 46,
    heightMaxCm: 58,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 12,
    exerciseTypePreference: ['running', 'agility', 'frisbee', 'herding'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'very_eager',
    energyIndoor: 'active',
    destructivenessTendency: 'high',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['eye', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Prevoyez au moins 1h30 d\'activite physique quotidienne pour eviter les comportements destructeurs.',
      'Stimulez-le intellectuellement avec des jeux de pistage, des puzzles ou de l\'agility.',
      'Brossez-le deux a trois fois par semaine pour eviter les noeuds dans son sous-poil.',
      'Attention aux yeux : surveillez regulierement leur clarte et leur proprete.',
    ],
    funFacts: [
      'Malgre son nom, le Berger Australien a ete developpe aux Etats-Unis, pas en Australie.',
      'Cette race est souvent choisie pour les competitions d\'agility grace a son agilite exceptionnelle.',
      'Les Bergers Australiens peuvent avoir des yeux vairons, un oeil bleu et un oeil marron.',
    ],
    breedGroupFci: 'shepherd',
    originCountry: 'US',
    dataCompleteness: 0.95,
    source: 'fci-standard-342',
  },

  // ── 3. Labrador Retriever ───────────────────────────────────────────
  {
    breedId: 'labrador-retriever',
    fciNumber: 122,
    displayNameFr: 'Labrador Retriever',
    displayNameEn: 'Labrador Retriever',
    sizeClass: 'large',
    weightMinKg: 25,
    weightMaxKg: 36,
    heightMinCm: 54,
    heightMaxCm: 57,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'heavy',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 10,
    exerciseTypePreference: ['swimming', 'fetch', 'running', 'hiking'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'eye', 'skin'],
    lifespanMinYears: 10,
    lifespanMaxYears: 12,
    onboardingTips: [
      'Surveillez sa ration alimentaire : le Labrador a une forte tendance a l\'embonpoint.',
      'Offrez-lui des activites aquatiques si possible, c\'est un nageur ne.',
      'Brossez-le une fois par semaine minimum pour gerer la perte de poils.',
      'Proposez-lui des jouets a macher robustes pour satisfaire son besoin de mastication.',
    ],
    funFacts: [
      'Le Labrador possede une queue dite "de loutre" qui lui sert de gouvernail dans l\'eau.',
      'C\'est la race la plus populaire au monde depuis plusieurs decennies.',
      'Les Labradors sont les chiens guides les plus utilises grace a leur temperament doux.',
    ],
    breedGroupFci: 'retriever',
    originCountry: 'GB',
    dataCompleteness: 0.95,
    source: 'fci-standard-122',
  },

  // ── 4. Golden Retriever ─────────────────────────────────────────────
  {
    breedId: 'golden-retriever',
    fciNumber: 111,
    displayNameFr: 'Golden Retriever',
    displayNameEn: 'Golden Retriever',
    sizeClass: 'large',
    weightMinKg: 25,
    weightMaxKg: 34,
    heightMinCm: 51,
    heightMaxCm: 61,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'heavy',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 10,
    exerciseTypePreference: ['swimming', 'fetch', 'running', 'hiking'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'cardiac', 'skin'],
    lifespanMinYears: 10,
    lifespanMaxYears: 12,
    onboardingTips: [
      'Brossez son poil long au moins trois fois par semaine pour eviter les noeuds.',
      'Comme le Labrador, surveillez son poids : c\'est une race gourmande.',
      'Proposez-lui des jeux de rapport : il adore rapporter des objets.',
      'Verifiez regulierement ses oreilles tombantes pour prevenir l\'humidite.',
    ],
    funFacts: [
      'Le Golden Retriever a ete cree en Ecosse au XIXe siecle pour la chasse au gibier d\'eau.',
      'C\'est l\'une des races les plus utilisees en zootherapie et comme chien de confort.',
      'Les Golden Retrievers gardent un temperament joueur bien au-dela de l\'age adulte.',
    ],
    breedGroupFci: 'retriever',
    originCountry: 'GB',
    dataCompleteness: 0.95,
    source: 'fci-standard-111',
  },

  // ── 5. Bouledogue Francais ──────────────────────────────────────────
  {
    breedId: 'bouledogue-francais',
    fciNumber: 101,
    displayNameFr: 'Bouledogue Francais',
    displayNameEn: 'French Bulldog',
    sizeClass: 'small',
    weightMinKg: 8,
    weightMaxKg: 14,
    heightMinCm: 24,
    heightMaxCm: 35,
    isBrachycephalic: true,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'moderate',
    activityLevel: 'low',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 40,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 3,
    exerciseTypePreference: ['short_walks', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'very_friendly',
    trainability: 'moderate',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'very_high',
    coldSensitivity: 'high',
    heatAlertThresholdC: 20,
    commonBreedConcerns: ['respiratory', 'skin', 'eye', 'joint'],
    lifespanMinYears: 10,
    lifespanMaxYears: 12,
    onboardingTips: [
      'Evitez les efforts physiques par temps chaud : sa morphologie le rend sensible a la chaleur.',
      'Nettoyez regulierement les plis de son visage pour eviter les irritations.',
      'Privilegiez les promenades courtes et fractionnees plutot qu\'un long effort.',
      'Gardez-le au frais en ete avec un acces permanent a l\'eau fraiche et a l\'ombre.',
      'Attention lors des voyages en avion : les races brachycephales sont a point de vigilance.',
    ],
    funFacts: [
      'Le Bouledogue Francais descend du Bulldog anglais importe par des dentellieres anglaises a Nottingham au XIXe siecle.',
      'Malgre sa petite taille, c\'est un excellent chien d\'vigilance qui previent ses maitres des visiteurs.',
      'Il est surnomme le "clown" en raison de son temperament joueur et espiegle.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'FR',
    dataCompleteness: 0.95,
    source: 'fci-standard-101',
  },

  // ── 6. Cavalier King Charles Spaniel ────────────────────────────────
  {
    breedId: 'cavalier-king-charles-spaniel',
    fciNumber: 136,
    displayNameFr: 'Cavalier King Charles Spaniel',
    displayNameEn: 'Cavalier King Charles Spaniel',
    sizeClass: 'small',
    weightMinKg: 5,
    weightMaxKg: 8,
    heightMinCm: 30,
    heightMaxCm: 33,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-3',
    sheddingLevel: 'moderate',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 30,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 2,
    dailyWalkKmMax: 5,
    exerciseTypePreference: ['walking', 'play', 'fetch'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['cardiac', 'eye', 'ear'],
    lifespanMinYears: 9,
    lifespanMaxYears: 14,
    onboardingTips: [
      'C\'est un chien tres attache a son maitre : evitez de le laisser seul trop longtemps.',
      'Brossez son poil soyeux tous les deux jours pour eviter les noeuds derriere les oreilles.',
      'Verifiez regulierement ses oreilles tombantes pour prevenir les infections.',
      'Des promenades moderees suffisent, mais il apprecie aussi les jeux en interieur.',
    ],
    funFacts: [
      'Le Cavalier King Charles tient son nom du roi Charles II d\'Angleterre qui ne se separait jamais de ses chiens.',
      'C\'est l\'une des races preferees des personnes agees grace a son temperament calme et affectueux.',
      'Il possede une expression faciale naturellement douce qui lui donne un air perpetuellement attendrissant.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'GB',
    dataCompleteness: 0.95,
    source: 'fci-standard-136',
  },

  // ── 7. Beagle ───────────────────────────────────────────────────────
  {
    breedId: 'beagle',
    fciNumber: 161,
    displayNameFr: 'Beagle',
    displayNameEn: 'Beagle',
    sizeClass: 'medium',
    weightMinKg: 9,
    weightMaxKg: 11,
    heightMinCm: 33,
    heightMaxCm: 40,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-1',
    sheddingLevel: 'moderate',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 4,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['walking', 'tracking', 'running', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'moderate',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['ear', 'eye', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Le Beagle suit son nez : gardez-le toujours en laisse ou dans un espace clos.',
      'C\'est un chien de meute, il supporte mal la solitude. Pensez a lui offrir de la compagnie.',
      'Surveillez son alimentation : il a une forte tendance a la gourmandise.',
      'Nettoyez ses oreilles tombantes chaque semaine pour prevenir les infections.',
    ],
    funFacts: [
      'Le Beagle est utilise dans les aeroports pour detecter des denrees alimentaires interdites grace a son flair exceptionnel.',
      'Snoopy, le celebre personnage de bande dessinee, est un Beagle.',
      'Un Beagle peut distinguer et memoriser environ 50 odeurs differentes simultanement.',
    ],
    breedGroupFci: 'hound',
    originCountry: 'GB',
    dataCompleteness: 0.95,
    source: 'fci-standard-161',
  },

  // ── 8. Border Collie ────────────────────────────────────────────────
  {
    breedId: 'border-collie',
    fciNumber: 297,
    displayNameFr: 'Border Collie',
    displayNameEn: 'Border Collie',
    sizeClass: 'medium',
    weightMinKg: 14,
    weightMaxKg: 22,
    heightMinCm: 46,
    heightMaxCm: 53,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 90,
    dailyExerciseMaxMinutes: 150,
    dailyWalkKmMin: 6,
    dailyWalkKmMax: 15,
    exerciseTypePreference: ['herding', 'agility', 'frisbee', 'running', 'tracking'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'very_eager',
    energyIndoor: 'active',
    destructivenessTendency: 'high',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['eye', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'C\'est le chien le plus intelligent du monde : il a besoin de stimulation mentale quotidienne.',
      'Sans activite suffisante, il developpera des comportements obsessionnels (poursuite d\'ombres, de lumieres).',
      'L\'agility et le frisbee sont d\'excellentes activites pour canaliser son energie debordante.',
      'Brossez-le regulierement, surtout en periode de mue saisonniere.',
      'Evitez les environnements sedentaires : ce chien n\'est pas fait pour l\'appartement sans sorties longues.',
    ],
    funFacts: [
      'Le Border Collie est considere comme la race de chien la plus intelligente au monde.',
      'Un Border Collie nomme Chaser a appris plus de 1 000 mots de vocabulaire.',
      'Son regard fixe et intense, appele "oeil", est utilise pour contrôler les troupeaux sans contact.',
    ],
    breedGroupFci: 'shepherd',
    originCountry: 'GB',
    dataCompleteness: 0.95,
    source: 'fci-standard-297',
  },

  // ── 9. Jack Russell Terrier ─────────────────────────────────────────
  {
    breedId: 'jack-russell-terrier',
    fciNumber: 345,
    displayNameFr: 'Jack Russell Terrier',
    displayNameEn: 'Jack Russell Terrier',
    sizeClass: 'small',
    weightMinKg: 5,
    weightMaxKg: 6,
    heightMinCm: 25,
    heightMaxCm: 30,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: true,
    furContactClass: 'FC-1',
    sheddingLevel: 'moderate',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 4,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['running', 'digging', 'agility', 'fetch', 'play'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'moderate',
    energyIndoor: 'active',
    destructivenessTendency: 'high',
    heatSensitivity: 'low',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 28,
    commonBreedConcerns: ['eye', 'ear', 'joint'],
    lifespanMinYears: 13,
    lifespanMaxYears: 16,
    onboardingTips: [
      'Ne vous fiez pas a sa petite taille : c\'est un chien extremement energique qui a besoin de beaucoup d\'exercice.',
      'Securisez votre jardin : le Jack Russell est capable de creuser sous les clotures et de sauter tres haut.',
      'Proposez-lui des jeux d\'intelligence pour occuper son esprit vif.',
      'Soyez ferme et coherent dans son education, il peut etre tetu.',
    ],
    funFacts: [
      'Le Jack Russell a ete cree par le reverend John Russell au XIXe siecle pour la chasse au renard.',
      'Malgre sa petite taille, il peut sauter jusqu\'a 1,50 metre de hauteur.',
      'C\'est l\'une des races les plus longevives, certains individus depassant 18 ans.',
    ],
    breedGroupFci: 'terrier',
    originCountry: 'GB',
    dataCompleteness: 0.95,
    source: 'fci-standard-345',
  },

  // ── 10. Staffordshire Bull Terrier ──────────────────────────────────
  {
    breedId: 'staffordshire-bull-terrier',
    fciNumber: 76,
    displayNameFr: 'Staffordshire Bull Terrier',
    displayNameEn: 'Staffordshire Bull Terrier',
    sizeClass: 'medium',
    weightMinKg: 11,
    weightMaxKg: 17,
    heightMinCm: 35,
    heightMaxCm: 40,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'low',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 4,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['running', 'tug', 'fetch', 'agility'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'low',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['skin', 'eye', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 14,
    onboardingTips: [
      'Socialisez-le tres tôt avec d\'autres chiens pour favoriser de bonnes interactions.',
      'C\'est un chien tres affectueux avec les humains, surnomme le "nanny dog" en Angleterre.',
      'Proposez-lui des jouets tres robustes car il a une machoire puissante.',
      'Il supporte mal la solitude : evitez de le laisser seul plus de quelques heures.',
    ],
    funFacts: [
      'En Angleterre, le Staffordshire Bull Terrier est surnomme "nanny dog" en raison de sa douceur legendaire avec les enfants.',
      'C\'est l\'une des races les plus populaires au Royaume-Uni depuis des decennies.',
      'Malgre sa musculature impressionnante, c\'est un chien qui adore les calins.',
    ],
    breedGroupFci: 'terrier',
    originCountry: 'GB',
    dataCompleteness: 0.93,
    source: 'fci-standard-76',
  },

  // ── 11. Yorkshire Terrier ───────────────────────────────────────────
  {
    breedId: 'yorkshire-terrier',
    fciNumber: 86,
    displayNameFr: 'Yorkshire Terrier',
    displayNameEn: 'Yorkshire Terrier',
    sizeClass: 'xs',
    weightMinKg: 2,
    weightMaxKg: 3.2,
    heightMinCm: 18,
    heightMaxCm: 23,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-3',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 40,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 3,
    exerciseTypePreference: ['walking', 'play', 'fetch'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'moderate',
    energyIndoor: 'active',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'high',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'eye', 'skin'],
    lifespanMinYears: 13,
    lifespanMaxYears: 16,
    onboardingTips: [
      'Son poil pousse en continu comme des cheveux : un brossage quotidien est indispensable.',
      'Protegez-le du froid en hiver avec un manteau adapte a sa petite taille.',
      'Attention aux sauts depuis les canapes et lits : ses os sont fragiles.',
      'Un toilettage regulier chez un professionnel est recommande tous les deux mois.',
    ],
    funFacts: [
      'Le Yorkshire Terrier etait a l\'origine utilise pour chasser les rats dans les mines du Yorkshire en Angleterre.',
      'Malgre sa petite taille, il a un temperament de terrier courageux et affirme.',
      'Son poil soyeux est hypoallergenique et se rapproche davantage du cheveu humain que du poil de chien.',
    ],
    breedGroupFci: 'terrier',
    originCountry: 'GB',
    dataCompleteness: 0.93,
    source: 'fci-standard-86',
  },

  // ── 12. Chihuahua ───────────────────────────────────────────────────
  {
    breedId: 'chihuahua',
    fciNumber: 218,
    displayNameFr: 'Chihuahua',
    displayNameEn: 'Chihuahua',
    sizeClass: 'xs',
    weightMinKg: 1.5,
    weightMaxKg: 3,
    heightMinCm: 15,
    heightMaxCm: 23,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'sparse',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 30,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 2,
    exerciseTypePreference: ['walking', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'low',
    sociabilityHumans: 'moderate',
    trainability: 'moderate',
    energyIndoor: 'active',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'high',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'cardiac', 'eye'],
    lifespanMinYears: 14,
    lifespanMaxYears: 18,
    onboardingTips: [
      'Protegez-le imperativement du froid : un manteau est necessaire des que la temperature baisse.',
      'Socialisez-le des son plus jeune age pour eviter les comportements craintifs ou agressifs.',
      'Attention aux chutes : ne le laissez pas sauter de hauteurs elevees.',
      'Privilegiez des croquettes adaptees aux tres petites races pour eviter les problemes dentaires.',
    ],
    funFacts: [
      'Le Chihuahua est la plus petite race de chien au monde.',
      'Il tire son nom de l\'etat de Chihuahua au Mexique ou il a ete decouvert au XIXe siecle.',
      'Les Chihuahuas ont la plus grande taille de cerveau par rapport a leur corps de toutes les races canines.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'MX',
    dataCompleteness: 0.93,
    source: 'fci-standard-218',
  },

  // ── 13. Cocker Anglais ──────────────────────────────────────────────
  {
    breedId: 'cocker-anglais',
    fciNumber: 5,
    displayNameFr: 'Cocker Anglais',
    displayNameEn: 'English Cocker Spaniel',
    sizeClass: 'medium',
    weightMinKg: 12,
    weightMaxKg: 14.5,
    heightMinCm: 38,
    heightMaxCm: 41,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'moderate',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'moderate',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 4,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['walking', 'fetch', 'swimming', 'tracking'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['ear', 'eye', 'skin'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Ses longues oreilles necessitent un nettoyage hebdomadaire pour eviter les infections.',
      'Brossez son poil mi-long deux a trois fois par semaine pour eviter les noeuds.',
      'C\'est un chien joyeux et energique qui a besoin de promenades variees.',
      'Utilisez une gamelle etroite pour eviter que ses oreilles trempent dans la nourriture.',
    ],
    funFacts: [
      'Le nom "Cocker" vient de "woodcock" (becasse), le gibier qu\'il etait specialise a chasser.',
      'C\'est l\'une des races de spaniels les plus anciennes, avec des origines remontant au XIVe siecle.',
      'Le Cocker Anglais remue la queue quasi en permanence, signe de son temperament joyeux.',
    ],
    breedGroupFci: 'gundog',
    originCountry: 'GB',
    dataCompleteness: 0.93,
    source: 'fci-standard-5',
  },

  // ── 14. Setter Anglais ──────────────────────────────────────────────
  {
    breedId: 'setter-anglais',
    fciNumber: 2,
    displayNameFr: 'Setter Anglais',
    displayNameEn: 'English Setter',
    sizeClass: 'large',
    weightMinKg: 20,
    weightMaxKg: 36,
    heightMinCm: 61,
    heightMaxCm: 68,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-3',
    sheddingLevel: 'moderate',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 10,
    exerciseTypePreference: ['running', 'hunting', 'fetch', 'hiking'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'calm',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['ear', 'joint', 'skin'],
    lifespanMinYears: 10,
    lifespanMaxYears: 12,
    onboardingTips: [
      'C\'est un chien de chasse qui a besoin de grands espaces pour s\'epanouir.',
      'Son poil long et soyeux demande un entretien regulier : brossage trois fois par semaine.',
      'Tres doux en interieur, il devient debordant d\'energie en exterieur.',
      'Verifiez ses oreilles tombantes chaque semaine.',
    ],
    funFacts: [
      'Le Setter Anglais est l\'un des plus anciens chiens d\'arret, avec des origines datant du XIVe siecle.',
      'Son nom vient de sa posture typique lorsqu\'il detecte du gibier : il "set" (se fige) en position basse.',
      'C\'est le chien de chasse prefere en France depuis de nombreuses annees.',
    ],
    breedGroupFci: 'gundog',
    originCountry: 'GB',
    dataCompleteness: 0.92,
    source: 'fci-standard-2',
  },

  // ── 15. Epagneul Breton ─────────────────────────────────────────────
  {
    breedId: 'epagneul-breton',
    fciNumber: 95,
    displayNameFr: 'Epagneul Breton',
    displayNameEn: 'Brittany Spaniel',
    sizeClass: 'medium',
    weightMinKg: 14,
    weightMaxKg: 18,
    heightMinCm: 46,
    heightMaxCm: 52,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'moderate',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'moderate',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 12,
    exerciseTypePreference: ['running', 'hunting', 'fetch', 'swimming', 'hiking'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['ear', 'joint', 'eye'],
    lifespanMinYears: 12,
    lifespanMaxYears: 14,
    onboardingTips: [
      'L\'Epagneul Breton est un chien sportif qui a besoin de courir chaque jour.',
      'Tres receptif a l\'education positive, il apprend vite et avec plaisir.',
      'Brossez-le une a deux fois par semaine pour entretenir son poil mi-long.',
      'Il s\'adapte a la vie en famille mais a besoin d\'un acces regulier a la nature.',
    ],
    funFacts: [
      'L\'Epagneul Breton est le chien de chasse le plus populaire en France.',
      'C\'est la plus petite race de chiens d\'arret au monde.',
      'Originaire de Bretagne, il est mentionne dans des textes et peintures des le XVIIe siecle.',
    ],
    breedGroupFci: 'gundog',
    originCountry: 'FR',
    dataCompleteness: 0.93,
    source: 'fci-standard-95',
  },

  // ── 16. Husky Siberien ──────────────────────────────────────────────
  {
    breedId: 'husky-siberien',
    fciNumber: 270,
    displayNameFr: 'Husky Siberien',
    displayNameEn: 'Siberian Husky',
    sizeClass: 'medium',
    weightMinKg: 16,
    weightMaxKg: 28,
    heightMinCm: 50,
    heightMaxCm: 60,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'very_dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 15,
    exerciseTypePreference: ['running', 'sledding', 'hiking', 'canicross'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'high',
    sociabilityHumans: 'friendly',
    trainability: 'independent',
    energyIndoor: 'active',
    destructivenessTendency: 'high',
    heatSensitivity: 'high',
    coldSensitivity: 'low',
    heatAlertThresholdC: 22,
    commonBreedConcerns: ['eye', 'skin', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 14,
    onboardingTips: [
      'Le Husky est un chien independant, pas un chien obeissant : soyez patient et coherent.',
      'Ne le detachez jamais en promenade : son instinct de fugue est tres fort.',
      'En ete, limitez les efforts physiques aux heures fraiches de la journee.',
      'Son sous-poil tres dense necessite un brossage quotidien en periode de mue.',
      'Prevoyez un jardin bien cloture car il peut escalader ou creuser sous les clotures.',
    ],
    funFacts: [
      'Le Husky Siberien peut courir plus de 150 km par jour en tractant un traineau.',
      'En 1925, des Huskys ont transporte un serum antidiphterique sur plus de 1 000 km en Alaska, sauvant la ville de Nome.',
      'Contrairement a la plupart des chiens, le Husky hurle plutôt qu\'il n\'aboie.',
    ],
    breedGroupFci: 'spitz',
    originCountry: 'RU',
    dataCompleteness: 0.95,
    source: 'fci-standard-270',
  },

  // ── 17. Shih Tzu ────────────────────────────────────────────────────
  {
    breedId: 'shih-tzu',
    fciNumber: 208,
    displayNameFr: 'Shih Tzu',
    displayNameEn: 'Shih Tzu',
    sizeClass: 'small',
    weightMinKg: 4,
    weightMaxKg: 7.5,
    heightMinCm: 20,
    heightMaxCm: 28,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'low',
    activityLevel: 'low',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 40,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 3,
    exerciseTypePreference: ['walking', 'play'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'moderate',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'high',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 23,
    commonBreedConcerns: ['eye', 'ear', 'skin', 'respiratory'],
    lifespanMinYears: 10,
    lifespanMaxYears: 16,
    onboardingTips: [
      'Son poil long necessite un brossage quotidien ou une coupe courte reguliere.',
      'Nettoyez ses yeux chaque jour pour eviter les coulures et irritations.',
      'Evitez les efforts intenses par temps chaud en raison de son museau court.',
      'C\'est un excellent chien d\'appartement, ideal pour les personnes sedentaires.',
    ],
    funFacts: [
      'Le Shih Tzu etait le chien favori des empereurs chinois de la dynastie Ming.',
      'Son nom signifie "chien lion" en chinois, en reference a son allure majestueuse.',
      'Tous les Shih Tzu modernes descendent de seulement 14 chiens sauves de Chine dans les annees 1930.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'CN',
    dataCompleteness: 0.93,
    source: 'fci-standard-208',
  },

  // ── 18. Bouvier Bernois ─────────────────────────────────────────────
  {
    breedId: 'bouvier-bernois',
    fciNumber: 45,
    displayNameFr: 'Bouvier Bernois',
    displayNameEn: 'Bernese Mountain Dog',
    sizeClass: 'large',
    weightMinKg: 35,
    weightMaxKg: 55,
    heightMinCm: 58,
    heightMaxCm: 70,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'very_dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 45,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 3,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['walking', 'hiking', 'carting', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'high',
    coldSensitivity: 'low',
    heatAlertThresholdC: 22,
    commonBreedConcerns: ['joint', 'cardiac', 'eye'],
    lifespanMinYears: 6,
    lifespanMaxYears: 10,
    onboardingTips: [
      'Sa croissance est rapide : evitez les efforts intenses pendant sa premiere annee.',
      'Brossez son poil long et dense au moins trois fois par semaine.',
      'Soyez particulierement vigilant par temps chaud : il supporte tres mal la chaleur.',
      'C\'est un chien sensible qui repond mieux a une education douce et positive.',
      'Prevoyez un budget sante : cette race peut etre sujette a des soucis articulaires.',
    ],
    funFacts: [
      'Le Bouvier Bernois etait utilise comme chien de trait pour tirer les charrettes de lait dans les Alpes suisses.',
      'C\'est l\'une des quatre races de bouviers suisses, reconnaissable a sa robe tricolore.',
      'Malgre sa grande taille, il reste un "chien de canape" qui adore se blottir contre ses maitres.',
    ],
    breedGroupFci: 'mountain',
    originCountry: 'CH',
    dataCompleteness: 0.95,
    source: 'fci-standard-45',
  },

  // ── 19. Boxer ───────────────────────────────────────────────────────
  {
    breedId: 'boxer',
    fciNumber: 144,
    displayNameFr: 'Boxer',
    displayNameEn: 'Boxer',
    sizeClass: 'large',
    weightMinKg: 25,
    weightMaxKg: 32,
    heightMinCm: 53,
    heightMaxCm: 63,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'moderate',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 4,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['running', 'play', 'fetch', 'agility'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'active',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'high',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 23,
    commonBreedConcerns: ['cardiac', 'joint', 'skin'],
    lifespanMinYears: 8,
    lifespanMaxYears: 12,
    onboardingTips: [
      'Le Boxer est un eternel chiot : il garde un temperament joueur et energique longtemps.',
      'Evitez les exercices intenses par temps chaud en raison de son museau court.',
      'Son poil court ne necessite qu\'un brossage hebdomadaire.',
      'Tres bon avec les enfants, il peut cependant etre brusque dans ses jeux : surveillez les interactions.',
    ],
    funFacts: [
      'Le Boxer tire son nom de sa tendance a se dresser sur ses pattes arrieres et a "boxer" avec ses pattes avant.',
      'C\'est l\'un des premiers chiens utilises comme chien policier en Allemagne.',
      'Le Boxer est connu pour son expression faciale unique, souvent comparee a celle d\'un humain perplexe.',
    ],
    breedGroupFci: 'molossoid',
    originCountry: 'DE',
    dataCompleteness: 0.93,
    source: 'fci-standard-144',
  },

  // ── 20. Caniche ─────────────────────────────────────────────────────
  {
    breedId: 'caniche',
    fciNumber: 172,
    displayNameFr: 'Caniche',
    displayNameEn: 'Poodle',
    sizeClass: 'medium',
    weightMinKg: 6,
    weightMaxKg: 22,
    heightMinCm: 24,
    heightMaxCm: 60,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'curly',
    furDensity: 'dense',
    hasDoubleCoat: false,
    furContactClass: 'FC-3',
    sheddingLevel: 'none',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 40,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 3,
    dailyWalkKmMax: 6,
    exerciseTypePreference: ['walking', 'swimming', 'agility', 'fetch'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['eye', 'ear', 'skin', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Son poil bouclé ne tombe pas mais pousse en continu : un toilettage regulier est essentiel.',
      'Faites-le toiletter par un professionnel toutes les 6 a 8 semaines.',
      'C\'est l\'un des chiens les plus intelligents : il adore apprendre de nouveaux tours.',
      'Verifiez ses oreilles regulierement car son poil dense peut pieger l\'humidite.',
    ],
    funFacts: [
      'Le Caniche est la deuxieme race la plus intelligente au monde apres le Border Collie.',
      'Son nom vient de l\'allemand "pudel" qui signifie "eclabousser" car c\'etait un chien d\'eau.',
      'Le Caniche existe en quatre tailles officielles : grand, moyen, nain et toy.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'FR',
    dataCompleteness: 0.93,
    source: 'fci-standard-172',
  },

  // ── 21. Berger Belge Malinois ───────────────────────────────────────
  {
    breedId: 'berger-belge-malinois',
    fciNumber: 15,
    displayNameFr: 'Berger Belge Malinois',
    displayNameEn: 'Belgian Malinois',
    sizeClass: 'large',
    weightMinKg: 20,
    weightMaxKg: 30,
    heightMinCm: 56,
    heightMaxCm: 66,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 90,
    dailyExerciseMaxMinutes: 150,
    dailyWalkKmMin: 6,
    dailyWalkKmMax: 15,
    exerciseTypePreference: ['running', 'tracking', 'agility', 'protection_sport', 'fetch'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'moderate',
    trainability: 'very_eager',
    energyIndoor: 'active',
    destructivenessTendency: 'high',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'eye', 'skin'],
    lifespanMinYears: 12,
    lifespanMaxYears: 14,
    onboardingTips: [
      'Ce chien necessite un maitre experimente et une activite physique intense quotidienne.',
      'Canalisez son energie dans des sports canins : ring, agility, pistage.',
      'La socialisation precoce est indispensable pour un Malinois equilibre.',
      'Sans stimulation mentale et physique suffisante, il peut devenir tres destructeur.',
      'Brossez-le une a deux fois par semaine, plus en periode de mue.',
    ],
    funFacts: [
      'Le Malinois est le chien prefere des forces speciales et des unites d\'elite dans le monde entier.',
      'Un Malinois nomme Cairo a participe a l\'operation qui a conduit a la neutralisation de Ben Laden en 2011.',
      'Le Malinois peut sauter a plus de 3 metres de hauteur sans elan.',
    ],
    breedGroupFci: 'shepherd',
    originCountry: 'BE',
    dataCompleteness: 0.95,
    source: 'fci-standard-15',
  },

  // ── 22. Teckel ──────────────────────────────────────────────────────
  {
    breedId: 'teckel',
    fciNumber: 148,
    displayNameFr: 'Teckel',
    displayNameEn: 'Dachshund',
    sizeClass: 'small',
    weightMinKg: 4,
    weightMaxKg: 9,
    heightMinCm: 13,
    heightMaxCm: 27,
    isBrachycephalic: false,
    isLongBacked: true,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 30,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 2,
    dailyWalkKmMax: 5,
    exerciseTypePreference: ['walking', 'tracking', 'digging', 'play'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'independent',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'eye', 'cardiac'],
    lifespanMinYears: 12,
    lifespanMaxYears: 16,
    onboardingTips: [
      'IMPORTANT : evitez absolument les sauts et les escaliers pour proteger sa colonne vertebrale.',
      'Installez des rampes pour l\'aider a monter sur le canape ou le lit.',
      'Surveillez strictement son poids : le surpoids aggrave les problemes de dos.',
      'C\'est un chien tetu mais intelligent : utilisez la motivation par la nourriture pour l\'eduquer.',
    ],
    funFacts: [
      'Le Teckel a ete cree pour chasser les blaireaux dans leurs terriers, d\'ou sa forme allongee.',
      'Son nom allemand "Dachshund" signifie litteralement "chien a blaireau".',
      'Il existe en trois varietes de poils : ras, long et dur.',
    ],
    breedGroupFci: 'hound',
    originCountry: 'DE',
    dataCompleteness: 0.93,
    source: 'fci-standard-148',
  },

  // ── 23. Rottweiler ──────────────────────────────────────────────────
  {
    breedId: 'rottweiler',
    fciNumber: 147,
    displayNameFr: 'Rottweiler',
    displayNameEn: 'Rottweiler',
    sizeClass: 'large',
    weightMinKg: 35,
    weightMaxKg: 60,
    heightMinCm: 56,
    heightMaxCm: 68,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'moderate',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 4,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['walking', 'running', 'fetch', 'tracking', 'carting'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'low',
    sociabilityHumans: 'moderate',
    trainability: 'eager',
    energyIndoor: 'calm',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'cardiac', 'eye'],
    lifespanMinYears: 8,
    lifespanMaxYears: 10,
    onboardingTips: [
      'La socialisation precoce et l\'education ferme mais bienveillante sont essentielles.',
      'Ce chien a besoin d\'un maitre coherent et assure pour s\'epanouir.',
      'Surveillez son poids : il peut facilement prendre de l\'embonpoint.',
      'Malgre les idees recues, c\'est un chien affectueux et loyal en famille.',
    ],
    funFacts: [
      'Le Rottweiler descend des chiens de troupeau romains qui accompagnaient les legions a travers les Alpes.',
      'Il tire son nom de la ville allemande de Rottweil, ou il gardait le betail des bouchers.',
      'C\'est l\'une des races les plus anciennes utilisees comme chien de garde et de trait.',
    ],
    breedGroupFci: 'molossoid',
    originCountry: 'DE',
    dataCompleteness: 0.93,
    source: 'fci-standard-147',
  },

  // ── 24. Dobermann ───────────────────────────────────────────────────
  {
    breedId: 'dobermann',
    fciNumber: 143,
    displayNameFr: 'Dobermann',
    displayNameEn: 'Dobermann',
    sizeClass: 'large',
    weightMinKg: 27,
    weightMaxKg: 45,
    heightMinCm: 63,
    heightMaxCm: 72,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'low',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 10,
    exerciseTypePreference: ['running', 'agility', 'tracking', 'fetch'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'moderate',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'high',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['cardiac', 'joint', 'skin'],
    lifespanMinYears: 10,
    lifespanMaxYears: 13,
    onboardingTips: [
      'Le Dobermann a besoin d\'un maitre present et attentif : il supporte mal la solitude.',
      'Son poil court et l\'absence de sous-poil le rendent sensible au froid : prevoyez un manteau en hiver.',
      'Canalisez son intelligence et son energie dans des activites structurees.',
      'La socialisation precoce est fondamentale pour un Dobermann equilibre.',
    ],
    funFacts: [
      'Le Dobermann a ete cree par Karl Friedrich Louis Dobermann, un percepteur d\'impôts allemand qui voulait un chien de protection.',
      'C\'est l\'une des races les plus rapides parmi les grands chiens, capable d\'atteindre 40 km/h.',
      'Le Dobermann est la cinquieme race la plus intelligente au monde selon le classement de Stanley Coren.',
    ],
    breedGroupFci: 'pinscher',
    originCountry: 'DE',
    dataCompleteness: 0.93,
    source: 'fci-standard-143',
  },

  // ── 25. Dogue Allemand ──────────────────────────────────────────────
  {
    breedId: 'dogue-allemand',
    fciNumber: 235,
    displayNameFr: 'Dogue Allemand',
    displayNameEn: 'Great Dane',
    sizeClass: 'giant',
    weightMinKg: 45,
    weightMaxKg: 90,
    heightMinCm: 72,
    heightMaxCm: 86,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: true,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'moderate',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 40,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 3,
    dailyWalkKmMax: 6,
    exerciseTypePreference: ['walking', 'play', 'light_jogging'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'calm',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['joint', 'cardiac', 'eye'],
    lifespanMinYears: 6,
    lifespanMaxYears: 10,
    onboardingTips: [
      'Pendant la croissance (jusqu\'a 18-24 mois), evitez les exercices intenses pour proteger ses articulations.',
      'Fractionnez ses repas en 2-3 portions pour limiter les points de vigilance de torsion d\'estomac.',
      'Malgre sa taille imposante, c\'est un geant doux qui a besoin de contact humain.',
      'Prevoyez un budget alimentation et sante consequent adapte a sa taille geante.',
      'Un couchage orthopedique adapte est fortement recommande pour ses articulations.',
    ],
    funFacts: [
      'Le Dogue Allemand est le chien le plus grand du monde : le record est detenu par un individu mesurant 1,12 m au garrot.',
      'Scooby-Doo est un Dogue Allemand, tout comme Marmaduke.',
      'Malgre son nom, cette race est originaire d\'Allemagne et non du Danemark.',
    ],
    breedGroupFci: 'molossoid',
    originCountry: 'DE',
    dataCompleteness: 0.95,
    source: 'fci-standard-235',
  },

  // ── 26. Braque Allemand ─────────────────────────────────────────────
  {
    breedId: 'braque-allemand',
    fciNumber: 119,
    displayNameFr: 'Braque Allemand',
    displayNameEn: 'German Shorthaired Pointer',
    sizeClass: 'large',
    weightMinKg: 22,
    weightMaxKg: 32,
    heightMinCm: 58,
    heightMaxCm: 66,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: true,
    furContactClass: 'FC-1',
    sheddingLevel: 'moderate',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 12,
    exerciseTypePreference: ['running', 'hunting', 'swimming', 'fetch', 'hiking'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'friendly',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'low',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 28,
    commonBreedConcerns: ['joint', 'ear', 'eye'],
    lifespanMinYears: 12,
    lifespanMaxYears: 14,
    onboardingTips: [
      'Le Braque Allemand est un athlete ne qui a besoin de courir chaque jour.',
      'C\'est un chien polyvalent qui excelle en pistage, rapport et nage.',
      'Offrez-lui des exercices varies pour stimuler son corps et son esprit.',
      'Son poil court est facile d\'entretien : un brossage hebdomadaire suffit.',
    ],
    funFacts: [
      'Le Braque Allemand est considere comme le chien de chasse le plus polyvalent au monde.',
      'Il peut pointer, traquer et rapporter aussi bien sur terre que dans l\'eau.',
      'Cette race a ete creee au XIXe siecle en croisant des chiens d\'arret allemands avec des Pointers anglais.',
    ],
    breedGroupFci: 'gundog',
    originCountry: 'DE',
    dataCompleteness: 0.92,
    source: 'fci-standard-119',
  },

  // ── 27. Springer Anglais ────────────────────────────────────────────
  {
    breedId: 'springer-anglais',
    fciNumber: 125,
    displayNameFr: 'Springer Anglais',
    displayNameEn: 'English Springer Spaniel',
    sizeClass: 'medium',
    weightMinKg: 18,
    weightMaxKg: 25,
    heightMinCm: 46,
    heightMaxCm: 51,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'moderate',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'moderate',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 10,
    exerciseTypePreference: ['running', 'fetch', 'swimming', 'hunting', 'agility'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'very_eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['ear', 'eye', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 14,
    onboardingTips: [
      'Ses oreilles tombantes necessitent un nettoyage regulier pour eviter les infections.',
      'C\'est un chien infatigable qui a besoin de longues sorties quotidiennes.',
      'Brossez son poil mi-long deux a trois fois par semaine, surtout les franges.',
      'Il adore l\'eau : proposez-lui des activites aquatiques quand c\'est possible.',
    ],
    funFacts: [
      'Le nom "Springer" vient de sa technique de chasse : il fait "surgir" (spring) le gibier hors des fourrés.',
      'C\'est la plus ancienne race de spaniels sportifs britanniques.',
      'Le Springer Anglais est tres utilise comme chien de detection de drogue et d\'explosifs.',
    ],
    breedGroupFci: 'gundog',
    originCountry: 'GB',
    dataCompleteness: 0.92,
    source: 'fci-standard-125',
  },

  // ── 28. Terre-Neuve ─────────────────────────────────────────────────
  {
    breedId: 'terre-neuve',
    fciNumber: 50,
    displayNameFr: 'Terre-Neuve',
    displayNameEn: 'Newfoundland',
    sizeClass: 'giant',
    weightMinKg: 45,
    weightMaxKg: 70,
    heightMinCm: 63,
    heightMaxCm: 74,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: true,
    furLength: 'long',
    furDensity: 'very_dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 30,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 2,
    dailyWalkKmMax: 5,
    exerciseTypePreference: ['swimming', 'walking', 'carting', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'very_high',
    coldSensitivity: 'low',
    heatAlertThresholdC: 20,
    commonBreedConcerns: ['joint', 'cardiac', 'skin'],
    lifespanMinYears: 8,
    lifespanMaxYears: 10,
    onboardingTips: [
      'Attention a la chaleur : sa fourrure dense le rend extremement sensible aux temperatures elevees.',
      'Brossez-le au minimum trois fois par semaine pour eviter les noeuds dans son sous-poil epais.',
      'C\'est un nageur exceptionnel : l\'eau est son element naturel.',
      'Prevoyez un espace suffisant : ce geant a besoin de place malgre son calme.',
      'Soyez pret pour la bave : le Terre-Neuve bave abondamment, surtout quand il a chaud.',
    ],
    funFacts: [
      'Le Terre-Neuve possede des pattes palmees qui en font l\'un des meilleurs nageurs du monde canin.',
      'Il est utilise comme chien de sauvetage en mer dans de nombreux pays.',
      'Le chien de Napoleon aurait ete un Terre-Neuve qui lui aurait sauve la vie lors de sa fuite de l\'ile d\'Elbe.',
    ],
    breedGroupFci: 'molossoid',
    originCountry: 'CA',
    dataCompleteness: 0.95,
    source: 'fci-standard-50',
  },

  // ── 29. Akita Inu ───────────────────────────────────────────────────
  {
    breedId: 'akita-inu',
    fciNumber: 255,
    displayNameFr: 'Akita Inu',
    displayNameEn: 'Akita Inu',
    sizeClass: 'large',
    weightMinKg: 30,
    weightMaxKg: 45,
    heightMinCm: 58,
    heightMaxCm: 70,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'very_dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 45,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 3,
    dailyWalkKmMax: 7,
    exerciseTypePreference: ['walking', 'hiking', 'play'],
    separationAnxietyTendency: 'low',
    vocalizationTendency: 'quiet',
    sociabilityDogs: 'low',
    sociabilityHumans: 'reserved',
    trainability: 'independent',
    energyIndoor: 'calm',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'high',
    coldSensitivity: 'low',
    heatAlertThresholdC: 22,
    commonBreedConcerns: ['joint', 'eye', 'skin'],
    lifespanMinYears: 10,
    lifespanMaxYears: 13,
    onboardingTips: [
      'L\'Akita est un chien independant et fier : l\'education doit etre ferme, calme et respectueuse.',
      'La socialisation avec d\'autres chiens est fondamentale des le plus jeune age.',
      'C\'est un chien a un seul maitre : il est loyal mais peut etre distant avec les inconnus.',
      'Son sous-poil tres dense mue deux fois par an de maniere spectaculaire : preparez l\'aspirateur.',
    ],
    funFacts: [
      'Hachiko, l\'Akita le plus celebre, a attendu son maitre decede a la gare de Shibuya pendant 9 ans.',
      'Au Japon, l\'Akita Inu est considere comme un tresor national et un symbole de fidelite.',
      'Historiquement, l\'Akita etait utilise pour la chasse aux ours au Japon.',
    ],
    breedGroupFci: 'spitz',
    originCountry: 'JP',
    dataCompleteness: 0.93,
    source: 'fci-standard-255',
  },

  // ── 30. Samoyede ────────────────────────────────────────────────────
  {
    breedId: 'samoyede',
    fciNumber: 212,
    displayNameFr: 'Samoyede',
    displayNameEn: 'Samoyed',
    sizeClass: 'medium',
    weightMinKg: 17,
    weightMaxKg: 30,
    heightMinCm: 50,
    heightMaxCm: 57,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'very_dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'seasonal_heavy',
    activityLevel: 'high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 90,
    dailyWalkKmMin: 4,
    dailyWalkKmMax: 8,
    exerciseTypePreference: ['walking', 'running', 'hiking', 'sledding', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'moderate',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'very_high',
    coldSensitivity: 'low',
    heatAlertThresholdC: 20,
    commonBreedConcerns: ['joint', 'eye', 'cardiac'],
    lifespanMinYears: 12,
    lifespanMaxYears: 14,
    onboardingTips: [
      'Son epaisse fourrure blanche necessite un brossage au moins trois fois par semaine.',
      'Tres sensible a la chaleur : evitez tout effort par temps chaud et offrez-lui toujours de l\'ombre.',
      'C\'est un chien sociable qui supporte mal la solitude : prevoyez de la compagnie.',
      'Ne rasez jamais sa fourrure en ete : elle le protege aussi bien du chaud que du froid.',
    ],
    funFacts: [
      'Le sourire caracteristique du Samoyede, appele "sourire du Samoyede", empeche la bave de geler en conditions polaires.',
      'Le peuple Samoyede de Siberie dormait avec ces chiens pour se rechauffer par -50 degres.',
      'La laine de Samoyede peut etre filee et tricotee : elle est aussi chaude que la laine de mouton.',
    ],
    breedGroupFci: 'spitz',
    originCountry: 'RU',
    dataCompleteness: 0.93,
    source: 'fci-standard-212',
  },

  // ── 31. Dalmatien ───────────────────────────────────────────────────
  {
    breedId: 'dalmatien',
    fciNumber: 153,
    displayNameFr: 'Dalmatien',
    displayNameEn: 'Dalmatian',
    sizeClass: 'large',
    weightMinKg: 24,
    weightMaxKg: 32,
    heightMinCm: 54,
    heightMaxCm: 62,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'heavy',
    activityLevel: 'very_high',
    dailyExerciseMinMinutes: 60,
    dailyExerciseMaxMinutes: 120,
    dailyWalkKmMin: 5,
    dailyWalkKmMax: 12,
    exerciseTypePreference: ['running', 'hiking', 'agility', 'fetch', 'canicross'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'moderate',
    energyIndoor: 'active',
    destructivenessTendency: 'high',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['ear', 'skin', 'joint'],
    lifespanMinYears: 10,
    lifespanMaxYears: 13,
    onboardingTips: [
      'Le Dalmatien est un chien d\'endurance qui a besoin de courir longuement chaque jour.',
      'Attention : environ 10% des Dalmatiens naissent sourds, faites tester l\'audition.',
      'Malgre son poil court, il perd enormement ses poils : brossez-le regulierement.',
      'Il peut etre reserve avec les inconnus : la socialisation precoce est importante.',
    ],
    funFacts: [
      'Le Dalmatien etait historiquement le chien des pompiers, il courait devant les voitures a chevaux pour degager la route.',
      'Les chiots Dalmatiens naissent entierement blancs ; les taches apparaissent progressivement.',
      'C\'est la seule race de chien qui produit de l\'acide urique au lieu de l\'uree, comme les primates.',
    ],
    breedGroupFci: 'hound',
    originCountry: 'HR',
    dataCompleteness: 0.93,
    source: 'fci-standard-153',
  },

  // ── 32. Lhassa Apso ─────────────────────────────────────────────────
  {
    breedId: 'lhassa-apso',
    fciNumber: 227,
    displayNameFr: 'Lhassa Apso',
    displayNameEn: 'Lhasa Apso',
    sizeClass: 'small',
    weightMinKg: 5,
    weightMaxKg: 8,
    heightMinCm: 22,
    heightMaxCm: 28,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 40,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 3,
    exerciseTypePreference: ['walking', 'play'],
    separationAnxietyTendency: 'low',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'moderate',
    trainability: 'independent',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['eye', 'skin', 'ear'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Son long poil necessite un brossage quotidien ou une coupe courte reguliere.',
      'C\'est un chien independant et un peu tetu : soyez patient dans son education.',
      'Nettoyez ses yeux chaque jour pour prevenir les irritations liees a son poil long.',
      'Malgre sa petite taille, c\'est un bon chien d\'vigilance, naturellement mefiant envers les inconnus.',
    ],
    funFacts: [
      'Le Lhassa Apso servait de chien de garde dans les monasteres tibetains il y a plus de 2 000 ans.',
      'Son nom vient de Lhassa, la capitale du Tibet, et "apso" signifie "barbu" en tibetain.',
      'Au Tibet, il etait considere comme un porte-bonheur et ne pouvait pas etre achete, seulement offert.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'CN',
    dataCompleteness: 0.90,
    source: 'fci-standard-227',
  },

  // ── 33. Bichon Maltais ──────────────────────────────────────────────
  {
    breedId: 'bichon-maltais',
    fciNumber: 65,
    displayNameFr: 'Bichon Maltais',
    displayNameEn: 'Maltese',
    sizeClass: 'xs',
    weightMinKg: 3,
    weightMaxKg: 4,
    heightMinCm: 20,
    heightMaxCm: 25,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'long',
    furDensity: 'moderate',
    hasDoubleCoat: false,
    furContactClass: 'FC-3',
    sheddingLevel: 'none',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 30,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 2,
    exerciseTypePreference: ['walking', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'very_friendly',
    trainability: 'moderate',
    energyIndoor: 'active',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'high',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['eye', 'joint', 'skin'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Son poil blanc soyeux necessite un brossage quotidien pour eviter les noeuds.',
      'Nettoyez le contour de ses yeux chaque jour pour eviter les taches de larmes brunâtres.',
      'Protegez-le du froid et de l\'humidite : sa petite taille le rend vulnerable.',
      'Un toilettage professionnel regulier est recommande toutes les 6 semaines.',
    ],
    funFacts: [
      'Le Bichon Maltais est l\'une des races les plus anciennes au monde, avec des traces remontant a l\'Egypte antique.',
      'Les dames de la noblesse romaine portaient des Maltais dans leurs manches.',
      'Son poil ne tombe pas et pousse en continu, un peu comme les cheveux humains.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'MT',
    dataCompleteness: 0.90,
    source: 'fci-standard-65',
  },

  // ── 34. Bichon Frise ────────────────────────────────────────────────
  {
    breedId: 'bichon-frise',
    fciNumber: 215,
    displayNameFr: 'Bichon Frise',
    displayNameEn: 'Bichon Frise',
    sizeClass: 'small',
    weightMinKg: 3,
    weightMaxKg: 5,
    heightMinCm: 23,
    heightMaxCm: 30,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'curly',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-3',
    sheddingLevel: 'none',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 40,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 3,
    exerciseTypePreference: ['walking', 'play', 'agility'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'eager',
    energyIndoor: 'active',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['eye', 'skin', 'ear'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Son poil bouclé ne tombe pas mais s\'emmele facilement : un brossage quotidien est indispensable.',
      'Un toilettage professionnel toutes les 4 a 6 semaines est recommande.',
      'C\'est un chien joyeux qui supporte mal la solitude : ne le laissez pas seul longtemps.',
      'Nettoyez regulierement le contour de ses yeux pour prevenir les taches de larmes.',
    ],
    funFacts: [
      'Le Bichon Frise etait le favori des cours royales francaises et espagnoles au XVIe siecle.',
      'Apres la Revolution francaise, il est devenu un chien de cirque grace a son intelligence et sa vivacite.',
      'Son poil bouclé est hypoallergenique, ce qui en fait un choix populaire pour les allergiques.',
    ],
    breedGroupFci: 'companion',
    originCountry: 'FR',
    dataCompleteness: 0.90,
    source: 'fci-standard-215',
  },

  // ── 35. West Highland White Terrier ─────────────────────────────────
  {
    breedId: 'west-highland-white-terrier',
    fciNumber: 85,
    displayNameFr: 'West Highland White Terrier',
    displayNameEn: 'West Highland White Terrier',
    sizeClass: 'small',
    weightMinKg: 7,
    weightMaxKg: 10,
    heightMinCm: 25,
    heightMaxCm: 28,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'medium',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 30,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 2,
    dailyWalkKmMax: 5,
    exerciseTypePreference: ['walking', 'play', 'digging', 'fetch'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'moderate',
    energyIndoor: 'moderate',
    destructivenessTendency: 'moderate',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['skin', 'ear', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 16,
    onboardingTips: [
      'Sa peau sensible merite une attention particuliere : utilisez des shampoings doux et adaptés.',
      'Un toilettage regulier est necessaire pour maintenir la texture de son poil dur.',
      'C\'est un terrier affirme : soyez coherent dans son education des le depart.',
      'Proposez-lui des jeux de fouille et de recherche pour satisfaire son instinct de chasse.',
    ],
    funFacts: [
      'Le Westie a ete selectionne blanc pour etre visible lors des chasses aux renards en Ecosse.',
      'Il est la mascotte de la marque de whisky Black & White depuis 1890.',
      'Malgre sa petite taille, c\'est un chien intrepide qui n\'hesite pas a affronter des adversaires plus grands.',
    ],
    breedGroupFci: 'terrier',
    originCountry: 'GB',
    dataCompleteness: 0.92,
    source: 'fci-standard-85',
  },

  // ── 36. Schnauzer Nain ──────────────────────────────────────────────
  {
    breedId: 'schnauzer-nain',
    fciNumber: 183,
    displayNameFr: 'Schnauzer Nain',
    displayNameEn: 'Miniature Schnauzer',
    sizeClass: 'small',
    weightMinKg: 4,
    weightMaxKg: 8,
    heightMinCm: 30,
    heightMaxCm: 35,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'wire',
    furDensity: 'dense',
    hasDoubleCoat: true,
    furContactClass: 'FC-2',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 30,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 2,
    dailyWalkKmMax: 5,
    exerciseTypePreference: ['walking', 'agility', 'play', 'fetch'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'friendly',
    trainability: 'eager',
    energyIndoor: 'moderate',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'low',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['eye', 'ear', 'skin'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Son poil dur necessite un epilation (stripping) reguliere ou une tonte chez le toiletteur.',
      'Brossez sa barbe et ses sourcils chaque jour pour eviter les noeuds et les salissures.',
      'C\'est un petit chien vif et vigilance qui peut etre aboyeur : travaillez le calme des le depart.',
      'Il s\'adapte tres bien a la vie en appartement avec des sorties regulieres.',
    ],
    funFacts: [
      'Le Schnauzer Nain est issu du croisement entre le Schnauzer standard et l\'Affenpinscher.',
      'Son nom vient du mot allemand "Schnauze" qui signifie "museau", en reference a sa moustache.',
      'C\'est la race de Schnauzer la plus populaire au monde.',
    ],
    breedGroupFci: 'pinscher',
    originCountry: 'DE',
    dataCompleteness: 0.92,
    source: 'fci-standard-183',
  },

  // ── 37. Carlin ──────────────────────────────────────────────────────
  {
    breedId: 'carlin',
    fciNumber: 253,
    displayNameFr: 'Carlin',
    displayNameEn: 'Pug',
    sizeClass: 'small',
    weightMinKg: 6,
    weightMaxKg: 8,
    heightMinCm: 25,
    heightMaxCm: 33,
    isBrachycephalic: true,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: true,
    furContactClass: 'FC-1',
    sheddingLevel: 'heavy',
    activityLevel: 'low',
    dailyExerciseMinMinutes: 20,
    dailyExerciseMaxMinutes: 30,
    dailyWalkKmMin: 1,
    dailyWalkKmMax: 2,
    exerciseTypePreference: ['short_walks', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'moderate',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'moderate',
    energyIndoor: 'moderate',
    destructivenessTendency: 'low',
    heatSensitivity: 'very_high',
    coldSensitivity: 'high',
    heatAlertThresholdC: 20,
    commonBreedConcerns: ['respiratory', 'eye', 'skin', 'joint'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'IMPORTANT : evitez absolument les efforts par temps chaud, il est tres sensible a la chaleur.',
      'Nettoyez les plis de son visage quotidiennement pour prevenir les infections cutanees.',
      'Malgre son poil court, il perd enormement : un brossage regulier aide a limiter les poils.',
      'Surveillez son poids de pres : l\'obesite aggrave ses difficultes respiratoires.',
      'Evitez les harnais qui compriment le thorax ; privilegiez un harnais en Y.',
    ],
    funFacts: [
      'Le Carlin etait le chien favori de Josephine de Beauharnais, epouse de Napoleon.',
      'En Chine, les Carlins etaient si precieux qu\'ils avaient leurs propres gardes dans le palais imperial.',
      'La devise latine de la race est "multum in parvo", ce qui signifie "beaucoup dans un petit espace".',
    ],
    breedGroupFci: 'companion',
    originCountry: 'CN',
    dataCompleteness: 0.95,
    source: 'fci-standard-253',
  },

  // ── 38. Whippet ─────────────────────────────────────────────────────
  {
    breedId: 'whippet',
    fciNumber: 162,
    displayNameFr: 'Whippet',
    displayNameEn: 'Whippet',
    sizeClass: 'medium',
    weightMinKg: 9,
    weightMaxKg: 13,
    heightMinCm: 44,
    heightMaxCm: 51,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'sparse',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 40,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 3,
    dailyWalkKmMax: 6,
    exerciseTypePreference: ['sprinting', 'lure_coursing', 'walking', 'play'],
    separationAnxietyTendency: 'high',
    vocalizationTendency: 'quiet',
    sociabilityDogs: 'high',
    sociabilityHumans: 'friendly',
    trainability: 'moderate',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'low',
    coldSensitivity: 'high',
    heatAlertThresholdC: 28,
    commonBreedConcerns: ['eye', 'cardiac', 'skin'],
    lifespanMinYears: 12,
    lifespanMaxYears: 15,
    onboardingTips: [
      'Le Whippet est un sprinter, pas un coureur de fond : proposez des courses courtes et intenses.',
      'Offrez-lui un couchage moelleux et chaud : sa fine couche de graisse le rend sensible au froid.',
      'Prevoyez un manteau en hiver : il greloutte facilement.',
      'Attention aux petits animaux en promenade : son instinct de poursuite est tres fort.',
    ],
    funFacts: [
      'Le Whippet est le chien le plus rapide pour sa taille, atteignant 56 km/h.',
      'Il etait surnomme le "levrier du pauvre" dans l\'Angleterre du XIXe siecle.',
      'Malgre son energie en exterieur, c\'est l\'un des chiens les plus calmes en interieur.',
    ],
    breedGroupFci: 'hound',
    originCountry: 'GB',
    dataCompleteness: 0.92,
    source: 'fci-standard-162',
  },

  // ── 39. Levrier Greyhound ───────────────────────────────────────────
  {
    breedId: 'levrier-greyhound',
    fciNumber: 158,
    displayNameFr: 'Levrier Greyhound',
    displayNameEn: 'Greyhound',
    sizeClass: 'large',
    weightMinKg: 27,
    weightMaxKg: 40,
    heightMinCm: 68,
    heightMaxCm: 76,
    isBrachycephalic: false,
    isLongBacked: false,
    isGiant: false,
    furLength: 'short',
    furDensity: 'sparse',
    hasDoubleCoat: false,
    furContactClass: 'FC-1',
    sheddingLevel: 'low',
    activityLevel: 'moderate',
    dailyExerciseMinMinutes: 40,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 3,
    dailyWalkKmMax: 6,
    exerciseTypePreference: ['sprinting', 'lure_coursing', 'walking'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'quiet',
    sociabilityDogs: 'moderate',
    sociabilityHumans: 'moderate',
    trainability: 'moderate',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'low',
    coldSensitivity: 'high',
    heatAlertThresholdC: 28,
    commonBreedConcerns: ['joint', 'skin', 'cardiac'],
    lifespanMinYears: 10,
    lifespanMaxYears: 14,
    onboardingTips: [
      'Le Greyhound est un sprinter : il a besoin de courtes courses intenses plutôt que de longues randonnees.',
      'Offrez-lui un couchage epais et moelleux pour proteger ses articulations saillantes.',
      'Prevoyez un manteau d\'hiver : son poil fin et son faible taux de graisse le rendent frileux.',
      'Attention aux petits animaux : son instinct de poursuite est tres developpe.',
    ],
    funFacts: [
      'Le Greyhound est le chien le plus rapide du monde, atteignant 72 km/h en course.',
      'C\'est l\'une des plus anciennes races de chien, representee dans des tombes egyptiennes datant de 4 000 ans.',
      'Contrairement a leur image de sportif, les Greyhounds sont surnommes "patates de canape" pour leur amour du repos.',
    ],
    breedGroupFci: 'hound',
    originCountry: 'GB',
    dataCompleteness: 0.92,
    source: 'fci-standard-158',
  },

  // ── 40. Basset Hound ────────────────────────────────────────────────
  {
    breedId: 'basset-hound',
    fciNumber: 163,
    displayNameFr: 'Basset Hound',
    displayNameEn: 'Basset Hound',
    sizeClass: 'medium',
    weightMinKg: 20,
    weightMaxKg: 29,
    heightMinCm: 30,
    heightMaxCm: 38,
    isBrachycephalic: false,
    isLongBacked: true,
    isGiant: false,
    furLength: 'short',
    furDensity: 'moderate',
    hasDoubleCoat: true,
    furContactClass: 'FC-1',
    sheddingLevel: 'moderate',
    activityLevel: 'low',
    dailyExerciseMinMinutes: 30,
    dailyExerciseMaxMinutes: 60,
    dailyWalkKmMin: 2,
    dailyWalkKmMax: 4,
    exerciseTypePreference: ['walking', 'tracking', 'sniffing_games'],
    separationAnxietyTendency: 'moderate',
    vocalizationTendency: 'very_vocal',
    sociabilityDogs: 'high',
    sociabilityHumans: 'very_friendly',
    trainability: 'independent',
    energyIndoor: 'calm',
    destructivenessTendency: 'low',
    heatSensitivity: 'moderate',
    coldSensitivity: 'moderate',
    heatAlertThresholdC: 25,
    commonBreedConcerns: ['ear', 'eye', 'joint', 'skin'],
    lifespanMinYears: 10,
    lifespanMaxYears: 12,
    onboardingTips: [
      'Comme le Teckel, protegez son dos : evitez les sauts et les escaliers.',
      'Nettoyez ses longues oreilles au moins deux fois par semaine pour eviter les infections.',
      'Surveillez son poids rigoureusement : l\'embonpoint aggrave les problemes de dos.',
      'C\'est un chien tres tetu guide par son nez : les rappels en promenade seront un defi.',
      'Ses yeux tombants accumulent facilement la poussiere : nettoyez-les regulierement.',
    ],
    funFacts: [
      'Le Basset Hound possede le deuxieme odorat le plus fin du monde canin, juste apres le Bloodhound.',
      'Ses longues oreilles ne sont pas decoratives : elles aident a ramener les odeurs du sol vers son nez.',
      'Le celebre logo de la marque de chaussures Hush Puppies represente un Basset Hound.',
    ],
    breedGroupFci: 'hound',
    originCountry: 'GB',
    dataCompleteness: 0.93,
    source: 'fci-standard-163',
  },
];
