/**
 * Bleiz Freemium Templates — Milestones
 * 30 celebratory templates for the EMOPET free companion app.
 * All content in French, warm and celebratory tone.
 */

export interface MilestoneTemplate {
  id: string;
  category: 'milestone';
  subcategory: 'milestone';
  breedFilter: string[];
  sizeFilter: string[];
  ageMinMonths: number | null;
  ageMaxMonths: number | null;
  seasonFilter: string[];
  monthFilter: number[];
  regionFilter: string[];
  titleFr: string;
  bodyFr: string;
  sourceType: 'milestone';
  neverSay: string[];
  suffix: string | null;
  requiresVetDisclaimer: boolean;
  channel: 'push';
  priority: number;
  cooldownHours: number;
  maxPerMonth: number;
  usesDogName: boolean;
  usesBreedName: boolean;
  usesAge: boolean;
  usesLocation: boolean;
  usesSeason: boolean;
}

export const MILESTONE_TEMPLATES: MilestoneTemplate[] = [
  // ═══════════════════════════════════════════════════════════════════
  // DURÉE ENSEMBLE (10)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'MS_001',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `1 semaine ensemble avec {dog_name} !`,
    bodyFr: `Cela fait déjà une semaine que {dog_name} partage votre quotidien. Ces premiers jours sont précieux : chaque regard échangé, chaque moment de complicité construit les fondations d'une relation unique. {dog_name} apprend à reconnaître vos habitudes, votre voix, votre odeur. En tant que {breed_name}, votre compagnon a ses propres façons de s'exprimer et de créer du lien. Profitez de chaque instant de découverte mutuelle. Cette première semaine est le début d'une belle aventure ensemble.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_002',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `2 semaines déjà avec {dog_name} !`,
    bodyFr: `Deux semaines se sont écoulées depuis l'arrivée de {dog_name} dans votre vie. Votre {breed_name} commence à prendre ses repères et à se sentir chez lui. Les routines se mettent en place : les heures de repas, les sorties, les moments de jeu. Vous commencez à décoder ses expressions et ses envies. La confiance grandit de jour en jour et les premiers liens profonds se tissent. Continuez à offrir à {dog_name} un cadre rassurant et plein de douceur. Chaque journée renforce votre complicité.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_003',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `1 mois avec {dog_name} : un cap franchi !`,
    bodyFr: `Un mois complet aux côtés de {dog_name}, quelle étape formidable ! Votre {breed_name} a désormais trouvé ses marques dans votre foyer. Les habitudes sont installées, les premiers apprentissages portent leurs fruits et la complicité entre vous est de plus en plus évidente. {dog_name} reconnaît votre pas dans l'escalier, anticipe l'heure de la promenade et sait exactement où se blottir pour un câlin. Ce premier mois est la preuve que votre duo fonctionne à merveille. Célébrez ce cap avec une sortie spéciale ou un moment privilégié ensemble.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_004',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `3 mois ensemble : {dog_name} fait partie de la famille !`,
    bodyFr: `Trois mois d'aventures partagées avec {dog_name}. Votre {breed_name} est désormais un membre à part entière de la famille. Les liens affectifs se sont solidifiés et vous comprenez de mieux en mieux son langage corporel. {dog_name} a développé ses petites habitudes, ses endroits préférés dans la maison, ses rituels du matin et du soir. La phase d'adaptation est derrière vous et c'est maintenant que la vraie complicité s'épanouit pleinement. Chaque jour apporte son lot de moments de enthousiasme et de tendresse.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_005',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `6 mois avec {dog_name} : une demi-année de bonheur !`,
    bodyFr: `Six mois déjà que {dog_name} illumine votre quotidien. Votre {breed_name} a grandi, évolué et mûri à vos côtés. Que de chemin parcouru depuis les premiers jours ! Les promenades sont devenues des rituels complices, les jeux se sont enrichis et la communication entre vous est devenue presque intuitive. {dog_name} sait lire vos émotions et vous savez décrypter les siennes. Cette demi-année est remplie de souvenirs précieux. Prenez un instant pour mesurer tout le bonheur que cette relation vous apporte au quotidien.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_006',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `1 an avec {dog_name} : joyeux anniversaire de duo !`,
    bodyFr: `Une année entière partagée avec {dog_name}. Quel chemin extraordinaire vous avez parcouru ensemble ! Votre {breed_name} et vous avez traversé toutes les saisons, découvert de nouveaux endroits, surmonté des défis et vécu des moments inoubliables. {dog_name} est devenu bien plus qu'un compagnon : un véritable partenaire de vie qui connaît vos enthousiasmes et vos peines. Cette première année est un trésor de souvenirs. Chaque promenade, chaque regard, chaque câlin a renforcé un lien unique et irremplaçable. Bravo pour cette magnifique année ensemble.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_007',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `2 ans avec {dog_name} : un duo qui dure !`,
    bodyFr: `Deux ans que {dog_name} et vous formez un duo inséparable. Votre {breed_name} vous connaît par cœur et vous aussi. Les automatismes sont parfaitement rodés, la communication est fluide et naturelle. Vous avez développé ensemble un langage unique fait de regards, de gestes et de rituels partagés. {dog_name} a traversé à vos côtés des saisons, des voyages et des moments de vie importants. Deux ans de fidélité, de tendresse et de complicité. Votre relation est un modèle de ce lien si spécial entre un humain et son chien.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_008',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `3 ans avec {dog_name} : une amitié solide !`,
    bodyFr: `Trois années magnifiques aux côtés de {dog_name}. Votre {breed_name} et vous avez bâti une relation profonde et durable. Les souvenirs s'accumulent et chacun d'entre eux raconte un chapitre de votre histoire commune. {dog_name} est devenu votre confident, votre compagnon de route, celui qui est toujours là quand il le faut. Trois ans de promenades, de jeux, de siestes partagées et de moments de pure complicité. Cette amitié est un trésor que le temps ne fait que renforcer. Continuez à savourer chaque jour ensemble.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_009',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `5 ans avec {dog_name} : un demi-décennie de bonheur !`,
    bodyFr: `Cinq ans déjà que {dog_name} partage votre vie. Votre {breed_name} a grandi avec vous, s'est adapté à vos changements de vie et a été présent à chaque étape. Un demi-décennie de fidélité absolue, de enthousiasmes quotidiennes et de moments qui comptent. {dog_name} connaît chaque recoin de votre univers et vous connaissez chaque nuance de son caractère. Cinq ans, c'est des milliers de promenades, des centaines de siestes partagées et un nombre incalculable de regards complices. Cette longévité de bonheur partagé est un vrai cadeau.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_010',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `10 ans avec {dog_name} : une décennie d\'amour !`,
    bodyFr: `Dix ans. Une décennie entière passée aux côtés de {dog_name}. Votre {breed_name} vous a accompagné à travers tant de moments de vie, de déménagements, de rencontres, de enthousiasmes et de peines. Dix ans de loyauté sans faille, de câlins matinaux et de bonheur simple. {dog_name} a peut-être un peu de gris sur le museau aujourd'hui, mais son regard est toujours aussi tendre et son amour toujours aussi fort. Cette décennie est un témoignage magnifique de la puissance du lien entre un humain et son compagnon à quatre pattes.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // ANNIVERSAIRES DE NAISSANCE (4)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'MS_011',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Joyeux 1er anniversaire {dog_name} !`,
    bodyFr: `{dog_name} souffle sa première bougie aujourd'hui ! Votre {breed_name} a quitté le stade de chiot pour entrer dans la vie de jeune adulte. Quelle transformation incroyable en seulement douze mois. {dog_name} a appris tant de choses, développé sa personnalité et trouvé sa place dans votre cœur. Ce premier anniversaire est l'occasion de célébrer toutes ces premières fois : première promenade, premier rappel réussi, premier câlin sur le canapé. Offrez à {dog_name} une journée spéciale remplie de ses activités préférées.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_012',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Joyeux 2e anniversaire {dog_name} !`,
    bodyFr: `Deux ans déjà pour {dog_name} ! Votre {breed_name} est maintenant un adulte accompli, plein de vitalité et de caractère. Ces deux années ont été riches en apprentissages mutuels et en moments de bonheur partagé. {dog_name} a trouvé son rythme, ses jeux favoris et ses petites manies qui vous font sourire chaque jour. Ce deuxième anniversaire marque une belle étape dans la vie de votre compagnon. Célébrez cette journée spéciale avec une longue promenade dans son endroit préféré ou une friandise bien méritée.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_013',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Joyeux 5e anniversaire {dog_name} !`,
    bodyFr: `Cinq bougies pour {dog_name} ! Votre {breed_name} est dans la fleur de l'âge, épanoui et plein d'énergie. Ces cinq années ensemble ont construit une relation exceptionnelle. {dog_name} est devenu un compagnon mature qui sait exactement comment vous faire sourire et qui est toujours prêt pour une nouvelle aventure. Ce cinquième anniversaire est le moment parfait pour se remémorer les meilleurs souvenirs partagés. Offrez à {dog_name} une journée exceptionnelle remplie de tendresse et de surprises canines.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_014',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a 8 ans : bienvenue dans la sagesse !`,
    bodyFr: `Huit ans pour {dog_name}, c'est l'entrée dans l'âge de la sagesse. Votre {breed_name} affiche désormais une sérénité et une maturité qui forcent l'admiration. Les yeux de {dog_name} portent la trace de toutes ces années de bonheur partagé. L'énergie est peut-être un peu plus mesurée, mais l'amour est toujours aussi intense. C'est le moment d'adapter les activités au rythme de votre compagnon senior et de lui offrir tout le confort qu'il mérite. Chaque jour avec {dog_name} est un cadeau à savourer pleinement.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // PREMIÈRES SAISONS (4)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'MS_015',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le premier printemps de {dog_name} !`,
    bodyFr: `{dog_name} découvre son tout premier printemps ! Les fleurs, les oiseaux, les nouvelles odeurs portées par le vent doux : tout est une découverte fascinante pour votre {breed_name}. Regardez-le explorer avec émerveillement les jardins qui reprennent vie et les prairies qui verdissent. Ce premier printemps est un festival de stimulations olfactives et visuelles pour {dog_name}. Profitez de cette saison magique pour multiplier les promenades dans la nature et observer la curiosité insatiable de votre compagnon face à ce monde en renouveau.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_016',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le premier été de {dog_name} !`,
    bodyFr: `L'été arrive et c'est une grande première pour {dog_name} ! Votre {breed_name} va découvrir la chaleur estivale, les longues soirées et peut-être même les enthousiasmes de l'eau. Les journées sont plus longues et offrent davantage d'occasions de sorties et de jeux en plein air. {dog_name} va adorer les promenades matinales dans la fraîcheur et les moments de détente à l'ombre l'après-midi. Pensez à toujours avoir de l'eau fraîche à disposition et à adapter les horaires d'activité. Ce premier été sera rempli de belles découvertes estivales.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_017',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le premier automne de {dog_name} !`,
    bodyFr: `{dog_name} découvre les couleurs chatoyantes de l'automne ! Les feuilles qui tombent, les odeurs de sous-bois humide, les matins brumeux : tout un univers sensoriel nouveau s'ouvre à votre {breed_name}. Observez {dog_name} courir dans les tas de feuilles mortes et renifler avec passion les champignons en lisière de forêt. L'automne est une saison extraordinaire pour les promenades en nature avec ses couleurs flamboyantes et ses ambiances apaisantes. Profitez de ces moments magiques avec votre compagnon avant l'arrivée de l'hiver.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_018',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le premier hiver de {dog_name} !`,
    bodyFr: `{dog_name} vit son tout premier hiver ! Le froid, la brume matinale et peut-être même la neige : votre {breed_name} va découvrir un monde transformé. Regardez sa réaction face aux premiers flocons ou au givre qui recouvre l'herbe le matin. {dog_name} pourrait être intrigué, enthousiaste ou un peu perplexe face à ces nouvelles sensations sous ses coussinets. Adaptez la durée des sorties selon la température et pensez à bien sécher votre compagnon au retour. Ce premier hiver est une expérience unique à savourer ensemble au coin du feu.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // PROMENADES ET ACTIVITÉS (3)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'MS_019',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `100 promenades avec {dog_name} !`,
    bodyFr: `Cent promenades partagées avec {dog_name}, quel accomplissement ! Chacune de ces sorties a été un moment de complicité, de découverte et de plaisir avec votre {breed_name}. Des matins brumeux aux soirées d'été, en passant par les après-midis pluvieux, vous avez exploré votre quartier et ses environs ensemble. {dog_name} connaît désormais par cœur les itinéraires, les endroits où renifler et les amis canins à saluer. Ces cent promenades représentent des heures de bonheur simple et de connexion avec votre fidèle compagnon.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_020',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `500 promenades avec {dog_name} : explorateurs infatigables !`,
    bodyFr: `Cinq cents promenades ensemble ! {dog_name} et vous êtes de véritables explorateurs. Votre {breed_name} a foulé tant de chemins, humé tant d'odeurs et croisé tant d'amis à quatre pattes. Chaque sortie est une aventure renouvelée, même sur un itinéraire familier, car le monde offre toujours de nouvelles senteurs et de nouvelles rencontres. Cinq cents fois, vous avez enfilé vos chaussures et {dog_name} a frétillé de enthousiasme en voyant la laisse. Cette constance dans le partage est le socle de votre relation exceptionnelle.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_021',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `1 000 km parcourus avec {dog_name} !`,
    bodyFr: `Mille kilomètres parcourus ensemble avec {dog_name} ! C'est l'équivalent d'une traversée de la France du nord au sud. Votre {breed_name} et vous avez foulé cette distance pas à pas, promenade après promenade, avec régularité et plaisir. Chaque kilomètre raconte une histoire : un lever de soleil aperçu, un écureuil poursuivi, un ami canin rencontré. Mille kilomètres de complicité, de conversation silencieuse et de bonheur partagé. {dog_name} est votre meilleur partenaire de marche et ces mille kilomètres ne sont que le début.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // PREMIÈRES EXPÉRIENCES (3)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'MS_022',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La première baignade de {dog_name} !`,
    bodyFr: `{dog_name} a découvert les enthousiasmes de l'eau pour la première fois ! Que votre {breed_name} ait plongé avec enthousiasme ou testé timidement du bout des pattes, cette première baignade est un moment mémorable. Certains chiens sont des nageurs nés tandis que d'autres préfèrent barboter tranquillement au bord. Quelle que soit la réaction de {dog_name}, cette découverte aquatique enrichit son univers sensoriel. Félicitez-le pour ce courage et gardez ce souvenir précieusement. Les prochaines baignades seront encore plus amusantes maintenant que la glace est brisée.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_023',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le premier voyage de {dog_name} !`,
    bodyFr: `{dog_name} a fait son premier voyage ! Que ce soit en voiture, en train ou en avion, votre {breed_name} a découvert que le monde s'étend bien au-delà de son quartier habituel. De nouveaux paysages, de nouvelles odeurs, de nouvelles rencontres : tout était une aventure pour {dog_name}. Voyager avec son chien crée des souvenirs uniques et renforce la complicité de manière extraordinaire. {dog_name} a prouvé qu'il est un excellent compagnon de route. Ce premier voyage ouvre la porte à de nombreuses autres escapades ensemble.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_024',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le premier Noël de {dog_name} !`,
    bodyFr: `{dog_name} vit son tout premier Noël ! Les guirlandes scintillantes, le sapin qui sent bon la forêt, les papiers cadeaux qui crissent : votre {breed_name} est émerveillé par toute cette magie festive. Noël est un moment de partage et de chaleur familiale, et {dog_name} en fait désormais partie intégrante. Pensez à lui prévoir une petite surprise adaptée pour qu'il participe à la fête. Attention toutefois au chocolat et aux petits objets décoratifs qui pourraient attirer sa curiosité. Ce premier Noël avec {dog_name} restera gravé dans vos souvenirs.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // ÉTAPES DE VIE (4)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'MS_025',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a fini sa croissance !`,
    bodyFr: `{dog_name} a atteint sa taille adulte ! Votre {breed_name} a terminé sa phase de croissance et arbore désormais sa silhouette définitive. Depuis son arrivée, {dog_name} a grandi, s'est musclé et a développé toutes les caractéristiques physiques de sa race. Cette étape marque le passage de chiot à adulte sur le plan corporel. C'est le moment idéal pour ajuster son alimentation aux besoins d'un chien adulte et pour adapter l'intensité de ses activités physiques. Admirez le magnifique compagnon que {dog_name} est devenu.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_026',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} entre dans l\'âge senior : un nouveau chapitre !`,
    bodyFr: `{dog_name} entre dans sa première année senior. Votre {breed_name} aborde cette nouvelle étape avec toute la sagesse accumulée au fil des ans. Le rythme peut ralentir un peu, les siestes s'allonger et les promenades devenir plus contemplatives, mais l'amour de {dog_name} pour vous reste intact et indéfectible. C'est le moment d'adapter son confort au quotidien : un couchage plus moelleux, des sorties à son rythme et une alimentation adaptée à ses nouveaux besoins. Chaque instant partagé avec votre compagnon senior est infiniment précieux.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_027',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} est officiellement adulte !`,
    bodyFr: `{dog_name} passe le cap de l'âge adulte ! Votre {breed_name} a quitté la turbulence de l'adolescence canine pour entrer dans la maturité. Le caractère de {dog_name} est maintenant bien affirmé, ses comportements plus stables et sa relation avec vous pleinement épanouie. L'âge adulte est une période merveilleuse où l'énergie est encore débordante mais mieux canalisée. Les apprentissages des premiers mois portent leurs fruits et votre duo fonctionne comme une équipe rodée. Profitez pleinement de cette belle période de la vie de {dog_name}.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_028',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Record de promenade pour {dog_name} !`,
    bodyFr: `{dog_name} vient de battre son record de distance en promenade ! Votre {breed_name} s'est surpassé aujourd'hui et mérite toutes les félicitations. Cette promenade exceptionnelle montre à quel point {dog_name} est en forme et enthousiaste pour les aventures en plein air. Chaque record est une célébration de la vitalité et de l'énergie de votre compagnon. {dog_name} a prouvé qu'il est un marcheur hors pair et un partenaire d'exploration formidable. Pensez à lui offrir un bon repos bien mérité après cet exploit et une belle récompense.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════════
  // COMMUNAUTÉ ET RÉGULARITÉ (2)
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 'MS_029',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `1 an dans la communauté EMOPET avec {dog_name} !`,
    bodyFr: `Cela fait un an que {dog_name} et vous faites partie de la communauté EMOPET ! Votre {breed_name} a bénéficié d'une année complète de suivi, de conseils personnalisés et d'accompagnement au quotidien. Ensemble, nous avons traversé les saisons, partagé des astuces et célébré les étapes importantes de la vie de {dog_name}. Cette première année dans la communauté est le reflet de votre engagement envers le bien-être de votre compagnon. Merci de faire partie de cette belle aventure et de contribuer à cette communauté bienveillante de passionnés.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'MS_030',
    category: 'milestone',
    subcategory: 'milestone',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `50 jours consécutifs avec {dog_name} sur EMOPET !`,
    bodyFr: `Cinquante jours d'affilée que vous consultez EMOPET pour {dog_name} ! Votre {breed_name} a la chance d'avoir un maître aussi attentif et régulier. Cette constance dans le suivi quotidien montre à quel point vous prenez à cœur le bien-être de votre compagnon. Cinquante jours consécutifs de conseils appliqués, de promenades enregistrées et d'attention bienveillante. {dog_name} bénéficie pleinement de cette régularité qui contribue à son épanouissement. Bravo pour cette belle série et continuez sur cette lancée formidable.`,
    sourceType: 'milestone',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
];
