/**
 * EMOPET Freemium Templates — Behavior Education (120 templates)
 * Subcategories: puppy (25), adolescent (15), adult (30), senior (20), socialization (15), separation (15)
 */

const NS = ['avis clinique', 'condition clinique', 'traitement', 'symptôme', 'pathologie', 'agité', 'forte sollicitation', 'trouble', 'agressif', 'dangereux'] as const;
const neverSay = [...NS];

export const BEHAVIOR_EDUCATION_TEMPLATES = [
  // ═══════════════════════════════════════════════════════════════
  // PUPPY — 25 templates (0-12 months)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'BE_PUPPY_001', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La propreté chez le chiot : patience et régularité`,
    bodyFr: "Apprendre la propreté à {dog_name} demande de la patience. Un chiot ne contrôle pas bien sa vessie avant 4-5 mois. Sortez-le après chaque repas, après chaque sieste et après chaque session de jeu. Quand il fait ses besoins dehors, félicitez-le chaleureusement. En cas d'accident à l'intérieur, ne grondez pas : nettoyez simplement avec un produit enzymatique pour éliminer l'odeur. Repérez les signaux — renifler le sol, tourner en rond — et sortez-le immédiatement. La nuit, prévoyez une sortie si {dog_name} est très jeune. La régularité de vos horaires est votre meilleur allié.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_002', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Le mordillement du chiot : rediriger sans punir`,
    bodyFr: "Les chiots explorent le monde avec leur gueule, et {dog_name} ne fait pas exception. Le mordillement est normal mais il faut lui apprendre les limites. Quand {dog_name} mordille vos mains, dites « aïe » d'une voix aiguë et arrêtez immédiatement le jeu pendant 10 secondes. Puis reprenez calmement. Proposez toujours un jouet à mâcher en alternative. Les jouets en caoutchouc, les cordes et les os à mâcher adaptés à son âge sont vos alliés. Ne retirez jamais brutalement votre main — cela déclenche l'instinct de poursuite. Avec de la constance, {dog_name} comprendra que mordiller la peau humaine arrête le jeu.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_003', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La fenêtre de socialisation : un moment clé`,
    bodyFr: "Entre 3 et 12 semaines, {dog_name} traverse une période critique : la fenêtre de socialisation. C'est le moment idéal pour lui faire découvrir le monde en douceur. Exposez-le à des personnes variées (enfants, personnes âgées, hommes à chapeau), des bruits (aspirateur, klaxon, musique), des surfaces différentes (gravier, herbe, carrelage) et d'autres animaux bien sociabilisés. L'objectif n'est pas de le submerger mais de lui offrir des expériences positives. Chaque nouvelle rencontre doit être associée à quelque chose d'agréable : une friandise, une caresse. Ce que {dog_name} apprend maintenant façonnera son tempérament pour la vie.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 8, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_004', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Les premiers bruits : habituer {dog_name} en douceur`,
    bodyFr: "Le monde est plein de bruits nouveaux pour {dog_name}. L'aspirateur, la machine à laver, les voitures, les claquements de porte — tout cela peut surprendre un chiot. L'astuce est d'introduire ces bruits progressivement et à faible volume. Quand un bruit survient, restez calme et détendu. Si {dog_name} réagit, ne le forcez pas à s'approcher mais ne le consolez pas excessivement non plus. Votre calme est son meilleur repère. Vous pouvez aussi diffuser des bruits urbains à faible volume pendant qu'il mange ou joue, pour créer des associations positives. Avec le temps, {dog_name} deviendra un chien confiant face aux sons du quotidien.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_005', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Un chiot dort beaucoup : c\'est normal !`,
    bodyFr: "Si {dog_name} dort 18 à 20 heures par jour, pas d'inquiétude — c'est tout à fait normal pour un chiot. Le sommeil est essentiel à sa croissance, au développement de son cerveau et à la consolidation de ses apprentissages. Respectez ses phases de repos et apprenez à toute la famille à ne pas le réveiller quand il dort. Aménagez un coin calme avec un panier confortable, à l'abri du passage. Un chiot qui ne dort pas assez peut devenir agité et avoir du mal à se concentrer pendant l'éducation. Le repos, c'est aussi de l'apprentissage.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_006', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Alimentation du chiot : fréquence et régularité`,
    bodyFr: "Un chiot a besoin de manger plus souvent qu'un adulte. Jusqu'à 4 mois, proposez 3 à 4 repas par jour à {dog_name}. Entre 4 et 6 mois, passez à 3 repas. Après 6 mois, 2 repas quotidiens suffisent généralement. Servez toujours aux mêmes heures et dans la même gamelle, au même endroit. Laissez la gamelle 15 à 20 minutes puis retirez-la, même si tout n'est pas fini. Cela structure la journée de {dog_name} et facilite aussi la propreté, car un chiot qui mange à heures fixes fait ses besoins à heures prévisibles.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_007', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Jeu vs surexcitation : trouver le bon équilibre`,
    bodyFr: "Jouer avec {dog_name} est essentiel, mais attention à la surexcitation. Un chiot qui s'emballe trop — qui mordille plus fort, qui saute partout, qui ne répond plus — a dépassé son seuil. Quand vous voyez les signes monter, arrêtez le jeu calmement. Proposez un moment calme, un jouet à mâcher ou simplement une pause. Les sessions de jeu courtes (5 à 10 minutes) suivies de repos sont plus bénéfiques qu'une longue session qui dégénère. Apprenez à reconnaître le moment où {dog_name} bascule de « joyeux » à « trop excité » et anticipez la pause.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_008', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Les premiers trajets en voiture avec {dog_name}`,
    bodyFr: "Pour que {dog_name} aime la voiture, commencez par de courtes sessions. Installez-le dans un panier ou un harnais de sécurité adapté. Faites-le monter dans la voiture à l'arrêt et récompensez-le. Puis allumez le moteur sans rouler. Ensuite, faites un tour du pâté de maison. Augmentez progressivement la durée. Ne nourrissez pas {dog_name} juste avant un trajet. Si le chiot bave ou semble mal à l'aise, raccourcissez les trajets et reprenez plus progressivement. Le but est que la voiture soit associée à des destinations agréables : le parc, la campagne, la plage.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_009', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Les premières nuits : aider {dog_name} à dormir`,
    bodyFr: "Les premières nuits dans un nouveau foyer peuvent être difficiles. {dog_name} quitte sa mère et ses frères et sœurs — c'est un grand changement. Placez son panier dans votre chambre les premières nuits pour le rassurer. Une bouillotte tiède et un tissu avec l'odeur de sa mère (si possible) peuvent aider. S'il pleure, posez simplement votre main près de lui sans trop le stimuler. Progressivement, vous pourrez déplacer son panier vers son emplacement définitif. Ne cédez pas à la tentation de le prendre dans votre lit si ce n'est pas votre souhait à long terme.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_010', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Les dents de lait de {dog_name}`,
    bodyFr: "Entre 3 et 7 mois, {dog_name} va perdre ses dents de lait pour laisser place aux dents définitives. C'est une période où le besoin de mâcher s'intensifie. Proposez des jouets adaptés : caoutchouc souple, jouets réfrigérés, cordes à mâcher. Si vous trouvez de petites dents par terre, c'est normal. Le mordillement peut s'intensifier pendant cette phase — soyez patient et redirigez toujours vers un objet approprié. Vérifiez régulièrement la gueule de {dog_name} pour vous assurer que les dents adultes poussent correctement.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_011', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Le rappel : la base de la sécurité`,
    bodyFr: "Le rappel est l'exercice le plus important pour {dog_name}. Commencez dans un environnement calme, à la maison. Appelez son nom suivi de « viens » d'un ton joyeux. Quand il arrive, récompensez généreusement avec une friandise de grande valeur. Ne l'appelez jamais pour quelque chose de désagréable. Pratiquez plusieurs fois par jour, en courtes sessions. Augmentez progressivement la difficulté : dans le jardin, puis dans un parc clôturé, puis avec des distractions. Un rappel solide peut sauver la vie de {dog_name}. Soyez toujours plus intéressant que l'environnement.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_012', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La marche en laisse : premiers pas`,
    bodyFr: "Avant même de sortir, habituez {dog_name} à porter un collier ou un harnais à la maison. Laissez-le traîner la laisse quelques minutes sous surveillance. Dehors, restez patient : un chiot va s'arrêter, renifler, changer de direction. C'est normal — il découvre le monde. Quand {dog_name} tire, arrêtez-vous simplement. Repartez quand la laisse se détend. Récompensez-le quand il marche à vos côtés. Les premières promenades doivent être courtes et positives. L'objectif n'est pas la distance mais la qualité de l'expérience.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_013', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Ne pas sauter sur les gens`,
    bodyFr: "{dog_name} saute sur vous ou vos invités par enthousiasme. C'est flatteur mais il faut lui apprendre une autre façon de dire bonjour. La règle est simple : ignorez le saut et récompensez les quatre pattes au sol. Quand {dog_name} saute, tournez-vous et ne le regardez pas. Dès qu'il pose ses pattes, félicitez et caressez. Demandez à vos visiteurs de faire pareil. Un « assis » bien récompensé à l'arrivée des invités est une excellente alternative. Avec de la constance de toute la famille, {dog_name} comprendra que les câlins arrivent quand il est calme.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_014', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La découverte de l\'eau pour {dog_name}`,
    bodyFr: "Certains chiots adorent l'eau, d'autres en ont réaction d’évitement. Ne forcez jamais {dog_name} à entrer dans l'eau. Commencez par de petites flaques ou un bac peu profond dans le jardin. Lancez un jouet flottant près du bord. Récompensez chaque initiative. Si {dog_name} montre de l'intérêt, laissez-le explorer à son rythme. Pour les races qui aiment naturellement l'eau, comme les retrievers, l'enthousiasme viendra vite. Pour d'autres, il faudra plus de patience. La première expérience avec l'eau doit toujours être positive et jamais contrainte.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_015', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Apprendre la frustration à {dog_name}`,
    bodyFr: "Un chiot doit apprendre que tout n'arrive pas immédiatement. C'est la tolérance à la frustration, et c'est une compétence qui s'enseigne. Commencez simplement : tenez une friandise dans votre main fermée. {dog_name} va gratter, lécher, pousser. Attendez qu'il recule ou s'assoie, puis ouvrez la main. Il apprend que la patience paie. Faites de même avant de poser la gamelle : demandez un « assis » et attendez quelques secondes de calme avant de la poser. Ces petits exercices au quotidien construisent un chien qui gère mieux les attentes.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_016', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Apprendre le calme : une compétence essentielle`,
    bodyFr: "Le calme ne vient pas naturellement à un chiot — ça s'apprend. Installez un tapis ou une couverture au sol. Chaque fois que {dog_name} s'y installe spontanément, récompensez doucement sans l'exciter. Vous pouvez aussi capturer les moments calmes : quand il se pose, glissez-lui une friandise sans rien dire. Il apprendra que « ne rien faire » est aussi récompensé. C'est l'exercice du « calme par défaut ». En quelques semaines, {dog_name} cherchera activement à se poser car il sait que ça rapporte. C'est un des apprentissages les plus précieux.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_017', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Explorer le monde avec prudence`,
    bodyFr: "Chaque sortie est une aventure pour {dog_name}. Laissez-le renifler, observer, écouter — c'est ainsi qu'il apprend. Mais guidez-le aussi. Si quelque chose l'effraie, ne le forcez pas à s'approcher. Restez calme, laissez-le observer à distance et récompensez son courage. Si quelque chose l'attire trop, utilisez des friandises pour rediriger son attention. L'exploration doit être un moment de complicité entre vous. {dog_name} apprend à faire confiance à votre jugement : si vous êtes détendu, il comprend que tout va bien.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_018', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Le panier : un refuge, pas une punition`,
    bodyFr: "Le panier de {dog_name} doit être son endroit préféré, un refuge où il se sent en sécurité. N'envoyez jamais {dog_name} au panier en guise de punition. Au contraire, rendez cet espace attractif : placez-y des friandises, un jouet à mâcher, une couverture douce. Quand {dog_name} y va de lui-même, félicitez-le calmement. Installez le panier dans un endroit calme mais pas isolé — il veut être proche de la famille tout en ayant son espace. Un chien qui aime son panier est un chien qui sait se reposer sereinement.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_019', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `{dog_name} mordille les meubles : comment rediriger`,
    bodyFr: "Un chiot qui mâchouille les pieds de chaise ou les chaussures fait quelque chose de parfaitement naturel — mais il faut le rediriger vers des objets appropriés. Quand vous surprenez {dog_name} en train de mâcher un meuble, ne criez pas. Interrompez calmement avec un « non » et proposez immédiatement un jouet à mâcher. Récompensez quand il accepte l'échange. Rangez les objets tentants hors de portée. Utilisez des sprays amers sur les pieds de meubles si nécessaire. Et surtout, assurez-vous que {dog_name} a suffisamment de stimulation et de repos — un chiot qui détruit manque d’occupation souvent.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_020', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La propreté de nuit : étape par étape`,
    bodyFr: "La propreté de nuit vient souvent après la propreté de jour. Un chiot de moins de 4 mois ne peut généralement pas se retenir toute la nuit. Prévoyez une dernière sortie tard le soir et une première sortie tôt le matin. Si {dog_name} pleure la nuit, c'est peut-être qu'il a besoin de sortir. Emmenez-le dehors sans jouer, sans parler — juste les besoins, puis retour au lit. Progressivement, {dog_name} tiendra plus longtemps. Vers 5-6 mois, la plupart des chiots passent la nuit sans accident. Félicitez chaque nuit propre au réveil.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_021', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Premiers contacts avec d\'autres chiens`,
    bodyFr: "Les rencontres avec d'autres chiens sont cruciales pour {dog_name}. Choisissez des chiens adultes calmes et bien sociabilisés pour les premières interactions. Laissez les chiens se renifler en gardant les laisses détendues. Si l'autre chien est trop brusque, éloignez {dog_name} calmement. Les cours collectifs pour chiots (puppy class) sont un excellent cadre, car les chiots sont du même âge et un professionnel supervise. Évitez les parcs à chiens fréquentés au début — trop de stimulation peut effrayer un jeune chiot.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_022', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La visite chez le vétérinaire sans réaction d’évitement`,
    bodyFr: "Les premières visites vétérinaires conditionnent le rapport de {dog_name} avec le cabinet pour toute sa vie. Faites des visites « sociales » : passez au cabinet juste pour dire bonjour, peser {dog_name} et lui donner une friandise. Habituez-le à être manipulé à la maison : touchez ses pattes, regardez ses oreilles, ouvrez sa gueule, en récompensant. Le jour du rendez-vous, restez calme et confiant. Emportez ses friandises préférées. Un chiot qui associe le vétérinaire à des bonnes choses sera un patient coopératif toute sa vie.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_023', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La nourriture comme outil éducatif`,
    bodyFr: "Les friandises sont votre meilleur outil pour éduquer {dog_name}. Utilisez de petits morceaux — la taille d'un petit pois suffit. Variez les friandises pour maintenir l'intérêt. Réservez les meilleures (dés de poulet, fromage) pour les exercices difficiles comme le rappel. Vous pouvez aussi utiliser une partie de la ration quotidienne de {dog_name} comme récompenses pendant l'éducation. Distribuez les croquettes une par une pendant les exercices plutôt que tout dans la gamelle. {dog_name} travaille pour manger et ça stimule son cerveau.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_024', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Les bruits de la maison : aspirateur et Cie`,
    bodyFr: "L'aspirateur, le sèche-cheveux, le mixeur, la machine à laver — la maison est pleine de monstres bruyants pour {dog_name}. Ne passez pas l'aspirateur en courant après votre chiot. Commencez en posant l'aspirateur éteint au sol et laissez {dog_name} l'inspecter avec des friandises autour. Puis allumez-le brièvement dans une autre pièce. Progressivement, rapprochez l'appareil. Si {dog_name} reste calme, récompensez. La clé est la progressivité et l'association positive. Avec quelques semaines de patience, {dog_name} ignorera ces bruits du quotidien.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_PUPPY_025', category: 'behavior_education', subcategory: 'puppy',
    breedFilter: [] as string[], sizeFilter: [] as string[],
    ageMinMonths: 0, ageMaxMonths: 12,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `{dog_name} et les enfants : apprendre ensemble`,
    bodyFr: "Les enfants et les chiots sont faits pour s'entendre, mais il faut poser des règles. Apprenez aux enfants à ne pas poursuivre {dog_name}, à ne pas le déranger quand il dort ou mange, et à ne pas lui tirer les oreilles ou la queue. Montrez-leur comment le caresser doucement sous le menton plutôt que sur la tête. Supervisez toujours les interactions. Apprenez à {dog_name} que les enfants sont des distributeurs de bonnes choses : les enfants peuvent lui donner des friandises en échange d'un « assis ». Respect mutuel dès le départ.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════
  // ADOLESCENT — 15 templates (12-24 months)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'BE_ADOL_001', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La crise d\'adolescence chez le chien`,
    bodyFr: "Si {dog_name} semble avoir oublié tout ce qu'il avait appris, bienvenue dans l'adolescence canine. Entre 6 et 18 mois selon les races, les chiens traversent une période de réorganisation cérébrale. Le rappel qui était parfait devient aléatoire, les règles semblent avoir disparu. C'est normal et temporaire. Ne relâchez pas la structure : continuez les exercices, récompensez les bons comportements, et soyez patient. C'est le moment de consolider, pas d'abandonner. {dog_name} a besoin de votre constance plus que jamais.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_002', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Le rappel qui se dégrade : que faire ?`,
    bodyFr: "Le rappel de {dog_name} était impeccable et maintenant il fait la sourde oreille ? C'est classique chez l'adolescent. Revenez aux bases : pratiquez dans des environnements peu stimulants avec des récompenses de très haute valeur. Ne l'appelez pas si vous savez qu'il ne viendra pas — chaque échec renforce l'habitude d'ignorer. Utilisez une longe pour maintenir le contrôle tout en lui offrant de la liberté. Et quand il revient, faites la fête. Le rappel doit toujours être associé à quelque chose de positif, jamais à la fin de la promenade.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_003', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Explosion d\'énergie chez l\'ado`,
    bodyFr: "{dog_name} a des pics d'énergie impressionnants — courses folles dans le salon, bonds dans tous les sens. C'est le propre de l'adolescence. La clé est de canaliser cette énergie plutôt que de tenter de l'épuiser. Alternez exercice physique et stimulation mentale. Les jeux de flair, les puzzles alimentaires et les exercices d'obéissance fatiguent autant que la course. Après une bonne stimulation, proposez un temps calme. Un adolescent canin a besoin de structure dans sa journée, pas de marathons.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_004', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Réactivité en laisse : les débuts`,
    bodyFr: "Si {dog_name} commence à tirer vers d'autres chiens ou à réagir en laisse, c'est fréquent à l'adolescence. La frustration de ne pas pouvoir aller saluer, combinée aux hormones, crée de l'agitation. Ne tirez pas sur la laisse en retour — cela augmente la tension. Au lieu de cela, augmentez la distance avec le déclencheur et récompensez {dog_name} quand il vous regarde plutôt que l'autre chien. C'est le principe du « regarde-moi ». Avec de la pratique, {dog_name} apprendra que vous regarder quand un chien passe est plus payant que de tirer. Un éducateur canin peut vous accompagner.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_005', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Le marquage urinaire à l\'adolescence`,
    bodyFr: "Vers 6-12 mois, certains chiens (surtout les mâles non stérilisés) commencent à lever la patte et à marquer leur territoire. En promenade, c'est normal — c'est de la communication canine. À l'intérieur, c'est différent. Si {dog_name} marque à la maison, ce n'est pas de la malpropreté — c'est un comportement hormonal. Nettoyez avec un produit enzymatique et renforcez les sorties régulières. La stérilisation réduit souvent ce comportement. Consultez votre vétérinaire pour en discuter. En attendant, la surveillance et les sorties fréquentes sont vos meilleurs outils.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: 'Votre vétérinaire peut vous conseiller sur la stérilisation.', requiresVetDisclaimer: true,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_006', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Les fugues et explorations de l\'adolescent`,
    bodyFr: "{dog_name} a soudain envie d'explorer au-delà des limites habituelles. Les fugues sont fréquentes chez l'adolescent, poussé par la curiosité et les hormones. Vérifiez la clôture de votre jardin, utilisez une longe en promenade si le rappel n'est pas fiable, et ne laissez pas {dog_name} en liberté dans des zones non sécurisées. Renforcez le rappel avec des récompenses exceptionnelles. Augmentez l'enrichissement : un chien stimulé mentalement a moins envie de partir chercher l'aventure ailleurs. La fugue n'est pas un caprice — c'est un instinct d'exploration. À vous de le canaliser.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_007', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `L\'indépendance de {dog_name} : un signe de maturité`,
    bodyFr: "Si {dog_name} semble soudain moins collé à vous, ne le prenez pas personnellement. L'indépendance naissante est un signe de maturité. Votre adolescent explore sa confiance en lui. C'est le moment de renforcer les liens par des activités partagées : jeux, promenades enrichissantes, séances d'éducation courtes et amusantes. Montrez-lui que revenir vers vous est toujours la meilleure option. Un chien qui choisit de rester près de vous parce qu'il le veut — pas parce qu'il a réaction d’évitement d'être seul — est un chien émotionnellement équilibré.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_008', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La cohérence : clé de l\'éducation de l\'ado`,
    bodyFr: "L'adolescence canine teste vos limites. La règle d'or : toute la famille doit appliquer les mêmes règles. Si {dog_name} n'a pas le droit de monter sur le canapé, personne ne doit l'y inviter en cachette. Si le rappel doit être récompensé, tout le monde récompense. Un chien qui reçoit des messages contradictoires ne peut pas progresser. Faites une réunion de famille rapide : quelles sont les règles pour {dog_name} ? Écrivez-les et affichez-les. La cohérence est le plus beau cadeau que vous puissiez lui faire pendant cette période.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_009', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La frustration du propriétaire : c\'est normal aussi`,
    bodyFr: "Si vous vous sentez dépassé par {dog_name} en ce moment, sachez que vous n'êtes pas seul. L'adolescence canine est la période où le plus de chiens sont abandonnés — c'est dire à quel point elle est difficile. Mais elle passe. Prenez du recul quand vous sentez la frustration monter. Demandez de l'aide à un éducateur canin si besoin. Rappelez-vous pourquoi vous avez choisi {dog_name}. Chaque petit progrès est une victoire. Un adolescent turbulent peut devenir un adulte formidable. Patience et bienveillance — pour {dog_name} et pour vous-même.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_010', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Le jeu adapté à l\'adolescent`,
    bodyFr: "{dog_name} a besoin de jeux qui canalisent son énergie débordante. Les jeux de traction (tire à la corde) sont excellents : ils permettent de travailler le « lâche » et le contrôle. Les jeux de flair fatiguent énormément : cachez des friandises dans le jardin et laissez-le chercher. Les sessions d'obéissance ludiques (enchaîner assis-couché-tourne-donne la patte) stimulent le cerveau. Évitez les jeux qui excitent trop sans canalisation. Terminez toujours par un temps calme. Un adolescent fatigué mentalement est un adolescent qui se repose.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_011', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Exercice physique vs mental : le bon dosage`,
    bodyFr: "Tenter d'épuiser {dog_name} uniquement par l'exercice physique est un piège courant. Plus vous courrez avec lui, plus il deviendra endurant — et vous devrez courir encore plus. Alternez : une promenade active le matin, puis un jeu de réflexion (puzzle alimentaire, recherche de friandises) l'après-midi. La stimulation mentale fatigue autant que la course. Cinq minutes de nosework valent trente minutes de balle. L'équilibre parfait pour un adolescent : 60 % stimulation mentale, 40 % exercice physique.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_012', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `La socialisation continue après l\'enfance`,
    bodyFr: "La socialisation ne s'arrête pas après la période chiot. L'adolescence est un moment où {dog_name} redéfinit ses relations sociales. Certains ados deviennent plus sélectifs dans leurs amitiés canines — c'est normal. Continuez à lui offrir des rencontres positives avec des chiens calmes et bien sociabilisés. Évitez de forcer les interactions avec des chiens qu'il n'apprécie pas. Respectez ses préférences. Un chien n'a pas besoin d'aimer tous les autres chiens — il doit simplement savoir les ignorer poliment.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_013', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Vers la maturité : chaque race a son rythme`,
    bodyFr: "La maturité comportementale n'arrive pas au même âge pour tous les chiens. Les petites races atteignent leur maturité vers 12-18 mois, les moyennes vers 18-24 mois, et les grandes races parfois pas avant 3 ans. {breed_name} a son propre rythme. Ne comparez pas {dog_name} avec le chien du voisin. Certains jours seront meilleurs que d'autres. L'important est la tendance générale : si dans l'ensemble {dog_name} progresse, même lentement, vous êtes sur la bonne voie. La maturité viendra — promis.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_014', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Hormones et comportement chez l\'adolescent`,
    bodyFr: "Les hormones jouent un rôle important dans le comportement de {dog_name} à cet âge. Chez les mâles, la testostérone peut entraîner plus de marquage, d'intérêt pour les femelles et de réactivité envers les autres mâles. Chez les femelles, l'arrivée des premières chaleurs modifie aussi le comportement. Ces changements sont naturels. Discutez avec votre vétérinaire du moment approprié pour une éventuelle stérilisation. En attendant, augmentez la vigilance en promenade et gardez {dog_name} en laisse dans les zones avec d'autres chiens.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: 'Votre vétérinaire peut vous conseiller sur la stérilisation adaptée à {dog_name}.', requiresVetDisclaimer: true,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },
  {
    id: 'BE_ADOL_015', category: 'behavior_education', subcategory: 'adolescent',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 12, ageMaxMonths: 24,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: `Patience et constance : le mantra de l\'ado`,
    bodyFr: "Répétez-vous ce mantra : patience et constance. {dog_name} n'a pas oublié ce que vous lui avez appris — son cerveau est en pleine réorganisation. Continuez les mêmes exercices, les mêmes récompenses, les mêmes règles. Célébrez chaque petit progrès. Ne vous comparez pas aux vidéos parfaites sur les réseaux sociaux. Votre relation avec {dog_name} se construit dans la réalité du quotidien, avec ses hauts et ses bas. L'adolescence est une épreuve temporaire. De l'autre côté vous attend un compagnon adulte extraordinaire.",
    sourceType: 'behavior_tip' as const, neverSay, suffix: null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  },

  // ═══════════════════════════════════════════════════════════════
  // ADULT — 30 templates (24+ months)
  // ═══════════════════════════════════════════════════════════════
  ...generateAdultTemplates(),

  // ═══════════════════════════════════════════════════════════════
  // SENIOR — 20 templates (96+ months)
  // ═══════════════════════════════════════════════════════════════
  ...generateSeniorTemplates(),

  // ═══════════════════════════════════════════════════════════════
  // SOCIALIZATION — 15 templates (all ages)
  // ═══════════════════════════════════════════════════════════════
  ...generateSocializationTemplates(),

  // ═══════════════════════════════════════════════════════════════
  // SEPARATION — 15 templates (all ages)
  // ═══════════════════════════════════════════════════════════════
  ...generateSeparationTemplates(),
];

function generateAdultTemplates() {
  const topics = [
    { id: 'BE_ADULT_001', title: 'Comprendre pourquoi {dog_name} aboie', body: "L'aboiement est un mode de communication naturel. {dog_name} peut aboyer pour prévenir d'une présence, par ennui, par excitation ou par frustration. Avant de vouloir faire taire les aboiements, cherchez à comprendre leur cause. Un chien qui aboie à la fenêtre veille sur son territoire. Un chien qui aboie quand il est seul exprime un mal-être. Un chien qui aboie en promenade est souvent frustré ou surexcité. La solution dépend de la cause. Observez le contexte, l'intensité et la durée des aboiements pour mieux comprendre ce que {dog_name} essaie de vous dire. Un éducateur canin peut vous aider à décoder ces signaux." },
    { id: 'BE_ADULT_002', title: 'Destructions : ennui ou inconfort ?', body: "Si {dog_name} détruit en votre absence, ce n'est pas de la vengeance. Les chiens ne fonctionnent pas ainsi. Deux causes principales : l'ennui ou un inconfort lié à la solitude. Un chien qui manque d’occupation mâche pour s'occuper — offrez-lui des jouets d'occupation (Kong fourré, tapis de léchage). Un chien inconfortable seul montre d'autres signes : halètement, salivation, déplacement constant. Dans ce cas, le problème est plus profond et nécessite un travail progressif sur la séparation. Observez {dog_name} avec une caméra pour comprendre ce qui se passe vraiment quand vous partez." },
    { id: 'BE_ADULT_003', title: 'Tirer en laisse : des solutions durables', body: "{dog_name} tire en laisse ? C'est le problème numéro un en promenade. La solution : ne plus avancer quand la laisse est tendue. Dès que {dog_name} tire, arrêtez-vous. Attendez que la laisse se détende, puis repartez. C'est long au début mais efficace. Récompensez chaque moment où {dog_name} marche à côté de vous. Un harnais anti-traction peut aider en complément. Mais surtout, rendez la promenade intéressante : laissez-le renifler, changez de direction, proposez des friandises quand il vous regarde. Un chien qui tire veut aller plus vite — montrez-lui que rester près de vous est tout aussi gratifiant." },
    { id: 'BE_ADULT_004', title: '{dog_name} a réaction d’évitement de l\'orage', body: "Beaucoup de chiens sont sensibles aux orages — le bruit, les changements de pression atmosphérique, l'électricité statique. Si {dog_name} se cache, tremble ou cherche votre contact pendant un orage, restez calme et disponible. Ne le forcez pas à sortir de sa cachette, ne le grondez pas, mais ne surjouez pas non plus la compassion. Offrez-lui un endroit sûr : une pièce intérieure, un panier couvert. La musique douce peut couvrir le bruit du tonnerre. Des friandises ou un jouet d'occupation peuvent aussi détourner son attention. Avec le temps, certains chiens s'habituent." },
    { id: 'BE_ADULT_005', title: 'Réactivité en laisse : comprendre et agir', body: "Un chien qui tire, aboie ou s'agite en croisant d'autres chiens en laisse est un chien réactif, pas un mauvais chien. La réactivité est souvent liée à la frustration (il veut aller dire bonjour) ou à l'inconfort (il se sent coincé par la laisse). La distance est votre amie : pratiquez le « regarde-moi » en éloignant {dog_name} suffisamment du déclencheur. Récompensez tout regard calme dans votre direction. Ne tirez pas sur la laisse — cela augmente la tension. Progressivement, réduisez la distance. Ce travail prend du temps mais les résultats sont durables." },
    { id: 'BE_ADULT_006', title: 'La routine : le secret d\'un chien serein', body: "Les chiens aiment la prévisibilité. Une routine régulière — promenades aux mêmes heures, repas à heures fixes, moments de jeu et de repos définis — aide {dog_name} à se sentir en sécurité. Un chien qui sait ce qui va arriver est un chien plus détendu. Cela ne veut pas dire que chaque journée doit être identique, mais le cadre général doit être stable. Les repas, la promenade du matin, le moment calme de l'après-midi, la promenade du soir — ces repères structurent la journée de {dog_name} et lui permettent de se reposer entre les moments d'activité." },
    { id: 'BE_ADULT_007', title: 'Les signaux d\'apaisement du chien', body: "Les chiens communiquent constamment avec leur corps. Les signaux d'apaisement sont des gestes que {dog_name} utilise pour montrer qu'il est calme, qu'il veut calmer l'autre, ou qu'il est mal à l'aise. Détourner la tête, lécher ses babines, bâiller, se secouer (hors de l'eau), renifler le sol — tous sont des signaux d'apaisement. Quand vous les observez chez {dog_name}, demandez-vous ce qui se passe dans son environnement. Apprendre à lire ces signaux transforme votre relation : vous comprenez {dog_name} avant qu'il n'ait besoin de monter en intensité." },
    { id: 'BE_ADULT_008', title: 'Jeu entre chiens : le bon et le moins bon', body: "Quand {dog_name} joue avec d'autres chiens, observez la dynamique. Un bon jeu est réciproque : les deux chiens s'amusent, ils alternent les rôles (poursuivant/poursuivi), ils font des pauses naturelles. Un jeu qui dérape : un chien est toujours au sol, les grognements deviennent graves, un chien tente de fuir sans y arriver, le jeu s'intensifie sans pause. Intervenez en douceur si vous voyez que {dog_name} ou son partenaire montre des signes d'inconfort. Mieux vaut une pause courte que de laisser la situation dégénérer." },
    { id: 'BE_ADULT_009', title: '{dog_name} dort beaucoup : c\'est normal !', body: "Un chien adulte dort entre 12 et 18 heures par jour. Oui, autant. Et c'est parfaitement normal. Le sommeil est essentiel pour la suivi vétérinaire physique et mentale de {dog_name}. Ne vous inquiétez pas si votre chien passe la majorité de la journée à se reposer entre les promenades. C'est son rythme naturel. Respectez ses moments de sommeil et offrez-lui un couchage confortable dans un endroit calme. Un chien bien reposé est un chien plus concentré, plus patient et plus agréable à vivre." },
    { id: 'BE_ADULT_010', title: 'L\'enrichissement au quotidien', body: "L'enrichissement n'est pas un luxe, c'est un besoin. {dog_name} a un cerveau qui demande à être stimulé. Variez les jouets d'occupation, proposez des puzzles alimentaires, cachez des friandises dans la maison ou le jardin, apprenez-lui de nouveaux tours. Cinq minutes de stimulation mentale par jour changent tout. Un Kong fourré, un tapis de fouille, une balle à friandises — ces objets simples occupent {dog_name} de façon constructive. Un chien stimulé est un chien qui ne cherche pas à inventer ses propres divertissements (comme détruire le canapé)." },
    { id: 'BE_ADULT_011', title: 'Promenade libre vs en laisse', body: "Idéalement, {dog_name} devrait profiter des deux. La promenade en laisse structure et rassure, la promenade libre permet d'explorer, de courir et de renifler à son rythme. Si le rappel de {dog_name} est fiable, cherchez des espaces sécurisés pour le lâcher. Sinon, une longe de 5 à 10 mètres offre un bon compromis. En ville, la laisse est obligatoire et nécessaire pour la sécurité. En campagne ou en forêt, la liberté contrôlée est un bonheur pour {dog_name}. L'important est de varier les types de promenade." },
    { id: 'BE_ADULT_012', title: 'Communiquer avec {dog_name}', body: "Votre voix, votre posture et vos gestes sont autant de messages pour {dog_name}. Parlez-lui d'un ton calme et clair. Les ordres courts (assis, viens, stop) sont plus efficaces que les phrases longues. Votre langage corporel compte énormément : penchez-vous légèrement en vous tournant de côté pour l'inviter, restez droit pour marquer un arrêt. {dog_name} lit votre humeur mieux que quiconque. Quand vous êtes détendu, il l'est aussi. Quand vous êtes tendu, il le perçoit. La communication est un dialogue permanent entre vous." },
    { id: 'BE_ADULT_013', title: 'Lire le langage corporel de {dog_name}', body: "La queue, les oreilles, la posture générale, les yeux — {dog_name} vous parle constamment. Queue haute et rigide : vigilance ou excité. Queue basse entre les pattes : inconfort. Oreilles plaquées : réaction d’évitement ou soumission. Oreilles dressées vers l'avant : intérêt. Corps détendu, bouche légèrement ouverte : chien serein. Corps raide, regard fixe : tension. Apprenez à observer {dog_name} dans différentes situations pour créer votre dictionnaire personnel. Chaque chien a ses propres nuances d'expression." },
    { id: 'BE_ADULT_014', title: '{dog_name} et le canapé : poser des règles claires', body: "Le canapé n'est ni un droit ni un interdit absolu — c'est votre choix. L'important est la constance. Si {dog_name} a le droit de monter, c'est toujours. S'il n'a pas le droit, c'est jamais. La confusion naît des exceptions. Si vous souhaitez limiter l'accès, enseignez le « descends » avec une récompense au sol. Proposez un panier confortable à côté du canapé — ainsi {dog_name} reste près de vous sans être dessus. Ce qui compte, c'est que la règle soit claire et constante pour tout le monde dans la maison." },
    { id: 'BE_ADULT_015', title: 'Gérer les invités avec {dog_name}', body: "L'arrivée d'invités est un moment excitant pour {dog_name}. Pour éviter les bonds et l'agitation, établissez un protocole. Avant l'arrivée, promenez {dog_name} pour diminuer son énergie. Quand la sonnette retentit, demandez un « assis » ou envoyez-le à son panier. Récompensez le calme. Demandez à vos invités de ne saluer {dog_name} que lorsqu'il est calme (quatre pattes au sol). Vous pouvez aussi lui donner un jouet d'occupation à l'arrivée des invités pour canaliser son excitation. La répétition crée la routine." },
    { id: 'BE_ADULT_016', title: 'Chien et chat : la cohabitation', body: "La cohabitation chien-chat est possible mais demande de la patience. Laissez le chat avoir des zones en hauteur inaccessibles au chien. Les premières rencontres se font à travers une porte fermée (échange d'odeurs), puis avec une barrière visuelle, puis en présence surveillée. Récompensez {dog_name} quand il ignore le chat ou reste calme en sa présence. Ne laissez jamais {dog_name} poursuivre le chat — même en jeu. Le chat doit toujours pouvoir fuir. Avec le temps, beaucoup de chiens et de chats trouvent un équilibre paisible." },
    { id: 'BE_ADULT_017', title: '{dog_name} aboie à la sonnette', body: "La sonnette est un déclencheur classique d'aboiements. {dog_name} a appris que sonnette = quelqu'un arrive = excitation. Pour changer cette association, entraînez en dehors des visites réelles. Demandez à quelqu'un de sonner pendant que vous envoyez {dog_name} sur son tapis avec une friandise. Récompensez-le quand il reste calme. Répétez des dizaines de fois. Vous pouvez aussi remplacer la sonnette par un carillon moins stimulant. L'objectif : sonnette = aller au tapis, pas sonnette = aboyer comme un fou." },
    { id: 'BE_ADULT_018', title: 'Protection de ressources : comprendre et agir', body: "Si {dog_name} grogne ou se raidit quand vous approchez de sa gamelle ou de son jouet, il protège ses ressources. C'est un comportement naturel, pas un signe de méchanceté. Ne retirez pas la gamelle de force — cela empire les choses. Au contraire, passez près de lui et ajoutez quelque chose de bon dans sa gamelle. Apprenez-lui que votre approche signifie « bonus ». Échangez les jouets plutôt que de les prendre. Si le comportement est intense, consultez un éducateur canin comportementaliste. Ce n'est pas à ignorer mais ce n'est pas non plus dramatique." },
    { id: 'BE_ADULT_019', title: '{dog_name} creuse dans le jardin', body: "Creuser est un instinct naturel chez de nombreuses races. {dog_name} peut creuser par ennui, pour chercher de la fraîcheur, pour cacher un os ou simplement par plaisir. Plutôt que d'interdire totalement, proposez une zone de fouille dédiée : un bac à sable ou un coin du jardin où il a le droit de creuser. Enterrez-y des jouets ou friandises pour l'y attirer. Augmentez l'enrichissement et l'exercice pour réduire l'ennui. Un chien qui creuse tout le jardin est souvent un chien qui manque de stimulation." },
    { id: 'BE_ADULT_020', title: 'Mâcher est un besoin naturel', body: "Mâcher n'est pas un caprice — c'est un besoin fondamental pour {dog_name}. La mastication soulage le forte sollicitation, nettoie les dents et occupe l'esprit. Offrez-lui des options variées et adaptées à sa taille : os à mâcher naturels, bâtonnets séchés, jouets en caoutchouc durables. Évitez les os cuits qui se cassent en éclats. Supervisez les premières utilisations d'un nouveau jouet à mâcher. Un chien qui a des options de mastication appropriées laissera vos chaussures tranquilles." },
    { id: 'BE_ADULT_021', title: '{dog_name} tire vers les autres chiens', body: "Quand {dog_name} tire vers chaque chien croisé en promenade, c'est généralement de la frustration sociale — il veut aller saluer. Arrêtez-vous dès qu'il tire. Attendez le retour au calme. Récompensez quand il vous regarde. Progressivement, il comprendra que le calme mène à la possibilité de saluer (quand c'est approprié). Tous les chiens ne sont pas compatibles pour un bonjour — apprenez à lire les signaux de l'autre chien et de son propriétaire avant d'autoriser le contact." },
    { id: 'BE_ADULT_022', title: 'Forêt vs ville : deux promenades différentes', body: "La promenade en forêt et la promenade en ville n'ont pas le même objectif pour {dog_name}. En ville, c'est la structure : marche au pied, gestion des stimuli, obéissance aux feux. En forêt ou en nature, c'est l'exploration : renifler, courir, patauger, suivre des pistes. {dog_name} a besoin des deux. L'idéal est de varier : ville en semaine pour la routine, nature le week-end pour la décompression. Adaptez votre matériel — un harnais confortable et une longe pour la nature, une laisse courte pour la ville." },
    { id: 'BE_ADULT_023', title: 'Le renforcement positif au quotidien', body: "Le renforcement positif n'est pas qu'un outil d'éducation — c'est un mode de vie. Chaque fois que {dog_name} fait quelque chose de bien, remarquez-le. Il se couche calmement ? « Bon chien. » Il regarde un vélo passer sans réagir ? Friandise. Il attend patiemment devant la porte ? Félicitation. Nous avons tendance à ne remarquer que les erreurs. Inversez : cherchez activement les bons comportements et récompensez-les. {dog_name} fera de plus en plus ce qui « paie » et de moins en moins ce qui est ignoré." },
    { id: 'BE_ADULT_024', title: 'Le rituel du coucher de {dog_name}', body: "Un rituel de coucher aide {dog_name} à comprendre que la journée est finie et qu'il est temps de se reposer. Dernière sortie pipi, dernière caresse, une friandise dans son panier et extinction des lumières. Chaque soir, même séquence. Les chiens adorent la prévisibilité. Si {dog_name} a du mal à se poser le soir, c'est peut-être qu'il n'a pas assez dépensé son énergie dans la journée — ou au contraire qu'il est surstimulé. Un temps calme de 30 minutes avant le coucher aide à la transition." },
    { id: 'BE_ADULT_025', title: '{dog_name} saute sur les gens : rappel', body: "Même adulte, certains chiens continuent de sauter pour dire bonjour. C'est un comportement appris dans l'enfance et renforcé involontairement (on le caresse quand il saute). La solution reste la même : ignorer le saut, récompenser les pattes au sol. Tournez le dos, croisez les bras, ne parlez pas. Dès que {dog_name} a les quatre pattes au sol, récompensez avec attention et friandise. Demandez à tout le monde — famille, amis, passants — de suivre la même règle. La cohérence est la clé." },
    { id: 'BE_ADULT_026', title: 'Promenades du soir en sécurité', body: "En hiver, les promenades du soir se font dans l'obscurité. Équipez {dog_name} d'un collier ou harnais réfléchissant, ou d'une petite lumière LED à accrocher au collier. Portez vous-même des vêtements clairs. Restez sur des chemins que vous connaissez bien. Gardez {dog_name} en laisse près des routes — les conducteurs voient moins bien la nuit. Emportez une lampe de poche pour surveiller ce que {dog_name} renifle au sol. La sécurité nocturne est une affaire de visibilité et de vigilance." },
    { id: 'BE_ADULT_027', title: '{dog_name} et les vélos ou trottinettes', body: "Certains chiens sont fascinés ou excités par les vélos et trottinettes qui passent. Si {dog_name} tire ou aboie au passage d'un cycliste, travaillez la désensibilisation. Asseyez-vous sur un banc dans un parc et récompensez {dog_name} à chaque passage de vélo qu'il observe sans réagir. Commencez à distance et rapprochez-vous progressivement. Ne grondez pas la réaction — récompensez le calme. En attendant que le travail porte ses fruits, anticipez en éloignant {dog_name} quand vous voyez un vélo arriver." },
    { id: 'BE_ADULT_028', title: '{dog_name} refuse de marcher en promenade', body: "Si {dog_name} plante ses pattes et refuse d'avancer, ne tirez pas sur la laisse. Cherchez la cause : a-t-il réaction d’évitement de quelque chose ? Le sol est-il trop chaud ou trop froid ? Est-il fatigué ? Un changement de parcours peut suffire. Proposez une friandise quelques pas devant lui. Si cela se répète régulièrement, vérifiez que ses pattes ne sont pas blessées et que son harnais est confortable. Un chien qui refuse systématiquement de marcher essaie de vous dire quelque chose." },
    { id: 'BE_ADULT_029', title: '{dog_name} et les bruits de travaux', body: "Les travaux dans le voisinage ou à la maison peuvent perturber {dog_name}. Bruits de perceuse, de marteau-piqueur, de camions — c'est beaucoup pour ses oreilles sensibles. Si possible, éloignez {dog_name} de la zone de bruit. Créez un espace refuge calme avec musique douce. Les jouets d'occupation aident à détourner l'attention. Si les travaux sont chez vous, sortez {dog_name} pendant les phases les plus bruyantes. Avec le temps, certains chiens s'habituent. D'autres restent sensibles — respectez le rythme de {dog_name}." },
    { id: 'BE_ADULT_030', title: 'La routine du matin avec {dog_name}', body: "Le matin donne le ton de la journée. Une bonne routine matinale pour {dog_name} : sortie pipi rapide, petit-déjeuner, puis promenade. Certains chiens préfèrent manger après la promenade — observez ce qui convient à {dog_name}. Évitez l'exercice intense juste après le repas. Le matin est souvent le meilleur moment pour les rencontres avec d'autres chiens, car tout le monde est frais et de bonne humeur. Même 20 minutes de promenade matinale de qualité posent les bases d'une bonne journée." },
  ];
  return topics.map(t => ({
    id: t.id, category: 'behavior_education' as const, subcategory: 'adult',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 24, ageMaxMonths: null as number | null,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: t.title, bodyFr: t.body, sourceType: 'behavior_tip' as const,
    neverSay: [...NS], suffix: null as string | null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 252, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: false, usesLocation: false, usesSeason: false,
  }));
}

function generateSeniorTemplates() {
  const topics = [
    { id: 'BE_SENIOR_001', title: 'Le ralentissement de {dog_name} : tout à fait normal', body: "{dog_name} ralentit un peu ? C'est naturel avec l'âge. Les promenades sont peut-être un peu plus courtes, les siestes un peu plus longues. Acceptez ce nouveau rythme avec bienveillance. Ne forcez jamais {dog_name} à dépasser ses limites. Adaptez les activités : des promenades plus courtes mais plus fréquentes, à un rythme qui lui convient. Le senior a encore beaucoup de enthousiasme à partager — simplement à un tempo différent.", vet: false },
    { id: 'BE_SENIOR_002', title: 'Adapter les promenades au senior', body: "Les longues randonnées font peut-être partie du passé pour {dog_name}, et c'est normal. Privilégiez des promenades plus courtes (15-30 minutes) mais régulières (2-3 fois par jour). Choisissez des terrains souples (herbe, terre) plutôt que le bitume dur. Évitez les montées et descentes raides. Laissez {dog_name} renifler à son rythme — c'est sa façon de profiter de la promenade. En hiver, les articulations peuvent être plus raides le matin. Attendez que la température se réchauffe pour sortir.", vet: false },
    { id: 'BE_SENIOR_003', title: 'Un couchage confortable pour {dog_name}', body: "Avec l'âge, le confort du couchage devient crucial. Investissez dans un matelas orthopédique ou à mémoire de forme pour {dog_name}. Placez-le au ras du sol — pas de saut pour y accéder. Choisissez un endroit sans courant d'air mais pas trop près du radiateur. Si {dog_name} a du mal à se lever, un tapis antidérapant autour de son panier l'aidera. Un bon sommeil est encore plus important pour un senior que pour un adulte.", vet: false },
    { id: 'BE_SENIOR_004', title: 'Enrichissement doux pour le senior', body: "L'enrichissement reste essentiel pour {dog_name}, même en douceur. Les puzzles alimentaires simples, les tapis de fouille et les jeux de recherche à la maison maintiennent son cerveau actif. Proposez des séances courtes (5-10 minutes) pour ne pas le fatiguer. Le reniflage en promenade est un enrichissement naturel et gratuit. {dog_name} n'a pas besoin de courir un marathon — juste de continuer à explorer et à apprendre à son rythme.", vet: false },
    { id: 'BE_SENIOR_005', title: 'Observer les changements chez {dog_name}', body: "Avec l'âge, certains changements sont normaux chez {dog_name} : sommeil accru, rythme plus lent, appétit parfois variable. Restez attentif sans vous alarmer. Un carnet de bord peut être utile : notez les heures de repas, l'énergie en promenade, la qualité du sommeil. Si vous remarquez un changement soudain ou progressif qui vous inquiète, notez-le pour en parler lors de la prochaine visite annuelle.", vet: true },
    { id: 'BE_SENIOR_006', title: 'La patience avec un chien senior', body: "{dog_name} met plus de temps à se lever ? Il ne répond plus aussi vite ? Ses capacités sensorielles changent peut-être. La patience est le plus beau cadeau que vous puissiez faire à votre compagnon vieillissant. Parlez-lui d'une voix douce et claire. Donnez-lui le temps de comprendre. Ne le brusquez pas. Chaque moment partagé a de la valeur, même les plus calmes.", vet: false },
    { id: 'BE_SENIOR_007', title: 'Articulations et temps froid', body: "Par temps froid, les articulations de {dog_name} peuvent être plus raides, surtout le matin. Attendez qu'il s'échauffe naturellement avant la promenade — un peu de marche lente dans la maison suffit. Dehors, évitez le verglas et les sols glissants. Un manteau chaud peut être utile pour les races à poil court ou les chiens très âgés. Gardez la maison à une température agréable et assurez-vous que son couchage est bien rembourré.", vet: true },
    { id: 'BE_SENIOR_008', title: 'La routine : encore plus importante pour le senior', body: "Si la routine est importante pour tout chien, elle est essentielle pour {dog_name} à cet âge. Les mêmes horaires de repas, les mêmes parcours de promenade, les mêmes rituels du coucher. La prévisibilité rassure un chien dont les sens peuvent changer. Si sa vision ou son audition diminue, il s'appuie encore plus sur ses repères habituels. Évitez de réaménager la maison ou de changer ses habitudes brusquement.", vet: false },
    { id: 'BE_SENIOR_009', title: 'Les siestes plus longues du senior : normal', body: "Si {dog_name} dort plus qu'avant, ne vous inquiétez pas. Un chien senior peut dormir jusqu'à 18-20 heures par jour. Son corps récupère plus lentement et a besoin de davantage de repos. Respectez ses phases de sommeil, ne le réveillez pas inutilement et assurez-vous qu'il a un endroit calme et confortable pour dormir. Le sommeil est réparateur et essentiel à son bien-être.", vet: false },
    { id: 'BE_SENIOR_010', title: 'Jeux calmes pour un senior à l’aise', body: "Le jeu ne s'arrête pas avec l'âge — il se transforme. {dog_name} appréciera les jeux calmes et courts : cache-cache dans la maison, recherche de friandises, le jeu de la « boîte aux trésors » (une boîte en carton avec des friandises cachées dans du papier). Les jeux d'intelligence doux stimulent son cerveau sans fatiguer son corps. Observez ce qui fait briller ses yeux et proposez-en régulièrement.", vet: false },
    { id: 'BE_SENIOR_011', title: 'Promenades courtes et fréquentes', body: "Deux longues promenades par jour sont peut-être devenues trop pour {dog_name}. Passez à trois ou quatre sorties plus courtes. Dix à quinze minutes de promenade tranquille, quatre fois par jour, apportent plus de bénéfices qu'une seule longue sortie épuisante. {dog_name} a aussi besoin de sorties pipi plus fréquentes en vieillissant. Adaptez votre emploi du temps à ses besoins actuels.", vet: false },
    { id: 'BE_SENIOR_012', title: 'Les escaliers et les accès difficiles', body: "Monter et descendre les escaliers peut devenir difficile pour {dog_name} avec l'âge. Si possible, installez son couchage et sa gamelle au rez-de-chaussée. Une rampe d'accès peut aider pour la voiture ou un marche-pied pour le canapé (s'il y a accès). Des tapis antidérapants dans les couloirs et les escaliers préviennent les glissades. Surveillez {dog_name} dans les escaliers et aidez-le si nécessaire. Mieux vaut prévenir qu'attendre une chute.", vet: false },
    { id: 'BE_SENIOR_013', title: 'Le senior et les chiots : cohabitation', body: "Si vous accueillez un chiot alors que {dog_name} est senior, supervisez attentivement les interactions. Un chiot débordant d'énergie peut fatiguer ou agacer un chien plus âgé. Offrez à {dog_name} des espaces de repos où le chiot ne peut pas le déranger. Supervisez les jeux et intervenez si le chiot est trop insistant. Respectez les signaux de {dog_name} quand il en a assez. Beaucoup de seniors apprécient la compagnie d'un jeune, mais à leur rythme.", vet: false },
    { id: 'BE_SENIOR_014', title: 'Alimentation adaptée à l\'âge de {dog_name}', body: "Les besoins nutritionnels de {dog_name} évoluent avec l'âge. Un chien senior a généralement besoin de moins de calories mais de protéines de qualité pour maintenir sa masse musculaire. Fractionnez les repas si nécessaire — deux petits repas sont parfois mieux digérés qu'un seul gros. Assurez-vous que l'eau est toujours fraîche et accessible facilement. Surélevez les gamelles si {dog_name} a du mal à se pencher.", vet: true },
    { id: 'BE_SENIOR_015', title: 'Vision et audition qui changent', body: "Avec l'âge, la vision et l'audition de {dog_name} peuvent diminuer. Si vous remarquez qu'il ne réagit plus à son nom de loin, parlez-lui de plus près et utilisez des gestes. Si sa vision baisse, évitez de déplacer les meubles et laissez des lumières allumées la nuit. Les chiens compensent remarquablement bien grâce à leur odorat et leur mémoire spatiale. Adaptez vos signaux de communication et continuez à interagir normalement avec {dog_name}.", vet: true },
    { id: 'BE_SENIOR_016', title: 'Stimulation mentale douce', body: "Le cerveau de {dog_name} a besoin d'être entretenu comme un muscle. Les exercices simples d'obéissance (assis, couché, donne la patte), même s'il les connaît depuis des années, sont une bonne stimulation. Proposez des jeux olfactifs : cachez une friandise sous un gobelet retourné parmi trois. Changez de parcours de promenade pour stimuler de nouvelles odeurs. La routine est rassurante mais de petites variations maintiennent la curiosité de {dog_name}.", vet: false },
    { id: 'BE_SENIOR_017', title: 'Câlins et contact physique', body: "Le contact physique prend une dimension encore plus importante avec l'âge. {dog_name} apprécie peut-être davantage les caresses, les massages doux et votre simple présence à ses côtés. Massez doucement ses épaules et ses hanches — cela soulage les tensions musculaires. Brossez-le avec douceur, c'est un moment de bien-être partagé. Ces moments de connexion renforcent votre lien et apportent un réel confort à {dog_name}.", vet: false },
    { id: 'BE_SENIOR_018', title: '{dog_name} senior en voiture', body: "Monter et descendre de voiture peut devenir difficile pour {dog_name}. Une rampe pliable est un investissement précieux — elle évite les sauts qui sont durs pour les articulations. Installez un tapis antidérapant sur la banquette ou dans le coffre. Pour les longs trajets, prévoyez des pauses plus fréquentes. Assurez-vous que la température dans la voiture est agréable. {dog_name} mérite un transport confortable à tous les âges.", vet: false },
    { id: 'BE_SENIOR_019', title: 'Garder une vie sociale pour le senior', body: "Ce n'est pas parce que {dog_name} ralentit qu'il doit rester isolé. Les rencontres avec des chiens calmes et compatibles restent bénéfiques. Même se contenter de renifler un congénère au passage est une interaction sociale riche pour {dog_name}. Adaptez les contextes : préférez les promenades à deux plutôt que les parcs bondés. La présence d'autres êtres vivants stimule {dog_name} et maintient sa enthousiasme de vivre.", vet: false },
    { id: 'BE_SENIOR_020', title: 'Profiter de chaque moment avec {dog_name}', body: "Le temps avec un chien senior est précieux. Savourez les promenades tranquilles, les moments de tendresse, les regards complices. {dog_name} n'a peut-être plus l'énergie de ses jeunes années, mais il a quelque chose de plus : la sérénité, la sagesse et un amour inconditionnel forgé par des années de vie commune. Photographiez, câlinez, promenez. Chaque jour est un cadeau. Profitez de {dog_name} tel qu'il est aujourd'hui, avec toute la gratitude qu'il mérite.", vet: false },
  ];
  return topics.map(t => ({
    id: t.id, category: 'behavior_education' as const, subcategory: 'senior',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: 96, ageMaxMonths: null as number | null,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: t.title, bodyFr: t.body, sourceType: 'behavior_tip' as const,
    neverSay: [...NS], suffix: t.vet ? 'Votre vétérinaire peut vous conseiller sur les besoins spécifiques de {dog_name} à cet âge.' : null,
    requiresVetDisclaimer: t.vet,
    channel: 'home_insight' as const, priority: 7, cooldownHours: 336, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: true, usesLocation: false, usesSeason: false,
  }));
}

function generateSocializationTemplates() {
  const topics = [
    { id: 'BE_SOCIAL_001', title: 'Comprendre la socialisation canine', body: "La socialisation, c'est apprendre à {dog_name} que le monde est un endroit sûr. Ce n'est pas forcer le contact avec tout et tout le monde, mais exposer progressivement à des stimuli variés en créant des associations positives. Un chien bien socialisé est un chien confiant, pas forcément un chien qui va vers tout le monde. L'objectif est que {dog_name} puisse évoluer dans le monde humain avec sérénité, en sachant ignorer ce qui ne le concerne pas." },
    { id: 'BE_SOCIAL_002', title: 'La fenêtre de socialisation du chiot', body: "Entre 3 et 14 semaines, le chiot est dans une période de grande ouverture au monde. C'est le moment où {dog_name} forme ses impressions durables sur ce qui est normal et ce qui ne l'est pas. Chaque expérience positive pendant cette fenêtre vaut de l'or. Exposez-le à différents types de personnes, d'animaux, de bruits, de surfaces et d'environnements. Allez-y progressivement et positivement. Ce qui n'est pas vu pendant cette période sera considéré comme nouveau — et potentiellement inquiétant — plus tard." },
    { id: 'BE_SOCIAL_003', title: 'Socialiser un chien adulte : c\'est possible', body: "La socialisation ne s'arrête pas à l'enfance. Si {dog_name} est adulte et manque de socialisation, tout n'est pas perdu — mais le travail sera plus progressif. Commencez par des expositions à distance, sans contact direct. Récompensez le calme. Augmentez très progressivement la proximité. Ne forcez jamais une interaction. Un éducateur canin peut vous accompagner dans ce parcours. La patience est la clé : chaque petit progrès compte et construit la confiance de {dog_name}." },
    { id: 'BE_SOCIAL_004', title: 'Exposer sans forcer : la règle d\'or', body: "La règle numéro un de la socialisation : ne jamais forcer {dog_name}. Si un chien, une personne ou un bruit l'inquiète, augmentez la distance. Ne le poussez pas vers ce qui lui fait réaction d’évitement « pour qu'il s'habitue ». Laissez-le observer de loin, récompensez son calme, et rapprochez-vous à son rythme sur plusieurs sessions. Forcer un chien à affronter sa réaction d’évitement produit l'effet inverse : ça renforce la réaction d’évitement. La socialisation doit toujours être une expérience positive et volontaire." },
    { id: 'BE_SOCIAL_005', title: 'Reconnaître les signaux de réaction d’évitement', body: "Quand {dog_name} est inconfortable, il vous le dit avec son corps. Queue basse ou entre les pattes, oreilles plaquées, corps recroquevillé, bâillements répétés, léchage de babines, détournement du regard. Si vous voyez ces signaux lors d'une socialisation, augmentez la distance et laissez {dog_name} se détendre. Ne le forcez pas à rester dans une situation qui le met mal à l'aise. Respecter ses signaux renforce sa confiance en vous." },
    { id: 'BE_SOCIAL_006', title: 'Les bons parcs à chiens pour {dog_name}', body: "Les parcs à chiens peuvent être formidables ou désastreux, selon la gestion. Choisissez des parcs avec peu de chiens au début. Observez l'ambiance avant d'entrer : les chiens jouent-ils calmement ? Les propriétaires sont-ils attentifs ? Entrez quand c'est calme. Restez attentif au langage corporel de {dog_name} et intervenez si le jeu s'intensifie trop. Quittez le parc si l'ambiance devient tendue. Un mauvais parc peut faire plus de mal que de bien." },
    { id: 'BE_SOCIAL_007', title: '{dog_name} et les autres espèces', body: "Chats, poules, chevaux, lapins — {dog_name} peut croiser d'autres espèces en promenade ou à la maison. Chaque nouvelle espèce doit être introduite à distance et sous contrôle. Récompensez {dog_name} quand il observe calmement. Ne laissez jamais un chien non supervisé avec un petit animal. L'instinct de chasse est naturel chez certaines races. La cohabitation est possible mais demande de l'encadrement et du respect des instincts de chacun." },
    { id: 'BE_SOCIAL_008', title: '{dog_name} et les enfants inconnus', body: "Les enfants bougent vite, crient et font des gestes imprévisibles — ce qui peut déconcerter {dog_name}. Apprenez-lui que les enfants sont associés à de bonnes choses (friandises à distance). Ne laissez jamais un enfant inconnu approcher {dog_name} sans votre accord. Supervisez toujours les interactions. Si {dog_name} semble inconfortable, éloignez-le calmement. Un chien à l'aise avec les enfants est un chien qui a été exposé progressivement et positivement." },
    { id: 'BE_SOCIAL_009', title: 'La promenade en groupe', body: "Promener {dog_name} avec d'autres chiens est un excellent exercice de socialisation. En marchant côte à côte, les chiens partagent une activité sans la pression du face-à-face. Commencez avec un seul chien calme et compatible. Marchez en parallèle à quelques mètres de distance, puis rapprochez-vous progressivement. La promenade en groupe crée des liens naturels entre chiens sans l'intensité du jeu libre. C'est souvent la meilleure façon de socialiser un chien réactif." },
    { id: 'BE_SOCIAL_010', title: 'Aider un chien craintif', body: "Si {dog_name} est craintif, votre rôle est d'être son pilier de sécurité. Ne le forcez jamais vers ce qui lui fait réaction d’évitement. Restez calme et confiant — votre sérénité le rassure. Récompensez chaque initiative courageuse, même infime. Un regard vers le stimulus ? Friandise. Un pas en avant ? Super friandise. Le travail est long mais chaque petite victoire construit la confiance de {dog_name}. Un éducateur canin spécialisé peut grandement accélérer le processus." },
    { id: 'BE_SOCIAL_011', title: 'Le chien trop joueur qui dérange', body: "Si {dog_name} est trop enthousiaste et bouscule les autres chiens, il faut lui apprendre les codes. Interrompez le jeu quand il devient trop intense — une pause de 10 secondes suffit. Récompensez les moments de calme entre les jeux. Choisissez des partenaires de jeu qui savent poser des limites — un chien adulte équilibré est le meilleur professeur. {dog_name} n'est pas méchant, il a juste besoin d'apprendre les bonnes manières canines." },
    { id: 'BE_SOCIAL_012', title: 'Habituer {dog_name} aux bruits urbains', body: "La ville est un concert permanent : klaxons, sirènes, travaux, musique de rue. Pour que {dog_name} soit à l'aise en ville, exposez-le progressivement. Commencez par des rues calmes, puis augmentez l'activité. Récompensez le calme face aux bruits. Si un bruit fait sursauter {dog_name}, ne surréagissez pas — restez détendu et continuez. Avec l'habitude, les bruits urbains deviennent un bruit de fond anodin." },
    { id: 'BE_SOCIAL_013', title: '{dog_name} dans la foule', body: "Marchés, brocantes, fêtes de village — les foules peuvent être stimulantes ou inquiétantes pour {dog_name}. Commencez en périphérie et observez ses réactions. S'il est détendu, avancez un peu. S'il se raidit, recule ou tire, éloignez-vous. Protégez-le des gens qui veulent le caresser sans demander. Tenez la laisse courte mais détendue. Certains chiens adorent les foules, d'autres non — respectez la personnalité de {dog_name}." },
    { id: 'BE_SOCIAL_014', title: 'Voyager avec {dog_name} : socialisation en mouvement', body: "Voyager expose {dog_name} à de nouveaux environnements, odeurs et sons — c'est une socialisation naturelle. Commencez par de courts trajets et augmentez progressivement. Emportez ses affaires familières (panier, jouet, couverture) pour le rassurer. Chaque nouveau lieu est une opportunité d'apprentissage : la gare, l'hôtel, le restaurant en terrasse. Les premiers voyages posent les bases d'un chien voyageur serein pour la vie." },
    { id: 'BE_SOCIAL_015', title: 'Chiens réactifs : comprendre et respecter', body: "Si vous croisez un chien qui aboie ou tire en laisse, ce n'est pas un mauvais chien ni un mauvais propriétaire. C'est un chien en apprentissage. Éloignez-vous calmement pour leur donner de l'espace. Ne laissez pas {dog_name} s'approcher d'un chien réactif — cela compliquerait leur travail. Un jour, c'est peut-être vous qui aurez besoin de cet espace. La communauté canine fonctionne mieux quand chacun respecte les besoins des autres." },
  ];
  return topics.map(t => ({
    id: t.id, category: 'behavior_education' as const, subcategory: 'socialization',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: null as number | null, ageMaxMonths: null as number | null,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: t.title, bodyFr: t.body, sourceType: 'behavior_tip' as const,
    neverSay: [...NS], suffix: null as string | null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 5, cooldownHours: 252, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: false, usesLocation: false, usesSeason: false,
  }));
}

function generateSeparationTemplates() {
  const topics = [
    { id: 'BE_SEPAR_001', title: 'Le détachement progressif', body: "Apprendre à {dog_name} à rester seul est un processus graduel. Commencez par de très courtes absences : quittez la pièce 10 secondes, revenez. Augmentez lentement la durée. Ne faites pas d'adieux émouvants — sortez naturellement. {dog_name} doit comprendre que vos départs sont normaux et que vous revenez toujours. Ce travail se fait sur des semaines, pas des jours. La clé est de ne jamais dépasser le seuil où {dog_name} devient inconfortable." },
    { id: 'BE_SEPAR_002', title: 'Les premiers moments seul', body: "Si {dog_name} n'a jamais été seul, ne le laissez pas huit heures d'un coup le premier jour. Commencez par cinq minutes, puis dix, puis trente. Laissez-lui un jouet d'occupation (Kong fourré, tapis de léchage). Partez et revenez sans fanfare. Si vous revenez et que tout va bien — pas de destruction, pas de vocalisation — vous pouvez augmenter la durée. Si {dog_name} a du mal, réduisez et progressez plus lentement." },
    { id: 'BE_SEPAR_003', title: 'Reconnaître le mal-être en l\'absence', body: "Comment savoir si {dog_name} vit mal vos absences ? Les signes : destructions ciblées (porte, fenêtre), vocalisation prolongée, malpropreté alors qu'il est propre habituellement, halètement et salivation excessive. Une caméra est un outil précieux pour observer ce qui se passe vraiment. Si {dog_name} se couche et dort après votre départ, tout va bien. S'il tourne en rond et vocalise pendant des heures, un travail spécifique est nécessaire avec un professionnel du comportement." },
    { id: 'BE_SEPAR_004', title: 'Le rituel de départ', body: "Créez un rituel de départ calme et prévisible. Cinq minutes avant de partir, donnez un jouet d'occupation à {dog_name}. Prenez vos affaires sans précipitation. Sortez sans le regarder ni lui parler. Pas de « sois sage » ni de câlin appuyé — cela augmente l'importance de votre départ. Le même rituel chaque jour permet à {dog_name} d'anticiper sereinement : jouet d'occupation = vous partez = vous revenez." },
    { id: 'BE_SEPAR_005', title: 'Le rituel de retour', body: "Quand vous rentrez, ignorez {dog_name} pendant les deux premières minutes. Posez vos affaires, enlevez votre manteau, puis saluez-le calmement. Si vous faites la fête à chaque retour, vous augmentez le contraste entre votre absence et votre présence — ce qui rend l'absence plus difficile. Votre retour doit être un non-événement. {dog_name} apprendra que vos allers-retours sont une routine banale, pas un drame." },
    { id: 'BE_SEPAR_006', title: 'Enrichissement pendant l\'absence', body: "Avant de laisser {dog_name} seul, préparez son environnement. Un Kong fourré de pâtée congelée peut l'occuper 30 minutes. Un tapis de fouille avec des croquettes cachées stimule son odorat. Laissez la radio ou une musique calme en fond sonore. Variez les jouets d'occupation pour maintenir l'intérêt. L'objectif : que {dog_name} associe votre départ à quelque chose de positif et d'occupant, pas à un vide." },
    { id: 'BE_SEPAR_007', title: 'Combien de temps {dog_name} peut-il rester seul ?', body: "La durée maximale dépend de l'âge, de la race et de l'individu. Un chiot ne devrait pas rester seul plus de 2-3 heures. Un adulte bien habitué peut gérer 4-6 heures, avec une sortie pipi avant et après. Au-delà de 6-8 heures, c'est long pour n'importe quel chien. Si vos journées sont longues, envisagez un dog-sitter, une garderie ou un promeneur qui passe en milieu de journée. {dog_name} mérite de ne pas attendre trop longtemps." },
    { id: 'BE_SEPAR_008', title: '{dog_name} pleure quand vous partez', body: "Si {dog_name} vocalise à votre départ, ne revenez pas immédiatement — cela renforcerait le comportement. Mais n'ignorez pas non plus un chien en réelle détresse. La nuance est importante. Un gémissement court qui s'arrête après quelques minutes est normal. Des vocalises intenses qui durent des heures sont un signe de mal-être profond. Utilisez une caméra pour évaluer la situation réelle et adaptez votre approche en conséquence." },
    { id: 'BE_SEPAR_009', title: 'Ne pas en faire un événement', body: "Votre énergie influence directement celle de {dog_name}. Si vous êtes tendu et en retrait en partant, il le présente. Si vous êtes culpabilisé et surexcité en revenant, il associe ces moments à de l'intensité émotionnelle. Partez comme si vous alliez juste vérifier la boîte aux lettres. Revenez comme si vous étiez parti cinq minutes. La banalisation de vos départs et retours est le meilleur cadeau que vous puissiez faire à {dog_name}." },
    { id: 'BE_SEPAR_010', title: '{dog_name} détruit en votre absence', body: "La destruction en l'absence est un signal, pas un caprice. Soit {dog_name} manque d’occupation (destructions variées, jouets, coussins), soit il est en détresse (destructions ciblées sur les sorties — porte, fenêtre, plinthe). Dans le premier cas, augmentez l'enrichissement et l'exercice avant votre départ. Dans le second, le travail est plus profond et nécessite souvent l'aide d'un éducateur comportementaliste. Ne punissez jamais au retour — {dog_name} ne peut pas faire le lien." },
    { id: 'BE_SEPAR_011', title: 'Utiliser une caméra pour observer {dog_name}', body: "Une caméra connectée est un outil précieux pour comprendre le comportement de {dog_name} en votre absence. Vous saurez s'il dort paisiblement après votre départ ou s'il tourne en rond pendant des heures. Certaines caméras permettent de lui parler — à utiliser avec parcimonie, car votre voix sans votre présence peut parfois l'agiter plus. L'observation objective vous permet d'ajuster votre approche et de mesurer les progrès." },
    { id: 'BE_SEPAR_012', title: 'Habituer progressivement à la solitude', body: "L'habituation à la solitude est un entraînement, pas un événement. Pratiquez des mini-séparations quotidiennes. Fermez la porte de la salle de bain quand vous y allez. Allez chercher le courrier. Sortez la poubelle. Chaque micro-absence sans drame construit la confiance de {dog_name}. Augmentez la durée très graduellement. Si à un moment {dog_name} montre des signes d'inconfort, revenez en arrière et reprenez plus lentement. La patience paie toujours." },
    { id: 'BE_SEPAR_013', title: '{dog_name} aboie quand il est seul', body: "Si les voisins vous signalent que {dog_name} aboie en votre absence, c'est un signal à prendre au sérieux. Déterminez d'abord la cause : ennui, bruits extérieurs ou mal-être. Un chien qui aboie par ennui bénéficiera d'enrichissement et d'exercice accru. Un chien qui réagit aux bruits peut être aidé par un fond sonore (radio, musique). Un chien en réelle détresse nécessite un travail de fond sur la séparation. Ne punissez jamais l'aboiement au retour." },
    { id: 'BE_SEPAR_014', title: 'Retour au bureau après le télétravail', body: "Après des mois de présence constante, {dog_name} s'est habitué à vous avoir à la maison. Le retour au bureau peut être un choc. Préparez-le en avance : commencez à vous absenter régulièrement, même pour de courts moments. Réintroduisez progressivement la routine « bureau ». Prenez vos clés, mettez votre manteau et sortez 15 minutes. Augmentez la durée. Le jour du retour au bureau, {dog_name} sera préparé. Si possible, envisagez un retour progressif (quelques jours par semaine)." },
    { id: 'BE_SEPAR_015', title: 'Le chiot et la solitude', body: "Un chiot n'a jamais connu la solitude avant d'arriver chez vous. Tout est nouveau et la séparation peut être effrayante. Ne laissez pas un très jeune chiot seul des heures d'emblée. Commencez par de très courtes absences dans une autre pièce. Laissez un vêtement qui porte votre odeur dans son panier. Proposez un Kong fourré au départ. Augmentez la durée très progressivement. Un chiot qui apprend tôt que la solitude est supportable sera un adulte serein." },
  ];
  return topics.map(t => ({
    id: t.id, category: 'behavior_education' as const, subcategory: 'separation',
    breedFilter: [] as string[], sizeFilter: [] as string[], ageMinMonths: null as number | null, ageMaxMonths: null as number | null,
    seasonFilter: [] as string[], monthFilter: [] as number[], regionFilter: ['all'],
    titleFr: t.title, bodyFr: t.body, sourceType: 'behavior_tip' as const,
    neverSay: [...NS], suffix: null as string | null, requiresVetDisclaimer: false,
    channel: 'home_insight' as const, priority: 6, cooldownHours: 252, maxPerMonth: 2,
    usesDogName: true, usesBreedName: true, usesAge: false, usesLocation: false, usesSeason: false,
  }));
}
