/**
 * EMOPET Freemium Content Templates - Health Seasonal
 * 60 templates: 15 per season (spring, summer, autumn, winter)
 * All content in French, original, warm tone.
 */

export interface HealthSeasonalTemplate {
  id: string;
  category: 'health_seasonal';
  subcategory: string;
  breedFilter: string[];
  sizeFilter: string[];
  ageMinMonths: number | null;
  ageMaxMonths: number | null;
  seasonFilter: string[];
  monthFilter: number[];
  regionFilter: string[];
  titleFr: string;
  bodyFr: string;
  sourceType: 'seasonal_alert';
  neverSay: string[];
  suffix: string | null;
  requiresVetDisclaimer: boolean;
  channel: 'home_insight';
  priority: number;
  cooldownHours: number;
  maxPerMonth: number;
  usesDogName: boolean;
  usesBreedName: boolean;
  usesAge: boolean;
  usesLocation: boolean;
  usesSeason: boolean;
}

export const HEALTH_SEASONAL_TEMPLATES: HealthSeasonalTemplate[] = [
  // ═══════════════════════════════════════════════════════════
  // SPRING (15 templates) — months 3, 4, 5
  // ═══════════════════════════════════════════════════════════
  {
    id: 'HS_SPRING_TICKS_001',
    category: 'health_seasonal',
    subcategory: 'parasites',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Les tiques sont de retour au printemps`,
    bodyFr:
      "Avec le retour des beaux jours, les tiques reprennent leur activite dans les herbes hautes et les sous-bois. Apres chaque promenade en nature, prenez le temps d'inspecter le pelage de {dog_name}, en insistant sur les zones chaudes : derriere les oreilles, entre les doigts, autour du cou et sous les pattes avant. Si vous trouvez une tique, retirez-la delicatement avec un tire-tique en tournant sans tirer. Certains chiens sont plus exposes que d'autres selon leur mode de vie et les regions ou ils se promenent. Un geste quotidien d'inspection peut faire une vraie difference pour le bien-etre de {dog_name}. N'hesitez pas a en parler a votre veterinaire pour choisir la protection la plus adaptee.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'symptome', 'traitement', 'condition clinique de Lyme', 'pathologie', 'soigner'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_CATERPILLARS_002',
    category: 'health_seasonal',
    subcategory: 'parasites',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Attention aux chenilles processionnaires`,
    bodyFr:
      "Au printemps, les chenilles processionnaires descendent des pins en longues files. Leurs poils urticants peuvent etre tres irritants pour {dog_name}, surtout au niveau de la truffe, de la langue et des coussinets. Si votre compagnon renifle ou leche le sol pres de pins, restez vigilant. En cas de contact suspect, il est possible que {dog_name} bave excessivement ou se frotte le museau. Ne tentez pas de rincer la bouche vous-meme sans precaution, car les poils urticants peuvent se repandre. Evitez les zones ou vous apercevez des nids soyeux dans les pins, et privilegiez des chemins degages. Certains chiens curieux sont plus a point de vigilance que d'autres. Si vous avez un doute apres une promenade, contactez rapidement votre veterinaire.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'pathologie', 'soigner', 'guerir', 'necrose'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_POLLEN_003',
    category: 'health_seasonal',
    subcategory: 'weather',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Pollens de printemps et confort de votre chien`,
    bodyFr:
      "Le printemps apporte son lot de pollens, et certains chiens peuvent y etre sensibles. {dog_name} se gratte plus que d'habitude, se leche les pattes apres les promenades ou a le nez qui coule ? Il est possible que les pollens en soient la cause. Pour limiter l'inconfort, vous pouvez rincer les pattes de {dog_name} a l'eau tiede apres chaque sortie et essuyer son pelage avec un linge humide. Aerer la maison tot le matin plutot qu'en pleine journee peut aussi aider. Brosser regulierement le pelage permet de retirer les particules accumulees. Si les inconforts persistent ou s'intensifient, votre veterinaire pourra vous accompagner pour trouver des solutions adaptees au quotidien de {dog_name}.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'allergie', 'pathologie', 'soigner', 'guerir', 'antihistaminique'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_SHEDDING_004',
    category: 'health_seasonal',
    subcategory: 'grooming',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `La mue de printemps de {dog_name}`,
    bodyFr:
      "Avec l'arrivee du printemps, {dog_name} perd son sous-poil d'hiver pour se preparer aux temperatures plus douces. C'est tout a fait normal ! Un brossage regulier, idealement tous les deux jours, aide a retirer les poils morts et favorise une bonne aeration de la peau. Pour les races a poil dense comme {breed_name}, une brosse adaptee au type de pelage fait toute la difference. Ce rituel de brossage est aussi un moment privilege avec {dog_name} : beaucoup de chiens finissent par adorer cette routine. Pensez a verifier qu'il n'y a pas de noeuds, surtout derriere les oreilles et sous les pattes. Une alimentation equilibree contribue aussi a un pelage sain et brillant.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'dermatite'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_LONG_WALKS_005',
    category: 'health_seasonal',
    subcategory: 'activity',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Reprendre les longues promenades en douceur`,
    bodyFr:
      "Le printemps donne envie de grandes balades, mais apres un hiver plus calme, il est preferable de reprendre progressivement. {dog_name} a peut-etre perdu un peu de condition physique pendant les mois froids, et des sorties trop intenses d'un coup peuvent fatiguer ses articulations et ses muscles. Augmentez la duree des promenades de 10 a 15 minutes par semaine. Observez comment {dog_name} se comporte apres les sorties : s'il semble fatigue ou ralentit pendant la balade, c'est un signe qu'il vaut mieux y aller doucement. Les chiots et les chiens seniors meritent une attention particuliere. Ce retour progressif a l'activite permettra a {dog_name} de profiter pleinement des beaux jours sans inconfort.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'arthrose'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_TOXIC_PLANTS_006',
    category: 'health_seasonal',
    subcategory: 'toxic_ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Plantes de jardin a surveiller au printemps`,
    bodyFr:
      "Le printemps fait fleurir nos jardins, mais certaines plantes courantes peuvent etre irritantes pour {dog_name} en cas d'ingestion. Le muguet, les tulipes, les jonquilles et le laurier-rose font partie des vegetaux a surveiller. Si {dog_name} aime explorer le jardin ou macher des feuilles, gardez un oeil sur ce qu'il porte a sa gueule. Amenager un espace de jeu eloigne des massifs les plus sensibles peut etre une bonne idee. En cas de doute apres une ingestion, notez quelle plante est concernee et contactez votre veterinaire. Certains chiens, surtout les chiots curieux, sont plus enclins a gouter tout ce qu'ils trouvent. Un amenagement reflechi du jardin au printemps protege {dog_name} tout au long de la saison.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'empoisonnement'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_STINGING_INSECTS_007',
    category: 'health_seasonal',
    subcategory: 'parasites',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Insectes piqueurs : proteger {dog_name} au printemps`,
    bodyFr:
      "Avec le retour du beau temps, moustiques, puces et autres insectes piqueurs redeviennent actifs. {dog_name} peut etre une cible facile, surtout dans les zones humides ou boisees. Les puces, en particulier, se multiplient rapidement au printemps. Un grattage frequent ou des petits points rouges sur le ventre peuvent indiquer leur presence. Pensez a verifier regulierement le pelage de {dog_name} avec un peigne fin, surtout apres les balades en nature. Des solutions preventives existent pour limiter les desagrements lies aux insectes. Votre veterinaire peut vous orienter vers la protection la mieux adaptee au mode de vie de {dog_name} et a votre region.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'dermatite'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_HYDRATION_008',
    category: 'health_seasonal',
    subcategory: 'hydration',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Hydratation de {dog_name} au fil du printemps`,
    bodyFr:
      "Les temperatures remontent au printemps, et {dog_name} a besoin de plus d'eau qu'en hiver, surtout s'il est plus actif lors des promenades. Assurez-vous que sa gamelle d'eau est toujours remplie d'eau fraiche et changee au moins deux fois par jour. Lors des sorties plus longues, emportez une gourde pliable pour lui offrir a boire regulierement. Certains chiens ne boivent pas assez spontanement : ajouter un peu d'eau tiede a ses croquettes peut encourager une meilleure hydratation. Observez la couleur de ses gencives et la souplesse de sa peau : ce sont de bons indicateurs de son niveau d'hydratation. Un chien bien hydrate est un chien plein d'energie pour profiter du printemps !",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'deshydratation'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_INCREASED_ACTIVITY_009',
    category: 'health_seasonal',
    subcategory: 'activity',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Le regain d\'energie de {dog_name} au printemps`,
    bodyFr:
      "Le printemps reveille l'energie de {dog_name} ! Les jours rallongent, les odeurs se multiplient, et votre compagnon a envie de bouger davantage. C'est le moment ideal pour diversifier les activites : nouvelles promenades, jeux de pistage, exploration de chemins differents. Adaptez le rythme a {dog_name} en observant ses signaux. Un chien qui halte beaucoup ou qui se couche pendant la balade a besoin de souffler. Pour les races energiques comme {breed_name}, cette periode est parfaite pour introduire des jeux plus stimulants. Variez les terrains pour solliciter differents muscles et maintenir la curiosite de {dog_name}. Ce regain d'activite est aussi excellent pour son equilibre emotionnel.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_HEAT_CYCLE_010',
    category: 'health_seasonal',
    subcategory: 'reproduction',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: 6,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Printemps et chaleurs des chiennes non sterilisees`,
    bodyFr:
      "Le printemps correspond souvent a une periode de chaleurs chez les chiennes non sterilisees. Si {dog_name} est concernee, vous remarquerez peut-etre des changements de comportement : agitation, attention accrue des males lors des promenades, pertes sanguines. Pendant cette periode, il est preferable de garder {dog_name} en laisse lors des sorties et d'eviter les zones tres frequentees par d'autres chiens. Certains chiens males peuvent se montrer insistants, ce qui peut generer du forte sollicitation. Prevoyez des promenades dans des endroits calmes et a des horaires plus tranquilles. Des culottes hygieniques pour chienne existent et peuvent aider a gerer les pertes a la maison. Si vous avez un doute sur la duree ou l'intensite des chaleurs, votre veterinaire est la meilleure personne a consulter.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'pyometre'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_FOXTAILS_EARLY_011',
    category: 'health_seasonal',
    subcategory: 'hazards',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [4, 5],
    regionFilter: ['all'],
    titleFr: `Debut de saison des epillets : vigilance pour {dog_name}`,
    bodyFr:
      "Des la fin du printemps, les epillets commencent a secher dans les herbes hautes et en bordure de chemin. Ces petites graines en forme de fleche peuvent se glisser dans les oreilles, entre les doigts ou dans les narines de {dog_name}. Apres chaque balade en zone herbeuse, inspectez attentivement les pattes, les oreilles et le pelage. Si {dog_name} secoue soudainement la tete de maniere repetee, se leche frenetiquement une patte ou eternue sans s'arreter, il est possible qu'un epillet se soit loge quelque part. N'essayez pas de le retirer vous-meme s'il n'est pas visible. Les chiens a poils longs ou frises peuvent etre plus concernes. Privilegiez les chemins degages quand les herbes sont hautes.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'abces', 'chirurgie'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_SUNBURN_LIGHT_SKIN_012',
    category: 'health_seasonal',
    subcategory: 'sun_protection',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [4, 5],
    regionFilter: ['all'],
    titleFr: `Soleil de printemps et chiens a peau claire`,
    bodyFr:
      "On n'y pense pas toujours, mais certains chiens a peau claire ou a pelage fin peuvent etre sensibles au soleil printanier, surtout sur la truffe, les oreilles et le ventre. Si {dog_name} a le poil blanc ou une peau rose visible, soyez attentif lors des journees ensoleillees. Privilegiez les promenades a l'ombre aux heures les plus lumineuses et evitez les expositions prolongees. Des cremes solaires specifiques pour chiens existent et peuvent etre appliquees sur les zones les plus exposees. Les races comme le Dalmatien, le Bull Terrier blanc ou le Dogo Argentino peuvent etre plus concernees. Un parasol ou un coin ombrage dans le jardin permet a {dog_name} de profiter du plein air en toute tranquillite.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'carcinome', 'melanome'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_SWIMMING_EARLY_013',
    category: 'health_seasonal',
    subcategory: 'activity',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [4, 5],
    regionFilter: ['all'],
    titleFr: `Debut de saison baignade pour {dog_name}`,
    bodyFr:
      "Les premieres belles journees donnent envie de baignade ! Si {dog_name} aime l'eau, la reprise doit se faire en douceur. L'eau peut encore etre froide au printemps, et un chien qui n'a pas nage depuis l'automne peut perdre ses reperes. Commencez par des pataugeages en eau peu profonde et laissez {dog_name} decider de son rythme. Ne forcez jamais un chien a entrer dans l'eau. Verifiez que le lieu de baignade est sur : pas de courant fort, pas de debris, et une sortie facile. Apres chaque bain, sechez bien les oreilles de {dog_name} pour eviter les desagrements lies a l'humidite. Certains chiens adorent nager et d'autres preferent rester au sec : respectez la nature de {dog_name}.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'otite'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_PARK_SOCIALIZATION_014',
    category: 'health_seasonal',
    subcategory: 'behavior',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Socialisation au parc : le printemps ideal`,
    bodyFr:
      "Le printemps ramene du monde dans les parcs, et c'est une belle occasion pour {dog_name} de retrouver ou developper ses competences sociales. Apres l'hiver, certains chiens peuvent etre un peu plus reactifs face a la presence d'autres congeneres. Allez-y progressivement : commencez par des moments calmes avec peu de chiens presents, puis augmentez la stimulation. Observez le langage corporel de {dog_name} : une queue detendue, des mouvements souples et un corps relache sont de bons signes. Si {dog_name} semble tendu ou grogne, accordez-lui de l'espace et ne le forcez pas. Les interactions positives au printemps posent les bases d'un ete serein en termes de sociabilite. Chaque chien a son propre rythme.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'agressivite'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SPRING_MUD_CLEANING_015',
    category: 'health_seasonal',
    subcategory: 'grooming',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [3, 4, 5],
    regionFilter: ['all'],
    titleFr: `Nettoyage apres les promenades boueuses`,
    bodyFr:
      "Le printemps rime souvent avec pluie et boue, et {dog_name} peut revenir bien sale de ses escapades ! Un bon nettoyage apres les promenades boueuses protege son pelage et votre interieur. Rincez les pattes a l'eau tiede et sechez-les soigneusement, surtout entre les coussinets ou la boue peut s'accumuler. Pour le corps, un coup de serviette ou un shampooing sec adapte aux chiens fait l'affaire entre deux vrais bains. Evitez de laver {dog_name} trop souvent avec du shampooing, car cela peut assecher sa peau. Une serviette microfibre pres de la porte d'entree devient vite indispensable a cette saison ! Transformez ce moment en routine positive avec des friandises, pour que {dog_name} associe le nettoyage a quelque chose d'agreable.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'dermatite'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },

  // ═══════════════════════════════════════════════════════════
  // SUMMER (15 templates) — months 6, 7, 8
  // ═══════════════════════════════════════════════════════════
  {
    id: 'HS_SUMMER_HEATSTROKE_001',
    category: 'health_seasonal',
    subcategory: 'heat',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Prevenir le coup de chaleur chez {dog_name}`,
    bodyFr:
      "En ete, le coup de chaleur est un point de vigilance reel pour tous les chiens. {dog_name} ne transpire pas comme nous : il se refroidit principalement en haletant. Lors des journees chaudes, evitez les efforts intenses entre 11h et 16h. Proposez toujours de l'eau fraiche et un endroit ombre. Ne laissez jamais {dog_name} dans une voiture, meme quelques minutes, meme avec une vitre entrouverte. Les signes a surveiller incluent un halètement excessif, une demarche chancelante ou un abattement soudain. Certains chiens sont plus sensibles que d'autres a la chaleur, notamment les seniors et les chiens en surpoids. En cas de doute sur l'etat de {dog_name}, contactez immediatement votre veterinaire. La prevention reste le meilleur reflexe.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'hyperthermie'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_HEATSTROKE_BRACHY_002',
    category: 'health_seasonal',
    subcategory: 'heat',
    breedFilter: ['bouledogue_francais', 'carlin', 'bulldog_anglais', 'shih_tzu', 'cavalier_king_charles', 'boxer', 'boston_terrier', 'pekinois'],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Chaleur et races a museau court : vigilance accrue`,
    bodyFr:
      "Les chiens au museau court comme {breed_name} sont particulierement sensibles a la chaleur. Leur anatomie rend la respiration et le refroidissement plus difficiles. En ete, {dog_name} peut se retrouver en difficulte meme avec des temperatures qui semblent moderees. Limitez les activites physiques aux heures les plus fraiches, tot le matin ou en fin de soiree. Proposez des tapis rafraichissants, de l'eau fraiche en permanence et un acces constant a l'ombre. Si {dog_name} commence a haleter bruyamment ou semble avoir du mal a reprendre son souffle, installez-le dans un endroit frais et humidifiez-lui le corps avec de l'eau tiede, pas glacee. Les races a museau court meritent une attention toute particuliere des que le thermometre depasse 25 degres.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'brachycephale', 'stenose'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_COOL_HOURS_003',
    category: 'health_seasonal',
    subcategory: 'heat',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Promenades aux heures fraiches pour {dog_name}`,
    bodyFr:
      "En plein ete, les heures les plus agreables pour promener {dog_name} sont tot le matin, avant 9h, et en soiree, apres 19h. La chaleur de l'apres-midi peut etre eprouvante, meme pour les chiens en bonne forme. Pensez a adapter la duree et l'intensite des sorties : une promenade tranquille le long d'un chemin ombrage vaut mieux qu'une course en plein soleil. Si {dog_name} ralentit ou cherche l'ombre pendant la balade, c'est le moment de faire une pause. Emportez toujours de l'eau et une gamelle pliable. Les parcs avec des arbres et de l'herbe sont a privilegier par rapport aux zones betonnees. {dog_name} vous remerciera pour ces promenades matinales pleine de fraicheur !",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_HOT_PAVEMENT_004',
    category: 'health_seasonal',
    subcategory: 'heat',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Le test de la main sur le bitume`,
    bodyFr:
      "Avant de partir en promenade avec {dog_name}, faites le test de la main : posez le dos de votre main sur le sol pendant 5 secondes. Si c'est trop chaud pour vous, c'est trop chaud pour les coussinets de {dog_name}. Le bitume en plein soleil peut atteindre 60 degres et bruler les pattes de votre compagnon. Privilegiez les chemins en terre, l'herbe ou les zones ombragees. Si vous devez traverser une zone goudronnee, faites-le rapidement. Des bottines protectrices pour chien existent aussi pour les situations ou l'on ne peut pas eviter les surfaces chaudes. Apres la promenade, inspectez les coussinets de {dog_name} : des fissures ou une sensibilite au toucher peuvent indiquer un inconfort.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'brulure'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_FRESH_WATER_005',
    category: 'health_seasonal',
    subcategory: 'hydration',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Eau fraiche en permanence pour {dog_name}`,
    bodyFr:
      "En ete, {dog_name} a besoin de beaucoup plus d'eau que d'habitude. Un chien actif peut avoir besoin de 50 a 100 ml d'eau par kilo de poids corporel par jour en periode chaude. Disposez plusieurs gamelles d'eau fraiche dans la maison et le jardin, a l'ombre. Changez l'eau au moins deux fois par jour pour qu'elle reste propre et agreable. Lors des promenades, faites des pauses regulieres pour proposer a boire. Certains chiens adorent les glacons dans leur gamelle ou les jouets remplis d'eau congelee. Evitez de laisser {dog_name} boire dans les flaques ou les eaux stagnantes, qui peuvent contenir des elements desagreables. Un chien bien hydrate reste vif et profite pleinement de l'ete.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'deshydratation'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_SWIMMING_SAFETY_006',
    category: 'health_seasonal',
    subcategory: 'activity',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Baignade en securite pour {dog_name}`,
    bodyFr:
      "L'ete est la saison ideale pour la baignade, mais quelques precautions s'imposent pour {dog_name}. Tous les chiens ne savent pas nager naturellement, et certains coulent tres vite, notamment les races a poitrine large et pattes courtes. Restez toujours a proximite lorsque {dog_name} est dans l'eau. Evitez les courants forts, les berges abruptes et les plans d'eau que vous ne connaissez pas. Un gilet de sauvetage pour chien est un investissement rassurant pour les sorties aquatiques. Apres la baignade, rincez {dog_name} a l'eau douce pour retirer le chlore, le sel ou les impuretes. Sechez bien les oreilles pour eviter l'humidite prolongee. La baignade est un excellent exercice, doux pour les articulations et rafraichissant.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'noyade', 'otite'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_TOXIC_ALGAE_007',
    category: 'health_seasonal',
    subcategory: 'toxic_ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Algues toxiques en eau douce : prudence`,
    bodyFr:
      "En ete, certains plans d'eau douce peuvent developper des algues bleu-vert (cyanobacteries) qui sont tres dangereuses pour les chiens. Si l'eau d'un lac ou d'un etang a un aspect verdatre, une odeur forte ou des depots mousseux en surface, n'y laissez pas {dog_name} se baigner ni en boire. Ces algues peuvent provoquer de graves inconforts tres rapidement apres ingestion ou contact. Avant de vous rendre a un point de baignade, verifiez les informations locales sur la qualite de l'eau. En cas de doute, privilegiez les cours d'eau vive ou les zones de baignade surveillees. Si {dog_name} a ete en contact avec une eau suspecte, rincez-le immediatement et consultez votre veterinaire sans attendre.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'empoisonnement'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_FOXTAILS_PEAK_008',
    category: 'health_seasonal',
    subcategory: 'hazards',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Epillets en ete : le pic de la saison`,
    bodyFr:
      "L'ete est la periode ou les epillets sont les plus presents et les plus secs, donc les plus dangereux pour {dog_name}. Ces petites graines pointues se detachent facilement des herbes seches et peuvent penetrer dans les oreilles, les narines, entre les doigts ou sous la peau. Inspectez systematiquement {dog_name} apres chaque promenade en zone herbeuse. Passez vos doigts entre ses coussinets, verifiez l'interieur des oreilles et le pourtour des yeux. Si {dog_name} se met a eternuer violemment, a secouer la tete sans cesse ou a boiter soudainement, il est possible qu'un epillet en soit la cause. Un toilettage court sur les pattes et les oreilles peut limiter les points de vigilance pour les races a poils longs.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'abces', 'chirurgie'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_WASP_STING_009',
    category: 'health_seasonal',
    subcategory: 'hazards',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Piqures de guepes et abeilles en ete`,
    bodyFr:
      "En ete, {dog_name} point de vigilance davantage de croiser guepes et abeilles lors de ses explorations. Les chiens curieux qui essaient d'attraper les insectes avec la gueule sont particulierement exposes. Une piqure peut provoquer un gonflement local et de l'inconfort. Si {dog_name} se fait piquer, retirez le dard s'il est visible en grattant delicatement avec une carte rigide, sans appuyer. Appliquez un linge frais sur la zone. Surveillez attentivement {dog_name} dans les heures qui suivent : certains chiens peuvent reagir plus fortement que d'autres. Si le gonflement augmente rapidement, si {dog_name} a du mal a respirer ou semble abattu, contactez votre veterinaire immediatement. Eloignez les gamelles de nourriture qui attirent les insectes.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'anaphylaxie', 'choc'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_FIREWORKS_010',
    category: 'health_seasonal',
    subcategory: 'anxiety',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Feux d\'artifice : aider {dog_name} a rester calme`,
    bodyFr:
      "L'ete est la saison des feux d'artifice, et beaucoup de chiens les vivent difficilement. Si {dog_name} est sensible aux bruits forts, preparez-vous a l'avance. Creez un espace rassurant dans la maison : une piece calme, volets fermes, avec de la musique douce ou la television en fond sonore. Restez detendu et present aupres de {dog_name} sans le forcer a interagir. Proposez-lui un jouet a macher ou un kong fourre pour l'occuper. Evitez de sortir {dog_name} pendant les tirs et verifiez que son identification est a jour au cas ou il prendrait réaction d’évitement. Certains chiens se cachent : laissez-les trouver leur refuge sans les en deloger. Si l'anxiete de {dog_name} est intense, votre veterinaire peut proposer des solutions apaisantes.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'phobie', 'anxiolytique', 'sedatif'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_CAR_HEAT_011',
    category: 'health_seasonal',
    subcategory: 'heat',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Voiture et chaleur : ne jamais laisser {dog_name} seul`,
    bodyFr:
      "Chaque ete, des chiens sont victimes de la chaleur dans les voitures. Meme par 22 degres dehors, l'interieur d'un vehicule peut atteindre 40 degres en moins de 20 minutes. Une vitre entrouverte ne suffit pas a refroidir l'habitacle. Ne laissez jamais {dog_name} seul dans la voiture, meme pour une course rapide. Si vous voyagez avec {dog_name}, prevoyez de l'eau, la climatisation et des pauses regulieres a l'ombre. Lors des arrets, un adulte doit rester avec le chien ou emmenez {dog_name} avec vous. Si vous voyez un chien en detresse dans une voiture, contactez les autorites. La regle est simple : s'il fait trop chaud pour vous dans la voiture fermee, il fait trop chaud pour {dog_name}.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'hyperthermie'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_BEACH_HAZARDS_012',
    category: 'health_seasonal',
    subcategory: 'hazards',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['bretagne', 'normandie', 'pays_de_la_loire', 'nouvelle_aquitaine', 'occitanie', 'provence_alpes_cote_azur', 'corse'],
    titleFr: `Plage : coquillages et meduses, attention a {dog_name}`,
    bodyFr:
      "La plage est un terrain de jeu formidable pour {dog_name}, mais quelques points de vigilance meritent votre attention. Les coquillages brises peuvent couper les coussinets, et certains chiens aiment macher des debris marins qui peuvent etre irritants. Les meduses echouees, meme mortes, conservent leur pouvoir urticant : empechez {dog_name} de les renifler ou de les lecher. Surveillez aussi l'ingestion d'eau salee, qui peut provoquer des desagrements digestifs si {dog_name} en boit trop. Apportez toujours de l'eau douce pour qu'il puisse se desalterer. Apres la plage, rincez le pelage a l'eau douce pour retirer le sel et le sable. Verifiez les espaces entre les coussinets et les oreilles.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_DOG_SUNSCREEN_013',
    category: 'health_seasonal',
    subcategory: 'sun_protection',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Creme solaire pour chien : quand l\'utiliser ?`,
    bodyFr:
      "Tous les chiens n'ont pas besoin de creme solaire, mais certains y gagneraient en confort. Si {dog_name} a la peau claire, un pelage fin ou des zones depourvues de poils, une protection solaire adaptee aux chiens peut etre utile sur la truffe, le bout des oreilles et le ventre. Attention : n'utilisez jamais de creme solaire pour humains, car certains composants comme le zinc peuvent etre nocifs en cas de lechage. Choisissez un produit specifiquement formule pour les chiens, sans parfum et sans zinc. Appliquez une fine couche 20 minutes avant l'exposition et renouvelez apres la baignade. En cas de doute sur les besoins de {dog_name}, votre veterinaire pourra vous guider. L'ombre reste bien sur la meilleure protection.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'carcinome', 'melanome'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_DRY_GRASS_014',
    category: 'health_seasonal',
    subcategory: 'hazards',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [7, 8],
    regionFilter: ['all'],
    titleFr: `Herbe seche en ete : points de vigilance pour les pattes`,
    bodyFr:
      "En plein ete, l'herbe seche et les chaumes de champs fauches peuvent etre coupants pour les coussinets de {dog_name}. Les tiges rigides et pointues agissent comme de petites lames, surtout si {dog_name} court a pleine vitesse. Apres les promenades dans les champs ou les prairies, verifiez les coussinets et les espaces entre les doigts. Des micro-coupures peuvent passer inapercues mais causer de l'inconfort. Si {dog_name} boite legerement ou se leche une patte avec insistance apres une balade, inspectez soigneusement la zone. Pour les terrains tres secs, privilegiez les chemins de terre battue ou les sous-bois plus frais. Hydrater les coussinets avec un baume adapte aux chiens peut aussi aider a maintenir leur souplesse.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'infection'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_SUMMER_HYDRATION_FOOD_015',
    category: 'health_seasonal',
    subcategory: 'nutrition',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Alimentation et hydratation estivale de {dog_name}`,
    bodyFr:
      "En ete, certains chiens mangent un peu moins, et c'est normal : la chaleur reduit naturellement l'appetit. Si {dog_name} mange moins mais reste actif et joyeux, pas d'inquietude. Vous pouvez adapter l'alimentation en proposant les repas aux heures fraiches, le matin ou en soiree. Ajouter un peu d'eau tiede aux croquettes peut les rendre plus appetissantes et contribuer a l'hydratation. Les friandises glacees maison, comme du bouillon de poulet sans sel congele dans un moule, font un excellent encas rafraichissant. Evitez les restes de table, surtout les barbecues : os cuits, epices et graisses ne conviennent pas a {dog_name}. Si la perte d'appetit persiste ou si {dog_name} semble apathique, parlez-en a votre veterinaire.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'anorexie'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },

  // ═══════════════════════════════════════════════════════════
  // AUTUMN (15 templates) — months 9, 10, 11
  // ═══════════════════════════════════════════════════════════
  {
    id: 'HS_AUTUMN_RAIN_MUD_COAT_001',
    category: 'health_seasonal',
    subcategory: 'grooming',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10, 11],
    regionFilter: ['all'],
    titleFr: `Pluie et boue d\'automne : secher le pelage de {dog_name}`,
    bodyFr:
      "L'automne apporte son lot de pluie et de boue, et {dog_name} revient souvent trempe de ses promenades. Un sechage correct est important pour son confort et la sante de son pelage. En rentrant, frottez-le energiquement avec une serviette absorbante, en insistant sur le ventre, les pattes et derriere les oreilles. Les chiens a sous-poil dense peuvent garder l'humidite longtemps s'ils ne sont pas bien seches, ce qui peut creer de l'inconfort. Un sechoir a air tiede, utilise a bonne distance, peut aider pour les races a poil long. Pensez aussi a nettoyer les espaces entre les coussinets ou la boue s'accumule. Ce rituel de sechage devient vite un moment agreable si vous l'accompagnez de caresses et de friandises.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'dermatite', 'mycose'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_TOXIC_MUSHROOMS_002',
    category: 'health_seasonal',
    subcategory: 'toxic_ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10, 11],
    regionFilter: ['all'],
    titleFr: `Champignons d\'automne : vigilance en promenade`,
    bodyFr:
      "L'automne fait pousser de nombreux champignons dans les forets et les jardins, et certains peuvent etre tres irritants pour {dog_name} en cas d'ingestion. Les chiens curieux qui reniflent et goutent tout ce qu'ils trouvent au sol sont particulierement concernes. Si {dog_name} a tendance a macher des choses en promenade, gardez-le en laisse dans les zones boisees ou les champignons sont abondants. En cas d'ingestion suspecte, essayez de photographier le champignon et contactez votre veterinaire rapidement. Ne tentez pas de faire vomir {dog_name} vous-meme sans avis professionnel. Apprendre le rappel a {dog_name} ou utiliser la commande 'laisse' peut aider a prevenir les ingestions indesirables.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'empoisonnement'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_LIGHT_MOOD_003',
    category: 'health_seasonal',
    subcategory: 'behavior',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [10, 11],
    regionFilter: ['all'],
    titleFr: `Baisse de luminosite et humeur de {dog_name}`,
    bodyFr:
      "Avec le passage a l'heure d'hiver et la baisse de luminosite, certains chiens peuvent sembler un peu moins enthousiastes ou plus calmes que d'habitude. Comme nous, {dog_name} est sensible aux changements de lumiere. Pour maintenir son moral, privilegiez les promenades en milieu de journee quand la lumiere est maximale. Les jeux d'interieur, les exercices de flair et les seances de jeu courtes mais regulieres aident a garder {dog_name} stimule. Un enrichissement mental quotidien, comme des puzzles alimentaires ou des jeux de recherche, peut compenser le manque d'activite exterieure. Si {dog_name} semble inhabituellement apathique pendant plusieurs jours, il est possible que d'autres facteurs entrent en jeu. N'hesitez pas a en parler a votre veterinaire.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'depression'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_SHEDDING_004',
    category: 'health_seasonal',
    subcategory: 'grooming',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10, 11],
    regionFilter: ['all'],
    titleFr: `La mue d\'automne : le pelage de {dog_name} se prepare`,
    bodyFr:
      "En automne, {dog_name} renouvelle son pelage pour se preparer au froid hivernal. Le sous-poil d'ete cede sa place a un pelage plus dense et isolant. Cette mue peut durer plusieurs semaines et generer beaucoup de poils dans la maison. Un brossage quotidien ou tous les deux jours aide a retirer les poils morts et favorise la pousse du nouveau pelage. Utilisez une brosse adaptee au type de poil de {breed_name} : une carde pour les poils longs, une brosse en caoutchouc pour les poils courts. Ce moment de brossage renforce le lien entre vous et {dog_name}. Une alimentation riche en acides gras, comme des huiles de poisson adaptees aux chiens, peut contribuer a un pelage sain et brillant pour affronter l'hiver.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'alopecie', 'dermatite'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_PARASITE_REMINDER_005',
    category: 'health_seasonal',
    subcategory: 'parasites',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10],
    regionFilter: ['all'],
    titleFr: `Rappel antiparasitaire d\'automne pour {dog_name}`,
    bodyFr:
      "L'automne n'est pas une raison pour relacher la prevention antiparasitaire de {dog_name}. Les puces sont toujours actives, surtout dans les maisons chauffees, et les tiques connaissent un second pic d'activite en automne. Verifiez que la protection de {dog_name} est a jour et continuez les inspections apres les promenades en nature. Les feuilles mortes et les sous-bois humides sont des environnements ou les parasites prosperent. N'oubliez pas non plus la vermifugation reguliere, surtout si {dog_name} a acces a un jardin ou mange de l'herbe. Votre veterinaire peut vous aider a etablir un calendrier de prevention adapte au mode de vie de {dog_name} et a votre region. La regularite est la cle d'une protection efficace.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'infestation'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_CHESTNUTS_ACORNS_006',
    category: 'health_seasonal',
    subcategory: 'toxic_ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10, 11],
    regionFilter: ['all'],
    titleFr: `Marrons et glands : attention a {dog_name}`,
    bodyFr:
      "Les marrons et les glands jonchent le sol en automne, et beaucoup de chiens trouvent amusant de les macher ou de les avaler. Pourtant, ces fruits d'automne peuvent provoquer des desagrements digestifs chez {dog_name}. Les glands contiennent des tanins irritants, et les marrons d'Inde (a ne pas confondre avec les chataignes comestibles) sont particulierement indigestes. Si {dog_name} aime jouer avec tout ce qu'il trouve au sol, soyez vigilant dans les parcs et les allees bordees de chenes ou de marronniers. Proposez-lui plutot un jouet ou une balle pour detourner son attention. Si {dog_name} en a mange une grande quantite, surveillez son appetit et son confort digestif. En cas de doute, votre veterinaire est le meilleur interlocuteur.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'empoisonnement', 'occlusion'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_HUNTING_SEASON_007',
    category: 'health_seasonal',
    subcategory: 'safety',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10, 11],
    regionFilter: ['all'],
    titleFr: `Saison de chasse : securite de {dog_name} en promenade`,
    bodyFr:
      "L'automne marque l'ouverture de la chasse dans de nombreuses regions. Pour la securite de {dog_name}, quelques precautions sont essentielles. Equipez {dog_name} d'un gilet ou bandana fluorescent bien visible, surtout pour les promenades en foret et en campagne. Renseignez-vous sur les jours de chasse dans votre commune : des panneaux ou des informations en mairie peuvent vous aider. Evitez les zones boisees les jours de battue et privilegiez les chemins balisees. Gardez {dog_name} en laisse dans les zones ou la chasse est active. Portez vous-meme des vetements de couleur vive. Si vous entendez des tirs, eloignez-vous calmement. Certaines communes interdisent la chasse le mercredi et le dimanche : ce sont des jours plus surs pour les grandes balades en foret.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_EARLY_DARK_008',
    category: 'health_seasonal',
    subcategory: 'safety',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [10, 11],
    regionFilter: ['all'],
    titleFr: `Nuit plus tot : visibilite en promenade`,
    bodyFr:
      "En automne, la nuit tombe plus tot et les promenades du soir se font souvent dans l'obscurite. Pour la securite de {dog_name} et la votre, pensez a equiper votre compagnon d'accessoires reflechissants ou lumineux : collier LED, pendentif clignotant, laisse reflechissante. Portez vous-meme des vetements clairs ou un brassard reflechissant. Privilegiez les itineraires eclaires et evitez les zones ou la visibilite est mauvaise. Si {dog_name} est detache dans un espace autorise, un collier lumineux vous permettra de le reperer facilement. Ces accessoires sont peu couteux et peuvent eviter bien des desagrements. La prudence est de mise aussi avec les velos et les trottinettes qui circulent sans eclairage suffisant.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_DECREASED_ACTIVITY_009',
    category: 'health_seasonal',
    subcategory: 'activity',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [10, 11],
    regionFilter: ['all'],
    titleFr: `Activite naturellement en baisse a l\'automne`,
    bodyFr:
      "Avec le raccourcissement des jours et la baisse des temperatures, il est normal que {dog_name} soit un peu moins actif qu'en ete. Ce ralentissement naturel fait partie du cycle saisonnier. Cependant, il est important de maintenir un minimum d'activite physique et mentale pour le bien-etre de {dog_name}. Adaptez les promenades en duree et en intensite, mais ne les supprimez pas. Les jeux d'interieur, les exercices de flair avec des croquettes cachees et les courtes seances d'education positive sont d'excellents complements. Certaines races sont naturellement plus sensibles aux changements de saison. Si {dog_name} semble anormalement fatigue ou dort beaucoup plus que d'habitude, un avis veterinaire peut etre utile.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'depression', 'hypothyroidie'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_NUTRITION_010',
    category: 'health_seasonal',
    subcategory: 'nutrition',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10, 11],
    regionFilter: ['all'],
    titleFr: `Alimentation d\'automne pour {dog_name}`,
    bodyFr:
      "L'automne est une periode de transition pour l'alimentation de {dog_name}. Si votre compagnon passe plus de temps dehors par temps frais, il est possible que ses besoins energetiques augmentent legerement. Observez son poids et son appetit : certains chiens mangent davantage a l'automne, ce qui est naturel. Pour les chiens qui vivent principalement a l'interieur, les besoins restent globalement les memes. Evitez de donner des restes de table, surtout les plats riches et les gratins d'automne qui contiennent souvent oignon ou ail, nocifs pour les chiens. Des complements en huile de poisson peuvent aider a preparer le pelage pour l'hiver. Si vous changez d'alimentation, faites-le progressivement sur une semaine.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'obesite'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_HALLOWEEN_CHOCOLATE_011',
    category: 'health_seasonal',
    subcategory: 'toxic_ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [10],
    regionFilter: ['all'],
    titleFr: `Halloween : le chocolat, un danger pour {dog_name}`,
    bodyFr:
      "A l'approche d'Halloween, les bonbons et chocolats sont partout dans la maison. Le chocolat est particulierement nocif pour les chiens, et {dog_name} ne doit jamais y avoir acces. Plus le chocolat est noir, plus il est dangereux, meme en petite quantite. Rangez tous les bonbons hors de portee de {dog_name}, y compris dans les sacs des enfants laisses par terre. Les emballages de bonbons peuvent aussi poser des desagrements s'ils sont avales. Si vous suspectez que {dog_name} a mange du chocolat, notez la quantite et le type (noir, au lait, blanc) et contactez votre veterinaire sans attendre. Les petits chiens sont plus sensibles en raison de leur poids. Proposez plutot a {dog_name} une friandise canine pour qu'il participe a la fete en securite !",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'empoisonnement', 'theobromine'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_DRAFTS_012',
    category: 'health_seasonal',
    subcategory: 'weather',
    breedFilter: [],
    sizeFilter: ['xs', 'small'],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [10, 11],
    regionFilter: ['all'],
    titleFr: `Courants d\'air : le confort de {dog_name} a la maison`,
    bodyFr:
      "Avec la baisse des temperatures automnales, les courants d'air dans la maison peuvent incommoder {dog_name}, surtout s'il dort pres d'une porte ou d'une fenetre. Les petits chiens et ceux a poil court ou fin sont plus sensibles aux variations de temperature. Verifiez que le couchage de {dog_name} est a l'abri des courants d'air et sureleve du sol si celui-ci est froid (carrelage, beton). Une couverture douillette ou un panier a bords hauts offre une bonne protection. Si {dog_name} se roule en boule plus que d'habitude ou tremble legerement, c'est peut-etre signe qu'il a besoin d'un peu plus de chaleur. Deplacer son couchage dans un coin plus abrite peut suffire a ameliorer son confort.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'hypothermie'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_BACK_TO_SCHOOL_013',
    category: 'health_seasonal',
    subcategory: 'behavior',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9],
    regionFilter: ['all'],
    titleFr: `Rentree scolaire : nouvelle routine pour {dog_name}`,
    bodyFr:
      "La rentree scolaire bouleverse les habitudes de toute la famille, y compris celles de {dog_name}. Apres un ete ou tout le monde etait present a la maison, {dog_name} peut se retrouver seul plus longtemps pendant la journee. Pour faciliter la transition, mettez en place une nouvelle routine progressive : promenade matinale avant le depart, jouets d'occupation pour la journee, retrouvailles calmes le soir. Evitez les au revoir trop emotionnels qui pourraient rendre {dog_name} agité. Un kong fourre ou un tapis de lechage peuvent occuper les premieres minutes de solitude. Certains chiens s'adaptent tres vite, d'autres ont besoin de quelques semaines. Soyez patient et coherent avec la nouvelle organisation. Si {dog_name} montre des signes persistants d'inconfort, parlez-en a votre veterinaire.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'anxiete de separation'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_FIRST_COLD_014',
    category: 'health_seasonal',
    subcategory: 'cold',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [10, 11],
    regionFilter: ['all'],
    titleFr: `Premiers froids : preparer {dog_name}`,
    bodyFr:
      "Les premiers froids de l'automne arrivent, et le corps de {dog_name} doit s'adapter progressivement. Continuez les promenades dehors meme quand il fait frais, car c'est ainsi que {dog_name} developpe sa tolerance au froid naturellement. Les chiens a poil court, les petits gabarits et les seniors meritent une attention particuliere : ils peuvent avoir besoin d'un manteau lors des sorties matinales les plus fraiches. A la maison, assurez-vous que le couchage de {dog_name} est confortable et bien isole du sol. C'est aussi le bon moment pour verifier que son alimentation est suffisante pour ses besoins energetiques croissants. Si {dog_name} tremble ou hesite a sortir, reduisez la duree des promenades et augmentez leur frequence.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'hypothermie'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_AUTUMN_RAIN_WALKS_BREEDS_015',
    category: 'health_seasonal',
    subcategory: 'weather',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9, 10, 11],
    regionFilter: ['all'],
    titleFr: `Promenades sous la pluie selon les races`,
    bodyFr:
      "Toutes les races ne reagissent pas de la meme facon a la pluie. Certains chiens comme les Retrievers ou les Terre-Neuve adorent l'eau et ne sont pas genes par une averse. D'autres, comme les Levriers ou les Chihuahuas, preferent rester au sec. Si {dog_name} est du genre a detester la pluie, ne le forcez pas a rester dehors longtemps : une promenade courte mais efficace suffit. Un imperméable pour chien peut aider les races sensibles a rester au sec et confortables. Apres la promenade sous la pluie, sechez bien {dog_name}, surtout le ventre et les pattes. Pour les races a poil long comme {breed_name}, un brossage apres le sechage evite la formation de noeuds. Gardez en reserve des jeux d'interieur pour les jours ou il pleut trop.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },

  // ═══════════════════════════════════════════════════════════
  // WINTER (15 templates) — months 12, 1, 2
  // ═══════════════════════════════════════════════════════════
  {
    id: 'HS_WINTER_ROAD_SALT_001',
    category: 'health_seasonal',
    subcategory: 'cold',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Sel de deneigement : proteger les pattes de {dog_name}`,
    bodyFr:
      "En hiver, le sel repandu sur les trottoirs et les routes peut irriter les coussinets de {dog_name}. Ce sel peut provoquer des irritations, des fissures et de l'inconfort si {dog_name} marche dessus regulierement. Apres chaque promenade hivernale, rincez les pattes de {dog_name} a l'eau tiede pour retirer les residus de sel. Sechez-les soigneusement, surtout entre les doigts. Un baume protecteur pour coussinets, applique avant la sortie, peut creer une barriere efficace. Des bottines pour chien sont aussi une option pour les promenades longues sur des surfaces traitees. Attention egalement au lechage : si {dog_name} se leche les pattes apres la promenade, il point de vigilance d'ingerer du sel. Un rincage systematique est le meilleur reflexe.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'brulure chimique'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_EXTREME_COLD_BREEDS_002',
    category: 'health_seasonal',
    subcategory: 'cold',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Froid extreme : chaque race reagit differemment`,
    bodyFr:
      "Tous les chiens ne sont pas egaux face au froid. Si les Huskies et les Malamutes sont batis pour les temperatures glaciales, {breed_name} peut avoir une tolerance differente. Les chiens a poil court, a faible masse corporelle ou a museau court sont generalement plus sensibles au froid. Les chiots et les chiens ages aussi. Quand les temperatures descendent sous zero, limitez la duree des sorties pour {dog_name} et observez son comportement : s'il leve les pattes, tremble ou cherche a rentrer, il a froid. Ne laissez jamais {dog_name} dormir dehors par grand froid. A l'interieur, proposez un couchage chaud, isole du sol. Si vous avez un doute sur la tolerance au froid de {dog_name}, votre veterinaire peut vous donner des reperes personnalises.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'hypothermie', 'engelure'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_DOG_COAT_003',
    category: 'health_seasonal',
    subcategory: 'cold',
    breedFilter: [],
    sizeFilter: ['xs', 'small', 'medium'],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Manteau pour chien : {dog_name} en a-t-il besoin ?`,
    bodyFr:
      "La question du manteau pour chien divise souvent les proprietaires. En realite, tout depend de {dog_name} et de sa race. Les chiens a poil court ou fin, les petites races, les chiens ages et ceux qui sont tondus beneficient generalement d'un manteau en hiver. A l'inverse, les races nordiques ou a double pelage n'en ont pas besoin et peuvent meme etre genes. Choisissez un manteau a la bonne taille, qui couvre le dos et le ventre sans entraver les mouvements de {dog_name}. Privilegiez les materiaux impermeables et doublés polaire. Le manteau doit etre facile a enfiler et a retirer. Habituez {dog_name} progressivement en le laissant porter le manteau quelques minutes a l'interieur avant les premieres sorties.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_ICE_SLIPPING_004',
    category: 'health_seasonal',
    subcategory: 'cold',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Verglas : eviter les glissades de {dog_name}`,
    bodyFr:
      "Le verglas hivernal peut etre traître pour {dog_name}. Les chiens ne marchent pas toujours prudemment sur la glace et peuvent glisser ou se tordre une patte. Les grands chiens et les seniors sont particulierement vulnerables aux faux mouvements sur sol glissant. Lors des promenades verglacees, gardez {dog_name} en laisse courte pour mieux controler sa vitesse. Evitez les surfaces gelees lisses comme les parkings ou les trottoirs metalliques. Privilegiez les zones ou le sol a une meilleure adherence : herbe, terre, sable. Des bottines a semelles antiderapantes existent pour les chiens. Si {dog_name} boite apres avoir glisse, laissez-le se reposer et observez-le. Si l'inconfort persiste au-dela de quelques heures, consultez votre veterinaire.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'fracture', 'luxation', 'entorse'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_ANTIFREEZE_005',
    category: 'health_seasonal',
    subcategory: 'toxic_ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Antigel : un liquide tres dangereux pour {dog_name}`,
    bodyFr:
      "L'antigel (ethylene glycol) a un gout sucre qui peut attirer {dog_name}, mais il est extremement dangereux, meme en tres petite quantite. En hiver, on en trouve souvent des flaques dans les garages, pres des voitures ou sur les parkings. Empechez absolument {dog_name} de lecher des flaques colorees au sol, surtout si elles ont un aspect huileux et une teinte verte ou orange. Nettoyez immediatement tout deverssement d'antigel chez vous et rangez les bidons en hauteur. Si vous pensez que {dog_name} a pu ingerer de l'antigel, contactez votre veterinaire de toute urgence, sans attendre que des signes apparaissent. Chaque minute compte dans cette situation. Des antigels moins nocifs a base de propylene glycol existent comme alternative.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'empoisonnement', 'insuffisance renale'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_DRY_HEATING_AIR_006',
    category: 'health_seasonal',
    subcategory: 'weather',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Air sec du chauffage et confort de {dog_name}`,
    bodyFr:
      "En hiver, le chauffage assèche l'air interieur, ce qui peut affecter le confort de {dog_name}. Un air trop sec peut rendre la peau de votre compagnon plus seche, favoriser les demangeaisons et ternir le pelage. Quelques gestes simples aident : un humidificateur d'air dans la piece principale, une gamelle d'eau fraiche toujours disponible, et un brossage regulier pour stimuler les huiles naturelles de la peau. Evitez de placer le couchage de {dog_name} trop pres d'un radiateur ou d'une cheminee, car la chaleur directe assèche davantage la peau et le pelage. Des complements en acides gras dans l'alimentation peuvent soutenir la qualite du pelage pendant l'hiver. Si {dog_name} se gratte excessivement, votre veterinaire peut vous aider a trouver la cause.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'dermatite', 'eczema'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_INDOOR_EXERCISE_007',
    category: 'health_seasonal',
    subcategory: 'activity',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Exercice en interieur pour {dog_name} en hiver`,
    bodyFr:
      "Quand il fait trop froid ou que le temps ne permet pas de longues sorties, l'exercice en interieur devient essentiel pour {dog_name}. Le jeu de cache-cache (cachez-vous et appelez {dog_name}) est excellent pour le stimuler physiquement et mentalement. Le tir a la corde, les exercices d'obeissance et les parcours d'obstacles improvises avec des coussins et des chaises font aussi merveille. Les escaliers de la maison offrent un bon exercice cardio en montant et descendant quelques fois. Proposez des seances courtes mais frequentes, 10 a 15 minutes plusieurs fois par jour, plutot qu'une longue session. {dog_name} depensera son energie et restera en forme meme pendant les jours les plus froids de l'hiver.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_MENTAL_ENRICHMENT_008',
    category: 'health_seasonal',
    subcategory: 'behavior',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Enrichissement mental pour les jours courts d\'hiver`,
    bodyFr:
      "Les journees courtes et froides d'hiver peuvent rendre {dog_name} un peu oisif. L'enrichissement mental est un excellent moyen de compenser le manque d'activite physique. Les puzzles alimentaires, les tapis de fouille, les kongs farcis congeles et les jeux de recherche olfactive occupent {dog_name} tout en le fatiguant positivement. Vous pouvez cacher des friandises dans la maison et encourager {dog_name} a les trouver en utilisant son flair. L'apprentissage de nouveaux tours, meme simples comme 'donne la patte' ou 'roule', stimule aussi le cerveau. Dix minutes d'enrichissement mental fatiguent autant qu'une demi-heure de promenade ! Ces activites renforcent la complicite entre vous et aident {dog_name} a traverser l'hiver sereinement.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'depression', 'anxiete'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 168,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_CHRISTMAS_TREE_009',
    category: 'health_seasonal',
    subcategory: 'hazards',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12],
    regionFilter: ['all'],
    titleFr: `Sapin de Noel : securiser la maison pour {dog_name}`,
    bodyFr:
      "Le sapin de Noel est une source de curiosite pour {dog_name}, mais il presente quelques points de vigilance. Les aiguilles de pin, qu'elles soient naturelles ou artificielles, peuvent irriter la bouche et l'estomac si elles sont machees. Les boules et les decorations fragiles point de vigilancent de se casser et de blesser les coussinets. Les guirlandes electriques, si {dog_name} mordille les fils, representent aussi un danger. Placez le sapin dans un endroit stable et si possible, bloquez l'acces avec une barriere. Evitez les decorations comestibles en bas du sapin et ne mettez pas de chocolats decoratifs a portee de {dog_name}. L'eau du pied du sapin peut contenir des substances irritantes : couvrez le reservoir. Avec quelques precautions, toute la famille, {dog_name} inclus, profite des fetes sereinement.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'occlusion'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_CHRISTMAS_CHOCOLATE_010',
    category: 'health_seasonal',
    subcategory: 'toxic_ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12],
    regionFilter: ['all'],
    titleFr: `Noel et chocolat : garder {dog_name} en securite`,
    bodyFr:
      "Noel rime avec chocolat, et c'est une periode ou {dog_name} point de vigilance d'en trouver partout : sous le sapin, sur la table, dans les papiers cadeaux. Le chocolat est nocif pour les chiens, surtout le chocolat noir et le chocolat de cuisson. Meme une petite quantite peut provoquer de l'inconfort chez les petits chiens. Rangez systematiquement les boites de chocolat en hauteur et prevenez vos invites de ne rien donner a {dog_name} sous la table. Si des enfants sont presents, expliquez-leur que les friandises de {dog_name} sont differentes des notres. Ayez des friandises canines a portee de main pour que {dog_name} ait sa propre gourmandise de Noel. Si malgré tout {dog_name} en mange, notez la quantite et appelez votre veterinaire.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'intoxication', 'empoisonnement', 'theobromine'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_DANGEROUS_TOYS_011',
    category: 'health_seasonal',
    subcategory: 'hazards',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1],
    regionFilter: ['all'],
    titleFr: `Jouets de Noel : attention aux points de vigilance pour {dog_name}`,
    bodyFr:
      "Les jouets offerts a Noel, qu'ils soient pour {dog_name} ou pour les enfants, meritent votre attention. Les petites pieces detachables, les couineurs faciles a extraire, les rubans et les ficelles peuvent etre avales par {dog_name} et causer des desagrements digestifs. Choisissez des jouets pour chien robustes, adaptes a la taille et a la puissance de machoire de {dog_name}. Les jouets trop petits presentent un point de vigilance d'etouffement. Supervisez les premieres seances de jeu avec un nouveau jouet et retirez-le des qu'il montre des signes d'usure. Les jouets des enfants laisses au sol sont aussi tentants pour {dog_name} : rangez-les apres utilisation. Un jouet sur et adapte est un cadeau qui procure du plaisir pendant longtemps.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'occlusion', 'chirurgie'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_HOLIDAY_NOISE_STRESS_012',
    category: 'health_seasonal',
    subcategory: 'anxiety',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1],
    regionFilter: ['all'],
    titleFr: `Fetes de fin d\'annee : gerer le bruit pour {dog_name}`,
    bodyFr:
      "Les fetes de fin d'annee sont souvent bruyantes : musique forte, petards, cris de enthousiasme, invites nombreux. Tout cela peut etre forte sollicitationant pour {dog_name}. Amenagez un espace calme ou {dog_name} peut se refugier quand l'ambiance devient trop animee : une piece tranquille avec son couchage, de l'eau et un jouet a macher. Ne le forcez pas a rester parmi les invites s'il semble mal a l'aise. Prevenez vos convives de ne pas insister si {dog_name} se retire. Les petards du Nouvel An sont particulierement eprouvants : fermez les volets, mettez de la musique en fond et restez si possible aupres de {dog_name}. Certains chiens reagissent plus fortement que d'autres aux bruits forts. Si le forte sollicitation de {dog_name} est intense, votre veterinaire peut proposer des solutions apaisantes.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'phobie', 'anxiolytique', 'sedatif'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_CALORIC_NEEDS_013',
    category: 'health_seasonal',
    subcategory: 'nutrition',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Alimentation hivernale : les besoins de {dog_name}`,
    bodyFr:
      "En hiver, les besoins caloriques de {dog_name} peuvent varier selon son mode de vie. Un chien qui passe beaucoup de temps dehors par temps froid depense plus d'energie pour maintenir sa temperature corporelle et peut avoir besoin d'une ration legerement augmentee. A l'inverse, un chien qui reste principalement a l'interieur et se promene moins point de vigilance de prendre du poids si la ration n'est pas adaptee. Pesez {dog_name} regulierement et ajustez les portions en fonction. Les friandises des fetes, meme celles donnees avec amour par les invites, s'ajoutent vite a l'apport calorique. Gardez une alimentation equilibree et de qualite tout au long de l'hiver. Si vous hesitez sur la ration ideale, votre veterinaire peut calculer les besoins energetiques precis de {dog_name}.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'obesite'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_SNOW_WALKS_014',
    category: 'health_seasonal',
    subcategory: 'activity',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Promenades dans la neige avec {dog_name}`,
    bodyFr:
      "Beaucoup de chiens adorent la neige, et les promenades hivernales peuvent etre des moments magiques avec {dog_name}. Cependant, quelques precautions s'imposent. La neige qui s'accumule entre les coussinets forme des boules de glace douloureuses : verifiez regulierement et retirez-les. Apres une sortie enneigee, sechez bien les pattes et le ventre de {dog_name}. Ne le laissez pas manger trop de neige, car cela peut provoquer des inconforts digestifs. Attention aussi a la neige qui masque des obstacles ou des trous : gardez {dog_name} pres de vous dans les zones inconnues. Pour les races a poil long, un leger degagement des poils entre les coussinets limite la formation de glaçons. Profitez de ces promenades enneigees pour stimuler {dog_name} avec des jeux de pistage dans la poudreuse !",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'hypothermie', 'engelure'],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'HS_WINTER_INCREASED_REST_015',
    category: 'health_seasonal',
    subcategory: 'behavior',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Repos hivernal accru : c\'est normal pour {dog_name}`,
    bodyFr:
      "En hiver, il est normal que {dog_name} dorme un peu plus qu'aux autres saisons. Les jours courts et les temperatures froides incitent naturellement les chiens a se reposer davantage. Si {dog_name} fait des siestes plus longues mais reste joyeux et actif pendant les moments d'eveil, tout va bien. Offrez-lui un couchage confortable, au chaud et a l'abri des courants d'air, pour qu'il profite pleinement de ses temps de repos. Ce sommeil supplementaire est reparateur et participe a son equilibre. Cependant, un chien qui dort tout le temps et ne montre plus d'interet pour les promenades ou les jeux merite une attention particuliere. Si le comportement de {dog_name} change de maniere importante, votre veterinaire peut vous aider a comprendre ce qui se passe.",
    sourceType: 'seasonal_alert',
    neverSay: ['condition clinique', 'avis clinique', 'traitement', 'symptome', 'pathologie', 'soigner', 'guerir', 'depression', 'hypothyroidie', 'lethargie'],
    suffix: 'Votre veterinaire peut vous conseiller sur la prevention adaptee a {dog_name}.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 336,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
];
