/**
 * EMOPET Bleiz Freemium Templates — First Aid / Premiers Secours
 * 40 templates — sourceType: 'educational'
 * ALL require vet disclaimer, priority 9-10
 */

export interface FreemiumTemplate {
  id: string;
  category: string;
  subcategory: string;
  breedFilter: string[];
  sizeFilter: string[];
  ageMinMonths: number | null;
  ageMaxMonths: number | null;
  seasonFilter: string[];
  monthFilter: number[];
  regionFilter: string[];
  titleFr: string;
  bodyFr: string;
  sourceType: string;
  neverSay: string[];
  suffix: string | null;
  requiresVetDisclaimer: boolean;
  channel: string;
  priority: number;
  cooldownHours: number;
  maxPerMonth: number;
  usesDogName: boolean;
  usesBreedName: boolean;
  usesAge: boolean;
  usesLocation: boolean;
  usesSeason: boolean;
}

const NEVER_SAY_MEDICAL = ['avis clinique', 'condition clinique', 'traitement', 'symptôme', 'soigner', 'guérir', 'pathologie'];

export const FIRST_AID_TEMPLATES: FreemiumTemplate[] = [
  {
    id: 'fa-001-coup-de-chaleur',
    category: 'first_aid',
    subcategory: 'urgence_thermique',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [5, 6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `Coup de chaleur chez {dog_name} : les bons gestes en attendant le véto`,
    bodyFr: "Si {dog_name} halète de manière intense, bave abondamment, semble désorienté ou a les gencives très rouges, il faut agir vite. Placez {dog_name} dans un endroit frais et ombragé. Appliquez des linges humides tièdes (pas glacés) sur le cou, les aisselles et l'intérieur des cuisses. Proposez de l'eau fraîche en petites quantités, sans forcer. Ne plongez jamais {dog_name} dans l'eau froide, le choc thermique pourrait aggraver la situation. Surveillez sa respiration et essayez de le garder calme. Les races comme {breed_name} peuvent être plus sensibles à la chaleur. Notez l'heure de début des signes pour informer le professionnel. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-002-blessure-patte',
    category: 'first_aid',
    subcategory: 'blessure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} s\'est blessé la patte : que faire ?`,
    bodyFr: "Si {dog_name} boite ou refuse de poser une patte, commencez par examiner délicatement le dessous des coussinets et entre les doigts. Recherchez une coupure, un corps étranger (épine, éclat de verre) ou un gonflement. Si vous voyez un objet planté, ne le retirez pas vous-même : immobilisez la zone avec un bandage propre sans trop serrer. Nettoyez les petites coupures superficielles à l'eau claire tiède. Évitez les produits désinfectants humains qui peuvent être irritants. Limitez les déplacements de {dog_name} en le portant si possible. Si le saignement est important ou si {dog_name} gémit au toucher, ne tardez pas. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-003-ingestion-chocolat',
    category: 'first_aid',
    subcategory: 'intoxication',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [12, 1, 2, 4],
    regionFilter: ['all'],
    titleFr: `{dog_name} a mangé du chocolat : réagir vite`,
    bodyFr: "Le chocolat contient de la théobromine, une substance très dangereuse pour les chiens. Plus le chocolat est noir, plus le point de vigilance est élevé. Si {dog_name} en a ingéré, notez la quantité estimée, le type de chocolat (noir, au lait, blanc) et l'heure de l'ingestion. Ne tentez pas de faire vomir {dog_name} sans avis professionnel. Gardez l'emballage pour le montrer au vétérinaire. Les premiers signes peuvent apparaître dans les deux à quatre heures : agitation, halètement, soif excessive, tremblements. Un petit chien comme un {breed_name} peut être plus vulnérable à de faibles quantités. Ne perdez pas de temps à chercher sur internet, chaque minute compte. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-004-piqure-insecte',
    category: 'first_aid',
    subcategory: 'piqure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring', 'summer'],
    monthFilter: [4, 5, 6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `{dog_name} s\'est fait piquer par un insecte`,
    bodyFr: "Si {dog_name} se gratte soudainement, couine ou présente un gonflement localisé, il a peut-être été piqué par un insecte. Si le dard est visible, retirez-le en grattant avec le bord d'une carte (ne pas utiliser de pince qui pourrait presser le venin). Appliquez une compresse froide sur la zone pendant quelques minutes pour limiter le gonflement. Surveillez attentivement {dog_name} pendant les trente minutes suivantes. Si vous observez un gonflement rapide du museau, des difficultés à respirer, des vomissements ou une faiblesse soudaine, cela peut indiquer une réaction grave. Les piqûres dans la gueule ou la gorge sont particulièrement risquées. Gardez {dog_name} au calme et observez son comportement. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-005-saignement-griffe',
    category: 'first_aid',
    subcategory: 'blessure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Griffe cassée ou qui saigne chez {dog_name}`,
    bodyFr: "Une griffe cassée ou coupée trop court peut saigner abondamment et être très douloureuse pour {dog_name}. Gardez votre calme, car votre forte sollicitation se transmet à votre compagnon. Si la griffe saigne, appuyez fermement avec une compresse propre pendant cinq à dix minutes sans relâcher. La poudre hémostatique (ou à défaut de la fécule de maïs) peut aider à stopper le saignement. Ne tirez jamais sur une griffe qui pend, même si elle semble prête à tomber. Empêchez {dog_name} de lécher la zone en le distrayant. Si le saignement ne s'arrête pas après quinze minutes de pression continue, ou si la griffe est arrachée à la base, il faut consulter rapidement. Gardez la patte propre en attendant. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-006-brulure-bitume',
    category: 'first_aid',
    subcategory: 'urgence_thermique',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Coussinets brûlés par le bitume : protéger {dog_name}`,
    bodyFr: "En été, le bitume peut atteindre 60 à 70 degrés au sol, même quand l'air semble supportable. Si {dog_name} lève les pattes, refuse d'avancer ou boite sur le trottoir, ses coussinets sont probablement brûlés. Portez-le immédiatement sur de l'herbe ou une surface fraîche. Rincez ses pattes à l'eau fraîche (pas froide) pendant plusieurs minutes. N'appliquez aucune crème sans avis professionnel. Laissez sécher à l'air libre. Le test simple : posez le dos de votre main sur le bitume pendant sept secondes. Si c'est trop chaud pour vous, c'est trop chaud pour {dog_name}. Privilégiez les promenades tôt le matin ou tard le soir en période de canicule. Si les coussinets sont cloqués ou très rouges, ne tardez pas. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-007-noyade-premiers-gestes',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [5, 6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `Noyade : les premiers gestes pour {dog_name}`,
    bodyFr: "Si {dog_name} vient d'être retiré de l'eau et ne respire pas ou respire très faiblement, chaque seconde compte. Placez {dog_name} sur le côté, tête légèrement plus basse que le corps pour aider l'eau à s'écouler. Pour un petit chien, vous pouvez le tenir tête en bas quelques secondes. Ouvrez sa gueule et dégagez tout ce qui pourrait obstruer les voies respiratoires. Si {dog_name} ne respire pas, fermez sa gueule et soufflez doucement dans ses narines toutes les trois à cinq secondes. Vérifiez le pouls à l'intérieur de la cuisse. Même si {dog_name} semble récupérer et reprendre conscience, une consultation reste indispensable car des complications peuvent survenir dans les heures suivantes. Enveloppez-le dans une couverture pour maintenir sa chaleur corporelle. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-008-convulsion',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a une convulsion : que faire`,
    bodyFr: "Si {dog_name} est pris de tremblements incontrôlables, se raidit, tombe sur le côté ou pédale avec les pattes, il est en crise convulsive. Ne tentez surtout pas de lui maintenir la gueule ouverte ou de lui tenir la langue, vous point de vigilanceriez d'être mordu. Éloignez les meubles et objets dangereux autour de lui. Ne le déplacez pas sauf s'il est près d'un escalier ou d'un danger immédiat. Tamisez la lumière et réduisez le bruit au maximum. Notez l'heure de début et la durée de la crise, cette information sera précieuse. Filmez si possible pour montrer au professionnel. Après la crise, {dog_name} sera désorienté et épuisé : restez près de lui, parlez-lui doucement. Si la crise dure plus de cinq minutes ou se répète, c'est une urgence absolue. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-009-etouffement',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} s\'étouffe : les gestes d\'urgence`,
    bodyFr: "Si {dog_name} tousse violemment, bave, panique ou essaie de se gratter la gueule, il a peut-être quelque chose de coincé dans la gorge. Ouvrez délicatement sa gueule et regardez si vous voyez l'objet. Si c'est le cas et qu'il est accessible, retirez-le avec précaution en utilisant vos doigts ou une pince, sans le pousser plus loin. Si l'objet n'est pas visible, pour un petit chien placez-le tête en bas et tapez fermement entre les omoplates. Pour un grand chien, réalisez la manoeuvre de Heimlich : placez-vous derrière lui, mains jointes sous le sternum, et poussez vers le haut et l'avant par pressions rapides. Si {dog_name} perd connaissance, dégagez les voies respiratoires et commencez la respiration artificielle par les narines. Chaque instant est crucial. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-010-chenille-processionnaire',
    category: 'first_aid',
    subcategory: 'intoxication',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring'],
    monthFilter: [2, 3, 4, 5],
    regionFilter: ['all'],
    titleFr: `{dog_name} et les chenilles processionnaires : danger`,
    bodyFr: "Les chenilles processionnaires sont extrêmement dangereuses pour {dog_name}. Leurs poils urticants provoquent des brûlures graves au contact de la langue, des babines ou du museau. Si {dog_name} bave abondamment, se frotte le museau, a la langue gonflée ou violacée, agissez immédiatement. Ne touchez pas les chenilles à mains nues. Rincez abondamment la gueule de {dog_name} avec de l'eau claire sans frotter, l'eau doit couler de l'arrière vers l'avant de la gueule. Ne le laissez pas se lécher. Le gonflement peut être très rapide et obstruer les voies respiratoires. Les zones à point de vigilance sont les jardins avec des pins entre février et mai. Apprenez à reconnaître les nids blancs soyeux dans les pins et les processions au sol. C'est une urgence vitale, ne tardez pas. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-011-morsure-serpent',
    category: 'first_aid',
    subcategory: 'morsure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring', 'summer'],
    monthFilter: [4, 5, 6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `{dog_name} mordu par un serpent : réagir correctement`,
    bodyFr: "Si {dog_name} a été mordu par un serpent, restez calme et limitez ses mouvements au maximum. L'agitation accélère la diffusion du venin dans l'organisme. Ne tentez pas d'aspirer le venin, de poser un garrot ou d'inciser la plaie, ces gestes sont inefficaces et dangereux. Identifiez si possible le serpent (couleur, taille, forme de la tête) sans vous mettre en danger. Si la morsure est sur une patte, immobilisez-la sans serrer. Portez {dog_name} jusqu'à la voiture plutôt que de le laisser marcher. Le gonflement peut apparaître rapidement autour de la morsure. Notez l'heure exacte de la morsure. Les vipères sont les serpents venimeux les plus courants en France, reconnaissables à leur pupille verticale et leur tête triangulaire. Le temps joue contre vous. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-012-renverse-par-voiture',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} renversé par une voiture : que faire`,
    bodyFr: "Si {dog_name} vient d'être percuté par un véhicule, approchez-le avec précaution car un chien blessé et effrayé peut mordre, même son maître. Parlez-lui doucement. Ne le déplacez pas brutalement, des lésions internes invisibles sont possibles. Si {dog_name} est conscient, glissez-le délicatement sur une couverture ou un manteau rigide qui servira de civière improvisée. En cas de saignement visible, appliquez une pression avec un tissu propre. Si {dog_name} est inconscient, vérifiez sa respiration en observant le mouvement de ses côtes. Assurez-vous que ses voies respiratoires sont dégagées. Gardez-le au chaud avec une couverture. Ne lui donnez ni eau ni nourriture. Même si {dog_name} semble aller bien et se relève, des complications internes peuvent apparaître dans les heures qui suivent. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-013-ingestion-corps-etranger',
    category: 'first_aid',
    subcategory: 'ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a avalé un objet : les bons réflexes`,
    bodyFr: "Les chiens, et particulièrement les chiots, adorent mâchouiller et peuvent avaler des objets variés : chaussettes, jouets, cailloux, morceaux de bois. Si vous avez vu {dog_name} avaler quelque chose, ne tentez pas de le faire vomir sans avis professionnel, certains objets peuvent causer des dégâts supplémentaires en remontant. Notez la nature de l'objet, sa taille estimée et l'heure de l'ingestion. Surveillez {dog_name} attentivement : refuse-t-il de manger, a-t-il des haut-le-coeur, semble-t-il avoir mal au ventre, est-il abattu ? Si l'objet est pointu, tranchant ou volumineux, n'attendez pas l'apparition de signes. Certaines races comme {breed_name} sont connues pour être de grands « avaleurs ». Gardez l'emballage ou un objet identique à montrer au professionnel. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-014-oeil-blesse',
    category: 'first_aid',
    subcategory: 'blessure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Oeil blessé chez {dog_name} : comment réagir`,
    bodyFr: "Si {dog_name} garde un oeil fermé, le frotte avec sa patte, larmoie abondamment ou si vous voyez une rougeur, un gonflement ou un corps étranger dans l'oeil, il faut agir avec douceur. Empêchez {dog_name} de se gratter l'oeil, utilisez une collerette si vous en avez une. Ne tentez pas de retirer un objet planté dans l'oeil. Pour un corps étranger superficiel (poussière, brin d'herbe), vous pouvez rincer doucement avec du sérum physiologique en laissant couler du coin interne vers l'extérieur. Ne mettez aucun collyre humain sans avis professionnel. Protégez l'oeil avec une compresse humide maintenue sans pression. Les yeux sont des organes fragiles et une prise en charge rapide peut faire toute la différence pour préserver la vision de {dog_name}. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-015-brulure-chimique',
    category: 'first_aid',
    subcategory: 'intoxication',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Brûlure chimique chez {dog_name} : gestes d\'urgence`,
    bodyFr: "Si {dog_name} est entré en contact avec un produit chimique (eau de Javel, soude, acide, produit ménager concentré), la priorité est de rincer abondamment la zone touchée avec de l'eau tiède pendant au moins quinze à vingt minutes. Portez des gants pour vous protéger. Si le produit a été ingéré, ne faites surtout pas vomir {dog_name} car le produit brûlerait une seconde fois en remontant. Donnez-lui de l'eau à boire en petites quantités pour diluer le produit. Si les yeux sont touchés, rincez-les abondamment avec du sérum physiologique ou de l'eau claire. Identifiez le produit en cause et gardez l'emballage. Notez la quantité estimée et le temps de contact. Ne mettez aucune crème, beurre ou pommade sur la brûlure. Gardez {dog_name} au calme et au chaud. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-016-hypothermie',
    category: 'first_aid',
    subcategory: 'urgence_thermique',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [11, 12, 1, 2, 3],
    regionFilter: ['all'],
    titleFr: `Hypothermie chez {dog_name} : réchauffer en toute sécurité`,
    bodyFr: "Si {dog_name} tremble violemment, est léthargique, a les extrémités froides ou semble désorienté après une exposition prolongée au froid, il est peut-être en hypothermie. Rentrez-le immédiatement dans un endroit chaud et à l'abri du vent. Enveloppez {dog_name} dans des couvertures sèches et chaudes. Vous pouvez placer des bouillottes enveloppées dans des serviettes contre son ventre et ses aisselles, mais jamais directement sur la peau. Réchauffez-le progressivement, un réchauffement trop rapide peut être dangereux. Proposez-lui de l'eau tiède à boire. Les petites races, les chiots, les chiens âgés et les races à poil court comme certains {breed_name} sont plus vulnérables. Si {dog_name} ne se réchauffe pas, reste apathique ou perd connaissance, c'est une urgence. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-017-choc-electrique',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: 2,
    ageMaxMonths: 18,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a mâché un câble électrique`,
    bodyFr: "Les chiots adorent mâchouiller et les câbles électriques sont un danger réel. Si {dog_name} a mordu un câble branché, coupez immédiatement le courant avant de le toucher. Ne touchez jamais un chien en contact avec une source électrique. Une fois le courant coupé, vérifiez sa respiration et son état de conscience. Examinez sa gueule : des brûlures peuvent apparaître sur les babines, la langue ou le palais. Si {dog_name} est inconscient, vérifiez son pouls à l'intérieur de la cuisse et commencez la respiration artificielle si nécessaire. Même si {dog_name} semble normal après le choc, des complications au niveau du coeur ou des poumons peuvent survenir dans les heures qui suivent. Protégez vos câbles avec des gaines ou des caches-câbles, surtout avec un jeune {breed_name} curieux. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-018-torsion-estomac',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: ['large', 'giant'],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Ballonnement et torsion d\'estomac : urgence absolue pour {dog_name}`,
    bodyFr: "La dilatation-torsion d'estomac est l'une des urgences les plus graves chez le chien, surtout les grandes races. Si {dog_name} a le ventre gonflé et dur, essaie de vomir sans y parvenir, est agité, bave et semble souffrir, il peut s'agir d'une torsion d'estomac. Le temps est compté : sans intervention rapide, cette situation peut être fatale en quelques heures. Ne tentez pas de le faire boire ou manger. Ne massez pas le ventre. Gardez {dog_name} aussi calme que possible et transportez-le immédiatement. En prévention, évitez l'exercice intense une heure avant et deux heures après les repas. Fractionnez les repas en deux ou trois portions. Les gamelles surélevées ne sont plus recommandées. Les {breed_name} de grande taille sont particulièrement concernés. C'est une urgence vitale absolue. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-019-intoxication-antigel',
    category: 'first_aid',
    subcategory: 'intoxication',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter', 'autumn'],
    monthFilter: [10, 11, 12, 1, 2, 3],
    regionFilter: ['all'],
    titleFr: `Intoxication à l\'antigel : danger mortel pour {dog_name}`,
    bodyFr: "L'antigel (éthylène glycol) a un goût sucré qui attire les chiens, mais c'est un poison mortel même en petite quantité. Si vous soupçonnez que {dog_name} en a léché ou bu, considérez cela comme une urgence absolue. Les premiers signes apparaissent dans les trente minutes à deux heures : {dog_name} peut sembler « ivre », titubant, désorienté, avec des vomissements et une soif excessive. Ne perdez pas de temps à observer l'évolution, chaque minute compte car le produit est rapidement absorbé par l'organisme. Ne faites pas vomir {dog_name} sans avis professionnel. Gardez l'emballage du produit. Nettoyez les flaques d'antigel dans votre garage avec du sable ou de la litière. Rangez toujours l'antigel hors de portée. Un simple flaque sous une voiture peut être fatale. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-020-intoxication-medicaments',
    category: 'first_aid',
    subcategory: 'intoxication',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a avalé un médicament humain`,
    bodyFr: "De nombreux médicaments courants pour les humains sont très dangereux pour les chiens. Ibuprofène, paracétamol, aspirine, antidépresseurs, somnifères : une seule pilule peut avoir des conséquences graves pour {dog_name}. Si votre chien a ingéré un médicament humain, identifiez précisément le produit, le dosage et la quantité avalée. Notez l'heure de l'ingestion. Ne faites pas vomir {dog_name} sans avis professionnel, certaines substances peuvent causer plus de dégâts en remontant. Gardez la boîte du médicament et la notice. Rangez toujours vos médicaments en hauteur dans un placard fermé, les chiens sont capables d'ouvrir des sacs et de mâcher des emballages. Deux comprimés de paracétamol peuvent être fatals pour un petit chien. N'administrez jamais de médicament humain à {dog_name} de votre propre initiative. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-021-ingestion-os-coince',
    category: 'first_aid',
    subcategory: 'ingestion',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a un os coincé : que faire`,
    bodyFr: "Si {dog_name} bave excessivement, se gratte la gueule, refuse de manger ou semble avoir quelque chose de bloqué après avoir mâché un os, il faut réagir calmement. Ouvrez doucement sa gueule en maintenant les babines sur les dents pour vous protéger. Si vous voyez un os coincé en travers du palais ou entre les dents, vous pouvez tenter de le retirer délicatement. Si l'os est coincé plus profondément dans la gorge, n'essayez pas de l'atteindre, vous point de vigilanceriez de le pousser davantage ou de blesser {dog_name}. Les os cuits (poulet, lapin, côtelette) sont les plus dangereux car ils se fragmentent en éclats tranchants. Évitez de donner des os cuits à {dog_name}. Les os crus de grande taille et adaptés à la mâchoire de {breed_name} sont plus sûrs, mais aucun os n'est sans point de vigilance. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-022-reaction-allergique',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Réaction allergique aiguë chez {dog_name}`,
    bodyFr: "Une réaction allergique grave (choc anaphylactique) peut survenir après une piqûre d'insecte, un aliment, un médicament ou un contact avec une substance. Si {dog_name} présente un gonflement rapide du museau, des babines ou de la gorge, des difficultés à respirer, des vomissements soudains, une faiblesse brutale ou s'effondre, c'est une urgence vitale. Gardez {dog_name} au calme et au chaud. Si le gonflement touche la gorge, maintenez sa tête légèrement surélevée pour faciliter la respiration. Ne lui donnez aucun médicament antihistaminique humain sans avis professionnel, les dosages ne sont pas les mêmes. Si vous connaissez l'allergène, éloignez-le. Notez ce que {dog_name} a mangé, touché ou reçu dans les dernières heures. Une réaction peut s'aggraver très rapidement en quelques minutes. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-023-griffure-chat-oeil',
    category: 'first_aid',
    subcategory: 'blessure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} griffé à l\'oeil par un chat`,
    bodyFr: "Les griffures de chat sont fréquentes et l'oeil est une cible particulièrement vulnérable. Si {dog_name} garde un oeil fermé, le frotte ou si vous voyez une griffure sur la cornée, agissez vite. Empêchez {dog_name} de se frotter l'oeil avec ses pattes, cela pourrait aggraver la lésion. Si vous disposez d'une collerette, mettez-la immédiatement. Rincez l'oeil avec du sérum physiologique en faisant couler doucement du coin intérieur vers l'extérieur. Ne mettez aucun collyre, même un reste de prescription ancienne. Les griffures de chat sont souvent contaminées par des bactéries et peuvent s'infecter rapidement. Même si la griffure vous semble superficielle, une lésion de la cornée peut s'aggraver en quelques heures et menacer la vision. Couvrez l'oeil avec une compresse humide sans appuyer. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-024-chute-hauteur',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} est tombé d\'une hauteur`,
    bodyFr: "Si {dog_name} est tombé d'un balcon, d'une fenêtre, d'un muret ou de toute autre hauteur, même s'il se relève et semble aller bien, une consultation est indispensable. Les chiens ne retombent pas sur leurs pattes comme les chats et les lésions internes peuvent être invisibles. Ne le faites pas courir ou sauter pour « tester » s'il va bien. Manipulez {dog_name} avec douceur, placez-le sur une surface rigide si possible. Vérifiez s'il y a des saignements visibles, un gonflement ou une position anormale des pattes. Observez sa respiration et ses gencives (elles doivent être roses). Un chien en état de choc peut sembler normal pendant quelques minutes puis se dégrader rapidement. Plus {dog_name} est petit, plus une chute même modeste peut être grave. Sécurisez vos balcons et fenêtres, surtout en étage. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-025-boiterie-soudaine',
    category: 'first_aid',
    subcategory: 'blessure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} boite soudainement`,
    bodyFr: "Si {dog_name} se met soudainement à boiter en promenade ou au réveil, commencez par un examen calme. Faites-le s'asseoir ou s'allonger et examinez doucement chaque patte en partant du bas. Vérifiez les coussinets (coupure, épine, brûlure), les espaces entre les doigts (épillet, gravier), les griffes (cassée, incarnée) et palpez doucement les articulations en remontant. Si {dog_name} retire vivement sa patte ou couine au toucher d'un endroit précis, vous avez localisé la zone sensible. Pour un corps étranger superficiel comme une petite épine, vous pouvez la retirer délicatement à la pince. Limitez les déplacements de {dog_name} et portez-le si possible. Si la boiterie persiste plus de quelques heures, si la patte est gonflée, en position anormale, ou si {dog_name} refuse totalement de la poser, ne tardez pas. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-026-saignement-oreille',
    category: 'first_aid',
    subcategory: 'blessure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Saignement d\'oreille chez {dog_name}`,
    bodyFr: "Les oreilles des chiens sont très vascularisées et saignent abondamment, même pour une petite coupure. Si {dog_name} saigne de l'oreille, le premier réflexe est de garder votre calme même si la quantité de sang est impressionnante. Appliquez une compresse propre et maintenez une pression ferme pendant au moins dix minutes sans regarder en dessous. Si le saignement est à l'extérieur du pavillon, rabattez l'oreille contre le crâne et maintenez avec un bandage léger autour de la tête. Empêchez {dog_name} de secouer la tête, ce qui relancerait le saignement. Si le sang vient de l'intérieur du conduit auditif, ne mettez rien dedans. Les races à longues oreilles comme les épagneuls ou les beagles sont plus exposées aux blessures du pavillon. Si le saignement ne cesse pas ou revient dès que la pression est relâchée, ne tardez pas. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-027-brulure-coussinet',
    category: 'first_aid',
    subcategory: 'blessure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer', 'winter'],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Brûlure au coussinet chez {dog_name}`,
    bodyFr: "Les coussinets de {dog_name} sont robustes mais pas invincibles. En été, le bitume et le sable brûlants, en hiver, le sel de déneigement et le gel peuvent les brûler. Si les coussinets sont rouges, cloqués, fissurés ou si {dog_name} lèche obsessionnellement ses pattes, rincez-les à l'eau tiède pendant cinq à dix minutes. Séchez délicatement en tamponnant sans frotter. N'appliquez ni crème ni baume sans avis professionnel. Vous pouvez protéger la zone avec une chaussette propre maintenue par un sparadrap médical (pas trop serré) pour empêcher {dog_name} de lécher. Évitez de le promener sur des surfaces dures jusqu'à la consultation. Les coussinets mettent du temps à cicatriser car ils sont en contact permanent avec le sol. Pensez aux bottines de protection pour les promenades extrêmes. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-028-ingestion-plante-toxique',
    category: 'first_aid',
    subcategory: 'intoxication',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring', 'summer'],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} a mangé une plante toxique`,
    bodyFr: "De nombreuses plantes courantes dans nos jardins et maisons sont dangereuses pour les chiens : le laurier-rose, le muguet, l'if, le lys, le philodendron, le dieffenbachia, l'azalée, le rhododendron, les bulbes de tulipes et jonquilles. Si {dog_name} a mâché ou avalé une plante suspecte, gardez un morceau de la plante pour l'identification. Ne faites pas vomir {dog_name} car certaines plantes irritent davantage en remontant. Rincez-lui la gueule à l'eau claire si le contact est récent. Notez l'heure d'ingestion et la quantité estimée. Les premiers signes peuvent être : bave excessive, vomissements, abattement, diarrhée, tremblements. Le muguet par exemple est dangereux, y compris l'eau du vase. Les chiots et les {breed_name} curieux sont particulièrement exposés. Sécurisez votre jardin et votre intérieur. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-029-piqure-vipere',
    category: 'first_aid',
    subcategory: 'morsure',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring', 'summer'],
    monthFilter: [3, 4, 5, 6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `{dog_name} piqué par une vipère`,
    bodyFr: "Les vipères sont actives du printemps à l'automne, surtout dans les zones rocheuses, les murets et les chemins ensoleillés. Si {dog_name} couine brusquement en promenade, recule et que vous observez deux petits points de ponction avec un gonflement rapide, il a probablement été mordu par une vipère. Les morsures touchent souvent le museau ou les pattes avant. Immobilisez {dog_name} au maximum, portez-le plutôt que de le laisser marcher. Ne posez pas de garrot, n'incisez pas la plaie, ne tentez pas d'aspirer le venin. Gardez la zone mordue en dessous du niveau du coeur si possible. Retirez le collier si la morsure est au museau car le gonflement peut être très rapide. Les petites races sont plus vulnérables. Notez l'heure de la morsure et l'endroit exact. Dirigez-vous vers le vétérinaire le plus proche. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-030-chien-coince',
    category: 'first_aid',
    subcategory: 'urgence',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} est coincé quelque part`,
    bodyFr: "Si {dog_name} est coincé dans une clôture, un grillage, entre des barreaux, sous un meuble ou dans un espace étroit, la priorité est de ne pas aggraver la situation. Parlez-lui calmement, votre voix rassurante l'aidera à ne pas paniquer et à ne pas se débattre davantage. Un chien qui se débat point de vigilance de se blesser plus gravement ou de se coincer encore plus. Évaluez la situation : pouvez-vous le libérer sans point de vigilance pour vous et pour lui ? Si {dog_name} est coincé dans du grillage, ne tirez pas car les fils métalliques peuvent couper. Utilisez une pince coupante si disponible. Si la tête est coincée, essayez de lubrifier avec du savon liquide ou de l'huile. Si {dog_name} semble avoir le souffle coupé, si la situation est complexe ou si vous n'arrivez pas à le libérer, appelez les pompiers qui disposent d'outils adaptés. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-031-transport-urgence',
    category: 'first_aid',
    subcategory: 'transport',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Transporter {dog_name} en urgence vers le véto`,
    bodyFr: "En situation d'urgence, le transport est une étape critique. Si {dog_name} est blessé ou ne peut pas marcher, utilisez une couverture ou un grand tissu comme civière improvisée. Pour un petit chien, une caisse de transport rigide est idéale. Pour un grand chien, deux personnes tenant chacune un côté de la couverture permettent un transport sécurisé. Stabilisez la tête et le cou si vous soupçonnez un problème à la colonne. Gardez {dog_name} au chaud avec une couverture supplémentaire. Attention, un chien qui souffre peut mordre par réflexe : si nécessaire, improvisez une muselière avec un lien souple (pas sur un chien qui vomit ou qui a du mal à respirer). En voiture, installez {dog_name} dans le coffre sur une couverture ou sur la banquette arrière avec quelqu'un pour le maintenir. Conduisez prudemment, un accident aggraverait tout. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-032-numeros-urgence-veto',
    category: 'first_aid',
    subcategory: 'preparation',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Numéros d\'urgence vétérinaire : préparez-vous pour {dog_name}`,
    bodyFr: "En cas d'urgence avec {dog_name}, chaque minute passée à chercher un numéro est une minute perdue. Préparez-vous dès maintenant. Enregistrez dans votre téléphone le numéro de votre vétérinaire habituel et celui de la clinique vétérinaire de garde la plus proche (souvent indiqué sur le répondeur de votre véto le soir et le week-end). Renseignez-vous sur le centre antipoison animal le plus proche. En France, les principaux centres antipoison vétérinaires sont joignables 24h/24. Affichez ces numéros sur le réfrigérateur et partagez-les avec toute personne susceptible de garder {dog_name}. Vérifiez les horaires de votre clinique et identifiez la clinique de garde de nuit dans votre secteur. Un itinéraire vérifié à l'avance peut faire gagner un temps précieux. La préparation sauve des vies. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  {
    id: 'fa-033-trousse-premiers-secours',
    category: 'first_aid',
    subcategory: 'preparation',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La trousse de premiers secours de {dog_name}`,
    bodyFr: "Avoir une trousse de premiers secours adaptée à {dog_name} peut faire la différence en cas d'urgence. Voici ce qu'elle devrait contenir : des compresses stériles, des bandes de gaze, du sparadrap médical, du sérum physiologique en dosettes, une paire de ciseaux à bouts ronds, une pince à épiler (pour les épines et tiques), de la poudre hémostatique, une couverture de survie, des gants jetables, une muselière adaptée à la taille de {breed_name}, une lampe de poche, le carnet de suivi vétérinaire de {dog_name} et les numéros d'urgence. Rangez cette trousse dans un endroit accessible et emportez-la en voyage et en promenade. Vérifiez régulièrement les dates de péremption. Familiarisez-vous avec le contenu avant d'en avoir besoin, ce n'est pas le moment d'apprendre en situation de forte sollicitation. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-034-garrot-quand-comment',
    category: 'first_aid',
    subcategory: 'technique',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le garrot chez le chien : quand et comment`,
    bodyFr: "Le garrot est un geste d'urgence à n'utiliser qu'en tout dernier recours pour {dog_name}, uniquement en cas d'hémorragie massive incontrôlable sur un membre. Un garrot mal posé ou laissé trop longtemps peut causer la perte du membre. Avant d'envisager le garrot, tentez d'abord une pression directe avec des compresses pendant au moins dix minutes. Si le sang jaillit par pulsations et que la pression ne suffit pas, placez un lien large (cravate, foulard, jamais de fil ou ficelle) en amont de la blessure et serrez juste assez pour ralentir le saignement. Notez impérativement l'heure de pose. Le garrot ne doit jamais rester plus de quinze à vingt minutes. Relâchez brièvement toutes les quinze minutes si le trajet vers le véto est long. Ne retirez jamais le garrot sans supervision professionnelle. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-035-position-laterale-securite',
    category: 'first_aid',
    subcategory: 'technique',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Position latérale de sécurité pour {dog_name}`,
    bodyFr: "Si {dog_name} est inconscient mais respire, la position latérale de sécurité permet de dégager ses voies respiratoires et d'éviter qu'il ne s'étouffe avec ses sécrétions. Allongez {dog_name} sur le côté droit de préférence. Étirez doucement sa tête vers l'avant pour aligner les voies respiratoires, sans forcer sur le cou. Ouvrez délicatement sa gueule et tirez la langue sur le côté pour qu'elle ne bloque pas la gorge. Si {dog_name} vomit, la gravité aidera les liquides à s'écouler hors de la gueule. Les pattes avant peuvent rester naturellement allongées. Couvrez {dog_name} avec une couverture pour maintenir sa température. Restez près de lui, parlez-lui doucement et surveillez sa respiration en comptant les mouvements de ses côtes. Si la respiration s'arrête ou devient très faible, préparez-vous à pratiquer la respiration artificielle. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-036-verifier-constantes-vitales',
    category: 'first_aid',
    subcategory: 'technique',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Vérifier les constantes vitales de {dog_name}`,
    bodyFr: "Savoir évaluer l'état de {dog_name} en urgence peut aider le vétérinaire à distance. La fréquence respiratoire normale est de dix à trente respirations par minute : comptez les mouvements du thorax pendant quinze secondes et multipliez par quatre. Le pouls se prend à l'intérieur de la cuisse, au niveau de l'artère fémorale : la fréquence normale est de soixante à cent quarante battements par minute selon la taille (plus rapide chez les petits chiens). La température rectale normale se situe entre 38 et 39 degrés. Les gencives doivent être roses et humides : appuyez sur la gencive avec un doigt, la couleur doit revenir en moins de deux secondes (temps de remplissage capillaire). Des gencives pâles, bleues, grises ou jaunes sont un signal d'vigilance grave. Entraînez-vous à prendre ces mesures quand {dog_name} va bien. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-037-haletement-excessif',
    category: 'first_aid',
    subcategory: 'observation',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} halète excessivement : quand s\'inquiéter`,
    bodyFr: "Le halètement est normal chez le chien après un effort ou par temps chaud, c'est son principal moyen de réguler sa température. Mais un halètement excessif au repos, la nuit, sans raison apparente ou accompagné d'autres signes doit vigilancer. Observez le contexte : {dog_name} a-t-il chaud, fait un effort intense, est-il sous forte sollicitation ? Si aucune de ces raisons n'explique le halètement, c'est peut-être un signal d'inconfort ou de douleur. Un halètement avec les babines tirées en arrière, les yeux grands ouverts et les oreilles plaquées indique souvent un forte sollicitation intense ou une douleur. Si le halètement s'accompagne de gencives bleues ou très pâles, d'un ventre gonflé, d'une agitation inhabituelle ou d'une difficulté à trouver une position confortable, la situation peut être sérieuse. Les races brachycéphales comme les bouledogues halètent davantage naturellement. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-038-gencives-pales-bleues',
    category: 'first_aid',
    subcategory: 'observation',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Gencives pâles ou bleues chez {dog_name} : vigilance`,
    bodyFr: "La couleur des gencives de {dog_name} est un indicateur précieux de son état général. Des gencives roses et humides sont le signe d'une bonne circulation. En revanche, des gencives pâles (blanches ou très claires) peuvent indiquer une perte de sang, un choc ou une anémie. Des gencives bleues ou violacées signalent un manque d'oxygène, c'est une urgence respiratoire ou cardiaque. Des gencives jaunes peuvent indiquer un problème hépatique. Des gencives rouge vif et collantes, accompagnées d'un halètement intense, peuvent signaler un coup de chaleur. Pour évaluer la circulation, appuyez une seconde sur la gencive avec votre doigt : la zone blanchit puis doit redevenir rose en moins de deux secondes. Au-delà, la circulation est ralentie. Apprenez à regarder les gencives de {dog_name} quand il va bien pour savoir reconnaître un changement. Appelez le vétérinaire de garde au plus vite.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Appelez le vétérinaire de garde au plus vite.',
    requiresVetDisclaimer: true,
    channel: 'home_insight',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'fa-039-deshydratation-signes',
    category: 'first_aid',
    subcategory: 'observation',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [5, 6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `Reconnaître la déshydratation chez {dog_name}`,
    bodyFr: "La déshydratation peut survenir rapidement chez {dog_name}, surtout par temps chaud, après des vomissements ou une diarrhée prolongée. Pour évaluer l'hydratation, faites le test du pli de peau : pincez doucement la peau entre les omoplates et relâchez. Chez un chien bien hydraté, la peau revient immédiatement à sa place. Si le pli reste marqué plus de deux secondes, {dog_name} est probablement déshydraté. Autres signes à surveiller : gencives sèches et collantes, yeux enfoncés, truffe très sèche, urine foncée et peu abondante, abattement général. Si {dog_name} peut boire, proposez de l'eau fraîche en petites quantités régulières, pas une grande gamelle d'un coup. Vous pouvez humidifier ses babines avec un linge mouillé. Si {dog_name} refuse de boire, vomit ou est très abattu, la déshydratation est peut-être déjà avancée. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 9,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'fa-040-chien-ne-se-releve-pas',
    category: 'first_aid',
    subcategory: 'urgence_vitale',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} ne se relève pas : que faire`,
    bodyFr: "Si {dog_name} refuse ou ne parvient pas à se lever, c'est un signal d'vigilance qui nécessite une évaluation rapide. Approchez-vous calmement et observez : est-il conscient, vous suit-il du regard, réagit-il quand vous l'appelez ? Vérifiez sa respiration en observant le mouvement de ses côtes. Examinez les gencives (couleur et humidité). Palpez doucement ses pattes pour détecter une zone de douleur. Un chien qui ne se relève pas peut souffrir de douleur intense, d'une faiblesse extrême, d'un problème neurologique ou d'un état de choc. Si {dog_name} est conscient mais ne bouge pas, ne le forcez pas à se lever. Couvrez-le pour maintenir sa chaleur corporelle. Si {dog_name} est inconscient, placez-le en position latérale de sécurité, tête dans l'axe du corps, langue dégagée sur le côté. Ne lui donnez ni eau ni nourriture. Notez depuis combien de temps il est dans cet état. Contactez votre vétérinaire immédiatement.",
    sourceType: 'educational',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: 'Contactez votre vétérinaire immédiatement.',
    requiresVetDisclaimer: true,
    channel: 'push',
    priority: 10,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
];
