/**
 * EMOPET Bleiz Freemium Templates — Life Events / Événements de vie
 * 60 templates — sourceType: 'life_event'
 */

import type { FreemiumTemplate } from './freemium-templates-first-aid';

const NEVER_SAY_MEDICAL = ['avis clinique', 'condition clinique', 'traitement', 'symptôme', 'soigner', 'guérir', 'pathologie'];

export const LIFE_EVENTS_TEMPLATES: FreemiumTemplate[] = [
  {
    id: 'le-001-demenagement',
    category: 'life_events',
    subcategory: 'changement_lieu',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Déménager avec {dog_name} : préparer la transition`,
    bodyFr: "Un déménagement est un bouleversement pour {dog_name} qui perd tous ses repères olfactifs et visuels. Préparez la transition en gardant ses affaires (panier, jouets, gamelles) sans les laver pour conserver les odeurs rassurantes. Le jour du déménagement, confiez {dog_name} à une personne de confiance ou isolez-le dans une pièce calme avec ses affaires pour éviter le forte sollicitation de l'agitation. Dans le nouveau logement, installez son coin dès le premier jour à un endroit calme. Laissez-le explorer à son rythme, pièce par pièce. Maintenez ses horaires de repas et de promenades habituels. Les premières nuits, {dog_name} peut être agité : c'est normal. Un vêtement porté par vous dans son panier le rassurera. Explorez le nouveau quartier ensemble progressivement pour créer de nouveaux repères. Les {breed_name} sensibles peuvent avoir besoin de quelques semaines pour s'adapter pleinement.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-002-nouveau-bebe',
    category: 'life_events',
    subcategory: 'famille',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Un bébé arrive : préparer {dog_name}`,
    bodyFr: "L'arrivée d'un bébé est un grand changement pour {dog_name}. Commencez les préparatifs plusieurs mois à l'avance. Habituez {dog_name} aux nouvelles règles (ne plus entrer dans certaines pièces, ne plus monter sur le canapé si c'est votre choix) avant l'arrivée du bébé pour qu'il n'associe pas ces restrictions au nouveau-venu. Familiarisez-le avec les bruits de bébé (pleurs, jouets) en douceur. Avant le retour de la maternité, faites sentir à {dog_name} un vêtement porté par le bébé. Lors de la première rencontre, restez calme et positif. Ne forcez jamais le contact. Continuez à accorder du temps exclusif à {dog_name} chaque jour, même cinq minutes de jeu comptent. Ne laissez jamais {dog_name} seul avec le bébé, quelle que soit sa gentillesse habituelle. Les {breed_name} sont souvent remarquablement doux avec les enfants quand la transition est bien préparée.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-003-divorce-separation',
    category: 'life_events',
    subcategory: 'famille',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Séparation : accompagner {dog_name} dans ce changement`,
    bodyFr: "Lors d'une séparation, {dog_name} présente le forte sollicitation ambiant et le changement de routine. Les chiens sont de véritables éponges émotionnelles. Si {dog_name} passe d'un foyer à l'autre, créez des rituels identiques dans chaque lieu : mêmes horaires de repas, mêmes commandes, mêmes règles. Prévoyez un kit de voyage avec ses affaires familières (couverture, jouet préféré) qui l'accompagne dans ses déplacements. Évitez les tensions ou disputes en présence de {dog_name}. S'il reste dans un seul foyer, maintenez au maximum la routine habituelle. Un changement de comportement (destruction, aboiements, malpropreté) est une réaction normale au forte sollicitation et non de la « vengeance ». Accordez-lui plus de temps de promenade et de jeu pour évacuer le forte sollicitation. Votre propre stabilité émotionnelle l'aidera plus que tout. {dog_name} s'adaptera progressivement à cette nouvelle réalité.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-004-deuil-autre-animal',
    category: 'life_events',
    subcategory: 'deuil',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et le deuil d\'un compagnon animal`,
    bodyFr: "Les chiens peuvent présenteir profondément la perte d'un compagnon animal avec lequel ils partageaient leur quotidien. {dog_name} peut chercher l'autre animal, être plus calme que d'habitude, manger moins, ou au contraire devenir plus collant et demander davantage d'attention. Ces réactions sont normales et témoignent de la richesse de leur vie émotionnelle. Ne changez pas brusquement la routine de {dog_name}, la stabilité est rassurante. Accordez-lui plus de temps et d'attention sans pour autant surcompenser (cela pourrait créer une dépendance). Proposez des activités nouvelles pour stimuler son esprit : nouvelles promenades, jeux d'occupation. Ne précipitez pas l'adoption d'un nouvel animal, laissez à {dog_name} et à vous-même le temps de faire votre deuil. Chaque chien réagit différemment, certains s'adaptent en quelques jours, d'autres en plusieurs semaines.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-005-adoption-second-chien',
    category: 'life_events',
    subcategory: 'famille',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Adopter un second chien quand on a {dog_name}`,
    bodyFr: "L'adoption d'un second chien est une belle aventure mais demande de la préparation. Avant tout, assurez-vous que {dog_name} est bien sociabilisé et à l'aise avec ses congénères. Organisez une première rencontre en terrain neutre (parc, chemin) plutôt que directement chez vous, qui est le territoire de {dog_name}. Promenez-les côte à côte avant de les mettre ensemble. À la maison, prévoyez deux gamelles séparées, deux couchages et suffisamment de jouets pour éviter les conflits de ressources. Les premières semaines, supervisez toutes les interactions. Ne punissez pas les grognements, c'est la communication normale entre chiens. Continuez à accorder des moments individuels à {dog_name} pour qu'il ne se sente pas remplacé. Le temps d'adaptation varie de quelques jours à plusieurs semaines. Patience et observation sont vos meilleurs alliés.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-006-preparation-vacances',
    category: 'life_events',
    subcategory: 'voyage',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [5, 6, 7],
    regionFilter: ['all'],
    titleFr: `Préparer les vacances avec {dog_name}`,
    bodyFr: "Les vacances approchent et il est temps de penser à {dog_name}. Si vous l'emmenez, vérifiez que votre hébergement accepte les chiens et renseignez-vous sur les vétérinaires de garde de la région de destination. Mettez à jour son identification (puce ou tatouage), emportez son carnet de suivi vétérinaire, ses croquettes habituelles (un changement d'alimentation en vacances peut causer des troubles digestifs) et de l'eau de la maison pour la transition. Prévoyez un kit de voyage : laisse, gamelles pliables, sacs à déjections, trousse de premiers secours, couverture familière. Si vous voyagez en voiture, habituez {dog_name} aux trajets longs progressivement. Faites une pause toutes les deux heures pour le laisser se dégourdir et boire. Ne laissez jamais {dog_name} seul dans une voiture, même fenêtres entrouvertes. Les {breed_name} voyagent généralement bien quand ils sont bien préparés.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-007-pension-garde',
    category: 'life_events',
    subcategory: 'garde',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [5, 6, 7, 12],
    regionFilter: ['all'],
    titleFr: `Pension ou garde : préparer {dog_name} à votre absence`,
    bodyFr: "Si {dog_name} doit aller en pension ou être gardé pendant votre absence, préparez-le en douceur. Visitez la pension à l'avance avec {dog_name} pour qu'il découvre les lieux et le personnel. Faites un essai d'une nuit avant un long séjour. Fournissez un vêtement porté par vous (votre odeur le rassure), son jouet préféré et ses croquettes habituelles. Communiquez bien les habitudes de {dog_name} : horaires de repas, commandes utilisées, particularités (réaction d’évitements, allergies alimentaires connues). Lors du départ, restez bref et positif, les adieux déchirants augmentent l'agitation de {dog_name}. Vérifiez que la pension est déclarée, que les locaux sont propres et que les chiens ne sont pas en surpopulation. Demandez si vous pouvez recevoir des nouvelles et des photos pendant votre absence. Au retour, retrouvez {dog_name} calmement, les retrouvailles trop enthousiastes peuvent créer de l'excitation excessive.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-008-changement-emploi-temps',
    category: 'life_events',
    subcategory: 'routine',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Changement d\'emploi du temps : aider {dog_name} à s\'adapter`,
    bodyFr: "Les chiens sont des animaux de routine et {dog_name} a probablement mémorisé vos horaires avec précision. Un changement d'emploi du temps (nouveau travail, nouveaux horaires, reprise après congé) peut être déstabilisant. Procédez par étapes progressives si possible : décalez les horaires de repas et de promenades de quinze minutes par jour jusqu'au nouvel horaire. Si {dog_name} doit rester seul plus longtemps, augmentez progressivement la durée sur une à deux semaines. Prévoyez des jouets d'occupation (Kong fourré, tapis de léchage) pour les moments de solitude. Un passage de dog-walker en milieu de journée peut couper une longue absence. Avant de partir, offrez une promenade active pour que {dog_name} soit plus détendu en votre absence. Au retour, évitez les retrouvailles excessives : entrez calmement, posez vos affaires, puis saluez {dog_name} quand il est calme.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-009-teletravail-retour-bureau',
    category: 'life_events',
    subcategory: 'routine',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Retour au bureau : {dog_name} après le télétravail`,
    bodyFr: "Après des semaines ou des mois de télétravail où {dog_name} a profité de votre présence constante, le retour au bureau peut être un choc. {dog_name} a pris l'habitude de vous avoir près de lui toute la journée et cette séparation soudaine peut déclencher de l'agitation. Préparez la transition progressivement : commencez par vous absenter quelques minutes, puis allongez la durée jour après jour. Créez un rituel de départ simple et identique (« je reviens bientôt ») sans effusions. Installez un coin confortable pour {dog_name} avec un vêtement porté par vous. Les jouets d'occupation comme les tapis de léchage sont d'excellents alliés. Évitez de culpabiliser, {dog_name} s'adaptera. La clé est la progressivité : ne passez pas de zéro absence à huit heures en un jour. Si possible, revenez déjeuner les premières semaines ou faites appel à un promeneur pour couper la journée.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-010-enfant-quitte-maison',
    category: 'life_events',
    subcategory: 'famille',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [8, 9],
    regionFilter: ['all'],
    titleFr: `Quand un enfant quitte la maison : {dog_name} aussi présente le changement`,
    bodyFr: "Le départ d'un enfant pour les études ou la vie adulte ne touche pas que les parents : {dog_name} perd aussi un compagnon de jeu et un membre de sa meute. Il peut chercher l'enfant dans la maison, rester devant sa porte ou sembler plus calme que d'habitude. Ce comportement est une forme de deuil temporaire tout à fait normale. Pour aider {dog_name}, maintenez une routine stable et proposez-lui des activités nouvelles pour remplacer le temps qu'il passait avec l'enfant. Si l'enfant peut appeler en vidéo, certains chiens reconnaissent la voix et l'image de leurs humains favoris. Lors des retours à la maison pour les vacances, les retrouvailles seront d'autant plus joyeuses. Profitez de ce nouveau rythme pour renforcer votre propre lien avec {dog_name} : nouvelles promenades, activités ensemble, moments de complicité.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-011-chien-personnes-agees',
    category: 'life_events',
    subcategory: 'famille',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et les personnes âgées : une belle complicité`,
    bodyFr: "La relation entre {dog_name} et une personne âgée est souvent d'une richesse exceptionnelle. {dog_name} apporte de la compagnie, une raison de sortir marcher, un rythme quotidien structurant et un amour inconditionnel. Si un parent âgé vit avec {dog_name}, quelques adaptations facilitent le quotidien : une gamelle surélevée évite de se baisser, une laisse avec poignée ergonomique assure une meilleure prise, des promenades plus courtes mais plus fréquentes conviennent aux deux. Assurez-vous que le sol n'est pas glissant (un chien qui court peut déséquilibrer). Si la personne âgée a des difficultés, identifiez un réseau d'entraide pour les promenades. {dog_name} s'adapte naturellement au rythme de son humain, les chiens sont remarquables pour cela. La stimulation mentale par le jeu et les caresses profite autant au chien qu'à la personne.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-012-premier-noel',
    category: 'life_events',
    subcategory: 'fetes',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['winter'],
    monthFilter: [12],
    regionFilter: ['all'],
    titleFr: `Le premier Noël de {dog_name}`,
    bodyFr: "Le premier Noël avec {dog_name} est un moment magique mais parsemé de petits dangers à connaître. Le sapin est une attraction irrésistible : fixez-le solidement et évitez les boules en verre et les guirlandes électriques à portée de truffe. Le chocolat des calendriers de l'Avent, l'alcool, les os de volaille cuits et le raisin sont toxiques pour les chiens. L'agitation des fêtes, les invités, les bruits de pétards et les papiers cadeaux froissés peuvent forte sollicitationer {dog_name} : prévoyez un coin calme où il peut se retirer. Si vous offrez un jouet à {dog_name}, choisissez-le adapté à sa taille et à sa mâchoire de {breed_name}. Les rubans et les ficelles de papier cadeau peuvent être avalés. Présentez les invités un par un à {dog_name} et rappelez aux enfants de ne pas le poursuivre. Profitez de ce premier Noël ensemble, il y en aura beaucoup d'autres.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-013-voyager-en-train',
    category: 'life_events',
    subcategory: 'voyage',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Voyager en train avec {dog_name}`,
    bodyFr: "Le train peut être un excellent moyen de transport avec {dog_name}, à condition de bien préparer le voyage. En France, les chiens de moins de six kilos voyagent dans un sac de transport fermé pour un tarif forfaitaire. Les chiens plus grands paient un billet à tarif réduit et doivent être tenus en laisse et muselés. Réservez une place près de la porte pour faciliter les sorties. Faites une longue promenade avant le départ pour que {dog_name} soit détendu. Prévoyez de l'eau, des friandises et un tapis familier. Habituez {dog_name} au bruit et à l'environnement de la gare progressivement avant le jour J. Pendant le trajet, installez-le à vos pieds sur son tapis. Évitez les heures de pointe. Si {dog_name} est agité, des séances de désensibilisation progressive (visiter la gare sans prendre le train) peuvent aider. Certaines lignes TGV sont plus adaptées que les TER bondés.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-014-voyager-en-avion',
    category: 'life_events',
    subcategory: 'voyage',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Prendre l\'avion avec {dog_name}`,
    bodyFr: "Voyager en avion avec {dog_name} demande une préparation minutieuse. Les chiens de moins de huit kilos (sac compris) peuvent généralement voyager en cabine dans un sac de transport homologué placé sous le siège. Les chiens plus grands voyagent en soute dans une caisse de transport rigide aux normes IATA. Contactez la compagnie aérienne bien à l'avance car les places pour animaux sont limitées. Vérifiez les documents nécessaires : carnet de suivi vétérinaire à jour, puce électronique, passeport européen pour les voyages internationaux. Attention aux races brachycéphales (bouledogues, carlins) souvent refusées en soute en raison de leurs difficultés respiratoires. Habituez {dog_name} à sa caisse de transport des semaines avant le voyage. Ne donnez pas de calmant sans avis du vétérinaire. Le jour du vol, une promenade longue avant le départ et un repas léger plusieurs heures avant sont recommandés.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-015-camping',
    category: 'life_events',
    subcategory: 'voyage',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Camping avec {dog_name} : l\'aventure en plein air`,
    bodyFr: "Le camping est une aventure formidable à partager avec {dog_name}. Vérifiez d'abord que le camping accepte les chiens et renseignez-vous sur les règles (laisse obligatoire, zones interdites). Prévoyez un couchage chaud et isolé du sol pour {dog_name}, les nuits en camping sont plus fraîches. Emportez suffisamment de croquettes, de l'eau potable et ses gamelles. Un piquet d'attache avec un câble long permet à {dog_name} de bouger tout en restant en sécurité. Attention aux dangers de la nature : épillets dans les herbes hautes, tiques, serpents et plantes toxiques. Inspectez {dog_name} chaque soir après les balades. La nuit, gardez {dog_name} dans la tente ou à proximité, les animaux sauvages pourraient l'attirer. Les feux de camp sont attirants mais dangereux, gardez {dog_name} à distance. Pensez aux sacs à déjections et respectez l'environnement. {dog_name} adorera toutes ces nouvelles odeurs et explorations.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-016-mariage',
    category: 'life_events',
    subcategory: 'fetes',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [5, 6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `Votre mariage et {dog_name}`,
    bodyFr: "Inclure {dog_name} dans votre mariage est une tendance adorable, mais cela demande de l'organisation. Si {dog_name} participe à la cérémonie, désignez une personne de confiance qui sera entièrement dédiée à sa gestion. Faites des répétitions pour que {dog_name} soit à l'aise avec le lieu et la foule. Un noeud papillon ou un petit bouquet sur le collier rend la chose encore plus mignonne. Cependant, soyez réaliste : si {dog_name} est agité dans les foules ou bruyant, sa présence à la cérémonie seulement (et pas à la réception) peut être un bon compromis. La musique forte, les pétards, les confettis et l'agitation de la fête peuvent être forte sollicitationants. Prévoyez un espace calme de repli avec de l'eau et son panier. Attention au gâteau, aux chocolats et à l'alcool laissés à portée de truffe. Les photos avec {dog_name} sont des souvenirs irremplaçables.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-017-nouveau-partenaire',
    category: 'life_events',
    subcategory: 'famille',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Un nouveau partenaire dans la vie de {dog_name}`,
    bodyFr: "L'arrivée d'un nouveau partenaire dans votre vie est aussi un événement pour {dog_name}. Les premières rencontres doivent être progressives et positives. Organisez la première rencontre en terrain neutre, lors d'une promenade par exemple. Demandez à votre partenaire de ne pas forcer le contact et de laisser {dog_name} venir à lui ou elle. Si {dog_name} est territorial, évitez que le nouveau venu s'installe directement dans « ses » espaces (canapé, lit). Progressivement, votre partenaire peut participer aux activités positives : donner des friandises, tenir la laisse en promenade, jouer. Ne modifiez pas brutalement les règles de {dog_name} (par exemple le laisser monter sur le lit) pour plaire à votre partenaire. La cohérence rassure votre chien. Si {dog_name} grogne ou est méfiant, ne le punissez pas, il exprime un inconfort. Patience et respect mutuel sont les clés d'une belle entente.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-018-depart-retraite',
    category: 'life_events',
    subcategory: 'routine',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Départ en retraite : plus de temps pour {dog_name}`,
    bodyFr: "La retraite est une merveilleuse nouvelle pour {dog_name} : vous serez plus disponible que jamais. Mais attention à ne pas tomber dans le piège de la présence constante. {dog_name} pourrait développer une dépendance excessive et avoir du mal à rester seul si vous vous absentez. Maintenez des moments de séparation réguliers, même brefs. Profitez de cette liberté pour explorer de nouvelles activités ensemble : randonnées plus longues, cours d'éducation canine, visites de nouveaux endroits. La retraite est aussi le moment idéal pour établir de nouvelles routines qui enrichissent votre quotidien à tous les deux. Si vous étiez souvent absent, la transition vers une présence quasi permanente peut aussi déstabiliser {dog_name} au début. Laissez-lui ses moments de calme et de solitude. Ce nouveau chapitre est l'occasion de renforcer votre complicité avec {dog_name} comme jamais auparavant.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-019-retour-vacances',
    category: 'life_events',
    subcategory: 'routine',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer', 'autumn'],
    monthFilter: [8, 9],
    regionFilter: ['all'],
    titleFr: `Retour de vacances : réadapter {dog_name}`,
    bodyFr: "Le retour de vacances est un moment de transition pour {dog_name}, que vous l'ayez emmené ou laissé en garde. Si {dog_name} revient de pension, il peut être fatigué, excité ou légèrement perturbé. Retrouvez vos rituels habituels rapidement : mêmes horaires, mêmes promenades, même routine. Si {dog_name} a voyagé avec vous, le retour à la maison après la liberté des vacances peut sembler ennuyeux. Compensez avec des promenades variées et des jeux stimulants. Si vous reprenez le travail en même temps, la double transition (fin des vacances plus solitude) peut être difficile. Augmentez progressivement les durées d'absence plutôt que de passer d'une présence permanente à une journée complète. {dog_name} peut aussi avoir pris de mauvaises habitudes en vacances (manger à table, dormir dans le lit), remettez les règles en place avec douceur et constance.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-020-visite-famille',
    category: 'life_events',
    subcategory: 'social',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Rendre visite à la famille avec {dog_name}`,
    bodyFr: "Emmener {dog_name} chez de la famille peut être une belle sortie ou une source de forte sollicitation selon la préparation. Avant la visite, renseignez-vous : y a-t-il d'autres animaux, des enfants en bas âge, des personnes qui ont réaction d’évitement des chiens ? Emportez les affaires de {dog_name} (panier, gamelle, jouet) pour qu'il ait ses repères. À l'arrivée, laissez {dog_name} explorer les lieux calmement avant de le présenter à tout le monde. Demandez aux membres de la famille de ne pas tous se précipiter sur lui en même temps. Désignez un espace calme où {dog_name} pourra se retirer s'il en a besoin. Surveillez les enfants qui peuvent être brusques sans le vouloir. Attention à la nourriture laissée à portée de truffe, surtout pendant les repas de famille. Si {dog_name} n'est pas à l'aise avec la foule, une visite courte est préférable à une journée entière forte sollicitationante.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-021-emmenager-appartement',
    category: 'life_events',
    subcategory: 'changement_lieu',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Emménager en appartement avec {dog_name}`,
    bodyFr: "Vivre en appartement avec {dog_name} est tout à fait possible avec les bonnes habitudes. L'espace réduit est compensé par des sorties régulières et enrichissantes. Prévoyez au minimum trois à quatre promenades par jour dont au moins une longue sortie stimulante. Créez un coin douillet pour {dog_name} dans un endroit calme, loin du passage. L'isolation phonique est importante : les bruits de voisins, d'ascenseur et de couloir peuvent être forte sollicitationants au début. Si {dog_name} aboie, travaillez la commande « silence » avec renforcement positif plutôt que la punition. Les voisins apprécieront. Les tapis de léchage et les jouets d'occupation sont vos alliés pour les moments d'attente. Les {breed_name} s'adaptent bien à la vie en appartement quand leurs besoins de dépense physique et mentale sont satisfaits. Un balcon sécurisé peut devenir un petit coin de détente apprécié.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-022-emmenager-maison-jardin',
    category: 'life_events',
    subcategory: 'changement_lieu',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Emménager en maison avec jardin : {dog_name} va adorer`,
    bodyFr: "Un jardin est un vrai bonheur pour {dog_name}, mais attention : un jardin ne remplace pas les promenades. Avant de laisser {dog_name} explorer, vérifiez la clôture sur tout le périmètre. Cherchez les trous, les passages sous le grillage et les endroits où il pourrait sauter. Les {breed_name} peuvent être surprenants en termes d'évasion. Identifiez et retirez les plantes toxiques (laurier-rose, if, muguet, azalée). Sécurisez les produits de jardinage, engrais et anti-limaces qui sont souvent toxiques. Si vous avez une piscine, protégez l'accès. Laissez {dog_name} découvrir le jardin progressivement, en laisse au début pour poser les limites (pas dans les plates-bandes). Le jardin est aussi un lieu de stimulation : cachez des friandises, créez un parcours de jeu. Attention aux fugues : un nouveau territoire donne envie d'explorer au-delà. Renforcez le rappel avant de le laisser en liberté complète.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-023-changement-quartier',
    category: 'life_events',
    subcategory: 'changement_lieu',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Nouveau quartier : créer de nouveaux repères avec {dog_name}`,
    bodyFr: "Après un déménagement, {dog_name} a besoin de créer de nouveaux repères dans son quartier. Les premières promenades sont cruciales : laissez {dog_name} renifler abondamment, c'est sa façon de lire le journal du quartier. Commencez par des itinéraires courts et réguliers pour créer des habitudes, puis élargissez progressivement le territoire. Repérez ensemble les espaces verts, les parcs à chiens et les zones calmes. Identifiez aussi les endroits à éviter (routes passantes, zones de chiens errants). Présentez {dog_name} aux voisins et à leurs chiens progressivement. Les premières rencontres canines dans un nouveau quartier doivent être calmes et en laisse. {dog_name} aura besoin de quelques semaines pour se sentir en confiance dans ce nouvel environnement. Les marquages urinaires seront plus fréquents au début : c'est normal, {dog_name} prend possession de son nouveau territoire.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-024-nouveau-voisin-chien',
    category: 'life_events',
    subcategory: 'social',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Un nouveau voisin a un chien : {dog_name} va avoir un copain ?`,
    bodyFr: "L'arrivée d'un nouveau voisin avec un chien peut être une excellente nouvelle pour {dog_name} ou une source de tension. La première rencontre est déterminante. Proposez au voisin une promenade commune en terrain neutre plutôt qu'une rencontre par-dessus la clôture (ce qui favorise la frustration et la réactivité). Laissez les chiens se renifler calmement en laisse détendue. Si la rencontre est positive, vous pouvez progressivement organiser des jeux ensemble. Si {dog_name} ou le chien voisin est réactif, respectez la distance et ne forcez pas le contact. Un bon voisinage canin passe par le respect mutuel : pas d'aboiements excessifs, des rencontres contrôlées, et une communication ouverte avec le voisin. Avec le temps, {dog_name} et son voisin peuvent devenir d'excellents compagnons de promenade et de jeu.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-025-arrivee-chat',
    category: 'life_events',
    subcategory: 'famille',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Un chat arrive à la maison : préparer {dog_name}`,
    bodyFr: "L'arrivée d'un chat dans un foyer avec {dog_name} demande de la patience et une introduction méthodique. Ne mettez jamais les deux animaux face à face immédiatement. Installez le chat dans une pièce séparée avec ses affaires pendant plusieurs jours. Échangez des couvertures entre les deux pour qu'ils s'habituent à l'odeur de l'autre. Après quelques jours, laissez-les se voir à travers une porte entrouverte ou une barrière. {dog_name} doit être calme et en laisse lors des premières interactions visuelles. Récompensez abondamment le calme de {dog_name} en présence du chat. Ne laissez jamais les deux animaux seuls sans supervision tant que la cohabitation n'est pas établie. Le chat doit toujours avoir un accès en hauteur pour se réfugier. La litière doit être inaccessible à {dog_name}. Certaines races comme {breed_name} cohabitent très bien avec les chats quand l'introduction est bien faite.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-026-adoption-refuge',
    category: 'life_events',
    subcategory: 'adoption',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Adopter {dog_name} depuis un refuge : les clés de la réussite`,
    bodyFr: "Adopter un chien en refuge est un geste magnifique. {dog_name} a peut-être vécu des expériences difficiles et a besoin de temps pour s'adapter. Les premières semaines, ne surchargez pas {dog_name} de stimulations : laissez-le découvrir son nouvel environnement à son rythme. La règle des « trois » est un bon repère : trois jours pour décompresser, trois semaines pour comprendre la routine, trois mois pour se sentir vraiment chez lui. Soyez patient avec les premiers comportements : malpropreté, destructions, agitation de séparation sont courants et temporaires. Établissez une routine claire et prévisible, c'est le meilleur cadeau que vous puissiez faire à {dog_name}. Évitez les invitations nombreuses et les sorties en foule les premières semaines. Un éducateur canin spécialisé dans les chiens de refuge peut être un allié précieux. L'amour et la confiance se construisent chaque jour.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 8,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-027-chien-ecole-enfants',
    category: 'life_events',
    subcategory: 'routine',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['autumn'],
    monthFilter: [9],
    regionFilter: ['all'],
    titleFr: `Rentrée scolaire : {dog_name} et la nouvelle routine`,
    bodyFr: "La rentrée des classes bouleverse la routine de {dog_name} qui a profité des enfants tout l'été. Soudain, la maison se vide et le silence s'installe. Préparez {dog_name} progressivement en réintroduisant les horaires scolaires une semaine avant la rentrée. Si les enfants promenaient {dog_name} pendant les vacances, assurez-vous de compenser ces sorties. Le matin peut devenir forte sollicitationant avec l'agitation du départ : gardez {dog_name} dans un espace calme pendant cette période. Le moment clé est la sortie d'école : les retrouvailles avec les enfants peuvent être joyeuses mais chaotiques. Apprenez aux enfants à saluer {dog_name} calmement plutôt que de lui sauter dessus. Les devoirs du soir sont un bon moment de compagnie paisible : {dog_name} aimera se coucher aux pieds de votre enfant. Cette nouvelle routine deviendra vite la normalité pour toute la famille.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-028-fetes-famille',
    category: 'life_events',
    subcategory: 'fetes',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [12, 1, 7],
    regionFilter: ['all'],
    titleFr: `Fêtes de famille et {dog_name} : mode d\'emploi`,
    bodyFr: "Les fêtes de famille sont synonymes d'agitation, de bruits, de nourriture partout et de personnes inhabituelles pour {dog_name}. Préparez un espace de repli calme où {dog_name} pourra se retirer quand il en aura besoin. Informez vos invités des règles à respecter : ne pas donner de nourriture à table, ne pas exciter le chien, respecter son espace quand il se repose. Attention particulière avec les enfants invités qui ne connaissent peut-être pas les chiens. La table de fête regorge de dangers : os de volaille, chocolat, raisin, alcool, petits objets décoratifs. Fermez la poubelle après le repas. Les pétards et feux d'artifice peuvent terroriser {dog_name} : gardez-le à l'intérieur, fenêtres fermées, avec une musique douce en fond sonore. Si {dog_name} est sociable et adore les invités, contrôlez quand même son excitation pour éviter les sauts et les bousculades.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-029-travaux-maison',
    category: 'life_events',
    subcategory: 'changement_lieu',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Travaux à la maison : protéger {dog_name}`,
    bodyFr: "Les travaux dans la maison sont une source de forte sollicitation et de danger pour {dog_name}. Le bruit des perceuses, des marteaux et des machines est bien plus intense pour ses oreilles sensibles. Les poussières de peinture, de plâtre, les solvants et les colles peuvent être nocifs. Pendant les travaux, isolez {dog_name} dans une pièce calme éloignée du chantier avec ses affaires, de l'eau et un jouet d'occupation. Si les travaux sont importants, confiez-le à une personne de confiance pour la journée. Le soir, inspectez les zones de travaux avant de laisser {dog_name} circuler : clous, vis, morceaux de bois, fils électriques dénudés sont autant de dangers. Les peintures fraîches et les sols traités chimiquement doivent être totalement secs et ventilés avant que {dog_name} y accède. Si des ouvriers entrent et sortent, sécurisez les accès pour éviter une fugue.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-030-depart-weekend',
    category: 'life_events',
    subcategory: 'garde',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Partir en week-end : {dog_name} vient ou reste ?`,
    bodyFr: "Un week-end approche et la question se pose : emmener {dog_name} ou le confier ? Si la destination le permet et que {dog_name} voyage bien, emmenez-le : deux jours d'aventure ensemble renforcent votre lien. Vérifiez que l'hébergement accepte les chiens et emportez le nécessaire : croquettes mesurées, gamelle, laisse, sacs à déjections, un jouet et son couchage. Si {dog_name} reste à la maison, une visite de la personne qui le garde avant votre départ permet de créer un premier lien. Laissez des consignes détaillées : horaires des repas, quantités, numéro du vétérinaire, habitudes de promenade. Un vêtement porté par vous dans le panier de {dog_name} le rassurera. Deux jours passent vite pour {dog_name} si sa routine est maintenue. Au retour, retrouvez-le avec enthousiasme mais sans excès, la meilleure chose est de reprendre le quotidien normalement.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-031-garde-par-ami',
    category: 'life_events',
    subcategory: 'garde',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Confier {dog_name} à un ami : les bonnes pratiques`,
    bodyFr: "Confier {dog_name} à un ami est souvent plus rassurant qu'une pension, mais il faut bien préparer l'échange. Avant votre départ, organisez une visite chez l'ami pour que {dog_name} se familiarise avec les lieux et la personne. Préparez un kit complet : nourriture mesurée pour chaque jour, gamelles, laisse, jouets, couchage, carnet de suivi vétérinaire, sacs à déjections. Rédigez une fiche pratique avec les horaires de repas, la quantité de nourriture, les commandes que {dog_name} connaît, ses habitudes de promenade, les aliments interdits et les numéros d'urgence. Prévenez votre ami des particularités de {dog_name} : a-t-il réaction d’évitement de l'orage, tire-t-il en laisse, est-il propre la nuit ? Si l'ami a des enfants ou d'autres animaux, préparez les présentations. Proposez à votre ami de vous envoyer des photos et nouvelles, cela vous rassurera tous les deux.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-032-dog-sitter-premiere-fois',
    category: 'life_events',
    subcategory: 'garde',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Première fois avec un dog-sitter pour {dog_name}`,
    bodyFr: "Faire appel à un dog-sitter pour la première fois est un grand pas. Commencez par une rencontre préalable entre le dog-sitter et {dog_name} : cette première impression est essentielle. Observez comment le dog-sitter interagit avec {dog_name} et comment votre chien réagit. Un bon dog-sitter pose des questions sur les habitudes, la suivi vétérinaire et le caractère de {dog_name}. Vérifiez les références et l'expérience, surtout avec les {breed_name}. Avant la première garde, faites une session test de quelques heures. Préparez des instructions écrites détaillées et laissez vos coordonnées ainsi que celles du vétérinaire. Demandez au dog-sitter d'envoyer des photos et des nouvelles pendant la garde. Si le dog-sitter vient chez vous, c'est souvent moins perturbant pour {dog_name} que d'aller ailleurs. La confiance se construit progressivement, ne confiez pas {dog_name} une semaine entière dès le premier essai.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-033-visite-veterinaire-annuelle',
    category: 'life_events',
    subcategory: 'sante',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La visite vétérinaire annuelle de {dog_name}`,
    bodyFr: "La visite annuelle chez le vétérinaire est un rendez-vous essentiel pour {dog_name}. Pour rendre cette expérience plus agréable, habituez votre chien à être manipulé régulièrement : touchez ses pattes, ouvrez sa gueule, regardez ses oreilles. Avant la visite, promenez {dog_name} pour qu'il soit plus détendu. Emportez des friandises pour récompenser son calme dans la salle d'attente. Si {dog_name} est agité, certaines cliniques proposent des créneaux calmes ou des entrées séparées. Préparez une liste de vos observations : changement de comportement, d'appétit, de poids. Notez les questions que vous souhaitez poser. Le vétérinaire vérifiera le poids, les dents, les yeux, les oreilles, le coeur et fera les rappels de vaccination nécessaires. C'est aussi le moment de parler de la prévention antiparasitaire adaptée à {breed_name}. Cette visite est un investissement dans le bien-être de {dog_name}.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-034-vermifuge-rappels',
    category: 'life_events',
    subcategory: 'sante',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Vermifuge et rappels : le calendrier de {dog_name}`,
    bodyFr: "La vermifugation régulière de {dog_name} est importante pour sa suivi vétérinaire et celle de votre famille. Un chien adulte doit généralement être vermifugé deux à quatre fois par an selon son mode de vie. Un chien qui mange des proies, se roule dans la terre ou vit avec des enfants en bas âge aura besoin de vermifugations plus fréquentes. Le produit et la fréquence doivent être adaptés au poids et au mode de vie de {dog_name}, demandez conseil à votre vétérinaire. Pour vous souvenir des dates, créez un rappel dans votre téléphone ou utilisez l'application EMOPET. Les antiparasitaires externes (puces et tiques) suivent un calendrier différent, généralement mensuel pendant la belle saison. Certains produits combinent les deux protections. Le carnet de suivi vétérinaire de {dog_name} permet de suivre toutes ces dates. Une protection régulière est bien plus simple qu'une infestation à gérer.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-035-assurance-sante',
    category: 'life_events',
    subcategory: 'administratif',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `L\'assurance suivi vétérinaire pour {dog_name} : utile ou pas ?`,
    bodyFr: "L'assurance suivi vétérinaire pour {dog_name} est un sujet qui mérite réflexion. Les frais vétérinaires peuvent être élevés, surtout en cas d'urgence ou d'intervention chirurgicale. Une assurance peut couvrir une partie de ces frais en échange d'une cotisation mensuelle. Comparez les offres en regardant : le pourcentage de remboursement, le plafond annuel, le délai de carence, les exclusions (certaines races ou conditions préexistantes), les franchises et l'âge limite de souscription. Plus {dog_name} est jeune à la souscription, plus les tarifs sont avantageux et les exclusions réduites. Les formules varient de la simple couverture accident à la couverture complète incluant la prévention. Gardez les factures de votre vétérinaire même sans assurance, elles peuvent servir de justificatif. Certaines mutuelles proposent des formules spécifiques pour les {breed_name}. Faites le calcul sur la durée de vie moyenne de votre chien.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-036-identification-puce',
    category: 'life_events',
    subcategory: 'administratif',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Identification et puce de {dog_name} : obligation légale`,
    bodyFr: "En France, l'identification de {dog_name} par puce électronique ou tatouage est obligatoire. C'est aussi le moyen le plus sûr de retrouver votre chien en cas de fugue ou de perte. La puce électronique est un petit dispositif injecté sous la peau, généralement entre les omoplates, par le vétérinaire. Elle contient un numéro unique relié au fichier national I-CAD qui enregistre vos coordonnées. Vérifiez que vos informations sont à jour : si vous avez déménagé, changé de numéro de téléphone ou de nom, mettez à jour votre dossier sur le site I-CAD. C'est gratuit et peut faire la différence entre retrouver {dog_name} en quelques heures ou le perdre définitivement. Lors des promenades, {dog_name} doit porter un collier avec une médaille indiquant votre numéro de téléphone. Cette double identification est la meilleure protection contre la perte de votre compagnon.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-037-chien-perdu',
    category: 'life_events',
    subcategory: 'urgence',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} est perdu : que faire immédiatement`,
    bodyFr: "Si {dog_name} disparaît, agissez rapidement et méthodiquement. Dans les premières heures, parcourez le quartier en appelant {dog_name} et en secouant un sachet de friandises ou son jouet sonore préféré. Vérifiez les cachettes habituelles et les endroits qu'il aime. Prévenez immédiatement vos voisins et les promeneurs du secteur. Déclarez la perte sur le fichier I-CAD (si {dog_name} est pucé), à la fourrière, aux vétérinaires du secteur, à la police municipale et à la gendarmerie. Publiez une annonce avec photo récente et description détaillée de {dog_name} sur les réseaux sociaux locaux et les sites dédiés (Pet Alert, Filalapat). Laissez un vêtement porté par vous et la gamelle de {dog_name} devant votre porte ou à l'endroit où il a disparu. Ne perdez pas espoir, des chiens sont retrouvés après des semaines. Plus les recherches sont rapides et larges, plus les chances de retrouver {dog_name} sont élevées.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 8,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-038-chien-trouve',
    category: 'life_events',
    subcategory: 'communaute',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Vous avez trouvé un chien : les bons réflexes`,
    bodyFr: "Si vous trouvez un chien errant, approchez-le calmement et sans gestes brusques. Un chien perdu peut être effrayé et réagir de manière imprévisible. Vérifiez s'il porte un collier avec une médaille d'identification. Si oui, contactez le propriétaire. Sinon, emmenez-le chez le vétérinaire le plus proche ou à la mairie pour faire lire la puce électronique. En France, vous êtes légalement tenu de signaler un chien trouvé à la mairie ou à la fourrière dans les 48 heures. Publiez une annonce sur les réseaux sociaux locaux et les groupes « animaux perdus ». Prenez une photo claire du chien. Si vous gardez le chien temporairement, gardez-le séparé de {dog_name} et de vos animaux jusqu'à une vérification vétérinaire. Quelque part, un propriétaire cherche désespérément son compagnon, votre geste peut réunir une famille.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-039-changement-alimentation',
    category: 'life_events',
    subcategory: 'sante',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Changer l\'alimentation de {dog_name} : la transition en douceur`,
    bodyFr: "Si vous souhaitez modifier l'alimentation de {dog_name}, que ce soit un changement de marque, un passage aux croquettes ou à la ration ménagère, la transition doit être progressive. Le système digestif du chien est sensible aux changements brutaux. La transition idéale se fait sur sept à dix jours : commencez par mélanger 75 pour cent de l'ancienne nourriture avec 25 pour cent de la nouvelle. Augmentez la proportion de la nouvelle nourriture de 25 pour cent tous les deux à trois jours. Observez les selles de {dog_name} pendant la transition : elles doivent rester bien moulées. Si des troubles digestifs apparaissent, ralentissez la transition. Les besoins nutritionnels varient selon la taille, l'âge et l'activité de {breed_name}. L'eau fraîche doit toujours être disponible. Évitez de changer d'alimentation en période de forte sollicitation (déménagement, voyage). Si vous avez des doutes, demandez conseil à votre vétérinaire.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-040-premier-hiver-chiot',
    category: 'life_events',
    subcategory: 'saison',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: 2,
    ageMaxMonths: 12,
    seasonFilter: ['winter'],
    monthFilter: [11, 12, 1, 2],
    regionFilter: ['all'],
    titleFr: `Le premier hiver de {dog_name}`,
    bodyFr: "Le premier hiver est une grande découverte pour {dog_name}. Le froid, la pluie, peut-être même la neige : tout est nouveau. Les chiots perdent de la chaleur corporelle plus vite que les adultes, surveillez les signes de froid (tremblements, pattes levées). Adaptez la durée des promenades : plus courtes mais plus fréquentes par grand froid. Après les sorties, séchez bien {dog_name}, notamment le ventre et les pattes. Le sel de déneigement peut irriter les coussinets : rincez-les à l'eau tiède après les promenades en ville. Pour les {breed_name} à poil court ou de petite taille, un manteau peut être utile quand il fait très froid. Veillez à ce que son couchage soit isolé du sol froid (pas directement sur le carrelage). L'eau de la gamelle doit être à température ambiante. La neige est souvent une source de enthousiasme incroyable pour les chiots, laissez {dog_name} la découvrir en s'amusant.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-041-premier-ete-chiot',
    category: 'life_events',
    subcategory: 'saison',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: 2,
    ageMaxMonths: 12,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `Le premier été de {dog_name}`,
    bodyFr: "Le premier été de {dog_name} est rempli de nouvelles sensations mais aussi de précautions à prendre. Les chiots sont plus sensibles à la chaleur car leur système de régulation thermique n'est pas encore mature. Promenez {dog_name} tôt le matin et tard le soir pour éviter les heures chaudes. Vérifiez la température du sol avant chaque sortie : si c'est trop chaud pour le dos de votre main, c'est trop chaud pour ses coussinets. Assurez-vous que {dog_name} ait toujours accès à de l'eau fraîche et à un coin ombragé. Vous pouvez lui proposer un tapis rafraîchissant ou des glaçons dans sa gamelle. Ne laissez jamais {dog_name} dans une voiture, même quelques minutes, même fenêtres entrouvertes. Attention aux épillets dans les herbes sèches, vérifiez les oreilles, les yeux et les pattes après chaque promenade. L'été est aussi le moment des tiques et des puces : pensez à la protection antiparasitaire.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'push',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: true,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-042-chien-vieillit',
    category: 'life_events',
    subcategory: 'senior',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: 84,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} vieillit : accompagner la transition`,
    bodyFr: "Quand {dog_name} vieillit, les changements sont souvent progressifs. Vous remarquerez peut-être un rythme plus lent en promenade, une difficulté à monter les escaliers, des siestes plus longues ou un blanchissement du museau. Ces évolutions sont naturelles. Adaptez les promenades : préférez des sorties plus courtes mais maintenues régulièrement, l'exercice modéré reste bénéfique. Le confort de son couchage devient crucial : un matelas orthopédique soulage les articulations. Si {dog_name} a du mal à se relever, placez son panier au ras du sol. Adaptez la hauteur de sa gamelle. La patience est de mise : {dog_name} peut être plus lent à répondre à vos appels, sa vue et son ouïe peuvent diminuer. Les {breed_name} vieillissent selon un rythme propre à leur taille. Les visites vétérinaires deux fois par an sont recommandées pour les chiens seniors. Profitez de chaque instant de complicité avec votre fidèle compagnon.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-043-deces-famille',
    category: 'life_events',
    subcategory: 'deuil',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et un décès dans la famille`,
    bodyFr: "Les chiens perçoivent le deuil de leurs humains avec une sensibilité remarquable. {dog_name} peut réagir à votre en retraitsse en étant plus collant, en refusant de manger, en cherchant la personne disparue ou en restant devant sa chambre. Ces comportements témoignent de l'attachement profond de votre chien. Ne repoussez pas {dog_name} dans ces moments difficiles, sa présence est souvent un réconfort irremplaçable. Maintenez sa routine autant que possible, la promenade quotidienne peut devenir un moment de respiration pour vous aussi. Si la personne décédée était le principal référent de {dog_name}, la transition sera plus longue. Entourez {dog_name} d'attention sans le surprotéger. Les chiens vivent le moment présent et s'adaptent progressivement. Votre compagnon peut devenir un soutien émotionnel précieux pendant cette période. Prenez soin de vous aussi, {dog_name} a besoin que vous alliez bien.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-044-absence-prolongee',
    category: 'life_events',
    subcategory: 'garde',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Préparer {dog_name} à une absence prolongée`,
    bodyFr: "Si vous devez vous absenter plusieurs semaines (voyage, hospitalisation, déplacement professionnel), la préparation est essentielle pour le bien-être de {dog_name}. Idéalement, confiez-le à une personne qu'il connaît déjà. Si ce n'est pas possible, organisez plusieurs rencontres préalables entre {dog_name} et la personne ou la pension choisie. Préparez un document complet avec toutes les informations sur {dog_name} : routine quotidienne, alimentation, commandes, réaction d’évitements, jeux préférés, numéro du vétérinaire et copie du carnet de suivi vétérinaire. Laissez suffisamment de nourriture et de produits habituels. Un vêtement imprégné de votre odeur sera un réconfort pour {dog_name}. Si possible, faites un appel vidéo, certains chiens reconnaissent la voix de leur humain. Préparez-vous aussi émotionnellement : {dog_name} s'adaptera mieux que vous ne le pensez. Au retour, les retrouvailles seront d'autant plus belles.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-045-chien-hotel',
    category: 'life_events',
    subcategory: 'voyage',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} à l\'hôtel : mode d\'emploi`,
    bodyFr: "De plus en plus d'hôtels acceptent les chiens, mais il y a des règles à respecter pour que l'expérience soit agréable. Vérifiez la politique de l'hôtel à la réservation : certains imposent un supplément ou une taille maximale. Emportez le couchage de {dog_name}, ses gamelles et de quoi le nourrir. Couvrez le lit d'un drap si {dog_name} a l'habitude de monter dessus. Ne laissez jamais {dog_name} seul dans la chambre : un environnement inconnu avec des bruits de couloir peut déclencher de l'agitation et des aboiements qui dérangeront les autres clients. Promenez {dog_name} dans les espaces verts de l'hôtel avant de monter en chambre pour qu'il se soulage. Ramassez toujours les déjections. Gardez la chambre propre en essuyant les pattes de {dog_name} avant d'entrer. Si vous dînez au restaurant de l'hôtel, renseignez-vous sur la possibilité d'emmener {dog_name} ou de dîner en terrasse.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-046-chien-restaurant',
    category: 'life_events',
    subcategory: 'social',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Emmener {dog_name} au restaurant`,
    bodyFr: "Déjeuner en terrasse avec {dog_name} est un plaisir simple mais qui demande un minimum de préparation. Avant d'entrer, assurez-vous que le restaurant accepte les chiens. Promenez {dog_name} avant pour qu'il soit détendu. Choisissez une table calme, de préférence en bout de terrasse, loin du passage. Emportez un tapis ou une couverture pour que {dog_name} sache où se coucher. Un jouet d'occupation silencieux (Kong, bois d'olivier) l'occupera pendant le repas. Gardez la laisse courte pour qu'il ne gêne pas le service. Ne lui donnez pas de nourriture depuis la table, cela encourage la mendicité. Apportez sa gamelle d'eau. Si {dog_name} est agité ou aboie, il n'est peut-être pas encore prêt pour cette expérience : commencez par des pauses café courtes. La clé est un chien calme qui se couche et attend patiemment. Récompensez ce calme pour l'encourager.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-047-plage-premiere-fois',
    category: 'life_events',
    subcategory: 'sortie',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8, 9],
    regionFilter: ['all'],
    titleFr: `La plage pour la première fois avec {dog_name}`,
    bodyFr: "La découverte de la plage est un moment extraordinaire pour {dog_name}. Vérifiez d'abord que la plage autorise les chiens (souvent hors saison ou sur des zones dédiées). Apportez de l'eau douce en quantité : l'eau de mer est nocive si {dog_name} en boit trop. Le sable chaud peut brûler les coussinets, testez avec le dos de votre main. Rincez {dog_name} à l'eau douce après la baignade pour éliminer le sel qui irrite la peau. Si {dog_name} découvre les vagues, laissez-le y aller à son rythme sans le forcer. Surveillez-le en permanence, les courants peuvent être dangereux même pour un bon nageur. Attention aux méduses échouées et aux hameçons sur la plage. Prévoyez de l'ombre avec un parasol ou une tente. Le sable peut s'infiltrer dans les oreilles, inspectez-les après la sortie. Un gilet de sauvetage est recommandé pour les races qui nagent difficilement.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-048-montagne-premiere-fois',
    category: 'life_events',
    subcategory: 'sortie',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: 12,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [5, 6, 7, 8, 9, 10],
    regionFilter: ['all'],
    titleFr: `La montagne pour la première fois avec {dog_name}`,
    bodyFr: "La montagne est un terrain de jeu fantastique pour {dog_name}, mais demande une préparation adaptée. Choisissez un sentier adapté au niveau de forme de {dog_name} et progressez graduellement en difficulté. Les {breed_name} ont leur propre endurance, ne les surestimez pas lors de la première sortie. Emportez suffisamment d'eau pour vous deux et une gamelle pliable. En altitude, le soleil est plus fort : protégez la truffe de {dog_name} avec un baume solaire adapté. Les coussinets peuvent souffrir sur les pierres coupantes, inspectez-les régulièrement. Attention aux vipères sur les sentiers ensoleillés, aux troupeaux gardés par des patous (ne vous approchez pas) et aux précipices. Tenez {dog_name} en laisse dans les réserves naturelles et près des troupeaux. Prévoyez des pauses régulières et observez les signes de fatigue. La descente est souvent plus éprouvante que la montée pour les articulations. La montagne crée des souvenirs inoubliables.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: true,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-049-ville-premiere-fois-chien-rural',
    category: 'life_events',
    subcategory: 'sortie',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La ville pour la première fois : {dog_name} le campagnard`,
    bodyFr: "Si {dog_name} a grandi à la campagne, la ville peut être une expérience très stimulante voire forte sollicitationante. Les bruits de circulation, les foules, les vélos, les trottinettes et les klaxons sont autant de stimuli inconnus. Préparez cette première sortie en choisissant un quartier calme et un horaire tranquille. Gardez {dog_name} en laisse courte et restez détendu, votre attitude le rassure. Récompensez le calme et l'attention de {dog_name} avec des friandises. Commencez par de courtes visites et augmentez la durée progressivement. Les escalators, les passages piétons et les portes automatiques peuvent surprendre. Les trottoirs sont durs pour les coussinets habitués à la terre et à l'herbe. En été, le bitume est brûlant. Le bruit des travaux, des sirènes et des métros est amplifié pour les oreilles sensibles de {dog_name}. Patience et progressivité sont les maîtres-mots pour un {breed_name} découvrant la ville.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-050-campagne-premiere-fois-chien-urbain',
    category: 'life_events',
    subcategory: 'sortie',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La campagne pour la première fois : {dog_name} le citadin`,
    bodyFr: "Pour un chien de ville, la campagne est un festival de nouvelles odeurs, de bruits et de libertés. {dog_name} va être submergé de stimulations : herbes hautes, animaux de ferme, ruisseaux, espaces immenses. Avant de lâcher {dog_name} en pleine nature, assurez-vous que son rappel est fiable. Un chien citadin peut être tenté de poursuivre des poules, des lapins ou des moutons, ce qui peut avoir des conséquences graves (un agriculteur a le droit de protéger son troupeau). Gardez la laisse ou une longe au début. Attention aux dangers ruraux : barbelés, fossés, machines agricoles, pesticides, mares stagnantes et animaux sauvages. Les épillets dans les champs sont un vrai danger pour les oreilles et les pattes. L'herbe fraîche peut provoquer des troubles digestifs si {dog_name} en mange trop. Profitez de ces grands espaces pour courir et jouer ensemble, c'est un bonheur partagé incomparable.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-051-chien-jardinage',
    category: 'life_events',
    subcategory: 'quotidien',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['spring', 'summer'],
    monthFilter: [3, 4, 5, 6, 7, 8],
    regionFilter: ['all'],
    titleFr: `{dog_name} et le jardinage : cohabitation au jardin`,
    bodyFr: "Jardiner avec {dog_name} peut être un plaisir partagé si quelques précautions sont prises. Votre chien adorera vous accompagner dehors, mais certains produits de jardinage sont dangereux : engrais, désherbants, anti-limaces à base de métaldéhyde, insecticides. Rangez tout hors de portée et respectez les délais avant de laisser {dog_name} accéder aux zones traitées. Certaines plantes courantes sont toxiques : laurier-rose, muguet, if, digitale, azalée. Si {dog_name} a tendance à déterrer vos plantations, créez-lui un coin de terre dédié où il peut creuser à volonté. Protégez vos plates-bandes avec des bordures. L'arrosage peut devenir un jeu amusant pour {dog_name}, surveillez qu'il ne boive pas l'eau stagnante des coupelles et des seaux. Le compost est souvent irrésistible mais peut être dangereux. Si {dog_name} mange de la terre, c'est souvent anodin mais surveillez les quantités.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-052-adopter-chien-senior',
    category: 'life_events',
    subcategory: 'adoption',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: 84,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Adopter un chien senior : {dog_name} mérite une seconde chance`,
    bodyFr: "Adopter un chien senior est un acte d'amour extraordinaire. {dog_name} arrive avec un passé et un caractère déjà formé, ce qui a aussi ses avantages : fini les destructions de chiot, les besoins de sorties toutes les deux heures et l'éducation de base. Un chien senior est souvent calme, reconnaissant et s'adapte avec une grâce qui touche le coeur. Patience pour la période d'adaptation : {dog_name} peut mettre plus de temps à faire confiance, surtout s'il a vécu des abandons. Prévoyez une visite vétérinaire complète pour connaître son état général. Adaptez votre maison : couchage douillet au ras du sol, gamelles surélevées si nécessaire, sols antidérapants. Les promenades seront peut-être plus courtes mais tout aussi précieuses. Chaque jour avec {dog_name} est un cadeau réciproque. Les chiens seniors ont beaucoup d'amour à offrir et savent apprécier le confort d'un foyer comme personne.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: true,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-053-cohabitation-deux-males',
    category: 'life_events',
    subcategory: 'multi_chien',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Cohabitation de deux mâles : {dog_name} et son nouveau compagnon`,
    bodyFr: "La cohabitation entre deux mâles est tout à fait possible mais demande de la vigilance, surtout au début. Lors de la première rencontre, choisissez un terrain neutre et laissez les deux chiens se renifler librement en laisse détendue. À la maison, respectez la hiérarchie naturelle qui va s'établir : ne forcez pas l'égalité, les chiens ont besoin de savoir qui a la priorité. Nourrissez-les séparément pour éviter les conflits autour de la gamelle. Offrez à chacun son propre couchage et ses propres jouets. Les grognements légers sont une communication normale, n'intervenez pas systématiquement. En revanche, une tension qui monte (regard fixe, poils hérissés, grondement sourd) doit être désamorcée calmement en redirigeant l'attention. La stérilisation peut réduire les tensions hormonales. Avec {dog_name} et son nouveau compagnon, la patience des premières semaines sera récompensée par une belle complicité.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-054-cohabitation-male-femelle',
    category: 'life_events',
    subcategory: 'multi_chien',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Cohabitation mâle-femelle : {dog_name} et sa nouvelle compagne`,
    bodyFr: "La cohabitation entre un mâle et une femelle est généralement plus harmonieuse, mais il y a un point crucial à anticiper : les chaleurs. Si la femelle n'est pas stérilisée, ses cycles (environ tous les six mois) rendront le mâle très agité, refusant parfois de manger et pleurant sans cesse. Vous devrez les séparer physiquement pendant cette période, ce qui peut être forte sollicitationant pour les deux. La stérilisation de l'un ou des deux simplifie grandement la vie quotidienne et évite les portées non désirées. En dehors de cette question, l'introduction suit les mêmes principes que toute cohabitation : rencontre en terrain neutre, ressources séparées, supervision des premiers jours. {dog_name} et sa compagne formeront probablement un duo complice rapidement. Les jeux entre un mâle et une femelle sont souvent plus fluides et moins compétitifs. Préparez-vous à deux fois plus de câlins et d'amour.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-055-premier-rdv-educateur',
    category: 'life_events',
    subcategory: 'education',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Premier rendez-vous avec un éducateur canin pour {dog_name}`,
    bodyFr: "Le premier rendez-vous avec un éducateur canin est une étape formidable pour vous et {dog_name}. Choisissez un éducateur qui utilise des méthodes positives et respectueuses (renforcement positif, pas de collier étrangleur ni de domination physique). Le premier rendez-vous est souvent un bilan : l'éducateur observe {dog_name}, évalue son caractère, identifie vos attentes et propose un programme adapté. Préparez une liste de ce que vous aimeriez travailler : le rappel, la marche en laisse, la propreté, un comportement spécifique. Soyez honnête sur les difficultés rencontrées, l'éducateur est là pour vous aider. N'attendez pas de miracles dès la première séance, l'éducation se construit dans la durée et la constance. Les {breed_name} répondent très bien à l'éducation positive quand elle est régulière. Impliquez toute la famille dans les exercices pour que les règles soient cohérentes.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: true,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-056-premier-cours-collectif',
    category: 'life_events',
    subcategory: 'education',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Premier cours collectif pour {dog_name}`,
    bodyFr: "Les cours collectifs sont une excellente opportunité de socialisation pour {dog_name}. Il apprendra à se concentrer sur vous malgré la présence d'autres chiens, ce qui est une compétence précieuse au quotidien. Avant le premier cours, assurez-vous que {dog_name} maîtrise les bases (assis, pas bouger) et qu'il est à l'aise avec les autres chiens. Arrivez quelques minutes en avance pour que {dog_name} explore le lieu calmement. Emportez beaucoup de friandises appétissantes et son jouet préféré. Ne comparez pas {dog_name} aux autres chiens du groupe : chacun progresse à son rythme. Si {dog_name} est surexcité ou agité, ne le forcez pas : un éducateur bienveillant adaptera les exercices. Les cours collectifs sont aussi l'occasion de rencontrer d'autres propriétaires passionnés et de créer des liens. Après le cours, félicitez {dog_name} et laissez-le se reposer, la concentration en groupe est fatigante.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-057-musique-forte-concert',
    category: 'life_events',
    subcategory: 'forte sollicitation',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: ['summer'],
    monthFilter: [6, 7, 8],
    regionFilter: ['all'],
    titleFr: `{dog_name} et la musique forte : protéger ses oreilles`,
    bodyFr: "L'ouïe de {dog_name} est bien plus sensible que la nôtre : il perçoit des sons à des fréquences et des volumes que nous ne captons pas. Les fêtes de village, les concerts en plein air, les feux d'artifice et même la musique forte à la maison peuvent être une véritable agression sonore. Si un événement bruyant a lieu près de chez vous, gardez {dog_name} à l'intérieur, fenêtres fermées, avec une musique calme ou le bruit blanc de la télévision en fond sonore. Créez un espace refuge confortable où il peut se cacher s'il le souhaite. N'emmenez jamais {dog_name} à un concert ou un festival, même en plein air. Si {dog_name} tremble, halète ou essaie de fuir, restez calme et rassurant sans le surprotéger (cela validerait sa réaction d’évitement). Des jouets d'occupation et des friandises peuvent aider à rediriger son attention. Anticipez les événements bruyants de votre commune.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: true,
  },
  {
    id: 'le-058-fetes-foraines',
    category: 'life_events',
    subcategory: 'forte sollicitation',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et les fêtes foraines : précautions`,
    bodyFr: "Les fêtes foraines combinent tout ce qui peut forte sollicitationer {dog_name} : foule dense, bruits forts (musique, cris, manèges), odeurs de nourriture partout, lumières clignotantes et sol parsemé de déchets tentants. La règle d'or est simple : n'emmenez pas {dog_name} à la fête foraine. Même un chien sociable et calme peut être submergé par cette accumulation de stimulations. Si la fête foraine est installée près de chez vous, les bruits peuvent perturber {dog_name} même à la maison. Fermez les fenêtres, mettez une musique apaisante et proposez un jouet d'occupation. Si vous devez passer à proximité en promenade, faites un détour par un chemin plus calme. En cas de passage obligé, gardez {dog_name} en laisse courte, avancez d'un pas décidé et rassurant, et récompensez son calme. Les pétards et les feux d'artifice de clôture sont souvent le pire moment : anticipez en gardant {dog_name} en sécurité à l'intérieur.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 5,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-059-passer-un-a-deux-chiens',
    category: 'life_events',
    subcategory: 'multi_chien',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Passer d\'un chien à deux : la vie avec {dog_name} évolue`,
    bodyFr: "Passer d'un chien à deux est une décision qui change le quotidien. L'arrivée d'un second compagnon modifie la dynamique avec {dog_name} et demande des ajustements pratiques. Le budget double (nourriture, vétérinaire, accessoires). L'espace nécessaire augmente. Les promenades avec deux chiens en laisse demandent de la pratique. Mais les avantages sont immenses : les deux chiens se tiennent compagnie, jouent ensemble et l'agitation de séparation diminue souvent. Pendant la période d'adaptation, accordez des moments individuels à {dog_name} pour qu'il ne se sente pas délaissé. Les sorties séparées permettent aussi de travailler l'éducation de chacun. La gestion des repas séparés, des couchages distincts et des jouets individuels est importante au début. Avec le temps, {dog_name} et son compagnon développeront leurs propres rituels et une complicité qui vous émerveillera au quotidien.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 6,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  {
    id: 'le-060-deuil-perte-chien',
    category: 'life_events',
    subcategory: 'deuil',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le temps du deuil après la perte de {dog_name}`,
    bodyFr: "La perte d'un chien est un deuil à part entière que l'entourage ne comprend pas toujours. La douleur que vous présenteez est légitime : {dog_name} faisait partie de votre famille, de votre routine, de vos souvenirs quotidiens. Autorisez-vous à pleurer, à être en retrait, à présenteir le vide de son absence. Le panier vide, la laisse sur le crochet, le silence de la maison sont des rappels douloureux. Chacun fait son deuil à son rythme : il n'y a pas de durée « normale ». Certains trouvent du réconfort à créer un petit hommage (photo encadrée, empreinte de patte). Parlez-en avec des personnes qui comprennent (associations, forums de propriétaires). La question d'un nouveau compagnon viendra en son temps : ne vous précipitez pas, mais ne culpabilisez pas non plus si l'envie revient vite. Un nouveau chien ne remplacera jamais {dog_name}, il écrira sa propre histoire dans votre coeur.",
    sourceType: 'life_event',
    neverSay: NEVER_SAY_MEDICAL,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 7,
    cooldownHours: 720,
    maxPerMonth: 1,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
];
