/**
 * Bleiz Freemium Templates — Community & Fun Facts
 * 70 templates for the EMOPET free companion app.
 * - 40 community templates (CM_001–CM_040)
 * - 30 fun fact templates (FF_001–FF_030)
 * All content in French, warm and educational tone.
 */

export interface CommunityTemplate {
  id: string;
  category: 'community';
  subcategory: 'community';
  breedFilter: string[];
  sizeFilter: string[];
  ageMinMonths: null;
  ageMaxMonths: null;
  seasonFilter: string[];
  monthFilter: number[];
  regionFilter: string[];
  titleFr: string;
  bodyFr: string;
  sourceType: 'community';
  neverSay: string[];
  suffix: null;
  requiresVetDisclaimer: false;
  channel: 'community_post';
  priority: 5;
  cooldownHours: 336;
  maxPerMonth: 2;
  usesDogName: true;
  usesBreedName: false;
  usesAge: false;
  usesLocation: true;
  usesSeason: false;
}

export interface FunFactTemplate {
  id: string;
  category: 'fun_fact';
  subcategory: 'fun_fact';
  breedFilter: string[];
  sizeFilter: string[];
  ageMinMonths: null;
  ageMaxMonths: null;
  seasonFilter: string[];
  monthFilter: number[];
  regionFilter: string[];
  titleFr: string;
  bodyFr: string;
  sourceType: 'fun_fact';
  neverSay: string[];
  suffix: null;
  requiresVetDisclaimer: false;
  channel: 'home_insight';
  priority: 4;
  cooldownHours: 336;
  maxPerMonth: 2;
  usesDogName: true;
  usesBreedName: false;
  usesAge: false;
  usesLocation: false;
  usesSeason: false;
}

const NEVER_SAY_COMMUNITY: string[] = ['avis clinique', 'condition clinique', 'traitement'];

// ═══════════════════════════════════════════════════════════════════════════════
// COMMUNITY TEMPLATES (40)
// ═══════════════════════════════════════════════════════════════════════════════

export const COMMUNITY_TEMPLATES: CommunityTemplate[] = [
  // --- CM_001 : promener en groupe ---
  {
    id: 'CM_001',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Promener {dog_name} en groupe : une aventure sociale`,
    bodyFr: `Les promenades collectives sont un excellent moyen de socialiser {dog_name} tout en rencontrant d'autres propriétaires près de {location}. Marcher en groupe permet aux chiens d'apprendre à gérer la présence de congénères dans un cadre structuré. Commencez par un petit groupe de deux ou trois chiens calmes, puis élargissez progressivement. Gardez une distance confortable entre les chiens au départ et laissez-les se rapprocher naturellement. Choisissez un parcours que {dog_name} connaît déjà pour réduire le forte sollicitation lié à la nouveauté. Avec le temps, ces sorties deviendront un rendez-vous attendu par {dog_name} et par vous.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_002 : aborder chien inconnu ---
  {
    id: 'CM_002',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Comment aborder un chien inconnu quand on est avec {dog_name}`,
    bodyFr: `Croiser un chien inconnu lors d'une balade avec {dog_name} près de {location} demande quelques précautions. Demandez toujours l'accord du propriétaire avant de laisser les chiens se renifler. Approchez en arc de cercle plutôt qu'en ligne droite, ce qui est moins confrontant pour les deux chiens. Observez le langage corporel : une queue détendue et des oreilles neutres sont de bons signes. Si l'un des deux chiens se raidit ou grogne, éloignez-vous calmement sans tirer brusquement sur la laisse. Gardez un ton de voix détendu car {dog_name} perçoit parfaitement votre niveau de forte sollicitation. La patience et le respect mutuel font les meilleures rencontres.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_003 : règles parc chiens ---
  {
    id: 'CM_003',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Les règles de base au parc à chiens avec {dog_name}`,
    bodyFr: `Les parcs à chiens près de {location} sont des espaces précieux pour que {dog_name} puisse se dépenser librement. Quelques règles de savoir-vivre s'imposent pour que tout le monde en profite. Gardez toujours un œil sur {dog_name} et restez prêt à intervenir. Ne laissez pas de jouets qui pourraient créer de la compétition entre chiens. Ramassez systématiquement les déjections de {dog_name}. Si votre compagnon est trop excité ou commence à harceler un autre chien, faites une pause en le rappelant. Respectez les zones séparées petits et grands chiens si elles existent. Un parc agréable, c'est l'affaire de tous les propriétaires présents.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_004 : chiens réactifs respecter ---
  {
    id: 'CM_004',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Respecter les chiens réactifs : un geste solidaire`,
    bodyFr: `Si {dog_name} est à l'aise avec ses congénères, ce n'est pas le cas de tous les chiens croisés à {location}. Un chien réactif n'est pas un chien méchant : il peut être en cours de rééducation, avoir vécu un traumatisme ou simplement être plus sensible. Quand vous voyez un propriétaire s'écarter ou raccourcir sa laisse, c'est un signal clair. Rappelez {dog_name} et changez de trottoir si possible. Ne dites pas « le mien est gentil » car cela ne change rien pour l'autre chien. En respectant l'espace de chacun, vous facilitez le travail des propriétaires qui font d'énormes efforts au quotidien. La bienveillance entre propriétaires fait toute la différence.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_005 : ramasser crottes ---
  {
    id: 'CM_005',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Ramasser après {dog_name} : petit geste, grand impact`,
    bodyFr: `Cela peut sembler évident, mais ramasser les déjections de {dog_name} à {location} est un acte civique essentiel. Les crottes laissées au sol polluent les sols et les cours d'eau, peuvent transmettre des parasites à d'autres chiens et dégradent l'image des propriétaires de chiens dans la communauté. Gardez toujours des sachets dans vos poches, dans le sac de promenade et accrochez-en à la laisse de {dog_name}. Si vous oubliez vos sachets, demandez-en un à un autre promeneur : la solidarité fonctionne. Certaines communes mettent à disposition des distributeurs gratuits. Un petit geste qui rend les espaces publics agréables pour tout le monde.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_006 : cohabitation immeuble ---
  {
    id: 'CM_006',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Vivre en immeuble avec {dog_name} : les clés de la cohabitation`,
    bodyFr: `La vie en appartement avec {dog_name} à {location} est tout à fait possible avec quelques attentions. Dans les parties communes, gardez {dog_name} en laisse courte et apprenez-lui à rester calme dans l'ascenseur. Évitez les horaires de sortie tardifs pour les besoins si {dog_name} a tendance à aboyer dans les escaliers. Présentez {dog_name} à vos voisins pour qu'ils se familiarisent avec votre compagnon. Si un voisin a réaction d’évitement des chiens, respectez cette crainte et gardez une distance rassurante. Investissez dans des jouets d'occupation pour que {dog_name} reste serein quand vous êtes absent. Une bonne cohabitation repose sur la prévention.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_007 : aboiements communauté ---
  {
    id: 'CM_007',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Aboiements de {dog_name} : préserver la tranquillité du voisinage`,
    bodyFr: `Les aboiements de {dog_name} peuvent vite devenir une source de tension avec les voisins à {location}. Comprendre pourquoi {dog_name} aboie est la première étape : ennui, agitation de séparation, réaction aux bruits extérieurs ou excitation. Enrichissez l'environnement de {dog_name} avec des jouets d'occupation et des séances de stimulation mentale avant vos absences. Travaillez progressivement les départs en augmentant la durée petit à petit. Si les aboiements persistent, un éducateur canin pourra vous accompagner. N'hésitez pas à prévenir vos voisins que vous prenez le sujet au sérieux : cette démarche est souvent très appréciée et désamorce les conflits.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_008 : entraide propriétaires ---
  {
    id: 'CM_008',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `L'entraide entre propriétaires de chiens à {location}`,
    bodyFr: `L'une des plus belles choses quand on a {dog_name}, c'est la communauté qui se crée naturellement entre propriétaires à {location}. Échanger des conseils sur les bons parcours de promenade, partager les contacts d'un vétérinaire de confiance ou simplement discuter lors des sorties quotidiennes enrichit votre quotidien et celui de {dog_name}. N'hésitez pas à proposer votre aide à un nouveau propriétaire qui semble désemparé ou à partager vos astuces avec ceux qui en ont besoin. La communauté canine se construit par ces petits gestes de solidarité. Ensemble, on rend la vie avec nos compagnons plus facile et plus joyeuse.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_009 : garde partagée voisins ---
  {
    id: 'CM_009',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Garde partagée : un réseau de confiance pour {dog_name}`,
    bodyFr: `Organiser une garde partagée entre voisins à {location} est une solution économique et rassurante pour {dog_name}. Le principe est simple : vous gardez le chien de votre voisin quand il est absent, et inversement. {dog_name} reste dans un environnement familier, avec des personnes qu'il connaît déjà. Avant de vous lancer, faites quelques rencontres entre les chiens pour vérifier la compatibilité. Établissez ensemble les règles de base : alimentation, horaires de promenade, habitudes de {dog_name}. Échangez les coordonnées de vos vétérinaires respectifs. Ce système fonctionne merveilleusement bien quand la confiance et la communication sont au rendez-vous.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_010 : SPA bénévolat ---
  {
    id: 'CM_010',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Devenir bénévole en refuge : une expérience enrichissante`,
    bodyFr: `Si vous aimez passer du temps avec {dog_name}, pourquoi ne pas offrir aussi un peu de votre temps aux chiens en attente de foyer près de {location} ? Les refuges et SPA ont besoin de bénévoles pour promener les chiens, les socialiser et leur offrir de l'affection. Quelques heures par semaine suffisent pour faire une vraie différence dans la vie d'un chien abandonné. Le bénévolat en refuge enrichit aussi votre propre expérience de propriétaire : vous apprendrez à décrypter des comportements variés et développerez votre sensibilité canine. Renseignez-vous auprès des associations locales pour connaître les besoins et les créneaux disponibles.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_011 : signaler maltraitance ---
  {
    id: 'CM_011',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Signaler une situation de maltraitance animale`,
    bodyFr: `En tant que propriétaire de {dog_name} à {location}, vous êtes sensible au bien-être animal. Si vous êtes témoin d'une situation de maltraitance ou de négligence envers un chien, vous pouvez agir. Notez les faits observés avec précision : lieu, date, description de l'animal et des conditions. Contactez la SPA, la fondation 30 Millions d'Amis ou les services vétérinaires départementaux. En cas d'urgence, appelez la police ou la gendarmerie. Ne tentez pas d'intervenir directement pour votre sécurité et celle de l'animal. Un signalement précis et documenté a beaucoup plus de poids. Chaque signalement compte et peut sauver une vie.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_012 : voisin réaction d’évitement chiens ---
  {
    id: 'CM_012',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Quand un voisin a réaction d’évitement de {dog_name}`,
    bodyFr: `Tout le monde n'est pas à l'aise avec les chiens, et c'est parfaitement légitime. Si un voisin à {location} exprime de la crainte envers {dog_name}, accueillez cette information avec respect. Tenez {dog_name} en laisse dans les espaces communs et évitez de le laisser s'approcher sans y être invité. Rassurez votre voisin en lui expliquant calmement les habitudes de {dog_name} sans minimiser sa réaction d’évitement. Avec le temps, une relation de confiance peut se construire naturellement. Proposez éventuellement une rencontre encadrée si votre voisin le souhaite. La cohabitation harmonieuse passe par l'écoute et le respect des limites de chacun.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_013 : espaces publics ---
  {
    id: 'CM_013',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} dans les espaces publics : bonnes pratiques`,
    bodyFr: `Profiter des espaces publics à {location} avec {dog_name} est un plaisir qui s'accompagne de responsabilités. Gardez {dog_name} en laisse dans les zones où c'est obligatoire et respectez les panneaux d'interdiction. Évitez les aires de jeux pour enfants et les terrains de sport. Assurez-vous que {dog_name} ne saute pas sur les passants, même par enthousiasme. Emportez toujours de l'eau fraîche et des sachets de ramassage. Si {dog_name} est détaché dans une zone autorisée, gardez-le sous contrôle vocal. Un chien bien éduqué et un propriétaire attentif sont les meilleurs ambassadeurs de la cause canine dans l'espace public.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_014 : loi chien France ---
  {
    id: 'CM_014',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Ce que la loi française dit sur la détention de {dog_name}`,
    bodyFr: `En France, posséder un chien comme {dog_name} implique des obligations légales. L'identification par puce électronique est obligatoire. La vaccination antirabique peut être requise selon les circonstances, notamment pour les voyages. Vous êtes civilement responsable des dommages causés par {dog_name}. La loi impose également de ne pas laisser divaguer son chien : {dog_name} doit être sous votre contrôle effectif en permanence. Les actes de cruauté envers les animaux sont punis par le Code pénal. Renseignez-vous auprès de votre mairie à {location} pour connaître les arrêtés locaux concernant la circulation des chiens sur votre commune.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_015 : muselière quand pourquoi ---
  {
    id: 'CM_015',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La muselière pour {dog_name} : quand et pourquoi`,
    bodyFr: `La muselière n'est pas un signe de dangerosité, c'est un outil de sécurité. Elle est obligatoire dans les transports en commun pour les chiens de plus de six kilos et pour certaines catégories. Même si {dog_name} n'y est pas contraint légalement, elle peut être utile dans des situations forte sollicitationantes : visite chez le vétérinaire, foule dense à {location} ou rencontre avec un chien craintif. Habituez {dog_name} progressivement à la muselière panier qui permet de haleter et boire librement. Associez-la à des friandises pour que {dog_name} la perçoive positivement. Un chien muselé et détendu, c'est un propriétaire responsable et prévoyant.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_016 : laisse obligatoire où ---
  {
    id: 'CM_016',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Où la laisse est-elle obligatoire pour {dog_name} ?`,
    bodyFr: `La réglementation sur la tenue en laisse varie selon les communes et les espaces autour de {location}. En règle générale, {dog_name} doit être tenu en laisse sur les voies publiques, dans les parcs municipaux sauf indication contraire, et dans les espaces naturels protégés. Les arrêtés préfectoraux et municipaux précisent les zones concernées. Même là où la laisse n'est pas obligatoire, elle reste recommandée si le rappel de {dog_name} n'est pas fiable. Une laisse de cinq mètres offre un bon compromis entre liberté et contrôle. Consultez le site de votre mairie ou l'office de tourisme local pour connaître les règles spécifiques à votre secteur.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_017 : transports en commun ---
  {
    id: 'CM_017',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Prendre les transports en commun avec {dog_name}`,
    bodyFr: `Voyager en transport en commun avec {dog_name} à {location} demande un peu de préparation. Les petits chiens peuvent généralement voyager dans un sac de transport. Les chiens plus grands doivent souvent être tenus en laisse courte et porter une muselière. Les conditions varient selon les réseaux de transport : renseignez-vous auprès de votre opérateur local. Habituez {dog_name} aux bruits et aux mouvements en faisant de courts trajets au départ. Choisissez les heures creuses pour les premières expériences. Gardez {dog_name} à vos pieds et veillez à ce qu'il ne gêne pas les autres voyageurs. Un chien calme dans les transports est toujours bien accueilli.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_018 : plages autorisées ---
  {
    id: 'CM_018',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Plages autorisées aux chiens : profiter de la mer avec {dog_name}`,
    bodyFr: `La plupart des plages françaises interdisent les chiens en période estivale, mais des alternatives existent près de {location}. Certaines communes aménagent des plages canines ou autorisent les chiens en dehors des heures de baignade surveillée. Renseignez-vous auprès de votre mairie ou de l'office de tourisme. Sur les plages autorisées, ramassez les déjections de {dog_name}, gardez-le sous contrôle et veillez à ce qu'il ne dérange pas les autres usagers. Après la baignade, rincez {dog_name} à l'eau douce pour éliminer le sel et le sable. Les balades sur la plage hors saison restent souvent autorisées et sont un vrai bonheur pour {dog_name}.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_019 : forêts réglementation ---
  {
    id: 'CM_019',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Balades en forêt avec {dog_name} : ce qu'il faut savoir`,
    bodyFr: `Les forêts proches de {location} sont des terrains de jeu formidables pour {dog_name}, mais certaines règles s'appliquent. Dans les forêts domaniales, les chiens doivent être tenus en laisse sur les allées forestières. En période de nidification au printemps et pendant la saison de chasse en automne, la vigilance est renforcée. Un chien en liberté qui poursuit du gibier peut être verbalisé et son propriétaire sanctionné. Équipez {dog_name} d'un gilet fluorescent en période de chasse. Restez sur les sentiers balisés pour préserver la faune et la flore. Vérifiez les tiques au retour de balade. La forêt est un espace partagé entre promeneurs, chasseurs et nature.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_020 : chiens catégorie info ---
  {
    id: 'CM_020',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Chiens de catégorie : comprendre la réglementation`,
    bodyFr: `En France, certains chiens sont classés en première ou deuxième catégorie selon leur morphologie. Cette classification entraîne des obligations spécifiques : permis de détention, évaluation comportementale, assurance responsabilité civile, muselière et laisse dans les lieux publics. Si {dog_name} est concerné ou si vous croisez des chiens catégorisés à {location}, il est utile de connaître ces règles. Les propriétaires de chiens catégorisés font souvent face à des préjugés injustes alors qu'ils respectent scrupuleusement la loi. Informez-vous sans juger et rappelez-vous que le comportement d'un chien dépend avant tout de son éducation et de son environnement.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_021 : assurance RC ---
  {
    id: 'CM_021',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Assurance responsabilité civile et {dog_name}`,
    bodyFr: `En tant que propriétaire de {dog_name} à {location}, votre responsabilité civile est engagée si votre compagnon cause un dommage à un tiers. La plupart des contrats d'assurance habitation incluent une garantie responsabilité civile qui couvre les dégâts causés par votre animal. Vérifiez votre contrat pour vous assurer que {dog_name} est bien couvert et qu'il n'y a pas d'exclusion. Pour les chiens de catégorie, une assurance spécifique est obligatoire. Même si ce n'est pas requis pour tous les chiens, une bonne couverture vous protège en cas de morsure, de dégât matériel ou d'accident provoqué par {dog_name}. Mieux vaut prévenir que subir des frais imprévus.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_022 : vaccination collectivité ---
  {
    id: 'CM_022',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Vaccination de {dog_name} et vie en collectivité`,
    bodyFr: `Quand {dog_name} fréquente d'autres chiens à {location}, que ce soit en parc, en pension ou en club canin, la vaccination joue un rôle essentiel pour la communauté. Les vaccins de base protègent contre des agents très contagieux qui circulent facilement entre chiens. Les pensions et garderies exigent généralement un carnet de vaccination à jour. En tenant les rappels de {dog_name} à jour, vous protégez votre compagnon mais aussi tous les chiens qu'il côtoie. Pensez à consulter votre vétérinaire pour adapter le protocole vaccinal au mode de vie de {dog_name}. C'est un acte de responsabilité individuelle qui profite à toute la communauté canine.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_023 : chien au bureau ---
  {
    id: 'CM_023',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Emmener {dog_name} au bureau : mode d'emploi`,
    bodyFr: `De plus en plus d'entreprises à {location} autorisent les chiens au bureau. Si c'est votre cas, quelques règles favorisent une cohabitation réussie. Assurez-vous que {dog_name} est propre, calme et sociable avec les inconnus. Prévoyez un espace dédié avec son panier, de l'eau fraîche et un jouet d'occupation silencieux. Respectez les collègues qui préfèrent garder leurs distances et ne forcez jamais le contact. Sortez {dog_name} régulièrement pour ses besoins et ses pauses détente. Un chien qui dort paisiblement sous votre bureau est le meilleur argument pour convaincre les sceptiques. La présence de {dog_name} réduit le forte sollicitation et crée des liens entre collègues.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_024 : chien et commerçants ---
  {
    id: 'CM_024',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et les commerçants : savoir-vivre en boutique`,
    bodyFr: `Faire vos courses avec {dog_name} à {location} demande un peu de tact. Les commerces alimentaires interdisent généralement les chiens pour des raisons d'hygiène, sauf les chiens d'assistance. Pour les autres boutiques, la décision appartient au commerçant. Demandez toujours avant d'entrer avec {dog_name}. Si {dog_name} est autorisé, gardez-le en laisse courte et veillez à ce qu'il ne renifle pas les marchandises. Si l'attente dehors est nécessaire, ne laissez jamais {dog_name} attaché seul trop longtemps. Remerciez les commerçants qui acceptent les chiens : ce geste encourage d'autres à faire de même et facilite la vie des propriétaires au quotidien.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_025 : bon voisinage aboiements ---
  {
    id: 'CM_025',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Bon voisinage : quand {dog_name} aboie un peu trop`,
    bodyFr: `Un voisin vous a signalé que {dog_name} aboie en votre absence à {location} ? Ne prenez pas cette remarque comme une attaque. Remerciez votre voisin de vous prévenir car c'est une information précieuse. Essayez de comprendre les déclencheurs : bruits de couloir, passage du facteur, solitude. Filmez {dog_name} en votre absence pour observer son comportement. Mettez en place des solutions progressives comme de la musique douce, des jouets d'occupation ou un enrichissement de l'environnement. Tenez votre voisin informé de vos efforts. Cette transparence transforme souvent un conflit potentiel en relation de bon voisinage durable autour de {dog_name}.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_026 : chien et facteur ---
  {
    id: 'CM_026',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et le facteur : gérer cette rencontre quotidienne`,
    bodyFr: `Le passage du facteur est souvent un moment d'excitation intense pour {dog_name} à {location}. Ce rituel quotidien peut devenir problématique si {dog_name} aboie excessivement ou se montre trop agité. Comprenez que pour {dog_name}, le facteur est un intrus qui approche puis repart, ce qui renforce le comportement de garde. Pour calmer cette réaction, travaillez la désensibilisation : récompensez le calme quand quelqu'un approche de la porte. Installez une boîte aux lettres accessible sans entrer dans votre propriété si possible. Présentez-vous au facteur et expliquez que vous travaillez sur ce comportement. Un petit mot amical sur la boîte aux lettres peut aussi aider.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_027 : chien et joggeurs ---
  {
    id: 'CM_027',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} face aux joggeurs : éviter les incidents`,
    bodyFr: `Les joggeurs qui passent en courant près de {dog_name} à {location} peuvent déclencher un instinct de poursuite. Ce comportement naturel n'est pas agressif mais peut effrayer le coureur et mettre {dog_name} en danger. Anticipez ces situations en gardant {dog_name} en laisse sur les parcours fréquentés par les joggeurs. Entraînez le rappel et le « reste » dans des environnements calmes avant de les tester en situation réelle. Quand un joggeur approche, attirez l'attention de {dog_name} avec une friandise et récompensez le calme. Avec de la pratique, {dog_name} apprendra à observer les coureurs passer sans réagir. Patience et constance sont vos meilleures alliées.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_028 : chien et vélos ---
  {
    id: 'CM_028',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et les vélos : cohabiter en sécurité`,
    bodyFr: `Les vélos qui passent rapidement peuvent surprendre {dog_name} lors de vos promenades à {location}. Certains chiens veulent les poursuivre, d'autres prennent réaction d’évitement. Dans les deux cas, gardez {dog_name} en laisse sur les voies partagées avec les cyclistes. Positionnez-vous entre {dog_name} et la piste cyclable pour créer une barrière naturelle. Travaillez la désensibilisation progressive en restant à distance des vélos puis en vous rapprochant graduellement en récompensant le calme. Si {dog_name} est en liberté dans un espace autorisé, rappelez-le dès qu'un vélo approche. La cohabitation piétons-cyclistes-chiens fonctionne quand chacun fait preuve de vigilance et de respect mutuel.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_029 : sécurité routière ---
  {
    id: 'CM_029',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Sécurité routière : protéger {dog_name} près des routes`,
    bodyFr: `Les routes autour de {location} représentent un danger réel pour {dog_name}. En milieu urbain, gardez toujours {dog_name} en laisse et traversez aux passages piétons en vous assurant que votre compagnon marche du côté intérieur du trottoir. Apprenez à {dog_name} à s'asseoir et attendre avant chaque traversée. En milieu rural, les routes de campagne sont trompeuses car les voitures roulent souvent vite. Équipez {dog_name} d'un collier ou harnais réfléchissant pour les sorties crépusculaires et nocturnes. En voiture, {dog_name} doit être attaché avec un harnais de sécurité ou placé dans une caisse de transport. Sa sécurité routière dépend entièrement de votre vigilance.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_030 : chien et skaters ---
  {
    id: 'CM_030',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et les skaters : gérer la surprise`,
    bodyFr: `Le bruit des planches de skate et les mouvements rapides des skaters à {location} peuvent beaucoup perturber {dog_name}. Ce stimulus inhabituel combine le son, la vitesse et des mouvements imprévisibles. Si {dog_name} réagit fortement, commencez par observer les skaters de loin en distribuant des friandises. Réduisez progressivement la distance au fil des séances, toujours en récompensant le calme. Ne forcez jamais {dog_name} à rester si le forte sollicitation est trop important. Avec le temps, la plupart des chiens apprennent à ignorer les skaters. Dans les espaces partagés, gardez {dog_name} en laisse courte pour éviter qu'il ne se mette en travers de la trajectoire d'un skater, ce qui serait dangereux pour les deux.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_031 : marches collectives ---
  {
    id: 'CM_031',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Marches collectives canines autour de {location}`,
    bodyFr: `Les marches collectives réunissent des propriétaires et leurs chiens pour des randonnées conviviales organisées près de {location}. Ces événements permettent à {dog_name} de découvrir de nouveaux sentiers en compagnie d'autres chiens, dans une ambiance encadrée et détendue. Les organisateurs choisissent généralement des parcours adaptés à tous les niveaux de forme physique, tant pour les chiens que pour les humains. C'est aussi l'occasion de partager des astuces, de nouer des amitiés et de découvrir la région sous un angle nouveau. Consultez les groupes locaux et les associations canines pour trouver les prochaines dates. {dog_name} adorera ces aventures partagées.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_032 : clubs canins ---
  {
    id: 'CM_032',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Rejoindre un club canin avec {dog_name}`,
    bodyFr: `Les clubs canins autour de {location} proposent des activités variées pour {dog_name} et vous : éducation, agility, obéissance, pistage ou encore canicross. Encadré par des moniteurs diplômés, le travail en club permet à {dog_name} d'apprendre dans un environnement structuré tout en se socialisant. Les tarifs annuels restent généralement accessibles. Visitez plusieurs clubs avant de vous décider pour trouver l'ambiance et les méthodes qui correspondent à {dog_name}. Les clubs affiliés à la Société Centrale Canine offrent un cadre reconnu. Au-delà de l'éducation, le club canin est un lieu de rencontre et de partage entre passionnés. {dog_name} y trouvera stimulation et plaisir.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_033 : associations race ---
  {
    id: 'CM_033',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Les associations de race : une ressource pour les propriétaires`,
    bodyFr: `Quel que soit le profil de {dog_name}, les associations de race regroupent des passionnés qui partagent leur expertise. Ces clubs organisent des rassemblements, des expositions et des rencontres régionales accessibles près de {location}. Ils sont une mine d'informations sur les particularités comportementales, les besoins spécifiques et les bonnes pratiques d'élevage. Même si {dog_name} n'est pas inscrit au LOF, certaines associations accueillent tous les propriétaires désireux d'en apprendre davantage. Les éleveurs membres peuvent vous conseiller sur l'alimentation, l'entretien du pelage ou les activités adaptées. Rejoindre une association de race, c'est intégrer une communauté de passionnés bienveillants.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_034 : groupes promenade ---
  {
    id: 'CM_034',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Créer un groupe de promenade pour {dog_name} à {location}`,
    bodyFr: `Pourquoi ne pas lancer votre propre groupe de promenade à {location} ? Commencez par inviter deux ou trois propriétaires que vous croisez régulièrement lors de vos sorties avec {dog_name}. Fixez un rendez-vous hebdomadaire à heure et lieu fixes pour créer une habitude. Choisissez un parcours agréable avec un mélange de laisse et de liberté selon les zones. Créez un petit groupe de discussion pour coordonner les sorties et prévenir en cas d'absence. Avec le temps, le groupe grandira naturellement par le bouche-à-oreille. Ces promenades deviendront un moment privilégié pour {dog_name} et pour vous, alliant exercice physique, socialisation et convivialité entre propriétaires.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_035 : bénévolat refuge ---
  {
    id: 'CM_035',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Bénévolat en refuge : comment s'engager près de {location}`,
    bodyFr: `Les refuges proches de {location} accueillent des dizaines de chiens en attente d'adoption et manquent souvent de bras. Le bénévolat prend des formes variées : promenades quotidiennes, socialisation des chiens craintifs, aide au nettoyage ou participation aux événements d'adoption. Votre expérience avec {dog_name} est un atout précieux. Contactez le refuge le plus proche pour connaître leurs besoins et les créneaux disponibles. Même quelques heures par mois font une différence immense pour ces chiens qui manquent de contact humain. Le bénévolat est aussi une expérience humaine forte qui renforce le lien entre vous et la communauté canine de votre région.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_036 : parrainage refuge ---
  {
    id: 'CM_036',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Parrainer un chien en refuge : un geste à la portée de tous`,
    bodyFr: `Si vous ne pouvez pas adopter un deuxième compagnon pour {dog_name}, le parrainage est une belle alternative. En parrainant un chien dans un refuge près de {location}, vous contribuez financièrement à ses frais de nourriture et de soins vétérinaires. Certains refuges proposent également un parrainage actif qui inclut des visites et des sorties régulières avec le chien parrainé. C'est une façon concrète d'aider sans les contraintes d'une adoption. Le parrainage aide aussi les chiens difficiles à placer, comme les seniors ou les chiens à besoins spécifiques, qui attendent parfois des mois en refuge. Un petit montant mensuel peut changer la vie d'un chien en attente de foyer.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_037 : sensibiliser enfants respect ---
  {
    id: 'CM_037',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Apprendre aux enfants à respecter {dog_name} et les autres chiens`,
    bodyFr: `Les enfants à {location} adorent souvent les chiens, mais ne savent pas toujours comment les approcher correctement. Apprenez-leur quelques règles essentielles : toujours demander au propriétaire avant de caresser {dog_name}, ne jamais déranger un chien qui mange ou dort, ne pas courir vers un chien inconnu et tendre la main paume vers le bas pour que le chien vienne renifler. Expliquez que tirer les oreilles ou la queue fait mal. Montrez-leur les signes de forte sollicitation chez le chien : bâillements, détournement de regard, léchage de babines. Éduquer les enfants au respect des animaux, c'est prévenir les accidents et former de futurs propriétaires responsables et bienveillants.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_038 : journée mondiale chien ---
  {
    id: 'CM_038',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Journée mondiale du chien : célébrer {dog_name}`,
    bodyFr: `Chaque année, la journée mondiale du chien est l'occasion de célébrer le lien unique entre {dog_name} et vous. À {location} et partout dans le monde, des événements sont organisés pour sensibiliser le public à la cause canine : adoptions, collectes pour les refuges, rassemblements festifs. Profitez de cette journée pour offrir à {dog_name} une sortie spéciale, une friandise exceptionnelle ou simplement un moment de complicité prolongé. C'est aussi le moment de partager sur les réseaux sociaux pourquoi {dog_name} rend votre vie plus belle, afin d'encourager l'adoption responsable et de montrer le bonheur qu'apporte un chien au quotidien. Chaque chien mérite d'être fêté.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_039 : diversité races ---
  {
    id: 'CM_039',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La diversité des races : richesse de la communauté canine`,
    bodyFr: `En promenant {dog_name} à {location}, vous croisez une incroyable variété de races, de tailles et de caractères. Cette diversité est une richesse pour la communauté canine. Chaque race a été sélectionnée pour des aptitudes particulières et possède ses propres besoins. Un lévrier ne se promène pas comme un bouledogue, un border collie n'a pas les mêmes besoins qu'un cavalier king charles. Respecter ces différences, c'est comprendre pourquoi certains chiens sont plus actifs, plus calmes, plus indépendants ou plus sociables que {dog_name}. Évitez les jugements rapides sur une race et apprenez des propriétaires que vous rencontrez. La diversité canine nous apprend la tolérance et l'ouverture.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
  // --- CM_040 : communauté EMOPET valeurs ---
  {
    id: 'CM_040',
    category: 'community',
    subcategory: 'community',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La communauté EMOPET : nos valeurs partagées`,
    bodyFr: `En rejoignant la communauté EMOPET avec {dog_name}, vous faites partie d'un réseau de propriétaires engagés à {location} et partout en France. Nos valeurs sont simples : le respect du bien-être animal, la bienveillance entre propriétaires, le partage de connaissances fiables et la promotion d'une cohabitation harmonieuse entre chiens et humains. Ici, pas de jugement ni de comparaison : chaque chien est unique et chaque propriétaire fait de son mieux. Partagez vos expériences, posez vos questions et n'hésitez pas à encourager les autres membres. Ensemble, nous construisons une communauté où {dog_name} et tous les chiens vivent mieux grâce à des propriétaires informés et solidaires.`,
    sourceType: 'community',
    neverSay: NEVER_SAY_COMMUNITY,
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'community_post',
    priority: 5,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: true,
    usesSeason: false,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// FUN FACT TEMPLATES (30)
// ═══════════════════════════════════════════════════════════════════════════════

export const FUN_FACT_TEMPLATES: FunFactTemplate[] = [
  // --- FF_001 : odorat vs humain ---
  {
    id: 'FF_001',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le super-pouvoir olfactif de {dog_name}`,
    bodyFr: `Le nez de {dog_name} est une véritable merveille de la nature. Là où vous possédez environ cinq millions de récepteurs olfactifs, {dog_name} en compte jusqu'à trois cents millions. Son cerveau consacre une proportion quarante fois plus importante à l'analyse des odeurs que le vôtre. Concrètement, {dog_name} peut détecter une cuillère de sucre diluée dans deux piscines olympiques. Chaque narine fonctionne indépendamment, ce qui permet à {dog_name} de localiser la direction d'une odeur. Son nez humide capture mieux les molécules odorantes. C'est grâce à ce talent que certains chiens détectent des substances, retrouvent des personnes disparues ou perçoivent des variations subtiles chez leurs humains.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_002 : tourner avant coucher ---
  {
    id: 'FF_002',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Pourquoi {dog_name} tourne en rond avant de se coucher`,
    bodyFr: `Vous avez sûrement observé {dog_name} tourner plusieurs fois sur place avant de se coucher. Ce rituel amusant est un héritage ancestral. Les ancêtres sauvages de {dog_name} tournaient pour aplatir l'herbe et créer un nid confortable, mais aussi pour vérifier l'absence de serpents ou d'insectes dans leur couchage. Tourner permettait également de se positionner face au vent pour détecter l'approche d'un prédateur. Même si {dog_name} dispose d'un panier moelleux, cet instinct reste profondément ancré dans son comportement. Le nombre de tours varie selon les chiens et le confort du support. C'est un petit rituel rassurant qui prépare {dog_name} à un sommeil serein et réparateur.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_003 : vision couleurs ---
  {
    id: 'FF_003',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Comment {dog_name} voit le monde en couleurs`,
    bodyFr: `Contrairement à une idée reçue, {dog_name} ne voit pas en noir et blanc. Les chiens perçoivent les couleurs, mais différemment de nous. {dog_name} possède deux types de cônes dans ses yeux contre trois chez l'humain. Résultat : {dog_name} distingue bien le bleu et le jaune, mais le rouge et le vert se confondent en nuances de brun ou de gris. C'est pourquoi les jouets bleus ou jaunes sont plus faciles à repérer pour {dog_name} dans l'herbe qu'une balle rouge. En revanche, {dog_name} vous surpasse en vision nocturne grâce au tapetum lucidum, une couche réfléchissante derrière la rétine. {dog_name} voit mieux que vous dans la pénombre, un héritage de ses ancêtres chasseurs crépusculaires.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_004 : vitesse par race ---
  {
    id: 'FF_004',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} est-il un sprinter ou un marathonien ?`,
    bodyFr: `La vitesse de pointe d'un chien varie considérablement selon sa morphologie. Le greyhound détient le record avec près de soixante-douze kilomètres par heure, rivalisant avec un guépard sur courte distance. Les races à pattes courtes comme le teckel ou le basset atteignent des vitesses bien plus modestes mais compensent par leur endurance. Le husky, lui, peut maintenir une allure soutenue pendant des heures dans la neige. La vitesse de {dog_name} dépend de la longueur de ses pattes, de sa masse musculaire et de sa capacité respiratoire. Quel que soit son gabarit, {dog_name} a besoin de courir régulièrement pour exprimer sa nature profonde et rester en forme.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_005 : races anciennes ---
  {
    id: 'FF_005',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Les ancêtres de {dog_name} : des millénaires de compagnonnage`,
    bodyFr: `La domestication du chien remonte à environ quinze mille ans, faisant du compagnon de {dog_name} le plus ancien animal domestiqué par l'homme. Certaines races actuelles comme le basenji, le saluki ou l'akita inu figurent parmi les lignées les plus anciennes, avec un ADN très proche du loup. Les premières traces de chiens domestiques ont été retrouvées en Eurasie. Au fil des siècles, les humains ont sélectionné les chiens pour la chasse, la garde, le travail de troupeau ou la simple compagnie. {dog_name} porte en lui des millénaires d'évolution aux côtés de l'homme. Cette longue histoire commune explique le lien si particulier et si profond entre {dog_name} et vous.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_006 : records plus grand petit rapide ---
  {
    id: 'FF_006',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Records canins : les extrêmes du monde de {dog_name}`,
    bodyFr: `Le monde canin regorge de records étonnants. Le plus grand chien jamais mesuré, un dogue allemand, dépassait un mètre dix au garrot. Le plus petit, un chihuahua, tenait dans la paume d'une main avec moins de dix centimètres de hauteur. Le chien le plus rapide, le greyhound, atteint soixante-douze kilomètres par heure. Le record de longévité revient à un kelpie australien ayant vécu plus de trente ans. Certains chiens ont appris plus de mille mots, d'autres ont parcouru des milliers de kilomètres pour retrouver leur famille. Chaque chien est exceptionnel à sa manière, et {dog_name} détient sûrement ses propres records dans votre cœur.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_007 : chiens célèbres histoire ---
  {
    id: 'FF_007',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Chiens célèbres de l'histoire : les cousins illustres de {dog_name}`,
    bodyFr: `L'histoire regorge de chiens célèbres qui ont marqué leur époque. Laïka, une petite chienne errante de Moscou, fut le premier être vivant en orbite en 1957. Balto, un husky, guida un attelage à travers une tempête en Alaska pour livrer un sérum vital. Hachiko, un akita japonais, attendit son maître devant une gare pendant près de dix ans après sa disparition. En France, Barry, un saint-bernard, sauva plus de quarante personnes dans les Alpes. Ces histoires montrent l'intelligence, la loyauté et le courage des chiens à travers les âges. {dog_name} partage ce même héritage de dévouement et de connexion profonde avec l'humain.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_008 : intelligence par race nuancer ---
  {
    id: 'FF_008',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `L'intelligence de {dog_name} : bien plus qu'un classement`,
    bodyFr: `On classe souvent les races par intelligence, mais cette notion mérite d'être nuancée. Le border collie excelle en obéissance, le beagle en pistage, le caniche en apprentissage de tours. Chaque type d'intelligence est adapté à la fonction initiale de la race. Un chien jugé « têtu » est souvent un chien indépendant qui réfléchit avant d'obéir, ce qui est une forme d'intelligence à part entière. {dog_name} possède sa propre forme de brillance : capacité à lire vos émotions, résolution de problèmes quotidiens, mémoire des routines et des lieux. L'intelligence canine est multiple et riche. Ne sous-estimez jamais la capacité de {dog_name} à comprendre bien plus que vous ne l'imaginez.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_009 : sens orientation ---
  {
    id: 'FF_009',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le sens de l'orientation incroyable de {dog_name}`,
    bodyFr: `Les chiens possèdent un sens de l'orientation remarquable qui fascine les scientifiques. {dog_name} utilise plusieurs outils pour se repérer : son odorat exceptionnel qui crée une carte olfactive du territoire, sa mémoire visuelle des repères et, selon certaines études, une sensibilité au champ magnétique terrestre. Des chiens ont retrouvé leur chemin sur des centaines de kilomètres après avoir été séparés de leur famille. {dog_name} mémorise les parcours de promenade avec une précision impressionnante et repère le chemin du retour bien avant vous. Cette capacité explique pourquoi les chiens de recherche et de sauvetage sont si efficaces. Le GPS interne de {dog_name} est un héritage de ses ancêtres nomades.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_010 : queue pas toujours enthousiasme ---
  {
    id: 'FF_010',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La queue de {dog_name} ne dit pas toujours « je suis content »`,
    bodyFr: `On croit souvent qu'un chien qui remue la queue est forcément à l’aise, mais c'est plus subtil que cela. La queue de {dog_name} est un outil de communication complexe. Un battement large et détendu indique effectivement la enthousiasme. En revanche, une queue raide qui bat rapidement peut exprimer de l'excitation nerveuse ou de la tension. Une queue basse et lente peut signaler de l'insécurité. Les recherches montrent même que les chiens qui remuent davantage vers la droite sont positifs, tandis qu'un mouvement vers la gauche indique un forte sollicitation. La hauteur, la vitesse et l'amplitude du mouvement de queue de {dog_name} racontent une histoire complète. Apprenez à lire ces nuances pour mieux comprendre {dog_name}.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_011 : moustaches utilité ---
  {
    id: 'FF_011',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Les moustaches de {dog_name} : de vrais capteurs sensoriels`,
    bodyFr: `Les vibrisses de {dog_name}, ces longs poils raides sur le museau, au-dessus des yeux et sur le menton, ne sont pas de simples poils. Ce sont des organes sensoriels connectés à des terminaisons nerveuses très sensibles. Elles détectent les vibrations de l'air, les changements de courant et aident {dog_name} à évaluer la taille des espaces dans l'obscurité. Grâce à ses moustaches, {dog_name} perçoit des obstacles avant même de les toucher. Elles complètent sa vision, particulièrement de près où les chiens voient moins bien. C'est pourquoi il ne faut jamais couper les vibrisses de {dog_name} lors du toilettage. Ces capteurs naturels sont indispensables à sa perception du monde.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_012 : chien rêve-t-il ---
  {
    id: 'FF_012',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} rêve-t-il pendant son sommeil ?`,
    bodyFr: `Oui, {dog_name} rêve bel et bien. Les études sur le sommeil canin ont démontré que les chiens traversent les mêmes phases de sommeil que les humains, incluant le sommeil paradoxal où surviennent les rêves. Quand vous voyez {dog_name} bouger les pattes, gémir doucement ou remuer les babines pendant le sommeil, il est probablement en train de rêver. Les chercheurs pensent que les chiens rêvent de leurs activités quotidiennes : courir après une balle, renifler un sentier ou interagir avec vous. Les petits chiens rêvent plus fréquemment mais plus brièvement que les grands. {dog_name} passe environ douze à quatorze heures par jour à dormir, avec de nombreuses occasions de rêver de ses aventures.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_013 : fréquence cardiaque ---
  {
    id: 'FF_013',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le cœur de {dog_name} bat à son propre rythme`,
    bodyFr: `Le rythme cardiaque de {dog_name} est fascinant et varie selon sa taille. Un petit chien peut avoir un cœur qui bat entre cent et cent quarante fois par minute au repos, tandis qu'un grand chien tourne plutôt autour de soixante à cent battements. À titre de comparaison, le cœur humain bat en moyenne soixante-dix fois par minute. Pendant l'exercice, le rythme de {dog_name} peut doubler. Fait remarquable : des études montrent que le rythme cardiaque d'un chien se synchronise avec celui de son propriétaire lors de moments de calme partagé. Quand vous caressez {dog_name}, vos deux cœurs tendent à ralentir ensemble, un signe tangible du lien profond entre vous.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_014 : chien et miroir ---
  {
    id: 'FF_014',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} face au miroir : se reconnaît-il ?`,
    bodyFr: `Quand {dog_name} passe devant un miroir, sa réaction peut être amusante : aboiements, curiosité ou indifférence totale. Les chiens ne réussissent pas le test classique du miroir utilisé pour mesurer la conscience de soi chez les animaux. Cependant, cela ne signifie pas que {dog_name} n'a pas conscience de lui-même. Les chiens se reconnaissent par l'odeur, pas par la vue. Des expériences récentes montrent que les chiens identifient parfaitement leur propre odeur parmi d'autres. {dog_name} sait très bien qui il est, simplement il utilise son nez plutôt que ses yeux pour le confirmer. La prochaine fois que {dog_name} ignore son reflet, c'est peut-être simplement parce que le miroir ne sent rien d'intéressant.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_015 : pourquoi pencher tête ---
  {
    id: 'FF_015',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Pourquoi {dog_name} penche la tête quand vous lui parlez`,
    bodyFr: `Ce geste adorable où {dog_name} incline la tête sur le côté quand vous lui parlez a plusieurs explications. Premièrement, {dog_name} ajuste la position de ses oreilles pour mieux localiser la source du son et en percevoir les nuances. Deuxièmement, le museau de {dog_name} peut gêner sa vision frontale : pencher la tête améliore son champ visuel sur votre visage et vos expressions. Troisièmement, {dog_name} a appris que ce geste provoque une réaction positive chez vous, ce qui le renforce. Les études montrent que les chiens familiers avec certains mots penchent davantage la tête, suggérant un effort de compréhension active. Ce petit mouvement de tête est la preuve que {dog_name} vous écoute attentivement.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_016 : coussinets empreintes uniques ---
  {
    id: 'FF_016',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Les coussinets de {dog_name} : bien plus que de simples semelles`,
    bodyFr: `Les coussinets de {dog_name} sont des structures remarquables. Composés d'une couche épaisse de graisse et de tissu conjonctif, ils absorbent les chocs et isolent les pattes du froid et de la chaleur. Les coussinets contiennent des glandes sudoripares, l'un des rares endroits où les chiens transpirent. Leur texture rugueuse offre une adhérence comparable à celle des pneus sur la route. Fait surprenant : les empreintes de coussinets de {dog_name} sont uniques, tout comme les empreintes digitales humaines. Avec l'âge et l'activité, les coussinets de {dog_name} s'épaississent et se renforcent naturellement. Protégez-les sur les surfaces brûlantes en été et sur le sel de déneigement en hiver.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_017 : chien et eau mer ---
  {
    id: 'FF_017',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et l'eau de mer : attraction ou méfiance ?`,
    bodyFr: `La relation des chiens avec l'eau de mer varie considérablement. Certains, comme les labradors et les terre-neuve, sont des nageurs nés grâce à leurs pattes palmées et leur pelage imperméable. D'autres, comme les bouledogues, ont une morphologie peu adaptée à la nage avec leur centre de gravité avant. {dog_name} a sa propre relation avec l'eau. Saviez-vous que les chiens nagent naturellement en « pédalant » avec leurs quatre pattes ? Ce mouvement instinctif se déclenche même chez les chiots qui n'ont jamais vu de plan d'eau. Après un bain de mer, rincez toujours {dog_name} à l'eau douce car le sel dessèche la peau et le pelage. L'eau douce reste généralement préférée par la plupart des chiens.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_018 : muscles oreille ---
  {
    id: 'FF_018',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Les oreilles de {dog_name} : dix-huit muscles en action`,
    bodyFr: `Les oreilles de {dog_name} sont pilotées par pas moins de dix-huit muscles, contre seulement six chez l'humain. Cette musculature permet à {dog_name} d'orienter ses oreilles indépendamment l'une de l'autre pour localiser un son avec une précision redoutable. {dog_name} entend des fréquences allant jusqu'à soixante-cinq mille hertz, bien au-delà des vingt mille hertz de l'oreille humaine. Il peut détecter un son quatre fois plus éloigné que ce que vous percevez. La forme des oreilles de {dog_name}, qu'elles soient droites, tombantes ou semi-dressées, influence la captation du son. Les oreilles de {dog_name} sont aussi un outil de communication expressif : dressées pour l'attention, plaquées pour la soumission, mobiles pour la curiosité.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_019 : nez empreinte unique ---
  {
    id: 'FF_019',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La truffe de {dog_name} : une empreinte unique au monde`,
    bodyFr: `Tout comme les empreintes digitales humaines, la truffe de {dog_name} possède un motif de crêtes et de sillons absolument unique. Aucun autre chien au monde n'a exactement la même empreinte nasale que {dog_name}. Cette caractéristique est si fiable que certaines entreprises développent des systèmes d'identification canine basés sur la reconnaissance de la truffe. La truffe de {dog_name} est humide en permanence grâce à une fine couche de mucus qui aide à capturer les molécules odorantes. Sa couleur peut varier au fil des saisons, un phénomène appelé « nez d'hiver » où la truffe s'éclaircit avec le froid. La truffe de {dog_name} est véritablement sa carte d'identité biologique la plus fiable.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_020 : chien et télévision ---
  {
    id: 'FF_020',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} regarde-t-il vraiment la télévision ?`,
    bodyFr: `Si {dog_name} semble captivé par l'écran, ce n'est pas une illusion. Les chiens peuvent effectivement percevoir les images télévisées, surtout avec les écrans modernes à haute fréquence de rafraîchissement. Les anciens téléviseurs cathodiques scintillaient trop pour les yeux canins. {dog_name} réagit principalement aux mouvements d'animaux, aux sons aigus et aux voix humaines diffusées. Des études montrent que les chiens préfèrent regarder d'autres chiens à l'écran plutôt que des humains ou des paysages. Cependant, {dog_name} ne comprend pas les scénarios et regarde de manière fragmentée, attiré par des stimuli ponctuels. Il existe même des chaînes télévisées conçues spécialement pour les chiens, avec des contenus visuels et sonores adaptés à leur perception.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_021 : chiens qui sourient ---
  {
    id: 'FF_021',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} sourit-il vraiment ?`,
    bodyFr: `Cette expression de la gueule ouverte, babines retroussées, que vous interprétez comme un sourire chez {dog_name} est un phénomène fascinant. Les chiens ont développé une musculature faciale spécifique au contact de l'homme que les loups ne possèdent pas. Le muscle releveur de la lèvre interne, responsable du regard « yeux de chiot », s'est développé au cours de la domestication. {dog_name} a appris que certaines expressions faciales provoquent une réponse positive chez vous. Ce n'est pas un sourire au sens humain, mais c'est un signal de communication intentionnel. {dog_name} adapte réellement ses expressions à votre présence, un talent unique parmi les animaux domestiques et un témoignage du lien profond entre nos espèces.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_022 : langue et chaleur ---
  {
    id: 'FF_022',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La langue de {dog_name} : son système de climatisation`,
    bodyFr: `Quand {dog_name} halète avec la langue pendante, il ne fait pas que reprendre son souffle : il régule sa température corporelle. Les chiens ne transpirent quasiment pas par la peau, sauf au niveau des coussinets. Le halètement est leur principal mécanisme de refroidissement. L'air circule rapidement sur la langue humide de {dog_name}, provoquant une évaporation qui refroidit le sang. {dog_name} peut haleter jusqu'à trois cents fois par minute lors d'un effort intense. La langue de {dog_name} est aussi un outil de communication : le léchage exprime l'affection, la soumission ou la demande d'attention. Saviez-vous que la langue des chiens possède moins de papilles gustatives que la nôtre ? {dog_name} compense par son odorat pour apprécier sa nourriture.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_023 : hypoallergéniques mythe réalité ---
  {
    id: 'FF_023',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Chiens hypoallergéniques : mythe ou réalité pour {dog_name} ?`,
    bodyFr: `L'idée de races « hypoallergéniques » est largement répandue, mais la réalité est plus nuancée. Aucune race de chien n'est totalement hypoallergénique. L'allergie aux chiens n'est pas causée par les poils eux-mêmes mais par une protéine présente dans la salive, l'urine et les squames. Tous les chiens, y compris {dog_name}, produisent cette protéine. Certaines races comme le caniche ou le bichon perdent moins de poils et de squames, ce qui réduit la quantité d'allergènes dispersés dans l'environnement. Un bain régulier, un bon aspirateur et des zones sans chien dans la maison peuvent aider les personnes sensibles à cohabiter avec {dog_name}. Consultez un allergologue pour des conseils adaptés à votre situation.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_024 : chien et ultrasons ---
  {
    id: 'FF_024',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et les ultrasons : un monde sonore invisible`,
    bodyFr: `{dog_name} perçoit des sons que votre oreille ne capte absolument pas. Les ultrasons, au-delà de vingt mille hertz, sont inaudibles pour les humains mais parfaitement perceptibles pour {dog_name} jusqu'à soixante-cinq mille hertz. C'est le principe du sifflet ultrasonique utilisé en éducation canine : vous n'entendez rien, mais {dog_name} reçoit le signal clairement. Cette capacité explique pourquoi {dog_name} réagit parfois à des sons que vous ne percevez pas, comme les appareils électroniques ou certains rongeurs dans les murs. Les ancêtres de {dog_name} utilisaient cette audition fine pour détecter les proies et les prédateurs à distance. Ce sens aigu fait de {dog_name} un compagnon qui perçoit un univers sonore bien plus riche que le vôtre.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_025 : mémoire du chien ---
  {
    id: 'FF_025',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `La mémoire de {dog_name} : comment fonctionne-t-elle ?`,
    bodyFr: `La mémoire de {dog_name} fonctionne différemment de la vôtre. Les chiens possèdent une excellente mémoire associative : {dog_name} retient les liens entre un événement et ses conséquences. Le bruit de la laisse signifie promenade, l'ouverture du placard signifie croquettes. Les recherches récentes suggèrent aussi que les chiens possèdent une forme de mémoire épisodique, se souvenant d'événements spécifiques vécus. {dog_name} reconnaît des personnes et des chiens même après des années de séparation. Sa mémoire olfactive est particulièrement puissante et durable. En revanche, la mémoire à court terme de {dog_name} est estimée à environ deux minutes pour les événements visuels. C'est pourquoi gronder {dog_name} longtemps après une bêtise est inefficace et contre-productif.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_026 : chien et goût ---
  {
    id: 'FF_026',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Le sens du goût chez {dog_name} : moins raffiné qu'on ne croit`,
    bodyFr: `{dog_name} possède environ mille sept cents papilles gustatives, contre neuf mille chez l'humain. Son sens du goût est donc nettement moins développé que le vôtre. {dog_name} perçoit le sucré, le salé, l'amer et l'acide, mais avec beaucoup moins de nuances. C'est pourquoi {dog_name} se fie principalement à son odorat pour évaluer la nourriture avant même de la goûter. L'odeur représente jusqu'à quatre-vingts pour cent de la perception gustative chez le chien. Fait intéressant : les chiens possèdent des récepteurs gustatifs pour l'eau, situés à l'extrémité de la langue, que les humains n'ont pas. Ces récepteurs s'activent davantage après un repas salé ou carné, poussant {dog_name} à boire pour maintenir son équilibre hydrique.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_027 : combien de dents ---
  {
    id: 'FF_027',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Combien de dents dans la mâchoire de {dog_name} ?`,
    bodyFr: `Un chien adulte comme {dog_name} possède quarante-deux dents, soit dix de plus que l'humain. Cette dentition impressionnante comprend douze incisives pour grignoter, quatre canines pour saisir et déchirer, seize prémolaires et dix molaires pour broyer. Les chiots naissent sans dents et développent vingt-huit dents de lait qui tombent vers quatre à six mois pour laisser place à la dentition définitive. La pression de la mâchoire de {dog_name} varie selon la race mais peut atteindre cent cinquante kilogrammes par centimètre carré chez certaines races. Malgré cette puissance, {dog_name} contrôle parfaitement la force de sa mâchoire, un apprentissage qui se fait naturellement au contact de sa fratrie pendant les premières semaines de vie.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_028 : magnétisme terrestre ---
  {
    id: 'FF_028',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `{dog_name} et le champ magnétique terrestre`,
    bodyFr: `Une découverte surprenante a révélé que les chiens sont sensibles au champ magnétique terrestre. Des chercheurs ont observé que les chiens, lorsqu'ils font leurs besoins, tendent à s'aligner sur l'axe nord-sud quand le champ magnétique est calme. Cette étude, menée sur des milliers d'observations, suggère que {dog_name} possède une forme de boussole interne. Ce magnétisme pourrait aussi contribuer au sens de l'orientation légendaire des chiens. Certains scientifiques pensent que des cristaux de magnétite dans le cerveau canin serviraient de capteurs magnétiques. La prochaine fois que {dog_name} prend son temps pour trouver la position idéale lors de ses besoins, il calibre peut-être sa boussole interne avec le champ magnétique terrestre.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_029 : chiens sauvetage montagne ---
  {
    id: 'FF_029',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Chiens de sauvetage en montagne : des héros à quatre pattes`,
    bodyFr: `Les chiens de sauvetage en montagne sont parmi les héros les plus admirés du monde canin. Bergers allemands, malinois, bergers belges et border collies excellent dans cette discipline exigeante. Un chien de recherche en avalanche peut couvrir en vingt minutes une zone qui nécessiterait quatre heures à vingt sauveteurs avec des sondes. Son flair détecte une personne ensevelie sous plusieurs mètres de neige. La formation dure environ deux ans et repose sur le jeu : le chien recherche son jouet caché, puis transfère cette motivation à la recherche de personnes. Ces chiens travaillent dans des conditions extrêmes avec un dévouement total. {dog_name} partage avec eux cette capacité innée des chiens à vouloir aider et protéger les humains.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
  // --- FF_030 : plus populaire par pays ---
  {
    id: 'FF_030',
    category: 'fun_fact',
    subcategory: 'fun_fact',
    breedFilter: [],
    sizeFilter: [],
    ageMinMonths: null,
    ageMaxMonths: null,
    seasonFilter: [],
    monthFilter: [],
    regionFilter: ['all'],
    titleFr: `Les races préférées dans le monde : et {dog_name} dans tout ça ?`,
    bodyFr: `Chaque pays a ses races favorites, reflet de sa culture et de son histoire. En France, le berger australien et le staffordshire bull terrier dominent les inscriptions au LOF depuis plusieurs années. Aux États-Unis, le labrador retriever règne en maître depuis des décennies. En Allemagne, le berger allemand reste une institution nationale. Au Japon, le shiba inu est la star incontestée. Au Royaume-Uni, le labrador partage le podium avec le cocker anglais. Ces préférences évoluent avec les modes, les films et les réseaux sociaux. Mais au-delà des tendances, chaque chien est unique. {dog_name} n'a pas besoin d'être dans le classement des races les plus populaires pour être le numéro un dans votre cœur.`,
    sourceType: 'fun_fact',
    neverSay: [],
    suffix: null,
    requiresVetDisclaimer: false,
    channel: 'home_insight',
    priority: 4,
    cooldownHours: 336,
    maxPerMonth: 2,
    usesDogName: true,
    usesBreedName: false,
    usesAge: false,
    usesLocation: false,
    usesSeason: false,
  },
];
