import type { BleizTemplate } from './bleiz-content-templates.js';

function createTemplate(template: BleizTemplate): BleizTemplate {
  return template;
}

const SEPARATION_NEVER_SAY = ['anxiété de séparation', 'trouble', 'pathologique', 'traumatisme'];
const NOISE_NEVER_SAY = ['phobie', 'trouble', 'pathologique', 'traumatisme'];
const THERMAL_NEVER_SAY = ['coup de chaleur', 'hyperthermie', 'urgence vétérinaire'];
const MULTI_SENSOR_NEVER_SAY = ['anormal', 'problème', 'inquiétant'];
const ALLOSTATIC_NEVER_SAY = [
  'charge allostatique',
  'stress chronique',
  'cortisol',
  'HPA',
  'système nerveux',
  'dérégulation',
  'pathologique',
];

const VET_SUFFIX = 'Si cela revient souvent, un vétérinaire peut vous guider.';

// =========================================================================
// PHASE 1 — SEPARATION (12 templates)
// =========================================================================
export const SEPARATION_TEMPLATES: BleizTemplate[] = [
  createTemplate({
    id: 'SEP_ABSENCE_CALM_TREND',
    category: 'relationship',
    channel: 'home_insight',
    priority: 78,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.absence_agitation_trend_4w', 'sensor.absence_confidence'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.absence_agitation_trend_4w',
        operator: 'eq',
        value: 'declining',
        description: 'Agitation during absences trends downward over 4 weeks',
      },
      {
        type: 'sensor',
        field: 'sensor.absence_confidence',
        operator: 'gte',
        value: 0.7,
        description: 'Sufficient confidence in the absence signal',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Rédige un insight maison en français pour {{dog.name}}.',
      'Observe que les moments d\'absence semblent plus paisibles ces dernières semaines.',
      'Reste prudent, non médical, et valorise la régularité des routines.',
      'Propose une piste douce pour entretenir cette tendance.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_ABSENCE_VOCAL_DECLINE',
    category: 'relationship',
    channel: 'home_insight',
    priority: 76,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.absent_vocal_events_per_hour', 'sensor.vocal_events_7d_avg'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.absent_vocal_events_per_hour',
        operator: 'lt',
        value: 3,
        description: 'Low vocal rate during absences',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Rédige un court insight en français pour {{dog.name}}.',
      'Décris une baisse des vocalises pendant les absences, sans étiqueter d\'émotion.',
      'Utilise des formulations prudentes (« il semble », « peut indiquer »).',
      'Suggère de maintenir les départs calmes et silencieux.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_PRE_DEPARTURE_PATTERN',
    category: 'relationship',
    channel: 'chat_message',
    priority: 72,
    cooldownHours: 240,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.pre_departure_agitation_index', 'sensor.absence_confidence'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.pre_departure_agitation_index',
        operator: 'gt',
        value: 0.6,
        description: 'Agitation rises in the minutes before departures',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Message chat en français pour la personne de {{dog.name}}.',
      'Il est possible que les signaux de départ (clés, manteau) modifient l\'activité.',
      'Propose des rituels de départ neutres et prévisibles.',
      'Reste non médical et sans jugement.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_REUNION_CALM',
    category: 'relationship',
    channel: 'home_insight',
    priority: 68,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.reunion_recovery_minutes'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.reunion_recovery_minutes',
        operator: 'lt',
        value: 5,
        description: 'Calm returns quickly after reunions',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'celebratory',
    prompt: [
      'Insight positif en français sur les retrouvailles avec {{dog.name}}.',
      'Le calme semble revenir vite après les retours.',
      'Souligne la qualité du lien sans anthropomorphiser.',
      'Encourage à conserver des retrouvailles posées.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_REUNION_SPIKE',
    category: 'relationship',
    channel: 'home_insight',
    priority: 70,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.reunion_agitation_peak'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.reunion_agitation_peak',
        operator: 'gt',
        value: 0.75,
        description: 'Clear activity peak at reunion',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français décrivant un pic d\'activité au moment des retrouvailles de {{dog.name}}.',
      'Reste descriptif, sans labelliser d\'émotion.',
      'Propose un retour progressif et des salutations calmes.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_WEEKDAY_WEEKEND',
    category: 'relationship',
    channel: 'home_insight',
    priority: 66,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.weekday_absence_index', 'sensor.weekend_absence_index'],
    triggers: [
      {
        type: 'computed',
        field: 'sensor.weekday_vs_weekend_delta',
        operator: 'gt',
        value: 0.3,
        description: 'Notable difference between weekday and weekend absences',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight en français comparant semaine et week-end pour {{dog.name}}.',
      'Il semble que le rythme d\'absence varie selon les jours.',
      'Propose d\'adapter les activités aux jours plus calmes.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_DEPARTURE_TIME_PATTERN',
    category: 'relationship',
    channel: 'home_insight',
    priority: 64,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.departure_hour_variance'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.departure_hour_variance',
        operator: 'lt',
        value: 1.0,
        description: 'Departure times are regular',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight en français soulignant la régularité des horaires de départ chez {{dog.name}}.',
      'La prévisibilité peut soutenir un rythme apaisé.',
      'Encourage à conserver ces repères horaires.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_FIRST_CALM_ABSENCE',
    category: 'relationship',
    channel: 'chat_message',
    priority: 80,
    cooldownHours: 720,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.first_calm_absence_flag'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.first_calm_absence_flag',
        operator: 'eq',
        value: true,
        description: 'First recorded absence classified as calm',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'celebratory',
    prompt: [
      'Message chat chaleureux en français pour célébrer une première absence paisible de {{dog.name}}.',
      'Reste mesuré, sans exagération.',
      'Invite à conserver les mêmes routines rassurantes.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_SHORT_VS_LONG',
    category: 'relationship',
    channel: 'home_insight',
    priority: 62,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.short_absence_agitation', 'sensor.long_absence_agitation'],
    triggers: [
      {
        type: 'computed',
        field: 'sensor.short_vs_long_delta',
        operator: 'gt',
        value: 0.25,
        description: 'Agitation differs between short and long absences',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight en français pour {{dog.name}} comparant absences courtes et longues.',
      'Il est possible que la durée influence le rythme d\'activité.',
      'Suggère d\'introduire progressivement des absences plus longues.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_ABSENCE_REST_RECOVERY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 70,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.absent_mat_rest_min'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.absent_mat_rest_min',
        operator: 'gt',
        value: 30,
        description: 'Meaningful rest on the mat during absences',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight en français pour {{dog.name}}.',
      'Le tapis semble servir de repère reposant même en votre absence.',
      'Valorise la constance de cet espace et son confort.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_OWNER_PRESENCE_EFFECT',
    category: 'relationship',
    channel: 'home_insight',
    priority: 66,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.absence_effect_size'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.absence_effect_size',
        operator: 'between',
        value: { min: 0.2, max: 0.5 },
        description: 'Modest effect between presence and absence',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français décrivant une légère différence de rythme selon votre présence, pour {{dog.name}}.',
      'Reste descriptif, non médical.',
      'Suggère de soigner les transitions.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'SEP_ROUTINE_ABSENCE_STABLE',
    category: 'relationship',
    channel: 'home_insight',
    priority: 60,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.absence_stability_4w'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.absence_stability_4w',
        operator: 'gt',
        value: 0.7,
        description: 'Absence pattern stable over 4 weeks',
      },
    ],
    targeting: {},
    never_say: SEPARATION_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight en français soulignant la stabilité des absences de {{dog.name}} sur quatre semaines.',
      'Mets en valeur les routines régulières.',
      'Invite à continuer sans bouleversement.',
    ].join('\n'),
  }),
];

// =========================================================================
// PHASE 2 — NOISE (6 templates)
// =========================================================================
export const NOISE_TEMPLATES: BleizTemplate[] = [
  createTemplate({
    id: 'NSE_THUNDER_RECOVERY',
    category: 'behavior',
    channel: 'home_insight',
    priority: 74,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.thunder_recovery_minutes'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.thunder_recovery_minutes',
        operator: 'lt',
        value: 20,
        description: 'Rapid return to calm after thunder',
      },
    ],
    targeting: {},
    never_say: NOISE_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français pour {{dog.name}} après un épisode d\'orage.',
      'Le retour au calme semble relativement rapide.',
      'Propose d\'entretenir un refuge confortable accessible.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'NSE_FIREWORK_SEASON',
    category: 'behavior',
    channel: 'chat_message',
    priority: 78,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.month'],
    triggers: [
      {
        type: 'temporal',
        field: 'sensor.month',
        operator: 'in',
        value: [6, 7, 12],
        description: 'Months with common fireworks events',
      },
    ],
    targeting: {},
    never_say: NOISE_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Message chat en français préparant à la saison des feux d\'artifice pour {{dog.name}}.',
      'Propose des aménagements simples : bruit de fond, refuge, fenêtres fermées.',
      'Reste non médical et sans alarmisme.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'NSE_CONSTRUCTION_DAILY',
    category: 'behavior',
    channel: 'home_insight',
    priority: 62,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.daytime_noise_index'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.daytime_noise_index',
        operator: 'gt',
        value: 0.6,
        description: 'High daytime ambient noise',
      },
    ],
    targeting: {},
    never_say: NOISE_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français décrivant un environnement sonore chargé dans la journée pour {{dog.name}}.',
      'Propose un coin calme et des temps de récupération.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'NSE_NOISE_ON_MAT_REFUGE',
    category: 'behavior',
    channel: 'home_insight',
    priority: 72,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.mat_presence_during_noise_min'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.mat_presence_during_noise_min',
        operator: 'gt',
        value: 15,
        description: 'Mat used as refuge during noise episodes',
      },
    ],
    targeting: {},
    never_say: NOISE_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight en français : le tapis semble servir de refuge à {{dog.name}} pendant les bruits forts.',
      'Souligne l\'importance de laisser cet espace libre et calme.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'NSE_NOISE_RECOVERY_TREND',
    category: 'behavior',
    channel: 'home_insight',
    priority: 70,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.noise_recovery_trend_4w'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.noise_recovery_trend_4w',
        operator: 'eq',
        value: 'improving',
        description: 'Recovery after noise improves over 4 weeks',
      },
    ],
    targeting: {},
    never_say: NOISE_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'celebratory',
    prompt: [
      'Insight en français pour {{dog.name}} : la récupération après les bruits forts semble s\'améliorer.',
      'Reste mesuré, invite à conserver les routines actuelles.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'NSE_MONTHLY_NOISE_EXPOSURE',
    category: 'behavior',
    channel: 'home_insight',
    priority: 58,
    cooldownHours: 720,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.monthly_noise_events'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.monthly_noise_events',
        operator: 'gte',
        value: 5,
        description: 'Multiple noise exposure events in a month',
      },
    ],
    targeting: {},
    never_say: NOISE_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Bilan mensuel en français sur les expositions sonores de {{dog.name}}.',
      'Décris les observations sans dramatiser.',
      'Propose d\'anticiper les prochains épisodes connus.',
    ].join('\n'),
  }),
];

// =========================================================================
// PHASE 3 — THERMAL (8 templates)
// =========================================================================
export const THERMAL_TEMPLATES: BleizTemplate[] = [
  createTemplate({
    id: 'THR_HEAT_ACTIVE_ALERT',
    category: 'health_seasonal',
    channel: 'push',
    priority: 95,
    cooldownHours: 24,
    weeklyBudget: 3,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.temperature_c', 'sensor.weather_alert_level'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.temperature_c',
        operator: 'gte',
        value: 30,
        description: 'Ambient temperature very warm',
      },
      {
        type: 'sensor',
        field: 'sensor.weather_alert_level',
        operator: 'gte',
        value: 2,
        description: 'Weather alert in effect',
      },
    ],
    targeting: { seasons: ['summer'] },
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: false,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Notification push en français pour {{dog.name}}.',
      'Il fait très chaud aujourd\'hui : rappeler l\'eau fraîche, l\'ombre, éviter les sorties aux heures les plus chaudes.',
      'Reste éducatif, non médical, sans catastrophisme.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'THR_BRACHY_HEAT_CAUTION',
    category: 'health_seasonal',
    channel: 'home_insight',
    priority: 86,
    cooldownHours: 72,
    weeklyBudget: 2,
    maxPerDay: 1,
    required_fields: ['dog.name', 'dog.is_brachycephalic', 'sensor.temperature_c'],
    triggers: [
      {
        type: 'breed',
        field: 'dog.is_brachycephalic',
        operator: 'eq',
        value: true,
        description: 'Dog has brachycephalic morphology',
      },
      {
        type: 'sensor',
        field: 'sensor.temperature_c',
        operator: 'gte',
        value: 24,
        description: 'Warm conditions for sensitive morphology',
      },
    ],
    targeting: { seasons: ['spring', 'summer'] },
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français pour {{dog.name}}, race brachycéphale.',
      'Par temps chaud, privilégier les sorties aux heures fraîches et rester attentif à la respiration.',
      'Reste éducatif, non médical.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'THR_HUMIDITY_COMFORT',
    category: 'health_seasonal',
    channel: 'home_insight',
    priority: 66,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.humidity_pct'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.humidity_pct',
        operator: 'gt',
        value: 70,
        description: 'High humidity',
      },
    ],
    targeting: {},
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight en français expliquant que l\'humidité élevée peut rendre la thermorégulation plus exigeante pour {{dog.name}}.',
      'Propose de ralentir le rythme et d\'offrir de l\'eau fraîche.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'THR_INDOOR_COOLING_TIP',
    category: 'health_seasonal',
    channel: 'home_insight',
    priority: 60,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.temperature_c'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.temperature_c',
        operator: 'between',
        value: { min: 26, max: 30 },
        description: 'Warm but not extreme indoor temperature',
      },
    ],
    targeting: { seasons: ['summer'] },
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français offrant des idées simples pour rafraîchir l\'intérieur autour de {{dog.name}} : tapis frais, ventilation, ombre.',
      'Reste éducatif.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'THR_ACTIVITY_REDUCTION_HEAT',
    category: 'health_seasonal',
    channel: 'home_insight',
    priority: 72,
    cooldownHours: 72,
    weeklyBudget: 2,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.activity_km_today', 'sensor.temperature_c'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.temperature_c',
        operator: 'gte',
        value: 28,
        description: 'High temperature',
      },
      {
        type: 'sensor',
        field: 'sensor.activity_km_today',
        operator: 'gt',
        value: 4,
        description: 'Activity still high despite heat',
      },
    ],
    targeting: { seasons: ['summer'] },
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français suggérant d\'ajuster l\'intensité d\'activité de {{dog.name}} lors des journées chaudes.',
      'Propose des sorties courtes aux heures fraîches.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'THR_WARMING_TREND_2W',
    category: 'health_seasonal',
    channel: 'home_insight',
    priority: 58,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.temperature_trend_2w'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.temperature_trend_2w',
        operator: 'eq',
        value: 'warming',
        description: 'Local temperature rising over two weeks',
      },
    ],
    targeting: {},
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight en français préparant {{dog.name}} à une tendance au réchauffement sur deux semaines.',
      'Propose d\'anticiper les sorties tôt le matin.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'THR_NIGHT_COOLING',
    category: 'health_seasonal',
    channel: 'home_insight',
    priority: 54,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.night_temperature_c'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.night_temperature_c',
        operator: 'gt',
        value: 22,
        description: 'Warm nights',
      },
    ],
    targeting: { seasons: ['summer'] },
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français sur le confort nocturne de {{dog.name}} par temps chaud.',
      'Suggère un espace aéré, sol frais, eau à disposition.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'THR_SEASONAL_ACCLIMATION',
    category: 'health_seasonal',
    channel: 'home_insight',
    priority: 52,
    cooldownHours: 720,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.season'],
    triggers: [
      {
        type: 'temporal',
        field: 'sensor.season',
        operator: 'in',
        value: ['spring', 'autumn'],
        description: 'Transition seasons',
      },
    ],
    targeting: { seasons: ['spring', 'autumn'] },
    never_say: THERMAL_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight saisonnier en français sur l\'acclimatation progressive de {{dog.name}}.',
      'Rappelle que le corps a besoin de temps pour s\'adapter.',
    ].join('\n'),
  }),
];

// =========================================================================
// PHASE 4 — MULTI-SENSOR (10 templates)
// =========================================================================
export const MULTI_SENSOR_TEMPLATES: BleizTemplate[] = [
  createTemplate({
    id: 'MS_DEEP_REST_WEEKLY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 66,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.deep_rest_minutes_7d'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.deep_rest_minutes_7d',
        operator: 'gt',
        value: 600,
        description: 'Good weekly deep rest total',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight hebdomadaire en français pour {{dog.name}} sur le repos profond.',
      'Valorise une semaine reposée sans surinterpréter.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_NIGHT_REST_QUALITY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 64,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.night_rest_quality_index'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.night_rest_quality_index',
        operator: 'gt',
        value: 0.7,
        description: 'Good night rest quality',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français sur la qualité des nuits de {{dog.name}}.',
      'Reste observationnel, propose de conserver un couchage stable.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_RR_STABILITY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 70,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.resting_rr_delta_pct', 'sensor.rest_rr_valid_today'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.rest_rr_valid_today',
        operator: 'eq',
        value: true,
        description: 'Valid resting RR measurement',
      },
      {
        type: 'sensor',
        field: 'sensor.resting_rr_delta_pct',
        operator: 'between',
        value: { min: -10, max: 10 },
        description: 'Resting respiration close to baseline',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight en français pour {{dog.name}} : la respiration au repos semble stable par rapport à sa ligne de base.',
      'Reste descriptif, non médical.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_POSITION_CHANGES_NIGHT',
    category: 'relationship',
    channel: 'home_insight',
    priority: 58,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.night_position_changes'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.night_position_changes',
        operator: 'lt',
        value: 12,
        description: 'Few position changes during the night',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français décrivant des nuits posées pour {{dog.name}}.',
      'Propose de maintenir un environnement calme au coucher.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_WALK_SNIFFING_RATIO',
    category: 'activity',
    channel: 'home_insight',
    priority: 62,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.walk_sniffing_ratio'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.walk_sniffing_ratio',
        operator: 'gt',
        value: 0.3,
        description: 'Meaningful share of walk time spent sniffing',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'playful',
    prompt: [
      'Insight en français valorisant les moments de reniflage durant les promenades de {{dog.name}}.',
      'Rappelle que l\'exploration olfactive fait partie d\'une sortie réussie.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_RECOVERY_POST_EXERCISE',
    category: 'relationship',
    channel: 'home_insight',
    priority: 68,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.post_exercise_recovery_minutes'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.post_exercise_recovery_minutes',
        operator: 'lt',
        value: 15,
        description: 'Quick recovery after activity',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight en français pour {{dog.name}} : la récupération après effort semble rapide.',
      'Reste observationnel, propose de garder un bon équilibre effort/repos.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_DAILY_RHYTHM_CONSISTENCY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 60,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.daily_rhythm_consistency'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.daily_rhythm_consistency',
        operator: 'gt',
        value: 0.7,
        description: 'Stable daily rhythm',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight en français sur la régularité du rythme quotidien de {{dog.name}}.',
      'Valorise la constance des repères horaires.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_WEIGHT_STABLE',
    category: 'relationship',
    channel: 'home_insight',
    priority: 56,
    cooldownHours: 720,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.weight_delta_pct_30d'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.weight_delta_pct_30d',
        operator: 'between',
        value: { min: -3, max: 3 },
        description: 'Weight stable over 30 days',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Insight en français : le poids de {{dog.name}} semble stable sur 30 jours.',
      'Reste descriptif et non médical.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_COPRESENCE_REGULAR',
    category: 'community',
    channel: 'home_insight',
    priority: 54,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'community.copresence_count', 'community.copresence_days'],
    triggers: [
      {
        type: 'community',
        field: 'community.copresence_count',
        operator: 'gte',
        value: 3,
        description: 'Regular copresence with another dog',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'playful',
    prompt: [
      'Insight en français évoquant les rencontres régulières de {{dog.name}} avec un autre chien.',
      'Reste factuel et chaleureux, sans anthropomorphiser.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'MS_INTERACTION_INTENSITY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 58,
    cooldownHours: 168,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.interaction_intensity_index'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.interaction_intensity_index',
        operator: 'between',
        value: { min: 0.4, max: 0.7 },
        description: 'Balanced interaction intensity',
      },
    ],
    targeting: {},
    never_say: MULTI_SENSOR_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight en français sur l\'intensité équilibrée des interactions avec {{dog.name}}.',
      'Valorise des échanges posés et réguliers.',
    ].join('\n'),
  }),
];

// =========================================================================
// PHASE 5 — ALLOSTATIC (4 templates)
// =========================================================================
export const ALLOSTATIC_TEMPLATES: BleizTemplate[] = [
  createTemplate({
    id: 'ALO_RECOVERY_IMPROVING',
    category: 'relationship',
    channel: 'home_insight',
    priority: 66,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.recovery_trend_4w'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.recovery_trend_4w',
        operator: 'eq',
        value: 'improving',
        description: 'Recovery after effortful periods improving',
      },
    ],
    targeting: {},
    never_say: ALLOSTATIC_NEVER_SAY,
    requires_hardware: true,
    suffix: VET_SUFFIX,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Insight en français pour {{dog.name}} : la capacité de récupération semble s\'améliorer sur quatre semaines.',
      'Reste prudent, sans vocabulaire médical.',
      'Invite à conserver les routines en place.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'ALO_AROUSAL_EPISODES',
    category: 'relationship',
    channel: 'home_insight',
    priority: 62,
    cooldownHours: 336,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.arousal_episodes_week'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.arousal_episodes_week',
        operator: 'lt',
        value: 4,
        description: 'Few high-arousal episodes per week',
      },
    ],
    targeting: {},
    never_say: ALLOSTATIC_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'gentle',
    prompt: [
      'Insight en français décrivant peu d\'épisodes d\'excitation marqués cette semaine pour {{dog.name}}.',
      'Reste descriptif, sans vocabulaire physiologique.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'ALO_MONTHLY_REST_QUALITY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 60,
    cooldownHours: 720,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.monthly_rest_quality_index'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.monthly_rest_quality_index',
        operator: 'gt',
        value: 0.65,
        description: 'Good monthly rest quality',
      },
    ],
    targeting: {},
    never_say: ALLOSTATIC_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'warm',
    prompt: [
      'Bilan mensuel en français pour {{dog.name}} sur la qualité du repos.',
      'Reste observationnel et non médical.',
    ].join('\n'),
  }),
  createTemplate({
    id: 'ALO_MONTHLY_CONSISTENCY',
    category: 'relationship',
    channel: 'home_insight',
    priority: 58,
    cooldownHours: 720,
    weeklyBudget: 1,
    maxPerDay: 1,
    required_fields: ['dog.name', 'sensor.monthly_rhythm_consistency'],
    triggers: [
      {
        type: 'sensor',
        field: 'sensor.monthly_rhythm_consistency',
        operator: 'gt',
        value: 0.7,
        description: 'Consistent monthly rhythm',
      },
    ],
    targeting: {},
    never_say: ALLOSTATIC_NEVER_SAY,
    requires_hardware: true,
    safety: { requireNonMedical: true },
    tone: 'informative',
    prompt: [
      'Bilan mensuel en français soulignant la régularité du rythme de {{dog.name}}.',
      'Valorise la constance sans surinterpréter.',
    ].join('\n'),
  }),
];
