// AUTO-GENERATED by scripts/privacy/generate-breach-recipient-surfaces.mjs.
// Do not edit by hand. The derivation guard fails closed if this file drifts.

export const BREACH_RECIPIENT_SURFACES = [
  {
    "surface": "non_sql:ANALYTICS_TELEMETRY",
    "authority": "NON_SQL_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "config/privacy/non-sql-erasure-surface-inventory.json"
  },
  {
    "surface": "non_sql:BACKUPS",
    "authority": "NON_SQL_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "config/privacy/non-sql-erasure-surface-inventory.json"
  },
  {
    "surface": "non_sql:CACHES_SEARCH_INDEXES",
    "authority": "NON_SQL_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "config/privacy/non-sql-erasure-surface-inventory.json"
  },
  {
    "surface": "non_sql:OBJECT_MEDIA_STORAGE",
    "authority": "NON_SQL_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "config/privacy/non-sql-erasure-surface-inventory.json"
  },
  {
    "surface": "non_sql:PROVIDER_HELD_COPIES",
    "authority": "NON_SQL_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "config/privacy/non-sql-erasure-surface-inventory.json"
  },
  {
    "surface": "provider:Anthropic",
    "authority": "PROVIDER_GAP_REQUIRED",
    "requiredGap": "provider_copy_unverified",
    "source": "config/privacy/provider-retention-erasure-evidence.json"
  },
  {
    "surface": "provider:Mapbox",
    "authority": "PROVIDER_GAP_REQUIRED",
    "requiredGap": "provider_copy_unverified",
    "source": "config/privacy/provider-retention-erasure-evidence.json"
  },
  {
    "surface": "provider:Open-Meteo",
    "authority": "PROVIDER_GAP_REQUIRED",
    "requiredGap": "provider_copy_unverified",
    "source": "config/privacy/provider-retention-erasure-evidence.json"
  },
  {
    "surface": "provider:OpenStreetMap_Overpass",
    "authority": "PROVIDER_GAP_REQUIRED",
    "requiredGap": "provider_copy_unverified",
    "source": "config/privacy/provider-retention-erasure-evidence.json"
  },
  {
    "surface": "provider:OpenWeatherMap",
    "authority": "PROVIDER_GAP_REQUIRED",
    "requiredGap": "provider_copy_unverified",
    "source": "config/privacy/provider-retention-erasure-evidence.json"
  },
  {
    "surface": "provider:Plausible",
    "authority": "PROVIDER_GAP_REQUIRED",
    "requiredGap": "provider_copy_unverified",
    "source": "config/privacy/provider-retention-erasure-evidence.json"
  },
  {
    "surface": "provider:Resend",
    "authority": "PROVIDER_GAP_REQUIRED",
    "requiredGap": "provider_copy_unverified",
    "source": "config/privacy/provider-retention-erasure-evidence.json"
  },
  {
    "surface": "sql:achievements",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:ai_messages",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:anticipation_events",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:auth_refresh_sessions",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:baseline_drift_monitor",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:baselines",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:behavioral_assessments",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:behavioral_factor_scores",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:behavioral_responses",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:comments",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:communities",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:community_events",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:community_members",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:community_reports",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:community_rules_acceptances",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:copresence_events",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:devices",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:dog_sub_baselines",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:dogs",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:eli_behavioral_priors",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:eli_states",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:health_entries",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:posts",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:professional_share_access_audits",
    "authority": "SQL_UNCONSTRAINED_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "config/privacy/dog-erasure-topology.json unconstrained identifiers"
  },
  {
    "surface": "sql:professional_share_grants",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:recovery_events",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:research_data_consents",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:routine_stability",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:sensor_summaries",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:subscriptions",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:user_config",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:users",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "sql:walk_quality",
    "authority": "CANONICAL_SQL",
    "requiredGap": null,
    "source": "config/privacy account+dog erasure topology"
  },
  {
    "surface": "web:breiz-community-events",
    "authority": "WEB_PROTOTYPE_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "apps/web localStorage discovery"
  },
  {
    "surface": "web:breiz-community-posts",
    "authority": "WEB_PROTOTYPE_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "apps/web localStorage discovery"
  },
  {
    "surface": "web:breiz-contact-requests",
    "authority": "WEB_PROTOTYPE_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "apps/web localStorage discovery"
  },
  {
    "surface": "web:breiz-journal-user-entries",
    "authority": "WEB_PROTOTYPE_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "apps/web localStorage discovery"
  },
  {
    "surface": "web:breiz-map-user-spots",
    "authority": "WEB_PROTOTYPE_GAP_REQUIRED",
    "requiredGap": "canonical_subject_missing",
    "source": "apps/web localStorage discovery"
  }
] as const;

export type BreachRecipientSurfaceDescriptor = (typeof BREACH_RECIPIENT_SURFACES)[number];
export type BreachAffectedSurface = BreachRecipientSurfaceDescriptor['surface'];
export type BreachRecipientAuthority = BreachRecipientSurfaceDescriptor['authority'];
